### ISSUE TITLE
[Crash] Left it the mist after a pvp match

### ISSUE THREAD

**Issue by Hanndel** [megai2/d912pxy#10]
Left the client alone in the mist after a pvp match, i was tabbed out and wasnt on the pc

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2793215/d912pxy_crash.txt)

^ d912pxy_crash.txt

https://cdn.discordapp.com/attachments/510086457046728726/538076553909633054/P7logs.rar

^ P7log

**Comment by megai2** [comment]
yes, this is a ram problem.
