### ISSUE TITLE
Visual output hangs after opening the open-shell-menu with the Windows key (more complicated vanilla shell method inside)

### ISSUE THREAD

**Issue by Atemu** [megai2/d912pxy#102]
**Describe the bug**
The visual output hangs after pressing the Windows key or making :

* Audio still works
* The mouse cursor still moves and still has the GW2 look
* Alt+tabbing out and in doesn't help
* Windows' alt+tab overlay and CTRL+ALT+DEL show up but you can't get any other program to show up on the screen GW2 is hanging on.  

**To Reproduce**

[Open-Shell-Menu](https://github.com/Open-Shell/Open-Shell-Menu):

1. Run the game
2. Have graphics settings on exclusive fullscreen
3. Open the open-shell start menu with the Windows key

Vanilla shell but more complicated way: 

1. Have two or more windows open of a program that supports window preview in the task bar (windows explorer or steam for example)
2. Have that program pinned to the task bar (valid positions: 1-10)
2. Run the game
2. Have graphics settings on exclusive fullscreen
2. Press the WIN+[1-0] shortcut *twice or more* to have the window selector for the program from 1. show up ([1-0] key depends on which position the program was pinned to in 2.)

**Expected behavior**
The game should minimize or go into the background and the start menu or window selector should show up

**Standard information**

1. Windows 10 build 17134
2. Hardware info: 7600K 5GHz AVX-1, 16GB 3.2GHz, GTX 970 1.475GHz, Gsync monitor
3. GPU Driver version 417.01
4. Version of d912pxy used: Beta v0.9.7.2
5. Log file from <game root>/P7logs folder is empty and d912pxy_crash.txt doesn't exist; I have to kill the game via task manager to do anything else on the screen

**Additional context**
ALT+TAB while using open-shell and opening Windows 10's horrible built-in start menu works as it should

**Comment by megai2** [comment]
#76

**Comment by Atemu** [comment]
Alt+tab works flawlessly in my case.

**Comment by megai2** [comment]
> 
> 
> Alt+tab works flawlessly in my case.

For me it works flawlessly 34/35 times too. Key problem is exclusive fullscreen focus switching.
