### ISSUE TITLE
wrong colors when using arcdps and d912pxy after March 5th

### ISSUE THREAD

**Issue by wolfrik17** [megai2/d912pxy#103]
After the latest patch with the newest arcDPS version class colors and highlights are the wrong color
![capture](https://user-images.githubusercontent.com/23453638/53907875-c6e87900-4056-11e9-8b1d-1f46a4c26ac0.PNG)

**Comment by megai2** [comment]
bug is in wrong imgui patch merge, posted it to deltaconnected

**Comment by megai2** [comment]
will keep it open until actual arcdps version is fixed

**Comment by megai2** [comment]
fixed
