### ISSUE TITLE
Game doesn't even start

### ISSUE THREAD

**Issue by alezhp** [megai2/d912pxy#104]
My game doesn't even start. After I press 'Play' in the launcher, it disappears and my memory gets all used up, remaining like that and starting to write up in the crash logs. I have to close the task from task manager to stop it.

At first I tried it by sideloading it with ArcDPS, but then I also removed them both, and the bin folder and tried again just with this one with no change.

[P7logs.zip](https://github.com/megai2/d912pxy/files/2939345/P7logs.zip)
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2939346/d912pxy_crash.txt)

My specs are pretty outdated, but I thought I met the minimum requirements:
Intel Core i5-3337U 1.8GHz
6144 RAM
NVIDIA GeForce GT 710M

**Comment by megai2** [comment]
looks like your GPU don't support sm5_1, so it will not work for now
