### ISSUE TITLE
ringbuffer overrun in ReRangeThreads

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#108]
[Guild Wars 2.zip](https://github.com/megai2/d912pxy/files/2975534/Guild.Wars.2.zip)

_Originally posted by @gzosiek21 in https://github.com/megai2/d912pxy/issues/13#issuecomment-473693797_

**Comment by megai2** [comment]
check on r147 https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

**Comment by KleyArk** [comment]
I'm still having this crash in the new release:
0 | "ring buffer overrun" | hr = FFFFFFFF

**Comment by megai2** [comment]
fixed in r150+
