### ISSUE TITLE
Texture object create failed and ring buffer overrun - v0.9.7.5

### ISSUE THREAD

**Issue by KleyArk** [megai2/d912pxy#109]
**Describe the crash**
Simply crash.

**To Reproduce**

- Background apps: Firefox Browser (v65.0.2), Discord
1. Run game
2. Set graphics settings to https://i.imgur.com/t6Wpzru.png
3. Head to "Mystlock Sanctuary"
4. Do this: "Walk around using special action"

**Expected behavior**
Crash without any visible crash report.

**Standard information**

1. Windows 10 1809 (Build 17763.379)
2. Hardware info: Intel Core i7 4770 (Hyper Threading ON), Nvidia GTX 1080, RAM HyperX DDR3 16GB 1600Mhz
3. Driver version 419.35
4. Addon v0.9.7.5
5. Log file from <game root>/d912pxy_crash.txt

**Addons installed**
ArcDPS (Latest version)
YoloMouse

**Crash Log 1**
0 | "texture object create failed" | hr = 887A0005

**Additional settings**
1. Optimizations from Nvidia Control Panel:
- Max pre-renderized frames: 1
- Power management mode: Performance
- Vertical Sync: Fast Sync
- Threaded Optimization: Activated

2. Windows Optimizatios (Gw2-64.exe, compatibility property):
- Disable Full Screen Optimization
- Override DPI Activated

**Additional informations**
Also Discord crashes with the game (No, the problem doesn't depend from Discord).
P.S: Discord's Overlay and Hardware acceleration are disabled.

__________________________________________

**Crash Log 2**
"ring buffer overrun" | hr = FFFFFFFF 

**Describe the crash**
Game crash if you switch window from GW2 to Firefox Browser while loading the map (Mystlock Sanctuary).

**To Reproduce**

- Background apps: Firefox Browser (v65.0.2), Discord
1. Run game
2. Set graphics settings to https://i.imgur.com/t6Wpzru.png
3. During map loading of "Mystlock Sanctuary" switch window to Firefox Browser.

**Additional informations**
Firefox's hardware acceleration disabled.

**Comment by megai2** [comment]
#108
