### ISSUE TITLE
Crash d912pxy_global_objects

### ISSUE THREAD

**Issue by KleyArk** [megai2/d912pxy#111]
**Describe the bug**
Game crash during login in Mystlock Sanctuary (during video streaming on Discord).

**To Reproduce**
1. Background apps: Discord (in streaming)
2. Run game
3. Set graphics settings to https://i.imgur.com/t6Wpzru.png
4. Head to "Mystlock Sanctuary"

**Expected behavior**
Crash while loading the map Mystlock Sanctuary.

**Standard information**
1. Windows 10 1809 (Build 17763.379)
2. Hardware info: Intel Core i7 4770 (Hyper Threading ON), Nvidia GTX 1080, RAM HyperX DDR3 16GB 1600Mhz
3. Driver version 419.35
4. Version of d912pxy used: 0.9.7.4
5. Log file from <game root>/d912pxy_crash.txt

**Crash Log**
0 | d912pxy_global_objects::DXDev->CreateCommittedResource( &rhCfg, D3D12_HEAP_FLAG_NONE, &rsDesc, D3D12_RESOURCE_STATE_RENDER_TARGET, &optimizedClearValue, __uuidof(**(&m_res)), IID_PPV_ARGS_Helper(&m_res) ) | hr = 887A0005

**Comment by megai2** [comment]
Better stick to https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by KleyArk** [comment]
I downgraded the D912PXY version due to too many crashes with the new one (i opened 4 times the game and had 4 crashes in 15 min). The game doesn't crash without D912PXY, never.
If you mean the log file, i can upload them if you want :)

**Comment by megai2** [comment]
Beter to add reports to issue #13 that is it.
Crashlogs can be good, can be bad, can be somewhat tricky.
If everyone will create issue for every crash, that will be a mess.
