### ISSUE TITLE
Lens flare clipthru / wrong behaivour

### ISSUE THREAD

**Issue by ghost** [megai2/d912pxy#112]
While i'm testing the new version of P912PXY v0.9.7.5 hotfix 2, i found a little texture/graphic bug.
This bug occurs in Domain of Vabbi map. I think this may happen also in other locations/situations.
Look at the sun and the "fish lens" texture in the screenshots below.

**Screenshot**
![gw062](https://user-images.githubusercontent.com/45238047/54570336-7a9a2300-49de-11e9-900e-0a0ac2cefaf5.jpg)
![gw063](https://user-images.githubusercontent.com/45238047/54570451-cd73da80-49de-11e9-92a5-9cd0669ab0c7.jpg)
![gw061](https://user-images.githubusercontent.com/45238047/54570455-d06ecb00-49de-11e9-93a7-bb5d3e789983.jpg)
![gw064](https://user-images.githubusercontent.com/45238047/54570661-a5d14200-49df-11e9-9c95-223bc8b663d1.jpg)

**Comment by megai2** [comment]
lens flare effect uses occlustion query to render
probable solution is custom shader

**Comment by megai2** [comment]
how about doing this in postprocess chain and cutting out standart ones?

https://john-chapman.github.io/2017/11/05/pseudo-lens-flare.html

**Comment by Deshke** [comment]
there is also this 

![image](https://user-images.githubusercontent.com/1473225/56601787-52fd3280-65fc-11e9-9674-2052a944bb02.png)

**Comment by ShiftLeftLogical** [comment]
I am woefully out of my depth here, both in the windows and graphics domains so please either direct me where to read up on or to go about modifying the post processing chain to apply this effect to negate the amount of lens flare generated from a light source, given you have a few minutes? Anyone have a solution in d912pxy for gw2 or is this getting into TOS issues?

**Comment by megai2** [comment]
> 
> 
> I am woefully out of my depth here, both in the windows and graphics domains so please either direct me where to read up on or to go about modifying the post processing chain to apply this effect to negate the amount of lens flare generated from a light source, given you have a few minutes? Anyone have a solution in d912pxy for gw2 or is this getting into TOS issues?

You need to compile RenderDoc with my custom patch, run debug build of d912pxy, capture that specific lens flare in RenderDoc, look up draw call with it, find shader hash name and make custom shader to overcome it.

**Comment by RubberDougie** [comment]
> > I am woefully out of my depth here, both in the windows and graphics domains so please either direct me where to read up on or to go about modifying the post processing chain to apply this effect to negate the amount of lens flare generated from a light source, given you have a few minutes? Anyone have a solution in d912pxy for gw2 or is this getting into TOS issues?
> 
> You need to compile RenderDoc with my custom patch, run debug build of d912pxy, capture that specific lens flare in RenderDoc, look up draw call with it, find shader hash name and make custom shader to overcome it.

I have the exact same issue in Draconis Mons.  Uninstalled until a fix comes out. Thanks for the work

**Comment by megai2** [comment]
should work on latest release, do clean install if it not.

**Comment by GnomeBeans** [comment]
BTW Im seeing the issue with draconis mons from above on version 2.0. I've ran the install and removed and reinstalled. I've deleted bin64. Any time I look at the sun spot where the lens flare seems to come from it drops my frames by half.

![image](https://user-images.githubusercontent.com/53883426/73603882-d6fa2880-4545-11ea-890a-ef8c140a5351.png)

**Comment by megai2** [comment]
there is tradeoff between keeping occlusions real and fake

you can set occlusion=2 in config so it will properly draw scene, but some performance drops can be expected

**Comment by GnomeBeans** [comment]
Thanks that fixed it. I tested amd and nvidia as well and without the proxy. There is no sun spot when setting '2' or when using dx 9. I thought I was crazy.

**Comment by megai2** [comment]
Proper occlusion was enabled in v2.1, so this bug should not be encountered again
