### ISSUE TITLE
Party UI blank portraits

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#113]
Even with PSO settings 

> keep_pairs=1
> use_pso_precompile=3
> use_pso_key_cache=3

party portraits are blank. It's worth noting they seem to work just as you load into the map but then flicker out from the top to the bottom.

![Annotation 2019-03-19 101355](https://user-images.githubusercontent.com/48250297/54625207-74cf2c80-4a34-11e9-9d4c-ad46e8e14ff7.jpg)

_Originally posted by @AlraiLux in https://github.com/megai2/d912pxy/issues/15#issuecomment-474465377_

**Comment by a5744585** [comment]
[sdb]
keep_pairs=0
use_pso_precompile=0
use_pso_key_cache=0

https://i.imgur.com/1LotAeL.jpg

A player leaves FOTM, but he is back.
I see the normal UI avatar until the avatar Urban Battleground is changed.

Maybe other reasons?

**Comment by megai2** [comment]
I need someone to catch this in realtime, ask me on discord.

**Comment by megai2** [comment]
Game wants to draw a 64x64 portrait from rendertarget with 128x128 portrait rendered in.
Possible some downsampling that is broken.

**Comment by megai2** [comment]
fixed in https://github.com/megai2/d912pxy/commit/717e2c938dbebdb4842520dc3a47822ce687e776
