### ISSUE TITLE
PSO cache corruption 

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#115]
PSO cache can go corrupted by some means, leaving game non-startable

**Comment by megai2** [comment]
Soure of corruption: shader recompilation fail

Fixed by skipping non loadable shader pairs on pso precompile.

**Comment by a5744585** [comment]
This is translation.

I can't just run, RAM will be full

But run with computer administrator privileges.
This situation is no.

Beta v0.9.7.6  Beta v0.9.7.5   Beta v0.9.7.4  Beta v0.9.7.3 All have this problem.
Earlier versions, I have not tried.

**Comment by megai2** [comment]
@a5744585 send logs to crash report issue #13
