### ISSUE TITLE
[&AgFRXQEA] Sun Temple Gecko Springer Skin visual glitch

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#117]
> > DX9：[https：](https://i.imgur.com/auFxrTb.jpg) 
> > //i.imgur.com/auFxrTb.jpg DX12：[https](https://i.imgur.com/YoorA25.jpg)：//i.imgur.com/YoorA25.jpg[](https://i.imgur.com/YoorA25.jpg)
> > Release_ps無法解決我的問題
> 
> 掛皮鏈接或名稱？
Game link [&AgFRXQEA]
Sun Temple Gecko Springer Skin

_Originally posted by @a5744585 in https://github.com/megai2/d912pxy/issues/15#issuecomment-476994077_

**Comment by megai2** [comment]
PS: 9dcce2dbe0e3f9f0.hlsl
VS: f080fce66894dd82.hlsl

**Comment by megai2** [comment]
PSO looks fine, textures too, maybe shader recompilation have an error.

**Comment by a5744585** [comment]
> PSO looks fine, textures too, maybe shader recompilation have an error.

Skyscale horns and harness are black BUG

But I am normal.

Clean installation v0.9.9.2b
E3 1230 V3
AMD RX460 You know magical magic, so it becomes  AMD RX560

https://i.imgur.com/Nt4Ipxo.jpg

**Comment by a5744585** [comment]
The latest version has been fixed BUG.
