### ISSUE TITLE
lag spike / oom crash

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#119]
Some ppl on reddit reported unusual lag spikes / oom crashes

**Comment by moriz1** [comment]
Possibly caused by memory fragmentation. Might be safer to limit the maximum amount of memory that d912pxy can use.

**Comment by megai2** [comment]
> 
> 
> Possibly caused by memory fragmentation. Might be safer to limit the maximum amount of memory that d912pxy can use.

Address space is big enough on GPU and CPU, which with paging should handle this fine.

I think that is plain memory leak is somewhere.

**Comment by ShiftLeftLogical** [comment]
> > Possibly caused by memory fragmentation. Might be safer to limit the maximum amount of memory that d912pxy can use.
> 
> Address space is big enough on GPU and CPU, which with paging should handle this fine.
> 
> I think that is plain memory leak is somewhere.

FWIW (AKA: I did not debug the issue so I do want to be careful to not pass my experience as having much merit): I have multiple accounts, and will run all the clients at once and twice now, I have had the experience where only one of the account's client will (different accounts both times) consume almost the max amount of RAM and video RAM (procmon will almost instantly highlight the process as you watch the RAM consumed jump by GBs in seconds) such that windows kills the GW2-64 process. I can launch the other accounts just fine.

In the end, I had to recreate one of the account's local.dat (each account uses it's own copy) as clearing the shaders, reinstalling d912pxy, then eventually uninstalling d912pxy did not fix the issue, the account would have the same issue with massive memory consumption even when running on it's own.

If this happens again, I will take the time to install the debugging .dll and figure out what is going on, scouts honor.

The order of removal was:
1. d912pxy (shaders/reinstall/uninstall)
2. local.dat

This leads me to believe it has something to do with the per account local_#.dat or account specific settings and will eventually try and just recreate a new local_#+1.dat prior to messing with d912 or delete the misbehaving account's data.

@megai2 Related question: Is it possible to have d912 logs on a per GW2 client basis so if I crash > 1 client around the same time I can easily associate the crash with the respective account/client?

**Comment by ShiftLeftLogical** [comment]
This is probably a different issue. Feel free to close and I will re-file. I apparently cannot read.

**Comment by megai2** [comment]
Mutltiboxing is not working now, i need to add write lock for it to work properly.

On other things:
Are you sure that you removed d912pxy fully, the d3d9.dll from bin64 and d912pxy folder?
And when did that happen? on startup or ingame?

**Comment by ShiftLeftLogical** [comment]
I am not sure that I properly removed d912pxy from bin64 in that I used the uninstall script which I believe restores the previous d3d9.dll in bin64.

Part of the reason I believe that I should file separately goes to your second question: This issue happens fractions of a second after procmon shows GW2.exe has spun up.

I'll note I only went to these lengths of removing d912pxy as this problem emerged in the first place, seemingly out of nowhere in that nothing was apparently causal other than starting GW2.exe. (I suspected there were/are shared resource / mutex issues with d912pxy as often one client will freeze when running alongside other clients ... but I have been so impressed with your trajectory, I didn't want to start filing bugs against multibox issues just yet.)

**Comment by megai2** [comment]
> 
> 
> I am not sure that I properly removed d912pxy from bin64 in that I used the uninstall script which I believe restores the previous d3d9.dll in bin64.
> 
> Part of the reason I believe that I should file separately goes to your second question: This issue happens fractions of a second after procmon shows GW2.exe has spun up.
> 
> I'll note I only went to these lengths of removing d912pxy as this problem emerged in the first place, seemingly out of nowhere in that nothing was apparently causal other than starting GW2.exe. (I suspected there were/are shared resource / mutex issues with d912pxy as often one client will freeze when running alongside other clients ... but I have been so impressed with your trajectory, I didn't want to start filing bugs against multibox issues just yet.)

When client asks d3d9 device it can handle startup crash and try to ask another one, but memory will be not released.
So when you see endless memory eating and crash on startup, there is something wrong with installation of mod.

**Comment by megai2** [comment]
About lag spikes. What is found

1. Windows Defender doing some "nice" things.
How to detect: Out-of-nowhere swap chain recreation in logs
Solution: Disable it/Whitelist gw2 and d912pxy

2. async texture load can't keep up with per-frame requests
Solution: up in latest commits

**Comment by ShiftLeftLogical** [comment]
I whitelisted the exe/dll(s) in question, I did notice swap chains in the logs but I will need to read up on the concept as I do not know if the ones I observed are "out of nowhere" or expected. (Note: Do not whitelist the gw2 folder, coherentUI will throw a fit, probably not smart security wise either.)

I pulled the code prior to latest release and have yet to crash. I have limited my multiboxing for the time being but so far so good even when multiboxing, maybe just luck, I do not know all the locks/sync you need to put in place.

**Comment by megai2** [comment]
No more lag spikes are found for me.

RAM usage can be configured in pooling section(mostly)

One thing that can heavily lag out client is a client side shader cache cleanup. 
Avoid this via keep_pairs=1.

**Comment by megai2** [comment]
If there is more of that problem, please comment with some data on it.
