### ISSUE TITLE
About Arcdps

### ISSUE THREAD

**Issue by ReallLins** [megai2/d912pxy#122]
When the file name is d3d9_mchain and d912pxy, the installation is invalid. When d3d9_chainload is selected, the plugin can be used normally, but the percentage of life bar of arcdps is invalid.

**Comment by megai2** [comment]
Life bars will not work with d912pxy due to d3dx used in that pass.
d3d9_mchain will not work, or will work but not load GW 2 Radial
d912pxy.dll will only work with patched GW 2 Radial.
