### ISSUE TITLE
RAM trashing with ArcDPS 

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#123]
#119 Here's the Basic RAM Usage with and without ArcDPS (location Mistlock Sanctuary, both screenshots taken after 5min of loading and walking):

**With ArcDPS**
![Taskmgr_2019-04-17_22-13-41](https://user-images.githubusercontent.com/45238047/56320934-96235580-6165-11e9-9b6a-b30fa3df86a1.png)

**Without ArcDPS**
![Taskmgr_2019-04-17_22-59-08](https://user-images.githubusercontent.com/45238047/56320944-9d4a6380-6165-11e9-8457-0f4fe275170d.png)

There should be a compatibility issue with ArcDPS somewhere. Because the RAM usage with only ArcDPS, without D912PXY, is the same of screenshot two.

P.S: I've done a clean install of Windows 10 1809 and Guild Wars 2, so the report is reliable.

_Originally posted by @KleyArk in https://github.com/megai2/d912pxy/issues/13#issuecomment-484261521_

**Comment by megai2** [comment]
7gb with and without for me, maybe you not even load it without arc?

**Comment by KleyArk** [comment]
> 
> 
> 7gb with and without for me, maybe you not even load it without arc?

As i wrote in my post, both screens are taken after 5 min after loading. I can confirm you that the game doesn't use that amount of memory without ArcDPS.

**Tech Specs**

CPU: Intel Core i7 4770
GPU: Nvidia GTX 1080
Driver Version: 425.31
OS: Windows 10 1809
RAM: DDR3 16GB 1600Mhz

**Game Settings**
![GW2Settings](https://user-images.githubusercontent.com/45238047/56377806-89593d00-620b-11e9-8c2a-f72b7b5ba028.png)

**Comment by megai2** [comment]
> 
> 
> > 7gb with and without for me, maybe you not even load it without arc?
> 
> As i wrote in my post, both screens are taken after 5 min after loading. I can confirm you that the game doesn't use that amount of memory without ArcDPS.
> 
> **Tech Specs**
> 
> CPU: Intel Core i7 4770
> GPU: Nvidia GTX 1080
> Driver Version: 425.31
> OS: Windows 10 1809
> RAM: DDR3 16GB 1600Mhz
> 
> **Game Settings**
> ![GW2Settings2](https://user-images.githubusercontent.com/45238047/56377923-d210f600-620b-11e9-9182-768341a5c65d.png)

I mean, you sure that d912pxy is loaded when you switch off ArcDPS?

**Comment by KleyArk** [comment]
> 
> 
> > > 7gb with and without for me, maybe you not even load it without arc?
> > 
> > 
> > As i wrote in my post, both screens are taken after 5 min after loading. I can confirm you that the game doesn't use that amount of memory without ArcDPS.
> > **Tech Specs**
> > CPU: Intel Core i7 4770
> > GPU: Nvidia GTX 1080
> > Driver Version: 425.31
> > OS: Windows 10 1809
> > RAM: DDR3 16GB 1600Mhz
> > **Game Settings**
> > ![GW2Settings2](https://user-images.githubusercontent.com/45238047/56377923-d210f600-620b-11e9-9182-768341a5c65d.png)
> 
> I mean, you sure that d912pxy is loaded when you switch off ArcDPS?

Absolutly yes.
This is the RAM usage after almost 2h, without ArcDPS:
![RAMusage](https://user-images.githubusercontent.com/45238047/56382041-ba8b3a80-6216-11e9-92aa-3d09730b58c9.png)

**Comment by megai2** [comment]
Domain of Vabbi, Vehjin palace wp, your settings.

DX9/w ArcDPS: 2.4 GB
DX12/w ArcDPS: 3.2 GB
DX12: 3.1 GB

So i think that you are not running d912pxy when you switch off ArcDPS.

**Comment by KleyArk** [comment]
This is my test, Avg FPS taken with MSI Afterburner + Rivatuner.

**Execution**
Walking around in Lion's Arch - Trader's Forum Waypoint, from Bank area to the Mystic Forge.

**Results**
DX12/w ArcDPS (Chainload): 3.8GB - 40/41 Avg FPS
DX12/w ArcDPS+TacO (Chainload): 4,2GB +  ~510MB TacO
D12: 4.3GB - ~40 Avg FPS
D12 (Chainload): ~3GB - 39/40 Avg FPS
D9: ~3GB - 38/39 Avg FPS

Question: Is it possible to install and use D912PXY in chainload without ArcDPS?

**Comment by megai2** [comment]
>
> Question: Does it works D912PXY installed and used as chainload without ArcDPS?

No. And as you can see by memory usage this is quite noticeable.

**Comment by megai2** [comment]
Related to #119

**Comment by KleyArk** [comment]
**Test 2**
Executed in Wayfarer Foothills - Grawlenfjord Waypoint

DX9: 1.8GB / 95 Avg FPS
DX9/w ArcDPS: 1.9GB / 95 Avg FPS
DX12: Max 2.7-2.9GB / 99 Avg FPS
DX12/w ArcDPS: 2.7-2.9GB / 99 Avg FPS
DX12/w ArcDPS+TacO: 2.7-2.9GB + ~510MB / 82 Avg FPS

**Comment by megai2** [comment]
>
> Anyway, there are still crashes using D912PXY with ArcDPS + TacO in populated/high memory usage zones.
> Also D912PXY creates a crash log all the times i quit from the game.

Attach it to crash reports

**Comment by KleyArk** [comment]
**Crash during exit**
[crash_report.zip](https://github.com/megai2/d912pxy/files/3099481/crash_report.zip)
