### ISSUE TITLE
Game crash at loading screen

### ISSUE THREAD

**Issue by derbayer36** [megai2/d912pxy#126]
The game freezes when I press windows buttom or windows+d during the loading screen (fullscreen mode).

1. Windows 10 update ver 1903
2. Hardware info: I7 4700HQ, 16GB, GTX 870M
3. Drivers: Latest
4. d912pxy version: Latest
5. Log file:

https://mega.nz/#!0wFx0CIZ!WJSxGXSqgduvXhxnGtSfF9rl2-ok0KMS0Mme4mfq0gs

**Comment by megai2** [comment]
Fixed on latest release. If still encountered, consider using windowed fullscreen mode.
