### ISSUE TITLE
How do i know if it loaded correctly? 

### ISSUE THREAD

**Issue by Olian04** [megai2/d912pxy#127]
I just followed the install instructions. But i don't know if it installed successfully. Is there a way to determine if the game is using d912pxy when its running?

**Comment by megai2** [comment]
1. Log files should show up in d912pxy folder
2. More RAM usage
3. Character icons on character select screen should be bugged by default

**Comment by Olian04** [comment]
@megai2 alright. Turns out the installer crashed when i typed "install" instead of simply pressing enter. Now its loaded. 

> Character icons on character select screen should be bugged by default

"by default"? Is there a way to fix it?

**Comment by megai2** [comment]
> 
> 
> @megai2 alright. Turns out the installer crashed when i typed "install" instead of simply pressing enter. Now its loaded. (the character icons are bugged and its producing logs)
> 
> > Character icons on character select screen should be bugged by default
> 
> "by default"? Is there a way to fix it?

Enable PSO precompile https://github.com/megai2/d912pxy/wiki/Config.ini#sdb
But note that this will create extra RAM usage!

**Comment by megai2** [comment]
Questions answered.
