### ISSUE TITLE
Crash File

### ISSUE THREAD

**Issue by rcjrulz** [megai2/d912pxy#128]
I get these crash files generated in the dx12 folder. It doesnt crash the game, but every time i open the gw2.exe file, the crash report is generated. i have now stacked up almost 45+ crash reports.

1. Windows 10 update ver : 1809
2. Hardware info: i7 8700k @ 4.8, 16GB DDR4, 1080 GTX
3. GPU Driver version : 425.31
4. Version of d912pxy used : d912pxy_v0.9.8.3b_r202
5. Log files :

[crash.txt](https://github.com/megai2/d912pxy/files/3108334/crash.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3108343/log.txt)

I dont have any overlays other than nvidia's game filter running when it loads up. i have disabled and checked also, yet the error gets generated.

**Comment by megai2** [comment]
High priority messages are repeated/translated to crash log, but they can be neutral.

**Comment by rcjrulz** [comment]
so these errors are not much an issue i take then.
