### ISSUE TITLE
Crash on 'Contacts Dialog'->Context Menu->'Send Mail'

### ISSUE THREAD

**Issue by RMRx** [megai2/d912pxy#129]
**Describe the bug**
GW2 Client crashes on trying to send ingame mal from 'Contacts Dialog' window.

**To Reproduce**
* Open 'Contacts Dialog' window
* Opening the context menu to a contact entry via right-click
* Selecting the entry 'Send Mail' via left-click

**Standard information**
Reports.zip: d912pxy (config.ini, crash.txt, log.txt), DxDiag.txt, GW2-Crash-Report.txt
[Reports.zip](https://github.com/megai2/d912pxy/files/3118817/Reports.zip)

**Comment by megai2** [comment]
Client assertion crash. 
Can't reproduce, maybe something more on this?

**Comment by RMRx** [comment]
I've tried to narrow down the cause, to no avail. However, the crashes ceased with v0.9.8.6+. 
TY for your work, it is greatly appreciated.
