### ISSUE TITLE
Crash on trying to use permanent hair stylist kit

### ISSUE THREAD

**Issue by Twintale** [megai2/d912pxy#131]
When you click 3-rd+ time on permanent hair stylist kit in a row or just too fast - the game crashes with KERNELBASE.dll error or d3d9.dll. (can happen on first click as well). Crash happens on 0.9.8.7. On 0.9.8.5 - works fine.

**Comment by megai2** [comment]
Please follow this https://github.com/megai2/d912pxy/wiki/Reporting-crashes
