### ISSUE TITLE
game crashing on launch

### ISSUE THREAD

**Issue by digitalruse** [megai2/d912pxy#132]
**Describe the bug**
Game crashes as soon as I get to the character select screen.

**To Reproduce**
1. Run game
2. Wait for char screen to load

**Expected behavior**
Should be able to select a character and log in.

**Standard information**

1. Windows 10 update ver
2. Hardware info: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, 32GB System RAM, Radeon Pro 560X 4GB
3. GPU Driver version - Catalyst 18.10.2
4. Version of d912pxy used: Beta v0.9.9
5. Log file - attached
**Additional context**
This was working fine for the longest time (aside from missing portraits) and suddenly just gave up.  Tried installing the most current release clean to resolve it too.

[gw2crash.txt](https://github.com/megai2/d912pxy/files/3136454/gw2crash.txt)
[crash.txt](https://github.com/megai2/d912pxy/files/3136455/crash.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3136456/log.txt)

**Comment by megai2** [comment]
Try to install Debug version, when installer asks "Use standart release?" answer  N and then 3.
Reproduce and attach log file from P7logs and d912pxy/crash.txt here.

**Comment by megai2** [comment]
Also try setting this in config if v0.9.8.7 worked(at least in terms to loading game).
`[pooling]
upload_alloc_step=0`

**Comment by oldnordic** [comment]
Hello, 

Microsoft Windows 10 (10.0) Professional 64-bit   (Build 17134)
NVIDIA GeForce RTX 2060
AMD Ryzen 5 1600 Six-Core Processor
Nvidia Driver 430.39


I have the same issue, I tried to upload_alloc_step=0 and still crash.
[crash.txt](https://github.com/megai2/d912pxy/files/3137788/crash.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3137789/log.txt)

[20190502-13205900.txt](https://github.com/megai2/d912pxy/files/3137791/20190502-13205900.txt)

**Comment by megai2** [comment]
Install "Graphics tools" first before running Debug, follow https://www.thewindowsclub.com/install-graphics-tools-in-windows-10 to do this.

**Comment by oldnordic** [comment]
Hello, 

Microsoft Windows 10 (10.0) Professional 64-bit   (Build 17134)
NVIDIA GeForce RTX 2060
AMD Ryzen 5 1600 Six-Core Processor
Nvidia Driver 430.39


I have the same issue, I tried to upload_alloc_step=0 and still crash.

[20190502-15454600.txt](https://github.com/megai2/d912pxy/files/3138286/20190502-15454600.txt)

[log.txt](https://github.com/megai2/d912pxy/files/3138288/log.txt)
[crash.txt](https://github.com/megai2/d912pxy/files/3138289/crash.txt)

Ok, I have installed graphics tools and attached the new logs.

**Comment by megai2** [comment]
> 
> 
> Hello,
> 
> Microsoft Windows 10 (10.0) Professional 64-bit (Build 17134)
> NVIDIA GeForce RTX 2060
> AMD Ryzen 5 1600 Six-Core Processor
> Nvidia Driver 430.39
> 
> I have the same issue, I tried to upload_alloc_step=0 and still crash.
> 
> [20190502-15454600.txt](https://github.com/megai2/d912pxy/files/3138286/20190502-15454600.txt)
> 
> [log.txt](https://github.com/megai2/d912pxy/files/3138288/log.txt)
> [crash.txt](https://github.com/megai2/d912pxy/files/3138289/crash.txt)
> 
> Ok, I have installed graphics tools and attached the new logs.

It was working before?

**Comment by oldnordic** [comment]
Yes, on the previous version, btw amazing work :)

**Comment by megai2** [comment]
@oldnordic  your log shows that something is blocking exclusive fullscreen and then DXGI locks up itself.

**Comment by oldnordic** [comment]
Thank you for the reply, I will take a look and check what is happening :)

**Comment by megai2** [comment]
As debug messages from d3d12 can be useless(like ERROR_UNKNOWN) or even non existent, better to check from what build this crash start to happen 

look for builds on https://ci.appveyor.com/project/megai2/d912pxy/history page
to download specific build open it and select artifacts, then download zip

**Comment by digitalruse** [comment]
P7log attached. 
[p7log.zip](https://github.com/megai2/d912pxy/files/3138579/p7log.zip)

**Comment by megai2** [comment]
> 
> 
> P7log attached.
> [p7log.zip](https://github.com/megai2/d912pxy/files/3138579/p7log.zip)

Sorry, i missed, it should be 4 on installer, not 3 i.e. "Use standart release?" answer N and then 4.
Anyway this log is detailed and shows an GPU error, so proper Debug version should show up some info.

**Comment by AlraiLux** [comment]
Does setting upload_alloc_step = 0 fix it?

**Comment by megai2** [comment]
@digitalruse i'm correct that it stopped working without updates?

**Comment by oldnordic** [comment]
ok in my case, razer central installed razer cortex, and that was affecting the game using the "boost" I uninstalled razer cortex and all runs fine now.

**Comment by megai2** [comment]
that looking to be fixed, if that is still happens - pls comment on this

**Comment by digitalruse** [comment]
[crash2.txt](https://github.com/megai2/d912pxy/files/3164832/crash2.txt)

Sorry. I had to go out of town for a couple of days.  I believe I did this correctly. I had to add the "Graphics Tools" and only see the attached log file. Let me know if you need a different one.

I also tried the hotfix release and that did not help.

**Comment by megai2** [comment]
> 
> 
> [crash2.txt](https://github.com/megai2/d912pxy/files/3164832/crash2.txt)
> 
> Sorry. I had to go out of town for a couple of days. I believe I did this correctly. I had to add the "Graphics Tools" and only see the attached log file. Let me know if you need a different one.
> 
> I also tried the hotfix release and that did not help.

check GPU drivers (not updated or updated to unstable/broken version) and RAM usage

**Comment by digitalruse** [comment]
Interestingly enough, using this build of drivers fixed issues with my other games.
Clean install: [crash.txt](https://github.com/megai2/d912pxy/files/3164852/crash.txt)
Clean install w/ Option 4: [crash1.txt](https://github.com/megai2/d912pxy/files/3164855/crash1.txt)
:

**Comment by digitalruse** [comment]
Going to try some different drivers now too

**Comment by digitalruse** [comment]
Radeon 19.1.2 seems to be stable, but I'm also not seeing the improvements like I previously saw in earlier d912pxy (avg 42 frames in mistlock and now average 32).  Not sure what else to try, but it seems stable enough for now.

**Comment by digitalruse** [comment]
[crash3.txt](https://github.com/megai2/d912pxy/files/3170808/crash3.txt)

NVM. Appears to be "crashing" on game exit now too.

**Comment by megai2** [comment]
if you use debug version you will not see any good results, use the release one
i'm not seeing any of "exit crash" data, so maybe that's other things causing problems, like gw2radial
