### ISSUE TITLE
Water in Straits of Devastation bugged

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#133]
Water in Straits of Devastation without dx12pxy:
![Gw2-64_2019-05-03_13-16-46](https://user-images.githubusercontent.com/880507/57134429-75ceda00-6da6-11e9-9567-a932a94392ed.jpg)

Water in Straits of Devastation with dx12pxy 0.9.9:
![Gw2-64_2019-05-02_21-34-52](https://user-images.githubusercontent.com/880507/57134435-7c5d5180-6da6-11e9-8bc5-478a1102b55e.jpg)

_Originally posted by @Ramontique in https://github.com/megai2/d912pxy/issues/15#issuecomment-489063911_

**Comment by changeofplans** [comment]
Siren's landing has the same issue last I checked
