### ISSUE TITLE
Texture Artifacts/Flickering

### ISSUE THREAD

**Issue by KleyArk** [megai2/d912pxy#138]
**Describe the bug**
Some textures in the entrance of Raid Wing 2 flickers.

**To Reproduce**
Join Wing 2, stand in the bush (look the screenshot) and move the camera around.

**Screenshots**
![GW2-64_Fk12i](https://user-images.githubusercontent.com/45238047/57527991-5c430a80-7331-11e9-8bfc-9f6e185c3455.png)

**Standard information**

1. Windows 10 1809
2. Hardware info: Intel Core i7 4770, 16GB DDR3, Nvidia GTX 1080
3. Driver 425.31
4. Version of d912pxy: r233 (0.9.9 hotfix 1)

**Game settings**
![Gw2-64_lFvwP6FX3f](https://user-images.githubusercontent.com/45238047/57528078-9dd3b580-7331-11e9-820b-d311f682fb30.png)

**Comment by megai2** [comment]
r248, all fine. i suppose that was some shader cache miss

**Comment by megai2** [comment]
running beetle mount both on dx9 and dx12 gives terrain flicker

i close this for now as this is a game behaivour
