### ISSUE TITLE
"hlsl generator not support passed dst modifier" related crashes

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#14]
Some crashes are triggered after that error being logged. On normal it should just ignore all draw calls related with errored out shader. But in fact can be some delayed logic check missing.

**Comment by WanYaa** [comment]
I think this happend to me today in silverwastes 
v0.9.6.3a
timestamp of d912pxy_crash is about 5 minutes earlier as latest entry in p7log
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2857789/d912pxy_crash.txt)
[20190212-19320500.zip](https://github.com/megai2/d912pxy/files/2857790/20190212-19320500.zip)

**Comment by megai2** [comment]
Need something to reproduce it.

**Comment by WanYaa** [comment]
v0.9.6.4a
without arcdps

d912pxy_crash.txt timestamp 10:43
actual crash happened 10:55 while leaving lions arch to lornar's pass via portal at cavern waypoint
after relogin I was still in lions arch but not at the portal to lornas pass 
but on the portal to gendaren fields
could not reproduce error 
[20190217-10425000.zip](https://github.com/megai2/d912pxy/files/2872822/20190217-10425000.zip)
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2872823/d912pxy_crash.txt)

next crash while switching chars
d912pxy_crash.txt timestamp 17:28
actual crash at 17:35
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2873158/d912pxy_crash.txt)
[20190217-16033600.zip](https://github.com/megai2/d912pxy/files/2873159/20190217-16033600.zip)
could not reproduce it either

overall the addon is pretty stable but sometimes on apprently random occasion it crashes the client
not sure if this logs are helpfull without steps to reproduce the error :-(

**Comment by megai2** [comment]
What ingame settings you use?

**Comment by WanYaa** [comment]
![settings](https://user-images.githubusercontent.com/47284752/52964291-3a755f80-33a2-11e9-8383-c1efef6679d0.jpg)

**Comment by megai2** [comment]
runned today for summary of ~5h, not encountered it, will check later with attached settings

**Comment by megai2** [comment]
shader bytecode with version less then sm 2_0 don't have opcode length in it, so this breaks whole recompilation process, will try to add opcode length tables, should work.

**Comment by megai2** [comment]
disabled sm 1_x recompilation as temporary fix for crash behaivour
