### ISSUE TITLE
Crash at Launcher Startup

### ISSUE THREAD

**Issue by Aussiemon** [megai2/d912pxy#141]
**Describe the bug**
Guild Wars 2 intermittently crashes before the launcher appears; instead showing the "Send crash reports to ArenaNet" dialogue window. Unlike #132, this issue occurs before the game launches, and does not happen every time.

**To Reproduce**
1. GW2 is started via batch script with the command:
"start "" "C:\Games\Guild Wars 2\Gw2-64.exe" -maploadinfo"
2. Crash occurs maybe 1 in 10 startup attempts.

**Expected behavior**
The launcher should appear without crashing.

**Standard information**

1. Windows 10 Enterprise Version 10.0.17134 Build 17134
2. Hardware info: i7 8700k, DDR4 3200 CL14, Nvidia GTX 1080
3. GPU Driver version 430.64 (26.21.14.3064)
4. Version of d912pxy: Beta v0.9.9 Hotfix 1
5. Log file
[crash.txt](https://github.com/megai2/d912pxy/files/3170165/crash.txt)
6. DxDiag Information
[DxDiag.txt](https://github.com/megai2/d912pxy/files/3170169/DxDiag.txt)

**Comment by megai2** [comment]
d912pxy are loaded fully on actual game load, not launcher load, so there will be zero to none log/crashlog
Attach the game's crash.dmp and log.

**Comment by Aussiemon** [comment]
I might've been mistaken about the timing, because I've just experienced the same crash twice at the point where the launcher transitions to the game window. After the launcher disappears, GW2 crashes before the game window appears. It seems to happen more frequently on cold starts.

I've attached the crash dump, GW2 crash report, d912pxy crash report, and d912pxy log from the last failure:
[CrashDmp.zip](https://github.com/megai2/d912pxy/files/3175255/CrashDmp.zip)
[gw2-crash-log.txt](https://github.com/megai2/d912pxy/files/3175251/gw2-crash-log.txt)
[crash.txt](https://github.com/megai2/d912pxy/files/3175250/crash.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3175252/log.txt)

**Comment by megai2** [comment]
```
50F3A [ info ] swap chain | Window: 303C2 Width: 2560 Height: 1440 Fullscreen: 1 Buffers: 2 Format: 21 

50F59 [ info ] swap chain | Window: 303C2 Width: 2560 Height: 1440 Fullscreen: 1 Buffers: 2 Format: 21 

51266 [ info ] swap chain | Window: 303C2 Width: 2560 Height: 1440 Fullscreen: 1 Buffers: 2 Format: 21 

51285 [ info ] swap chain | Window: 303C2 Width: 2560 Height: 1440 Fullscreen: 1 Buffers: 2 Format: 21 

51331 [ error ] helper | Exception: E06D7363 

51331 [ error ] swap chain | Fullscreen 

51331 [ error ] swap chain | HR: 887A0022 

51331 [ error ] swap chain | Init error, 1 in sequence 

51331 [ info ] swap chain | Window: 303C2 Width: 2560 Height: 1440 Fullscreen: 1 Buffers: 2 Format: 21 

51331 [ error ] helper | Exception: E06D7363 

51341 [ error ] swap chain | Init 

51341 [ error ] swap chain | HR: 80070005 

51341 [ error ] swap chain | Init error, 2 in sequence 

51341 [ info ] swap chain | Window: 303C2 Width: 2560 Height: 1440 Fullscreen: 1 Buffers: 2 Format: 21 

51341 [ error ] helper | Exception: E06D7363 ```

This is caused by antivirus/other fullscreen apps blocking exclusive screen access for some reason.

**Comment by Aussiemon** [comment]
Could be related to Windows Defender, W10 Game Mode, or something similar then. It seems like this is pretty conclusively not a d912pxy issue, at least.

I'll post an update if I find the exact cause.
