### ISSUE TITLE
The computer is not responding

### ISSUE THREAD

**Issue by zhouhuichen741** [megai2/d912pxy#143]
The monitor has a black screen, the game has sound, the computer cannot be operated, and it can only be restarted.

**Comment by zhouhuichen741** [comment]
The previous version crashes, it will be restored after the black screen, and the computer is not responding after the black screen.

**Comment by zhouhuichen741** [comment]
version:v0.9.9.2b

**Comment by zhouhuichen741** [comment]
[crash5.txt](https://github.com/megai2/d912pxy/files/3197144/crash5.txt)
[crash4.txt](https://github.com/megai2/d912pxy/files/3197145/crash4.txt)

**Comment by megai2** [comment]
There is many overlays and custom d3d9 files, follow https://github.com/megai2/d912pxy/wiki/Reporting-crashes to report properly

**Comment by zhouhuichen741** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/3199431/log.txt)

**Comment by zhouhuichen741** [comment]
![F9IHUO1~$A1_OSEUVIRFF6U](https://user-images.githubusercontent.com/50648819/58045772-09115900-7b76-11e9-9550-678a1142d0d1.png)

**Comment by megai2** [comment]
https://github.com/megai2/d912pxy/wiki/Reporting-crashes
^ please read it
Update drivers, run it without any other overlays and attach crash.txt and log.txt from the same run.
