### ISSUE TITLE
Iris Pro 5100 dx 11.1 80% compatible, not suitable crash

### ISSUE THREAD

**Issue by xxskorpion88xx** [megai2/d912pxy#144]
Hi,

i have a macbook pro late 2013 with integrated graphic card, im paying low setting 25fps but i couldnt istall the d912pxy due to no suitable GPU found.
I'm running Gw2 64bit from Windows 10 on the MbP late 2013 since i bought it

here my gpu https://www.notebookcheck.it/Intel-Iris-Graphics-5100.106542.0.html

[crash4.txt](https://github.com/megai2/d912pxy/files/3198913/crash4.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3198914/log.txt)

i tried to Press N to perform a not custom istallation but after pressing N it says press a button to contine and close withouth istall

**Comment by megai2** [comment]
it says that is should work with 80% probability.
errors show that it can't handle needed features
