### ISSUE TITLE
Skyscale horns and harness are black

### ISSUE THREAD

**Issue by digitalruse** [megai2/d912pxy#145]
**Describe the bug**
When using the skyscale, the horns and harness are black and do not load with textures.  Loading the game with a clean bin64 corrects the issue.

**To Reproduce**
Install d912pxy and run gw2.
Mount Skyscale.

**Expected behavior**
Mount should load with all textures.

**Standard information**

Windows 10
Hardware info: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz, 32GB System RAM, Radeon Pro 560X 4GB
GPU Driver version - Catalyst 19.1.2
Version of d912pxy used: Most current release

**Comment by digitalruse** [comment]
![gw008](https://user-images.githubusercontent.com/4588179/58138098-b6718480-7be9-11e9-998e-a0398bb41c3b.jpg)

Interestingly, it loads fine on the preview window for mount selection and dyes.

**Comment by megai2** [comment]
same as #117 
i will capture that thing and look out for a fix as soon as i get that mount
