### ISSUE TITLE
Crashes while multiboxing

### ISSUE THREAD

**Issue by strigefleur** [megai2/d912pxy#146]
I play with like 5 GW2 windows run simultaneously.
In random moments (not dependant on high load) one or two of those may crash.

Log: "0 | "shader replace error" | hr = FFFFFFFF "

All windows are in fullscreen windowed mode.
4 of 5 are set to almost lowest possible gfx.

Tested on 3 different PC setup (all Windows 10 x64 based).
However it seems to happen more often on GTX 1080 GPU than AMD ones.

**Comment by megai2** [comment]
You simply run out of memory running 5 instances with dx12. 
Comment out if that is not your case.
