### ISSUE TITLE
Screen-tearing on FreeSync monitor after Win10 1903 update

### ISSUE THREAD

**Issue by LegendaryHeretic** [megai2/d912pxy#147]
CPU: i7-8086k
RAM: 32GB DDR4 2666 MHz
GPU: GTX 1660 ti
Monitor: LG 27UD68-P

With FreeSync enabled in the Nvidia settings and MONITOR settings, screen-tearing is present on any variation of GW2 settings - V-sync, frame limiters, refresh rate, etc. With FreeSync disabled in the monitor settings, the screen-tearing stops.
Prior to the 1903 update, this wasn't present. I can still use d912pxy comfortably with FreeSync disabled.

**Comment by megai2** [comment]
What about gw2 windowed/windowed fullscreen/fullscreen variation?

It should work fine with that gw2 options
```
Mode: Windowed Fullscreen
VSync: On
```

**Comment by LegendaryHeretic** [comment]
I'm going to sound crazy, but I can't reproduce it anymore. The key difference:
After the 1903 update and not being able to resolve the screen-tearing, I just removed dx912pxy, and left FreeSync enabled. Prior to posting this message, I reinstalled the mod to verify the issue was still present. It was, and I disabled FreeSync (in the monitor settings, not Nvidia settings) for the first time to keep the mod installed. To validate your question of the windowed variations, I re-enabled FreeSync and **now** there is no issue at all (on any settings, including windowed/fullscreen). I guess it's possible my monitor was the cause and needed FreeSync to be toggled.

**Comment by megai2** [comment]
maybe there was another update too, or just "reboot it" bug

**Comment by LegendaryHeretic** [comment]
The issue is back after a few hours with the pc being turned off. Resetting
the monitor doesn't help like I thought fixed it before. Winowed mode is
smooth with and without Vsync on, but Windowed Fullscreen and normal
Fullscreen are tearing with and without vsync. Even the Nvidia overlay is
tearing and has flashing streaks when I open it.

**Comment by megai2** [comment]
turned off or sleep/hibernate?

**Comment by megai2** [comment]
or maybe nvidia gpu can't keep up with freesync monitor? brand wars you know

**Comment by LegendaryHeretic** [comment]
It was fully shut down and I've rebooted as well.

> or maybe nvidia gpu can't keep up with freesync monitor? brand wars you know
Could be, but it was running fine before the 1903 update and my nvidia drivers haven't updated since then.

**Comment by LegendaryHeretic** [comment]
Did a little research and testing and found that:

1. Win10 now has a Variable Refresh Rate setting after 1903 that isn't fully accessible to all users yet (including myself)
2. Tried playing other games with g-sync enabled and it was so bad in some that I literally couldn't even see what was going on.

So I suppose that means I have to sit back and wait for MS and Nvidia to play nice with each other.
