### ISSUE TITLE
Latest version - r265 doesn't show ArcDPS windows

### ISSUE THREAD

**Issue by llitz** [megai2/d912pxy#148]
When running the Latest version, r265, with ArcDPS none of the ArcDPS windows are shown but ArcDPS is running (confirmed through logs).

Also, when you try to open an ArcDPS window (alt+shift+t) you can confirm pressing ESC once closes that window instead of opening the game "ESC" window.

**Comment by megai2** [comment]
That revision is compiled from bns-draft branch, so you "should" expect some errors

**Comment by llitz** [comment]
I am aware of that, just reporting what isn't working on case it was missed
(=

**Comment by megai2** [comment]
fixed that

**Comment by llitz** [comment]
Awesome, will keep testing and reporting if I find anything else, thanks!
