### ISSUE TITLE
Water surface disappears with low/medium shaders

### ISSUE THREAD

**Issue by RMRx** [megai2/d912pxy#149]
**Describe the bug**
Apparently the issue #43 returned; the water surface becomes invisible with low/medium shaders.

**To Reproduce**
1. Run game
2. Set shaders to low or medium
3. Head to [Ireko Tradecamp Waypoint]
4. Take alook at the water surface

**Screenshots**
[Screenshots @ imgur](https://imgur.com/a/sKepDD2)

**Standard information**
Version of d912pxy used: d912pxy_v0.9.9.4b1_r279
[logs.zip](https://github.com/megai2/d912pxy/files/3303806/logs.zip)

**Additional context**
NVIDIA System Information report created on: 06/19/2019 01:36:29
[Display]
Operating System:	Windows 10 Pro, 64-bit
DirectX version:	12.0 
GPU processor:		GeForce GTX 970
Driver version:		430.86
Driver Type:		DCH
Direct3D API version:	12
Direct3D feature level:	12_1
CUDA Cores:		1664 
Core clock:		1114 MHz 
Memory data rate:	7.01 Gbps
Memory interface:	256-bit 
Memory bandwidth:	224.32 GB/s
Total available graphics memory:	12244 MB
Dedicated video memory:	4096 MB GDDR5
System video memory:	0 MB
Shared system memory:	8148 MB
Video BIOS version:	84.04.36.00.F1
Bus:			PCI Express x16 Gen3
Device Id:		10DE 13C2 31601462
Part Number:		G401 0010
[Components]
nvui.dll		8.17.14.3086		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.14.3086		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.14.3086		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.14.3086		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.14.3086		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		26.21.14.3086		NVIDIA Workstation Server
nvWSS.dll		26.21.14.3086		NVIDIA Workstation Server
nvViTvSR.dll		26.21.14.3086		NVIDIA Video Server
nvViTvS.dll		26.21.14.3086		NVIDIA Video Server
nvLicensingS.dll		6.14.14.3086		NVIDIA Licensing Server
nvDevToolS.dll		26.21.14.3086		NVIDIA 3D Settings Server
nvDispSR.dll		26.21.14.3086		NVIDIA Display Server
nvDispS.dll		26.21.14.3086		NVIDIA Display Server
PhysX		09.19.0218		NVIDIA PhysX
NVCUDA.DLL		26.21.14.3086		NVIDIA CUDA 10.2.120 driver
nvGameSR.dll		26.21.14.3086		NVIDIA 3D Settings Server
nvGameS.dll		26.21.14.3086		NVIDIA 3D Settings Server

**Comment by Atsthio** [comment]
For me with Reflections set to "None" and Shaders "Low" or "Medium": water surface invisible too. 
With Reflections setting "All" or "Terrain&Sky" and any Shaders setting: water visible.

**Comment by kurim** [comment]
@RMRx, did you try this https://github.com/megai2/d912pxy/issues/15#issuecomment-504080092 to solve it? For me water come back with it.
