### ISSUE TITLE
some log error

### ISSUE THREAD

**Issue by frowlyk** [megai2/d912pxy#152]
Here is what i got from the crash.txt after launching the game.

However it doesn't look like something is going wrong .
Still i'm wondering where does this come from .

I have ArcDps and reshade installed , both in Bin64 directory ( the reshade instal put stuffs into gw2 main directory so i moved it to bin64 in order for pxy to hook it). 
Arc dps is D3d9.dll
Reshade is Dxgi.ddl
D912pxy is chainload so 

And i have this in crash log

0 | [00:00:00.002][PID 9564] hook_thread started

 1 | [00:00:00.005][PID 9564] Process name: G:\JEUX\Guild Wars 2\Gw2-64.exe

 2 | [01:06:39.562][PID 9564] Starting graphics hook in process G:\JEUX\Guild Wars 2\Gw2-64.exe

 3 | [01:06:39.563][PID 9564] CMipMap::CMipMap - offset = 204A0, address = 00007FFE19FA04A0

4 | [01:06:39.612][PID 9564] Hooked D3D9

 5 | [01:06:39.670][PID 9564] Hooked DXGI

 6 | [01:06:39.802][PID 9564] D3D1XState::InitDevice12: using queue 0000016717420B90 for thread 11864

 7 | [01:06:39.802][PID 9564] InitDevice12 finished with device 000001670AA26A30

 8 | [01:06:39.844][PID 9564] D3D1XState::InitOverlay12: initialized to 000001670AA26A30 (D3D12, window 0000000000180B60: 2560x1440)

 9 | [01:06:49.032][PID 9564] HandleSetDrawingState: Updating state to 'Overlay' (was 'Initialize')

Attached my log.txt

[log.txt](https://github.com/megai2/d912pxy/files/3329786/log.txt)

**Comment by frowlyk** [comment]
Here is a 2nd log.txt i had after reinstalling gw2+d912pxy ( nothing more)

[log.txt](https://github.com/megai2/d912pxy/files/3330107/log.txt)

Still some error , however it looks to work , even if the texture/shader loading is very long.

**Comment by megai2** [comment]
it's fine. if you want to keep that logs empty you can set enable_veh (or something like that) to 0 in config

but it will disable crash handler
