### ISSUE TITLE
[Blade&Soul] 64bit client doesn't work  on amd cards

### ISSUE THREAD

**Issue by GinzaJ** [megai2/d912pxy#153]
32 bit runs fine, but will not boot up the game at all

**Comment by megai2** [comment]
Read this first

1. https://github.com/megai2/d912pxy/wiki/Installing-for-Blade-&-Soul
2. https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by GinzaJ** [comment]
so i follow all the steps, but to avail it doesnt start at all,
![image](https://user-images.githubusercontent.com/17295258/60295719-68d7ee00-98f2-11e9-8a35-665c7dfccf11.png) when i run the debug this is what i get

**Comment by megai2** [comment]
Read this again https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by GinzaJ** [comment]
found the issue i just repaired game
