### ISSUE TITLE
Updated Release v1.1,arcdps not running

### ISSUE THREAD

**Issue by zhouhuichen741** [megai2/d912pxy#166]
Updated Release v1.1,arcdps not running

**Comment by zhouhuichen741** [comment]
Jul 14 12:07:03 arcdps 20190611.190540-300-x64
Jul 14 12:07:04 client: gw2 0x7FF7F8500000-0x7FF7FAA21000 (0xD6B43D57)
Jul 14 12:07:04 client: arcdps 0x7FFD84650000-0x7FFD846FF000 (0xFB61710F)
Jul 14 12:07:04 client: d3d9 0x7FFD608A0000-0x7FFD61319000 (0xC41FCE38)
Jul 14 12:07:04 client: chainloading d3d9
Jul 14 12:07:04 extensions: buildtemplates 0x7FFD9A980000-0x7FFD9A993000 (20190305.201717-289-x64, 0x7621E183)
Jul 14 12:07:04 extensions: extras 0x7FFD8EAF0000-0x7FFD8EB16000 (20190611.190514-300-x64, 0xEDD506DC)
Jul 14 12:07:04 config: loading from "E:\GuildWars2\addons\arcdps\arcdps.ini"

**Comment by zhouhuichen741** [comment]
After restoring Release v1.0, it will run normally.

**Comment by AlraiLux** [comment]
Seems there's an issue with 1.1 r323. Please wait for an update.

**Comment by zhouhuichen741** [comment]
> 看来1.1r323有问题了。请等待更新。
> 
> 编辑：看起来1.1是错误地从错误的分支构建的。哎呀。
> 链接到r322，即rc：[https：/ci.appveyor.com/project/mgai 2/d912pxy/builds/25959924/工件](https://ci.appveyor.com/project/megai2/d912pxy/builds/25959924/artifacts)

Wow! r322 is running normally

**Comment by megai2** [comment]
appveyour taked v1.1 branch instead of tag, should be fine rn
