### ISSUE TITLE
0 | "PSO item are not created" | hr = 80070057 

### ISSUE THREAD

**Issue by misterdapper** [megai2/d912pxy#170]
Continous PSO error in log file 0 | "PSO item are not created" | hr = 80070057

1. Set PSO compile and cache to 3
2. Run game
![gw115](https://user-images.githubusercontent.com/52939513/61260269-5eab5180-a732-11e9-9923-be53d84a7a50.jpg)

Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 18362) (18362.19h1_release.190318-1202)
                 Language: English (Regional Setting: English)
      System Manufacturer: ASUSTeK COMPUTER INC.
             System Model: TUF GAMING FX504GM_FX80GM
                     BIOS: FX504GM.307 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 CPUs), ~2.2GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16238MB RAM
                Page File: 7571MB used, 11099MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 144 DPI (150 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: Unknown
           DxDiag Version: 10.00.18362.0001 64bit Unicode

**Comment by megai2** [comment]
Is it fixed?

**Comment by megai2** [comment]
If you have this error in logs bug all things are working, that is not a problem.

**Comment by misterdapper** [comment]
Ok I was just worried it would crash my game at some point. It's spamming my logs with this error.

**Comment by misterdapper** [comment]
I set PSO compile and cache to 1. That at least stops the error from spamming my logs.
