### ISSUE TITLE
bns_ru crash report

### ISSUE THREAD

**Issue by Nirraen** [megai2/d912pxy#171]
[crash7.txt](https://github.com/megai2/d912pxy/files/3415118/crash7.txt)
![Client_VH0PJbHEDI](https://user-images.githubusercontent.com/15426767/61597536-8b6fd500-ac1a-11e9-847d-8a531c54daba.png)

**Standard information**

1. Windows 10 1903
2. AMD Ryzen 5 2600X, 16GB, 1050ti 
3. 417.35
4. is here https://vk.com/wall-156796493_4991
5. C:\Innova\bin64\d912pxy\crash7.txt

**Comment by megai2** [comment]
Read this first: https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by Drauk13** [comment]
Runtime Crash only playing with my gunner trying to go for ajanara or f12
