### ISSUE TITLE
[crash][BnS] GPU crash on load screen/game load

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#172]
hi,
always when i try to log in on a char i get loading screen and at the end before i can reach zone i get crash, error you can see at picture, also vram that is used!
![bns_crash](https://user-images.githubusercontent.com/21971955/62000189-11839400-b0d1-11e9-90e7-5743cd2a82d8.png)
`1.Make sure that the game runs without d912pxy!`
Its running without/with bnsbuddy and also without d912pxy!
`2.Next, update your driver and directx9.(link to dx9 https://www.microsoft.com/en-us/download/details.aspx?id=34429)`
my GPU driver is actually and the link i couldn´t install. It says that i must run this on Windows 98/Millenium Edition/2000/XP/Server 2003 and i have Windows 10^^
`3.If you see something related to missing DLL file, also try to install MSVC redistributable(link to vc redist https://aka.ms/vs/15/release/vc_redist.x64.exe)`
i installed this!
`4.Next, be sure you are on latest release of d912pxy.`
i used d912pxy version: v1.3 r345
`5.Next, if you use some other overlay/addon/tool that hooks graphics API, please, try to run d912pxy without it first. If crash occurs only with overlay/addon/tool, please add this info to your report!`
i went bnsbuddy + addons off but problem still the same!

>Check that you are not hitting 100% VRAM usage

I have 4gb Vram and its not coming over 2,5gb
`7.Then, if you are still here, make sure that config option enable_veh is set to 1, try to reproduce your problem and post it here with`
i set enable_veh to 1 and will post it now^^
[crash(without bnsbuddy_or_addons).txt](https://github.com/megai2/d912pxy/files/3438671/crash.without.bnsbuddy_or_addons.txt)
[crash(without bnsbuddy_or_addons)_2.txt](https://github.com/megai2/d912pxy/files/3438672/crash.without.bnsbuddy_or_addons._2.txt)
[crash(without bnsbuddy_or_addons)_3.txt](https://github.com/megai2/d912pxy/files/3438673/crash.without.bnsbuddy_or_addons._3.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3438674/log.txt)
Extra Infos from Installguide that i did
`1.Remove any other old d912pxy folder.`
no other folder exist
`2.Unpack the d912pxy archive next to 64-bit Client.exe`
that i did: C:\Program Files (x86)\NCSOFT\BnS\bin64\d912pxy
`3.Install via installer to root folder or copy "d912pxy/dll/release/d3d9.dll" next to "Client.exe".`
that i did also!
`4.Rename "d912pxy/bns_config.ini" file to "d912pxy/config.ini".`
that i did also!

_Originally posted by @gamillton in https://github.com/megai2/d912pxy/issues/13#issuecomment-515718823_

**Comment by megai2** [comment]
https://github.com/megai2/d912pxy/issues/13#issuecomment-515742429

**Comment by rushuna86** [comment]
try updating to current version. I was having this same issue when rejoining F8 after a disconnect will keep getting that Runtime Error. And the crashlog would only show "PSO item are not created" | hr = 80070057
 And will only be able to rerun the game once I'd time out from the party. Sometimes it woud do that on a fresh start as well. Stopped getting it after HF2 update.

**Comment by megai2** [comment]
do you run game from ncsoft launcher?

**Comment by megai2** [comment]
As Dx12 debug runtime gives zero help on things, Release_d dll need to be used instead of Debug one.
Take it from d912pxy/dll/Release_d/ , keep enable_veh=1 and dx_debug=1 .

There is one thing i should warn you about: Release_d will create massive amount of logged data, so prepare for it. Try to crash game as fast as you can.

Then drop p7d and crash.txt here as always.

**Comment by gamillton** [comment]
@megai2
i used your d912pxy__r364, now i know why i should get fast crash, that file is really big :D but now here(it was really not easy to find out, how i should upload it here :D, only allowed archive type is zip and not bigger then 10mb, if you split into zip, you get one zip+ other archive type that i couldn´t ipload here again then, so i did rar and convert this into zip, so you must extract it double, sorry for that, didn´t find another solution so fast^^)
[20190802-013323000.part001.zip](https://github.com/megai2/d912pxy/files/3459160/20190802-013323000.part001.zip)
[20190802-013323000.part002.zip](https://github.com/megai2/d912pxy/files/3459161/20190802-013323000.part002.zip)
[20190802-013323000.part003.zip](https://github.com/megai2/d912pxy/files/3459162/20190802-013323000.part003.zip)
[20190802-013323000.part004.zip](https://github.com/megai2/d912pxy/files/3459163/20190802-013323000.part004.zip)
[20190802-013323000.part005.zip](https://github.com/megai2/d912pxy/files/3459164/20190802-013323000.part005.zip)
[20190802-013323000.part006.zip](https://github.com/megai2/d912pxy/files/3459165/20190802-013323000.part006.zip)
[20190802-013323000.part007.zip](https://github.com/megai2/d912pxy/files/3459166/20190802-013323000.part007.zip)
[20190802-013323000.part008.zip](https://github.com/megai2/d912pxy/files/3459167/20190802-013323000.part008.zip)
[20190802-013323000.part009.zip](https://github.com/megai2/d912pxy/files/3459168/20190802-013323000.part009.zip)
new files:
[crash.txt](https://github.com/megai2/d912pxy/files/3459050/crash.txt)

**Comment by megai2** [comment]
Logs show only one thing to note: >2 seconds gpu wait after massive texture loads

```
02:35:26.816'116"0 wait 0000000030CADD70
02:35:29.069'708"4 GPU wait finished
```

Called shaders are fine, textures too,
My current suspect is that GPU somehow takes more time to load things from RAM to VRAM, ending up in TDR driver shutdown.

I added GPU wait times in metrics, so running Debug dll should record needed info. (do not run _d dll)

You can try go forward and change TdrDelay value in registry [Info on TDR registry keys](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys)

**Comment by gamillton** [comment]
@megai2 

> I added GPU wait times in metrics, so running Debug dll should record needed info. (do not run _d dll)
I couldn´t see any new version, when i started try it again, so I did it with the old one and used debug/dll
> You can try go forward and change TdrDelay value in registry to something like 10 or 5 Info on TDR registry keys
There was nothing set so I did a new one:
![grafik](https://user-images.githubusercontent.com/21971955/62371662-b240dc00-b535-11e9-8780-64848fab8891.png)
After that i didn´t get any gamecrashs it seems, but fps was really low alltime, so using it so would not bring anything, when i used it first time fps was really nice, so somehting is still wrong it seems or i don´t know, so should i run the new version and give you new files then? Here files from last test, gam run over 1 hour:
[crash.txt](https://github.com/megai2/d912pxy/files/3461301/crash.txt)
[20190802-132320000.part01.rar.zip](https://github.com/megai2/d912pxy/files/3461328/20190802-132320000.part01.rar.zip)
[20190802-132320000.part02.rar.zip](https://github.com/megai2/d912pxy/files/3461329/20190802-132320000.part02.rar.zip)

**Comment by megai2** [comment]
Now you can set 
```
dx_debug=0
enable_veh=0
```
then take d912pxy/dll/Release/d3d9.dll to run the game and it should work fine.

**Comment by megai2** [comment]
Hello again @gamillton can you run latest release Release_pp dll and send a p7d log here, i want see actual gpu time metric as logs you sended before was with revision that was without that metric.

**Comment by megai2** [comment]
Changed some code that can affect this one crash, need to recheck on r372+

**Comment by qhhuang** [comment]
so did you check this bug report ?
https://github.com/megai2/d912pxy/issues/180

**Comment by qhhuang** [comment]
and here have another computer not crash but black screen
[log(1).txt](https://github.com/megai2/d912pxy/files/3491153/log.1.txt)

**Comment by qhhuang** [comment]
does AMD gpu  support this project?
[log.txt](https://github.com/megai2/d912pxy/files/3491249/log.txt)
[crash.txt](https://github.com/megai2/d912pxy/files/3491250/crash.txt)

**Comment by megai2** [comment]
@qhhuang https://github.com/megai2/d912pxy/wiki/Installing-for-Blade-&-Soul pt 4

**Comment by qhhuang** [comment]
> @qhhuang https://github.com/megai2/d912pxy/wiki/Installing-for-Blade-&-Soul pt 4

[crash2.txt](https://github.com/megai2/d912pxy/files/3491333/crash2.txt)
[crash1(1).txt](https://github.com/megai2/d912pxy/files/3491334/crash1.1.txt)
[log(1).txt](https://github.com/megai2/d912pxy/files/3491340/log.1.txt)
<img width="658" alt="QQ20190812-153317@2x" src="https://user-images.githubusercontent.com/14370207/62850761-89c79780-bd16-11e9-941c-86f3d5db82a3.png">

The fourth step was implemented in  https://github.com/megai2/d912pxy/wiki/Installing-for-Blade-&-Soul, and use d912pxy/tdr_delay_10.reg but the problem still exists

**Comment by megai2** [comment]
@qhhuang step 4 is for that blackscreen-no crash problem

**Comment by qhhuang** [comment]
> @qhhuang step 4 is for that blackscreen-no crash problem

ok.so what's the problem for the above crash?

**Comment by megai2** [comment]
> 
> 
> > @qhhuang step 4 is for that blackscreen-no crash problem
> 
> ok.so what's the problem for the above crash?

dunno, or there is a bug somewhere, or that is simply long memory transfer that is causing driver tdr

r377 will be up soon, maybe will work properly

**Comment by megai2** [comment]
@gamillton @qhhuang r377 worked on one case of that crashes. 

Try it, but be sure that no graphics overlays is in place.

**Comment by qhhuang** [comment]
no crash, but cannot loading map and the progress bar stops at 0% when i go to F8 or  the sliver mountain tower based on use_pso_precompile=0 ,use_pso_key_cache=0 . 
and i changed use_pso_precompile=1 ,use_pso_key_cache=1 , then i can access 6-person team map. and go to F8. Now everything seems normal.

**Comment by megai2** [comment]
Looks like load screen gpu crash is gone. 
Use v1.5+ and be sure that you do a clean install.

**Comment by qhhuang** [comment]
whatever use 376 or v1.5 won't cause crash.But it can lead to the following problems:

When I return to the server from F8, Windows10 pops up a prompt box, which probably means that Windows can't complete the operation and refuse access.And windows taskmanager cannot exit game.What I can do is restart my computer.

Because the game did not crash, there was no crash.txt feedback.
[log.txt](https://github.com/megai2/d912pxy/files/3505112/log.txt)

**Comment by megai2** [comment]
Odd, maybe some anticheat bugs. Anyway need more logs on this
