### ISSUE TITLE
[hang][bns] hang when entering loading screan

### ISSUE THREAD

**Issue by darkmah** [megai2/d912pxy#174]
this happens randomly and no specific loading screen causes this , the game just completely hangs like shown here 
![image](https://user-images.githubusercontent.com/39097475/62048794-05e9b780-b20e-11e9-9dde-d7ce20c5d97a.png) 
ram usage is inaccurate since it was using 3 gb of ram and when this happens the percentage in task manager doesn't drop
the prcess cant be killed from task manager or from bns buddy
only overlay I use is shadowplay
system specs:
i5 7600k 
8gb ram 
1060 3gb
…
windows 10 1903
driver version 430.86
version 1.3.1 hotfix 2
no crash file was found so here is the log
[log.txt](https://github.com/megai2/d912pxy/files/3442243/log.txt)

**Comment by megai2** [comment]
As there is no crash log or error logged, this is mostly the game problem or one of crashes like #172 
Or you simply run out of memory.
Update to latest and if still encountered report using this guide https://github.com/megai2/d912pxy/wiki/Reporting-crashes
