### ISSUE TITLE
Frequent Fps drops to 30 and lock at it on a 60 hz display

### ISSUE THREAD

**Issue by magnapeccatrix** [megai2/d912pxy#175]
**1. p7d logfile** 
I included log.txt and crashes.txt found on d912pxy, i hope it's one of them.
**2. performance_graph.png** 
Not sure which one that is.
**3. Time of performance drop relative to game start. (@ 33s, @ 42s)**
Regardless of duration.
**4. Description of encountered error and how to reproduce it.**
It happens randomly, on idle scenery or during fights. FPS drops to 30 and stays there, If I move camera around, it gets back to 60 and this is a fix for it. Say I am afking at Divinity's Reach, it occurs randomly, when i move camera around and get it back to same angle, it's back to 60.

[crash.txt](https://github.com/megai2/d912pxy/files/3451467/crash.txt)
[crash1.txt](https://github.com/megai2/d912pxy/files/3451468/crash1.txt)
[crash2.txt](https://github.com/megai2/d912pxy/files/3451469/crash2.txt)
[crash3.txt](https://github.com/megai2/d912pxy/files/3451470/crash3.txt)
[crash4.txt](https://github.com/megai2/d912pxy/files/3451471/crash4.txt)
[crash5.txt](https://github.com/megai2/d912pxy/files/3451472/crash5.txt)
[crash6.txt](https://github.com/megai2/d912pxy/files/3451473/crash6.txt)
[crash7.txt](https://github.com/megai2/d912pxy/files/3451474/crash7.txt)
[crash8.txt](https://github.com/megai2/d912pxy/files/3451475/crash8.txt)
[crash9.txt](https://github.com/megai2/d912pxy/files/3451476/crash9.txt)
[crash10.txt](https://github.com/megai2/d912pxy/files/3451477/crash10.txt)
[log.txt](https://github.com/megai2/d912pxy/files/3451478/log.txt)

**Comment by megai2** [comment]
Updated this page https://github.com/megai2/d912pxy/wiki/Reporting-performance-issues
While I see you refer to some parts of that page, you not fully readed it. Please read it fully.

**Comment by magnapeccatrix** [comment]
Hello and thank you for quick reply.
And sorry about that I usually get lost between pages, there're many things to check on that page. I will need sometime to follow all steps and update here accordingly.
Thank you again Megai2.

**Comment by loqi93** [comment]
I have the same problem.

**Comment by zhouhuichen741** [comment]
I have the same problem.

**Comment by megai2** [comment]
Seeing this kind of errors means that you have vsync/gsync/tripble buffering enabled, or configured wrongly, 

Normally there is builtin driver profiles for game, but as game runs on dx12, that profiles can be missing or not working.

So you should check and config this by yourself.
Google is your best bet on finding _precise_ guide.

Updated https://github.com/megai2/d912pxy/wiki/Reporting-performance-issues part 7.

```
Be sure that you properly configured vertical sync/variable refresh rate behaivour/triple buffering both in game settings and in driver settings. 
This options define frame synchronization, making different frame limiting situations. 
All "off" should yield uncapped fps.
``
