### ISSUE TITLE
BNS force close when loading/loaded

### ISSUE THREAD

**Issue by octavianus7** [megai2/d912pxy#176]
**Describe the bug**
it worked well for half an hour or longer.then it continuously crashed when BNS loading or loaded.Already installed latest GPU driver,MSDX9,MSVC and d912pxy,and even tried set TdrDelay to ten,but it doesn't work

**Standard information**

1. Windows 10 1903
2. Hardware info: CPU AMD ryzen 1600x , RAM G.skill 8GB*2@2666  , GPU sapphire rx 590
3. GPU Driver version 19.5.2
4. Version of d912pxy used release 1.4
[crash.txt](https://github.com/megai2/d912pxy/files/3465258/crash.txt)
[crash1.txt](https://github.com/megai2/d912pxy/files/3465259/crash1.txt)

**Comment by megai2** [comment]
Read this one fully https://github.com/megai2/d912pxy/wiki/Reporting-crashes
