### ISSUE TITLE
Please make 32 bit version for F.E.A.R.

### ISSUE THREAD

**Issue by funkerwolf** [megai2/d912pxy#177]
Please make 32 bit version for F.E.A.R. On modern systems with nvidia there are artifacts that are easily eliminated with the help of wrappers.

**Comment by megai2** [comment]
Making this to work with 32 bit will require some extra translation library that routes 32bit calls to 64 bit dll. I'm not found proper and fast solution on this.

**Comment by funkerwolf** [comment]
There are several projects that work and even very well, but one of them, alas, with a closed code ..
dgVoodoo2 is ideal solution, but cursor flickering over scope in game. And D9VK https://github.com/Joshua-Ashton/d9vk

**Comment by megai2** [comment]
This project was crated to fix modern(or modern-ish) game performance issues.

So it deals only with modern dx9 rendering approaches and have different old and unused things cutted out.

Moreover some algorithms that are used to: smooth out dx9 lags, transition problems and optimize out some CPU usage, for bringing more stable and better frame times, are RAM greedy, making it only x64 thing.

I'm not plan to make fully compatible dx9 implementation, so for now all 32 bit titles and old ones(with fixed pipeline and etc) are not goin to work with d912pxy.
