### ISSUE TITLE
[BnS] ReShade

### ISSUE THREAD

**Issue by Lennard1978** [megai2/d912pxy#178]
is it possible to make reshade available for it?
it crashes everytime i try to start it with it enabled

**Comment by megai2** [comment]
Take latest release from reshade website and install as for dx10+ game, or just name the reshade dll as dxgi.dll and put it next to client.exe 

Should work just fine.

If it not works, and giving crashes read this one page first https://github.com/megai2/d912pxy/wiki/Reporting-crashes
