### ISSUE TITLE
[BNS]NO Crash,Only map rendering is too slow

### ISSUE THREAD

**Issue by qhhuang** [megai2/d912pxy#179]
**Before starting**
I'm playing bns_cn in china
At present, there is no crash,but the memory usage seems too high for 7536MB

**Expected behavior**

**Screenshots**

**Standard information**

1. Windows 10 LTSC 2019
2. Hardware info:
CPU 9900K OC5Ghz     ring OC4.5GHz
RAM G.SKILL TRIDENTZ 8G*4 3733c17 （oc4200 C18）
GPU   asus 2080ti O11g
3. GPU Driver version 431.660
4. Version of d912pxy used d912pxy_v1.4_r367

In the new raid 6-person map, my teammates gave me a transfer way to the boss - the F key. Then start to fight the boss, until the boss's blood volume reaches 86%, my display material is fully loaded, you need to know that the first wave mechanism is 90% of the blood volume.
I am very sorry that I don’t know how to translate these professional game words.

Then i changed this thing:
[pooling]
upload_alloc_step=256
upload_limit=256
vstream_alloc_step=256
vstream_limit=256
surface_limits=00000
lifetime=10000
host_va_reserve=37
[compat]
occlusion=1
clear=0
cpu_api_reduction=0
batch_commit=1
omrt_viewport_reset=1
track_rs=1
But the material loading speed is still very slow，and i see that the cpu and gpu occupancy rate is not very high.Is there any way to speed up the rendering speed of DX12?
thank you for you create this project, It makes me feel the game is smoother

**Comment by megai2** [comment]
Memory usge will rise, yes. With your config it will rise even more.

Slow loading times can originate from true fulscreen mode and fresh install.

Setting cpu_api_reduction to 0 is bad idea as BnS renderer have tons of reduntant calls that will end up in GPU overutilization, this can even create shader loading delay you see.

You can change use_pso_precompile and use_pso_key_cache in config to force load shaders on game startup, but this will increase memory usage even more.

**Comment by qhhuang** [comment]
now i will set cpu_api_reduction to 1.And set pso_precompile and use_pso_key_cache to 3.but how long do I need to wait them written to PSO keys and then set them to 2?
I have a friend run bns at 3840*2160dpi,He found that the game was running at 1080p and did not load 4K footage. Is there any way to solve this problem?
Thank you again

**Comment by megai2** [comment]
> 
> 
> now i will set cpu_api_reduction to 1.And set pso_precompile and use_pso_key_cache to 3.but how long do I need to wait them written to PSO keys and then set them to 2?
> I have a friend run bns at 3840*2160dpi,He found that the game was running at 1080p and did not load 4K footage. Is there any way to solve this problem?
> Thank you again

you need to set it to 2 and 1 when you visit enough places where load times are critical

about 4k: game loads what it loads with d3d9, nothing is changed on this point, even monitor resolution listing is passed to system's d3d9 library. 
Maybe there is some resolution fallback due to exclusive fullscreen crashes, or 4k is enabled via DSR(the nvidia thing) and can have some problems
