### ISSUE TITLE
[crash][BnS] crash on map load screen

### ISSUE THREAD

**Issue by qhhuang** [megai2/d912pxy#180]
![QQ图片20190810125852](https://user-images.githubusercontent.com/14370207/62817782-a4f7a300-bb6e-11e9-9eca-90cdee85fcff.png)
[crash.txt](https://github.com/megai2/d912pxy/files/3488531/crash.txt)
[crash1.txt](https://github.com/megai2/d912pxy/files/3488533/crash1.txt)

cpu: i7-8550u

gpu: intel UHD 620 + nvidia mx150
reinstalled c++ and vcredist_x64 but crash again

**Comment by megai2** [comment]
1. Duplicated #172 
2. Re-read https://github.com/megai2/d912pxy/wiki/Reporting-crashes i don't see log.txt and see 3-rd party overlays running

**Comment by qhhuang** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/3489488/log.txt)
i will try it again and exit other application by overlays running
