### ISSUE TITLE
What does this crash file mean?

### ISSUE THREAD

**Issue by ThoralfTh** [megai2/d912pxy#181]
In average I have 95 FPS in the Heart of Mists. But when I turn my camera, my FPS drop a lot. 
It has nothing to do with players, as I have set all character related options to the lowest setting.
The weird thing is, sometimes it works (steady 95 FPS even when turning), sometimes it doesnt.

I have found following crash file, and would like to know if this could be the cause for the FPS problems.

crasht.txt
0 | connected to server EX
 

1 | "shader replace error" | hr = FFFFFFFF 

2 | ReadFileEx() failed with 109 for pipe 2972
 

3 | CPipeRequestThread::StartReceive ERROR = 0000006d

**Comment by megai2** [comment]
There is debug messages from logitech drivers and maybe some nahimic drivers.

Writing this log is unbuffered, meaning that it can create some lag.

You can turn this off with enable_veh=0 in config

Camera pan lag consist of 3 factors 

1. Disk speed
2. Pooling state
3. Config switches

I can't fix disk speed, but you can try to use gw2_hiend_config.ini (pour contents of it into config.ini), it should cover some lags if your rig can afford extra performance.

**Comment by ThoralfTh** [comment]
I only understood half of what youre saying ^o^
Can you tell me what exactly I have to do / could do to fix the problem? ^^

**Comment by megai2** [comment]
> 
> 
> I only understood half of what youre saying ^o^
> Can you tell me what exactly I have to do / could do to fix the problem? ^^

try delete config.ini and rename gw2_hiend_config.ini to config.ini =]

**Comment by ThoralfTh** [comment]
OK, I'll try that. I'll tell yall how it went ^^

**Comment by ThoralfTh** [comment]
Still lags when turning camera :( And I noticed the circle thing down right corner on loading screens is also lagging. I just dont understand why sometimes my FPS are steady and sometimes just - its just so random. Thx anyways :)

**Comment by ThoralfTh** [comment]
| "shader cso load error" | hr = FFFFFFFF 

1 | "shader cso load error" | hr = FFFFFFFF 

2 | "shader cso load error" | hr = FFFFFFFF 

3 | "shader cso load error" | hr = FFFFFFFF 

4 | "shader cso load error" | hr = FFFFFFFF 

5 | "shader cso load error" | hr = FFFFFFFF 

6 | "shader cso load error" | hr = FFFFFFFF 

7 | "shader cso load error" | hr = FFFFFFFF 

8 | "shader cso load error" | hr = FFFFFFFF 

9 | "shader cso load error" | hr = FFFFFFFF 

10 | "shader cso load error" | hr = FFFFFFFF 

11 | "shader cso load error" | hr = FFFFFFFF 

12 | "shader cso load error" | hr = FFFFFFFF 

13 | "shader cso load error" | hr = FFFFFFFF 

14 | "shader cso load error" | hr = FFFFFFFF 

15 | "shader cso load error" | hr = FFFFFFFF 

16 | "shader cso load error" | hr = FFFFFFFF 

17 | "shader cso load error" | hr = FFFFFFFF 

18 | "shader cso load error" | hr = FFFFFFFF 

19 | "shader cso load error" | hr = FFFFFFFF 

20 | "shader cso load error" | hr = FFFFFFFF 

21 | "shader cso load error" | hr = FFFFFFFF 

22 | "shader cso load error" | hr = FFFFFFFF 

23 | "shader cso load error" | hr = FFFFFFFF 

24 | "shader cso load error" | hr = FFFFFFFF 

25 | "shader cso load error" | hr = FFFFFFFF 

26 | "shader cso load error" | hr = FFFFFFFF 

27 | "shader cso load error" | hr = FFFFFFFF 

28 | "shader cso load error" | hr = FFFFFFFF 

29 | "shader cso load error" | hr = FFFFFFFF 

30 | "shader cso load error" | hr = FFFFFFFF 

31 | "shader cso load error" | hr = FFFFFFFF 

32 | "shader cso load error" | hr = FFFFFFFF 

33 | "shader cso load error" | hr = FFFFFFFF 

34 | "shader cso load error" | hr = FFFFFFFF 

35 | "shader cso load error" | hr = FFFFFFFF 

36 | "shader cso load error" | hr = FFFFFFFF 

37 | "shader cso load error" | hr = FFFFFFFF 

38 | "shader cso load error" | hr = FFFFFFFF 

39 | "shader cso load error" | hr = FFFFFFFF 

40 | "shader cso load error" | hr = FFFFFFFF 

41 | "shader cso load error" | hr = FFFFFFFF 

42 | "shader cso load error" | hr = FFFFFFFF 

43 | "shader cso load error" | hr = FFFFFFFF 

44 | "shader cso load error" | hr = FFFFFFFF 

45 | "shader cso load error" | hr = FFFFFFFF 

46 | "shader cso load error" | hr = FFFFFFFF 

47 | "shader cso load error" | hr = FFFFFFFF 

48 | "shader cso load error" | hr = FFFFFFFF 

49 | "shader cso load error" | hr = FFFFFFFF 

50 | "shader cso load error" | hr = FFFFFFFF 

51 | "shader cso load error" | hr = FFFFFFFF 

52 | "shader cso load error" | hr = FFFFFFFF 

53 | "shader cso load error" | hr = FFFFFFFF 

54 | "shader cso load error" | hr = FFFFFFFF 

55 | "shader cso load error" | hr = FFFFFFFF 

56 | "shader cso load error" | hr = FFFFFFFF 

57 | "shader cso load error" | hr = FFFFFFFF 

58 | "shader cso load error" | hr = FFFFFFFF 

59 | "shader cso load error" | hr = FFFFFFFF 

60 | "shader cso load error" | hr = FFFFFFFF 

61 | "shader cso load error" | hr = FFFFFFFF 

62 | "shader cso load error" | hr = FFFFFFFF 

63 | "shader cso load error" | hr = FFFFFFFF 

64 | "shader cso load error" | hr = FFFFFFFF 

65 | "shader cso load error" | hr = FFFFFFFF 

66 | "shader cso load error" | hr = FFFFFFFF 

67 | "shader cso load error" | hr = FFFFFFFF 

68 | "shader cso load error" | hr = FFFFFFFF 

69 | "shader cso load error" | hr = FFFFFFFF 

70 | "shader cso load error" | hr = FFFFFFFF 

71 | "shader cso load error" | hr = FFFFFFFF 

72 | "shader cso load error" | hr = FFFFFFFF 

73 | "shader cso load error" | hr = FFFFFFFF 

74 | "shader cso load error" | hr = FFFFFFFF 

75 | "shader cso load error" | hr = FFFFFFFF 

76 | "shader cso load error" | hr = FFFFFFFF 

And so on. Whats that?

**Comment by ThoralfTh** [comment]
0 | connected to server EX
 

1 | ReadFileEx() failed with 109 for pipe 3360
 

2 | CPipeRequestThread::StartReceive ERROR = 0000006d

**Comment by ThoralfTh** [comment]
In 2 crash files, both created 7 Min ago.

**Comment by megai2** [comment]
All is fine on that errors. What PC you have?

**Comment by ThoralfTh** [comment]
WIN 10 Pro
i7 6700k 
16GB RAM I think.
Nvidia GTX 970

**Comment by megai2** [comment]
> 
> 
> WIN 10 Pro Version 1803
> i7 6700k
> 16GB RAM I think.
> Nvidia GTX 970

and disk used? HDD/SDD?

**Comment by ThoralfTh** [comment]
HDD and SSD. GW2 installed on SSD. 122GB Space left on SSD.

**Comment by megai2** [comment]
> 
> 
> HDD and SSD. GW2 installed on SSD. 122GB Space left on SSD.

All should be fine(or fine-ish) then. First pan will always slower, but not that slow as on dx9.

Maybe there is some other software on your system causing delays. Like realtime AV or some background heavy load.

**Comment by ThoralfTh** [comment]
I dont know. Sometimes it works sometimes not. I thought its maybe temperature related. But temp is all fine. I am just clueless. Until now turning the computer off and wait till next day fixed it. But Today i turned it on and all laggy again.
:(

**Comment by megai2** [comment]
Install Release_pp by installer or take it from d912pxy/dll if installer is not an option (Use standart release? N => 2)

Run game, try to repeat performance drop 2-3 times, better with a timestamp from the game start.

Exit the game properly, with no crash.

Report here with a logfile from P7logs(next to game executable) and d912pxy/dx12_perf_graph.html.

**Comment by ThoralfTh** [comment]
That file type is not supported here.

**Comment by megai2** [comment]
> 
> 
> That file type is not supported here.

Zip and upload, or upload somewhere else like google drive.

**Comment by ThoralfTh** [comment]
https://drive.google.com/open?id=1cbV8bKZP1BkePrm3-iQ2vLZLrACjh3UY

I logged in XX:49. Waited till XX:50 and started turning my camera a bit. Stopped at like XX:51. I you can see time stamps, idk.

**Comment by megai2** [comment]
Do you have vsync enabled in game settings or somewhre in driver settings?

**Comment by ThoralfTh** [comment]
No. Not ingame nor in Nvidia Settings.

**Comment by megai2** [comment]
> 
> 
> No. Not ingame nor in Nvidia Settings.

Logs shows that your GPU is at 100% load or waiting for something like VSync/Gsync or triple buffering.

**Comment by ThoralfTh** [comment]
How can I fix that and why is that problem only occuring sometimes and sometimes I have perfect FPS?

**Comment by ThoralfTh** [comment]
triple buffering is also disabled in Nvidia System Settings.

**Comment by megai2** [comment]
Dunno, you have to find this yourself. 
Maybe windowed fullscreen/exclusive fullscreen issues.
Maybe some other software interference. 
I can't say what the cause from logs.

**Comment by ThoralfTh** [comment]
It works again.

**Comment by megai2** [comment]
You can join discord channel and ask ppl there, maybe someone will get to the problem.

**Comment by ThoralfTh** [comment]
But that makes me even more desperate xD Because I know it will come again and I still dont know what causes it. What I did now was a Runtime Update or smth from Windows, following a restart. Before the restart I removed dxpy12 via installer, and installed it again after via installler just hitting enter.

**Comment by ThoralfTh** [comment]
But I am sure it has nothing to do with the update because it came and went away again without me updating anything in between.

**Comment by ThoralfTh** [comment]
I dont even dare to close GW 2 again, in fear it will lag again afterwards. gonna enjoy this lag free high fps gameplay ^^ btw your directx12 addon is the reason i am above 60 fps it helps me so much. thanks :)

**Comment by ThoralfTh** [comment]
:)
