### ISSUE TITLE
gpu runs in copy not 3D

### ISSUE THREAD

**Issue by qhhuang** [megai2/d912pxy#182]
This problem was discovered in version 1.5. gpu runs in copy not in 3D at picture 1,2 .The normal graph is picture 3.
Feeling more stuck while running copy than before.
GPU is nvidia mx150 with 2GB gpu memory
<img width="421" alt="433" src="https://user-images.githubusercontent.com/14370207/63087140-fd221100-bf83-11e9-85ea-8130d30742a2.png">
<img width="672" alt="444444" src="https://user-images.githubusercontent.com/14370207/63087149-01e6c500-bf84-11e9-827b-d0a14029538b.png">
![444433322](https://user-images.githubusercontent.com/14370207/63087160-07dca600-bf84-11e9-9c90-4b676593adc6.png)

When I return to the server from F8, Windows10 pops up a prompt box, which probably means that Windows can't complete the operation and refuse access.And windows taskmanager cannot exit game.What I can do is restart my computer.

**Comment by megai2** [comment]
That is known problem of Windows 10 since some of Windows 10 update.
Task manager shows wrong GPU usage, use some tools like GPU-Z to overcome it.
