### ISSUE TITLE
Confused how to handle installing this with Reshade

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#184]
Instructions say "ReShade should be installed as dxgi.dll (probably you need to put it next to Gw2-64.exe)"

So does that mean I need to go into my reshade folder and rename d3d9.dll -> dxgi.dll?  

The place it mentions in the install is confusing to read through
https://github.com/megai2/d912pxy/issues/38 
ReShade => allfile => Game directory ReShade64.dll => dxgi.dll or d3d12.dll

What does allfile and game directory reshade64.dll. If I use an older version of reshade do I need to upgrade to 4.3.0 first?  Im still using an older 1.0 version.

EDIT:
OK I got it, at first I thought I had it fixed just copying over the Reshade.fx and dxgi.dll to my main game directory, but it didn't look right - said reshade compiled but I saw no difference, realized I need to copy over the sweetfx folder and sweet.fx file as well into my main game directory (where gw2-64.exe is).  THEN it all worked

**Comment by bzeeeb** [comment]
I installed this and just changed the reshade's d3d9 to dxgi.dll, but doesn't seem to work now.  Anything else I need to tweak?

**Comment by bzeeeb** [comment]
Edit Nvm I think I got it.  Had to cut paste the dxgi.dll and reshade.fx into the root gw2 folder.  Then it worked

**Comment by bzeeeb** [comment]
Leaving open in case I missed anything else to do.

**Comment by bzeeeb** [comment]
It doesnt seem to be working even though reshade says it succeeded compiling

**Comment by megai2** [comment]
You need latest reshade that supports dx12.

**Comment by megai2** [comment]
Updated a bit https://github.com/megai2/d912pxy/wiki/Using-with-other-addons-and-overlays

**Comment by PompeiaPaetenari** [comment]
When you run the ReShade installer, for use with this plugin, you need to select the "Direct3D 10+" option in the centre rather than the "Direct3D 9" on the left you normally use without the plugin.  It will then generate the dxgi.dll file instead of the usual one it did before (d3d9.dll we had to rename into chainload).

@megai2 I believe if you add a screenshot of the ReShade installer with this pointed out, it will make the instructions a lot clearer and easier for people to follow :)

**Comment by bzeeeb** [comment]
What do I install first?  Reshade with dx10 then d912?  Do I need to move anything around then or would it make it all for me?

**Comment by megai2** [comment]
If you install reshade in dx10+ mode, order does not matter.

**Comment by bzeeeb** [comment]
How do I confirm dx12 is properly installed after I install reshade 4.3.0 properly.  When I brought up the reshade menu it still said it was in dx9.  How do I reinstall it properly.

**Comment by bzeeeb** [comment]
"ReShade should be installed as dxgi.dll and have dx12 support (version 4.3 and up) (probably you need to put it next to Gw2-64.exe)"

Am I renaming the d3d9.dll or leaving that in bin-64 and renaming the reshade?

**Comment by megai2** [comment]
You need to name dll that comes from/with reshade as dxgi.dll and put it in folder where Gw2-64.exe is located. d912pxy should still be installed as d3d9.dll in bin64 folder.

**Comment by PuggNerd** [comment]
Ok, so just installing ReShade and pointing it to the game exe, it will drop a d3d9.ll in the bin folder itself. it *also* drops dxgi.dll in the game's root folder. This is where my confusion lies.

**Comment by megai2** [comment]
> 
> 
> Ok, so just installing ReShade and pointing it to the game exe, it will drop a d3d9.ll in the bin folder itself. it _also_ drops dxgi.dll in the game's root folder. This is where my confusion lies.

Keep only dxgi.dll in the game root folder.

**Comment by bzeeeb** [comment]
@megai2 so if I do that it looks like dx12 works but reshade doesnt.  hmm

**Comment by bzeeeb** [comment]
is there a special way I need to install it?  So the d3d9 picks up the reshade or do I just install it normally @megai2?

**Comment by megai2** [comment]
@bzeeeb what os you use?

**Comment by bzeeeb** [comment]
Windows 10, I ended up getting reshade and dx12 to work by moving everything reshade related into the bin.  

https://reshade.me/compatibility it noted you need to install reshade into the bin folder for compatability,

**Comment by bzeeeb** [comment]
I think its all working now since I see the character portraits messed up, but I also see reshade working.  Will test a bit to see if I see the expected performance gains in large events.

**Comment by bzeeeb** [comment]
how would I update the d3d9.dll since I see you are still tweaking it.  Do I just download the latest version and install it again?  Do I need to uninstall first?  I believe this would be just removing the d3d9.dll file right?

**Comment by bzeeeb** [comment]
Well for some reason the screenshots aren't saving right now >_>

**Comment by megai2** [comment]
No idea, use system wide screenshot tools.

**Comment by bzeeeb** [comment]
Are you expecting the folder structure to look like mine? @megai2 When I try to just install reshade to the root and d3d9.dll to bin64 reshade works but I dont get the bad character portraits to signal that its working (or the long initial first time load of all the meshes).  I do see reshade working and dx12 if I put them all into the same bin64 folder.

Is that how you are expecting it to work?  I don't get why mine is special.

**Comment by megai2** [comment]
Some systems have screwed dll load paths, if it works by putting all in bin64, it works.

**Comment by PuggNerd** [comment]
I can confirm this. Dumping all into /bin64 does indeed allow Reshade to function with dx912 properly. I'm using no other addons.

**Comment by megai2** [comment]
Well, i think we sorted out how to install it.

**Comment by bzeeeb** [comment]
I guess, but the screen caps still don't work with it.  Seems like they do work if you chain load it?

**Comment by bzeeeb** [comment]
I have attempted to use nvidia overlay to take screenshots but it also does not work.  What system wide screen capturing tool are you referring to?

**Comment by bzeeeb** [comment]
I have attempted to use nvidia overlay to take screenshots but it also does not work.  What system wide screen capturing tool are you referring to? @megai2

**Comment by megai2** [comment]
> 
> 
> I have attempted to use nvidia overlay to take screenshots but it also does not work. What system wide screen capturing tool are you referring to? @megai2

Print Screen -> Ctrl+V

**Comment by bzeeeb** [comment]
Btw @megai2 I did install arcdps and found that I can put reshade in the root folder if I use the d3d9_chainload.dll but screenshots still didnt work
