### ISSUE TITLE
 Skyscale mount skin bug

### ISSUE THREAD

**Issue by OskarwaR** [megai2/d912pxy#187]
The necklace and the saddle look totally black.

![snip_20190907142754](https://user-images.githubusercontent.com/55022458/64475010-fbabc900-d17c-11e9-9ff0-d9ba58a3b28d.png)

I've tried other skins too.

v1.7

**Comment by megai2** [comment]
Give a comparable dx9 screenshoot too, please.

**Comment by OskarwaR** [comment]
![snip_20190907151653](https://user-images.githubusercontent.com/55022458/64475393-93f87c80-d182-11e9-8b3e-22c406ddabff.png)

**Comment by megai2** [comment]
Can't repro that https://cdn.discordapp.com/attachments/423201399665590295/622761747237044234/unknown.png

**Comment by megai2** [comment]
Maybe due to #193
