### ISSUE TITLE
Random Crash (GW2)

### ISSUE THREAD

**Issue by Queph** [megai2/d912pxy#188]
I was waiting Auric Basin Meta at South Gate, got crash. 
PC Spec:
+Ryzen 5 1600 @3.9 OC
+MSI GTX 1050 Ti
+2x8GB 3000 MHz RAM
+Samsung 860 EVO
+Windows 10 (1903-18362.295)
+Latest version of d912px mod.

[crashnlog.zip](https://github.com/megai2/d912pxy/files/3596398/crashnlog.zip)

**Comment by megai2** [comment]
I'm not seeing any crash related error logged.
Callstacks show that crash is not in my code.

This programs loaded into process can create problems
```
59 | C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll:RTSSHooks64.dll (0000000180000000), size: 2564096 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks64.dll'
92 | C:\ProgramData\Microsoft\Windows Defender\platform\4.18.1907.4-0\MpOav.dll:MpOav.dll (00007FFA3FA20000), size: 139264 (result: 0), SymType: '-exported-', PDB: 'C:\ProgramData\Microsoft\Windows Defender\platform\4.18.1907.4-0\MpOav.dll', fileVersion: 4.18.1907.4
115 | C:\Program Files\Logitech Gaming Software\SDK\LCD\x64\LgLcdApi.dll:LgLcdApi.dll (0000018C85E90000), size: 679936 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files\Logitech Gaming Software\SDK\LCD\x64\LgLcdApi.dll', fileVersion: 1.0.0.0
```

Also try to check your max memory commitment, maybe you simply hitting it.

**Comment by megai2** [comment]
If problem is still here, read this https://github.com/megai2/d912pxy/wiki/Reporting-crashes article.
