### ISSUE TITLE
RTSS Issue

### ISSUE THREAD

**Issue by PaperCat810420** [megai2/d912pxy#189]
RTSS can show the FPS in d912pxy ver1.6.
But gw2 will auto close without any crash.dmp(main folder) or crash.txt(d912pxy folder) in ver1.7.

**Comment by megai2** [comment]
Does it work without d912pxy?

**Comment by IsmetBesic** [comment]
Just to pitch in; using the latest artifact (r423) RTSS is working for me (nvidia GPU, if it matters).

**Comment by megai2** [comment]
I changed some startup code, maybe it will fix RTSS crash, but i seen RTSS crash related to windows and RTSS itself.

**Comment by PaperCat810420** [comment]
Works now. Sorry I'm late to reply you. I was too busy.
