### ISSUE TITLE
"shader replace error" | hr = FFFFFFFF

### ISSUE THREAD

**Issue by dailletg** [megai2/d912pxy#190]
**Describe the bug**
The game client randomly crash, with a generic textbox that doesn't give any details and just warns us that it might be linked to add-ons. It doesn't seem to be linked to a specific map or class. Happens in fractals, open world, WvW, but never seen in sPvP.

**Standard information**
1. Windows 10 1903
2. Hardware info: i7-8750H, GTX1060, 16GO
3. GPU Driver 431.60
4. Version of d912pxy 1.7.1

**Crash.dmp**
`0 | "shader replace error" | hr = FFFFFFFF `

**log.txt**
```
17EF1CE4 [ error ] shader replacer | throw on "shader replace error" with HR = 0xFFFFFFFF 
17EF1CE4 [ error ] helper | Exception: E06D7363 
17EF1CE4 [ error ] PSO item | final error compiling shader pair VS 1929C561F834A3C6 PS C1F26A70F41985BA 
```

I tried running the windows option "disable fullscreen optimizations" : same.
I always run in borderless window. No overlay such as Gefore Experience or Discord.
I only use ARCDPS, properly installed and reinstalled both. Still the same issue.

Any idea ?

**Comment by megai2** [comment]
After recent game update?

**Comment by dailletg** [comment]
No, it happened before the update as well.


[log.txt](https://github.com/megai2/d912pxy/files/3624846/log.txt)

[crash6.txt](https://github.com/megai2/d912pxy/files/3624842/crash6.txt)
[crash10.txt](https://github.com/megai2/d912pxy/files/3624844/crash10.txt)

**Comment by megai2** [comment]
Looks like another GPU crash. 

Any overclock you have?
Does your system temps fine?

**Comment by dailletg** [comment]
My temps are really reasonable : CPU typically around 80-85C, and GPU never goes beyond 70C.

No overclock on CPU or GPU. I only run an undervolt on my CPU core and cache that allows me to run lower temps, avoid thermal throttling and have stable CPU clocks at 3.9GHz.
I have been running this CPU undervolt for months, but this crash started only about two weeks ago.

**Comment by megai2** [comment]
So it is not happening on 1.6 or 1.5?

**Comment by dailletg** [comment]
I only see this crash under 1.7.1.
I am not 100% sure about 1.7 : the first crash log on 07/09/2019, but I performed a windows wipe around that date, so I can't see the previous logs.
My Windows is a clean install, and all drivers are updated. I pretty much have the perfect environment, yet I still run into frequent crashes.

**Comment by megai2** [comment]
Ok, thanks

**Comment by Deshke** [comment]
hey seeing the same thing on my rig with v1.7.1

[crash.txt](https://github.com/megai2/d912pxy/files/3637730/crash.txt)

up2date win10 & nvidia drivers (updated to r3900x) used [config.ini](https://github.com/megai2/d912pxy/files/3637736/config.txt)

**Comment by megai2** [comment]
> 
> 
> hey seeing the same thing on my rig with v1.7.1
> 
> [crash.txt](https://github.com/megai2/d912pxy/files/3637730/crash.txt)
> 
> up2date win10 & nvidia drivers (updated to r3900x) used [config.ini](https://github.com/megai2/d912pxy/files/3637736/config.txt)

message is same but callstack looks like a oom crash

anyway, try last revision.

**Comment by Deshke** [comment]
seems to have done the trick

**Comment by megai2** [comment]
Found a problem #193
