### ISSUE TITLE
GW2 Bound by Blood update freeze and crash after select character

### ISSUE THREAD

**Issue by patrickmaciel** [megai2/d912pxy#191]
**Describe the bug**

Game crash after load the map.

**To Reproduce**
Steps to reproduce the behavior.

1. Login
2. Select the character
3. Loading screen
4. After that, some 3D objects load and the other 90% not (invisible)
5. Game freeze
6. After 2~5 minutes, game crash
7. I see the error one time: Effect.....cpp

Obs.: effect load is enabled and character quality/limit is low. Others settings are in high/medium.

**Screenshots**
![Anotação 2019-09-18 065716](https://user-images.githubusercontent.com/671670/65138871-0dde0080-d9e2-11e9-8ff1-d14f2b6289c0.png)

1. Windows 10 with the latest updated
2. Hardware info: i7 7700k 4.9ghz OC, 16gb RAM 2400mhz, 980gb SSD, GTX 1060
3. Latests Nvidia Drivers
4. Version of d912pxy used: 1.7.0.414
5. Log [log.txt](https://github.com/megai2/d912pxy/files/3625724/log.txt)

**Comment by githubShadw** [comment]
When ArcDps , is not update and bug , rename d3d9.dll > d3d9.dllold (arcdps) , and rename d3d9_chainload.dll (d912pxy) > d3d9.dll  . and u have remove arcdps and d912pxy work

**Comment by megai2** [comment]
I see multiple overlay errors
Please read this one https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by patrickmaciel** [comment]
@megai2 thats the current errors.

```
655B171 [ error ] helper | Exception: 406D1388 

655B190 [ error ] helper | Exception: 406D1388 

655B190 [ error ] helper | Exception: 406D1388 

655B1CF [ error ] helper | Exception: 406D1388 

655B1EE [ error ] helper | Exception: 406D1388 

655B1EE [ error ] helper | Exception: 406D1388 

655B1EE [ error ] helper | Exception: 406D1388 

6562C6D [ error ] shader replacer | throw on "shader replace error" with HR = 0xFFFFFFFF 

655BD58 [ info ] swap chain | Window: 60C02 Width: 2544 Height: 1001 Fullscreen: 0 Buffers: 2 Format: 21 

655BD67 [ info ] swap chain | Window: 60C02 Width: 2560 Height: 1080 Fullscreen: 0 Buffers: 2 Format: 21 

655C1AD [ info ] swap chain | Window: 60C02 Width: 2560 Height: 1080 Fullscreen: 0 Buffers: 2 Format: 21 

655C1CC [ info ] swap chain | Window: 60C02 Width: 2560 Height: 1080 Fullscreen: 0 Buffers: 2 Format: 21 

655CB33 [ info ] swap chain | Window: 60C02 Width: 2560 Height: 1080 Fullscreen: 0 Buffers: 2 Format: 21 

655CB71 [ error ] helper | Exception: 406D1388 

6562C5E [ error ] shader replacer | shd compile err = C:\Program Files\Guild Wars 2\d912pxy\shaders\hlsl\1929C561F834A3C6.hlsl(37,51): warning X1519: 'dx9_halfpixel_pos_reg_ac' : macro redefinition
C:\Program Files\Guild Wars 2\d912pxy\shaders\hlsl\1929C561F834A3C6.hlsl(56,5-20): error X3018: invalid subscript 'reg_rastout0'
 

6562C5E [ error ] shader replacer | Failed to replace shader with UID = 1929C561F834A3C6 

6562C6D [ error ] helper | Exception: E06D7363 

6562C6D [ error ] PSO item | final error compiling shader pair VS 1929C561F834A3C6 PS C1F26A70F41985BA 
```

**Comment by patrickmaciel** [comment]
@megai2 only d912pxy works.
with arcdps = crash
with arcdps + build template = crash
with arcdps + build template + gw2radial = crash

all this happens after the last GW2 update

**Comment by megai2** [comment]
> 
> 
> @megai2 load only d912pxy works.
> with arcdps = crash
> with arcdps + build template = crash
> with arcdps + build template + gw2radial = crash
> 
> all this happens after the last GW2 update

Yes, arcdps tend to crash/error out game after new game patch, until deltaconnected update it.
This game update it spams error which is logged by d912pxy, making game acting very slow and then crashing.
Wait for arcdps update.
