### ISSUE TITLE
FPS stuck at 2 when loading into any map.

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#192]
1. Windows 10 update ver | 1903
2. Hardware info: CPU, RAM, GPU | 16gig https://www.amazon.com/gp/product/B01I60OGUK/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
3. GPU Driver version | Nvidia 436.30
4. Version of d912pxy used (downloaded on 9/2)
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
[crash10.txt](https://github.com/megai2/d912pxy/files/3628530/crash10.txt)

**Additional context**
FPS today is at a crawl ~2fps whenever I load into an area, character select screen seems fine. Ended up leaving my last character on the dragon's nest map, and when I loaded back in there thats when it started.  Using ArcDPS, D912pxy, and Reshade 4.3.0

**Comment by megai2** [comment]
Update ArcDPS.

**Comment by bzeeeb** [comment]
Bless
