### ISSUE TITLE
1.8 and 1.7.1 crash with ARCdps on start

### ISSUE THREAD

**Issue by OskarwaR** [megai2/d912pxy#194]
The game closes before starting and the log is empty in version 1.8 and 1.7.1 with ARCdps dll, without ARCdps It works well.

With 1.7 and ARCdps works without problem.

My chainload is:
ARCdps => d3d9.dll
d912pxy => d3d9_chainload.dll

**Comment by megai2** [comment]
For me it works fine. 
Please add screenshot of bin64 folder and also check that you running latest ArcDPS.

**Comment by OskarwaR** [comment]
Fixed. I clean up my bin64 folder (old reshade folder and trash) and now it works well :3

![snip_20190929184528](https://user-images.githubusercontent.com/55022458/65835664-5900e900-e2e9-11e9-826d-3a5df5c3f1d8.png)

Thanks for your hard work

**Comment by megai2** [comment]
sorted out.
