### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by kaurie** [megai2/d912pxy#195]
Bug description:
With both D912PXY and ArcDPS installed, the game will not start. Launcher will load, hit login, hit play, game does not open. Game is set to Windowed Full Screen. When either addon is installed/enabled separately, the game loads fine. Am using d912pxy.dll naming.

Attempted troubleshooting steps, including reinstalling graphics drivers, direct x update, visual C++ update. Deleted entire bin64 folder and reinstalled.

Windows 10 Home 64 update ver 1903 build 18362.356
GPU Nvidia GeForce 1080, driver 436.30
CPU 8700k, 16 GB RAM
There are no log files

Additional Info:
The two worked fine for me until the 3rd build on the latest living world patch day. At that time, 1.7.1 stopped working with ArcDPS. I reinstalled everything, and it still did not work, until I chose "debug mode" for the non standard release of 1.7.1. With 1.8, debug mode no longer works as a work around.

I have GeForce Experience installed, but closed it int Troubleshooting. I have ReShade installed now, but did not when the problem originally presented itself. I have no other addons/overlays that should cause issues.

**Comment by patrickmaciel** [comment]
I think the problem is with this new version (1.8) with ArcDPS.
If I only use d912pxy = works
If I use with ArcDPS = the game wont start

**Comment by megai2** [comment]
Try to clean-up bin64 folder. Other ppl reported this bug was having extra non used dlls there, that ArcDPS was loading in, making crash.

**Comment by kaurie** [comment]
I did do that, and I also attempted to completely delete the Bin64 folder and reinstalled just arcdps/d912pxy

**Comment by megai2** [comment]
ArcDPS should be latest.
Show me screenshot of your bin64 and "Guild Wars 2" folders please.

**Comment by kaurie** [comment]
Here is the screenshot: https://imgur.com/YnAS6Ua

**Comment by megai2** [comment]
d912pxy will not work at all if you run it as d912pxy.dll with ArcDPS only.
Try with d3d9_chainload.dll

**Comment by kaurie** [comment]
Sorry that was just the bin64 folder, here is gw2: https://imgur.com/w7B3qzy

**Comment by megai2** [comment]
I see reshade, check that you use reshade 4.3+ and see the log of it too. Also try to run game without it, just to pinpoint error. (you should note that you use ReShade first)

**Comment by kaurie** [comment]
Thanks, changing it to d3d9 chainload worked. I swear I tried that before, but ah well. Appreciate the help!

**Comment by megai2** [comment]
Good then.
