### ISSUE TITLE
No installer file?

### ISSUE THREAD

**Issue by Kyoshia** [megai2/d912pxy#196]
I cant find any installer.exe in the file on Github nor the file in the gw2 file how do i installe it then?

**Comment by MTVirux** [comment]
Make sure you downloaded from https://github.com/megai2/d912pxy/releases
and not the "d912pxy-master"

**Comment by patrickmaciel** [comment]
I think the problem is with this new version (1.8) with ArcDPS.
If I only use d912pxy = works
If I use with ArcDPS = the game wont start

**Comment by megai2** [comment]
As said, use release page to download actual release, not source code https://github.com/megai2/d912pxy/releases
