### ISSUE TITLE
1.8 Can't Clear shader cache?

### ISSUE THREAD

**Issue by a5744585** [megai2/d912pxy#198]
Choose an action:
1. Install
2. Remove
3. Clear shader cache
4. Exit

[default: 1, Install]: 3

Clear pck_bns (all but profiles) ? Yes/No
[default: No]:

Clear derived cso, sources and PSO precompile cache? Yes/No
[default: No]:

Remove profiles too? Yes/No
[default: No]:

Perform additional hlsl sources cleaning? Yes/No
[default: No]:

Can't find Z:\Guild Wars 2\d912pxy\pck\shader_cso.pck
Finished
===============================================
Shadow shows error.
Ultra shadow normal.
After the previous version of Clear shader cache, normal.
https://imgur.com/a/KhkrhBg

**Comment by megai2** [comment]
That option is now working now. Just delete latest.pck if you need cache reset.
Shadow is probably missing doe to not profiled shaders for gfx setting you use. 
There will be more profile updates soon.

**Comment by megai2** [comment]
shader cache clear fixed in r439+
profiles will be updated a bit later.
Closing due title being "shader cache clear" error related.
