### ISSUE TITLE
Update / Clean Install Instructions?

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#201]
Whats the proper way to do a clean install If I have reshade and arcdps installed with d912pxy?  Wasn't sure what may get deleted.

**Comment by megai2** [comment]
> 
    Run the install.exe within the d912pxy\ folder
    Choose "Remove" by entering 2 during the fifth input prompt
    Manually remove the d912pxy folder

**Comment by bzeeeb** [comment]
Is there a way to avoid the looong load of textures first time in when just updating d912pxy?

**Comment by bzeeeb** [comment]
Closed it as you answered my original question, just curious about the update question I posted above now ^^

**Comment by megai2** [comment]
you can use https://github.com/megai2/d912pxy/wiki/Shader-packs
