### ISSUE TITLE
GW2 not starting lately because of DX912

### ISSUE THREAD

**Issue by hukyly** [megai2/d912pxy#204]
Okay so main problem is when i click "Play" game doesn't start,
i do not have any other plugin just dx912. Here is my log from that run , hope it helps.

[log.txt](https://github.com/megai2/d912pxy/files/3775715/log.txt)

**Comment by hukyly** [comment]
Oh yea forgot to mention, it did work before i downloaded hotfixed version!

**Comment by megai2** [comment]
It is bug in AMD dx12 drivers, they report out of memory error for no reason.

```
23AA55D8 [ error ] helper | D3D12: Removing Device.
23AA55D8 [ note ] note | 0 | D3D12: Removing Device.
23AA55D8 [ error ] helper | Recived D3D12 device removal message due to 8007000E 
```

You can try set this in config as workaround 
```
[compat] 
dheap_mode = 1 
```

**Comment by hukyly** [comment]
Thanks really for prompt reply, i will try to put that in config, if not i will try to reinstall drivers, i will mark this as solved because if drivers are fucking nothing you can do with it.
