### ISSUE TITLE
gw2 preview/legendary effects transparency bug

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#206]
From reports:
https://github.com/megai2/d912pxy/issues/15#issuecomment-552017912
https://github.com/megai2/d912pxy/issues/15#issuecomment-551998251
https://github.com/megai2/d912pxy/issues/15#issuecomment-543311257

More info needed on repro sequence

**Comment by Cyphall** [comment]
Log with pre-existing shader cache:
[log with shadercache.txt](https://github.com/megai2/d912pxy/files/3827241/log.with.shadercache.txt)

Log without shader cache (I cleared the shader cache before this run):
[log without shadercache.txt](https://github.com/megai2/d912pxy/files/3827242/log.without.shadercache.txt)

Graphics settings:
![config](https://user-images.githubusercontent.com/12214360/68528244-50400180-02f0-11ea-92f7-ca8cec467e78.jpg)

Config:
[config.txt](https://github.com/megai2/d912pxy/files/3827245/config.txt)
Note that the bug also happens with the default autogenerated config)

Steps to reproduce:
1. Install d912pxy with the default values.
2. Run the game
3. Check one of the bugged mounts in the preview window.

**Comment by Atsthio** [comment]
1. 
[log.txt](https://github.com/megai2/d912pxy/files/3827239/log.txt) clear install, not remove any files from archive, default auto-config

2. Set "Render Sampling" to Subsample or Supersample. Open Mount change UI - Select Primeval skin (mostly transparent for me) any mount that got it, even you don't own it.  Ingame everything fine with those skins

**Comment by a5744585** [comment]
![gw206](https://user-images.githubusercontent.com/48787016/68546292-9dff5b80-040f-11ea-8d32-e6f67ef8a96b.jpg)


Stow/Draw Weapons.
Xiuquatl Close-up of the pet snake.

**Comment by Hezkore** [comment]
I have this issue as well.
Anything but "Native" rendering resolution will cause the transparency issue on my mounts.
I'm running the game in Window mode though.

GIF of the issue:
![2020-02-16_01-00-25](https://user-images.githubusercontent.com/1727541/74597012-c5417680-5057-11ea-81f9-dc4ca0670643.gif)

**Comment by megai2** [comment]
should be fixed in [this commit](https://github.com/megai2/d912pxy/commit/cfd4a3336623386998f33e93797f2b0a6deff05c)

![изображение](https://user-images.githubusercontent.com/1693251/82735778-ebe50c80-9d2c-11ea-9c3f-93b4e00c678c.png)

**Comment by Atsthio** [comment]
Primeval and Mad Realm skins now fine for me with r536. 
Trailblazer Beetle, Fire Pinion Griffon, Balthazar's Regalia Outfit now show no transparent effect but something other with vertical lines.
![gw028](https://user-images.githubusercontent.com/20736562/82737184-ae39b100-9d37-11ea-888b-e91852cdd5c2.jpg)
![gw027](https://user-images.githubusercontent.com/20736562/82737189-b72a8280-9d37-11ea-8863-2738a67dc724.jpg)

**Comment by Atsthio** [comment]
(using r542) Found that Gem Shop Preview window also affected with
> Effect when draw Lege Exordium in character menu now without transparency but not limited by the menu window https://youtu.be/cbvnY3Aq7wE

![gw032](https://user-images.githubusercontent.com/20736562/85532480-68af2300-b618-11ea-9b53-e4ccb8ce4906.jpg)
![gw033](https://user-images.githubusercontent.com/20736562/85532504-6baa1380-b618-11ea-9992-7bac61081fbf.jpg)

**Comment by megai2** [comment]
added some fixes, but bug with clipping remains

**Comment by megai2** [comment]
i'll close this issue as transparency is fixed , and open new one with clipping
