### ISSUE TITLE
Grothmar Valley FPS Drops?

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#208]
Just curious is this area poorly optimized or have a lot to render?  I have no FPS issues in say dragon stand but in Grothmar valley my FPS can't get higher than ~35.

Tried tweaking graphic settings setting post processing shaders etc to lowest setting but no dice.

Anyone else have issues with this area?  Maybe I'll lower my view distance too.. think I left that on ultra.

**Comment by megai2** [comment]
follow this one https://github.com/megai2/d912pxy/wiki/Reporting-performance-issues
