### ISSUE TITLE
32 bit won't compile

### ISSUE THREAD

**Issue by handsomematt** [megai2/d912pxy#21]
There are a few use cases of size_t where a Uint64 is required, on 32 bit size_t is 32 bits, thus breaking compilation.

**Comment by Eloquence4** [comment]
Under the "requirements" section of the readme.md

> 16 Gb RAM

Compiling under 32bit is not really intended i imagine.

**Comment by megai2** [comment]
> 
> 
> Under the "requirements" section of the readme.md
> 
> > 16 Gb RAM
> 
> Compiling under 32bit is not really intended i imagine.

Correct.

**Comment by Matthew-Garvey** [comment]
Practically speaking, nobody with a D3D12 capable GPU will require 32-bit.

**Comment by handsomematt** [comment]
I will add an additonal PR to remove 32 bit builds from the solution in that case.

**Comment by worksasintended** [comment]
Although best practise would be to actualle change to Uint64.

**Comment by megai2** [comment]
32 bit builds is removed
