### ISSUE TITLE
add lost ark support

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#212]
uses ue3, looks close to BnS, but can be different
crashes due to locks on resources being held over frame end

**Comment by megai2** [comment]
some quick tests with latest builds

![изображение](https://user-images.githubusercontent.com/1693251/85411936-ae64e080-b571-11ea-90a9-8c5dca1c6193.png)

![изображение](https://user-images.githubusercontent.com/1693251/85417014-d2c3bb80-b577-11ea-9fc7-28cf4bdd4ae6.png)

**Comment by megai2** [comment]
So it works =)

**Comment by ngc7743** [comment]
![image](https://user-images.githubusercontent.com/67748893/113539414-bd0c1800-9618-11eb-9d0c-f45ed78ef526.png)
![image](https://user-images.githubusercontent.com/67748893/113539532-ed53b680-9618-11eb-8043-825cde82105e.png)

I want to use it in Lost Ark, but the buildings are not loaded.

**Comment by VinceBT** [comment]
@megai2 Which configuration did you use ? I get this when trying on the closed beta (Steam version):
![image](https://user-images.githubusercontent.com/1362505/140626558-7307b9ed-f2cf-400d-a758-1bf838d735da.png)

**Comment by megai2** [comment]
> 
> 
> @megai2 Which configuration did you use ? I get this when trying on the closed beta (Steam version): ![image](https://user-images.githubusercontent.com/1362505/140626558-7307b9ed-f2cf-400d-a758-1bf838d735da.png)

version that was actual at time of testing, dunno

this error shows that EAC treats file as untrusted, and you can't run game with it, so i can't do much about it
