### ISSUE TITLE
Add Astellia Online support

### ISSUE THREAD

**Issue by Zalatis** [megai2/d912pxy#218]
A support for this mmorpg would be nice I think :) 
https://www.astellia-mmo.com/

**Comment by megai2** [comment]
If it have 64 bit client and uses dx9, you can try to install it using standart instructions https://github.com/megai2/d912pxy/wiki/Installing

If installation is ok and d912pxy is loaded normally, you should see d912pxy/log.txt file and general behaivour related to d912pxy.

**Comment by Zalatis** [comment]
It looks like it doesn't do anything

**Comment by megai2** [comment]
i'm quite low on time now to properly debug and fix things for Astellia.
I'll let you know if there is some progress

**Comment by Zalatis** [comment]
Okay no problems thanks :)

**Comment by yong24k** [comment]
oh very thanks

**Comment by seathasky** [comment]
Would also like this working for astellia! Thanks for working on it for us!

**Comment by megai2** [comment]
latest builds are able to startup game

**Comment by megai2** [comment]
apitrace based dumps are working too (at least not crashing)

but RU client are not loading with d912pxy, probably due to protection
don't have other localizations at hand, so it will be nice if someone test latest build on them

**Comment by seathasky** [comment]
the april build doesnt work with Astellia NA. is there another build you're talking about?

**Comment by seathasky** [comment]
Here, I made you a video to show you what happens. I'm using the latest April release of d912pxy. https://www.youtube.com/watch?v=BjzxfINYXXk&feature=youtu.be
I install, run client and game does not load. If I "remove" d912pxy, the game runs again. I cant get this to work.

**Comment by megai2** [comment]
> 
> 
> the april build doesnt work with Astellia NA. is there another build you're talking about?

the latest build, from here https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts


> 
> 
> Here, I made you a video to show you what happens. I'm using the latest April release of d912pxy. https://www.youtube.com/watch?v=BjzxfINYXXk&feature=youtu.be
> I install, run client and game does not load. If I "remove" d912pxy, the game runs again. I cant get this to work.

Better to install it without other things, just as d3d9.dll(no other chainloads & etc) using default BnS config (or you will get a blackscreen/crash)

**Comment by seathasky** [comment]
> 
> the latest build, from here https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

> 
> Better to install it without other things, just as d3d9.dll(no other chainloads & etc) using default BnS config (or you will get a blackscreen/crash)

Thanx for this! Much appreciated! Gonna test now

**Comment by seathasky** [comment]
Still doesnt work, same thing happens. Crashes when launching. Just installed with d3d9.dll like you said as well.

**Comment by megai2** [comment]
> 
> 
> Still doesnt work, same thing happens. Crashes when launching. Just installed with d3d9.dll like you said as well.

and no d912pxy/log.txt created/updated?

**Comment by seathasky** [comment]
> > Still doesnt work, same thing happens. Crashes when launching. Just installed with d3d9.dll like you said as well.
> 
> and no d912pxy/log.txt created/updated?

None whatsoever. I even reinstalled the game twice  to make sure i had clean install. Tried different settings after the d3d9.dll install did not work. Idk, just not working for me. I'm on NA Astellia btw.

**Comment by megai2** [comment]
> 
> 
> > > Still doesnt work, same thing happens. Crashes when launching. Just installed with d3d9.dll like you said as well.
> > 
> > 
> > and no d912pxy/log.txt created/updated?
> 
> None whatsoever. I even reinstalled the game twice to make sure i had clean install. Tried different settings after the d3d9.dll install did not work. Idk, just not working for me. I'm on NA Astellia btw.

Now it looks like problem is in proxy, will try to dig around.

**Comment by megai2** [comment]
check latest build, worked for me, but can be different in another locales

**Comment by seathasky** [comment]
April build? Is there a nightly build website? I cant find that.

**Comment by seathasky** [comment]
Okay found it. Now getting this: https://imgur.com/a/1FHfPrc

I tried to make all folder not read only  but it reverts everytime.

**Comment by megai2** [comment]
> 
> 
> April build? Is there a nightly build website? I cant find that. https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts this?

yep, latest build is always there


> 
> 
> Okay found it. Now getting this:
> https://imgur.com/a/1FHfPrc
> https://imgur.com/a/fcxYoX2
> 
> I tried to make all folder not read only but it reverts everytime.

Can you show full path to game .exe file ? 
Like this: F:\games\ast\live\Binaries\Win64\Astellia.exe

**Comment by seathasky** [comment]
E:\Astellia\AstelliaClient\Binaries\Win64

**Comment by megai2** [comment]
changed code to include this case, but not tested at all (no time for today)

now you can try to install d912pxy in any folder that is on path to client and it should properly catch up needed files

like E:\Astallia\d912pxy or E:\Astellia\AstelliaClient\d912pxy, whatever folder will not be blocked by game will be good to go

**Comment by seathasky** [comment]
Hey! Getting closer! So I can enter the launch screen now, but it crashes after 10 seconds.
Also no background art or anything. I see this before it crashes:  https://imgur.com/a/3JeCYP8

**Comment by megai2** [comment]
> 
> 
> Hey! Getting closer! So I can enter the launch screen now, but it crashes after 10 seconds.
> Also no background art or anything. I see this before it crashes: https://imgur.com/a/3JeCYP8
> 
> Log file: https://filebin.net/zlqz86z7fktq62l6/log.txt?t=14cl7hxh
> 
> **### Update:**
> **Things i've tried:**
> Made sure it was running in Borderless window mode. Tried Regular windowed and fullscreen as well.
> Reinstalled a few times. Tried the BnS config as well as the default.
> Turned off and on the d912pxy GUI in the config.
> 
> Crashes after I click my character to enter game: This is as far as i get: https://imgur.com/a/br1v5w3

you need to delete all latest.pck files in pck and pck_bns folder, and run with bns config, if it still crashes, send log to me

**Comment by megai2** [comment]
@seathasky no news on subject?

**Comment by seathasky** [comment]
Just hasnt worked so I kind of gave up on this but i tried again today. Here is the crash log: https://drive.google.com/file/d/1ruhiZn8bK5mfH0yxtweBvmNUl09pDhNn/view?usp=sharing

**Comment by megai2** [comment]
> 
> 
> Just hasnt worked so I kind of gave up on this but i tried again today. Here is the crash log: https://drive.google.com/file/d/1ruhiZn8bK5mfH0yxtweBvmNUl09pDhNn/view?usp=sharing
> i'm down to keep helping to get this running though if was can. 👍

there is 2 variants to troubleshoot

1) you can run _d build (just copy d3d9 from d912pxy\dll\release_d to win64 folder), run game and send a log from win64/p7logs here


2) you can download [apitrace ](https://ci.appveyor.com/api/projects/jrfonseca/apitrace/artifacts/build/apitrace-latest-win64.7z?branch=master&job=msvc64) put d3d9.dll from lib\wrappers to game win64 folder. run game, exit as soon as it loaded,  and then send Astellia.trace from desktop


both variants will make huge log/dump, so make sure you have ~500Mb-1.5Gb on drives

**Comment by valeryan** [comment]
I just picked up Astellia from steam cause its half price right now. Works great using the bns config with the latest successful build. It takes a lot longer for the initial render than guildwars 2 but the performance boost is great. I am getting about ~60-70 fps and no horrible game studders. I played it for about an hour vanilla before I tried it with the proxy.

**Comment by megai2** [comment]
I did not found source of crashes @seathasky :(
But it works for me and @valeryan 

Maybe there is some integrated overlay in non steam version, or there is something restrictive (like install in Program files, windows restricts file access there)

**Comment by megai2** [comment]
any news? v2.3 have some fixes around the board, maybe they helped out with NA build

**Comment by makemefeelgr8** [comment]
@megai2 
I've captured a crash log using debug dll file, hope it helps.
[log.zip](https://github.com/megai2/d912pxy/files/5347992/log.zip)

**Comment by megai2** [comment]
again very quiet.
is that an NA version @makemefeelgr8 ?

**Comment by seathasky** [comment]
The game is dead

**Comment by makemefeelgr8** [comment]
@megai2 Yes

**Comment by megai2** [comment]
Logs give zero info on problem on NA version of game, other versions seem to work properly.
I close this issue for now, if you want to troubleshoot NA version then reach me on discord and we troubleshoot it there.
