### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by Entity-Five** [megai2/d912pxy#219]
Installs ok, game (Guild wars 2) runs great. Next time 
- game may not open (launcher spawns game process then it silently dies). Log says feature level not supported

- game may crash about a second after entering world (or re entering world after exiting pvp) with a prompt to send to a bug report to anet

- unusual > 50% vram usage when game is not running

system details:
d912pxy version: d912pxy_v1.9h2_r455
cpu: I7 4790
RAM: 16GB
gpu: AMD RX 470 4GB (driver version 19.12.2)
OS: Windows 10 x64 1909
AV: Kaspersky free 20.0.14 (said this addon was clean & windows defender did not complain either)
no other addons

Can't think of anything else that would help. Thank you for the great work

**Comment by megai2** [comment]
Start with https://github.com/megai2/d912pxy/wiki/Reporting-crashes

Also you this line can be helpfull:

> 
> -I'm crashing with "D3D12 device removal due to 8007000E" since v1.6. Any help?
> 
> This thing looks like a driver bug, so i added a quick workaround:
> 
> add dheap_mode=1 under [compat] section in config, that should cover your problem.

**Comment by Entity-Five** [comment]
will test and let you know, thanks

**Comment by Entity-Five** [comment]
[log.1.txt](https://github.com/megai2/d912pxy/files/4011897/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/4011898/log.txt)

Using that fix had it working for a week without issue. About 2 days ago the game started doing the following approx every hour of gameplay

- Freeze for about 2 seconds

- About a 10% chance of crashing on above freeze

- Windows taskbar briefly shows above game (only 200ms at most), about every 30 min

Please don't take my feedback as any form of complaint, just trying to help you by testing.

**Comment by a5744585** [comment]
Delay to start GW2, maybe a few seconds or a few minutes (within 5 minutes).
I do n’t know why, but the game will start slowly rather than freeze.
I also thought he had a problem, until one time I inadvertently waited until his GW2 operation started.

**Comment by LinearBotSystems** [comment]
Same here a few days ago GW2 started to crash very often could be the new NVIDIA driver at least this is the only thing what changed besides winterday being not there any more. ARC DPS also fixed also updated because of the crashed . I use the newest version of 
d912pxy  from December. For me it after a few minutes after start the game slows down very quickly until it freeze and then it crashes if this is not happening it runs relative long without crash. Okay I wouldn't be me if couldn't tell more I let run Code Analysis from VS over it and besides a lot of warning which can be mostly ignored(mostly type casts) it showed at least 1 error client.h 379 no member type
`   template <typename U>
    HRESULT CopyTo(Details::ComPtrRef<ComPtr<U>> ptr, typename Details::EnableIf<
      ((Details::IsSame<T, IInspectable>::value && !Details::IsSame<U, IUnknown>::value) || (Details::IsSame<T, IUnknown>::value))
      && !Details::IsSame<U*, T*>::value, void *>::**type** * = 0) const throw()`

**Comment by megai2** [comment]
@LinearBotSystems i can't understand you really. start with logs and bin64 cleanup.

**Comment by LinearBotSystems** [comment]
> 
> 
> @LinearBotSystems i can't understand you really. start with logs and bin64 cleanup.


Okay easier the main problem  : 
 https://en-forum.guildwars2.com/discussion/94319/crashes-after-wintersday-update#latest
The  other go in VS to analyze => Code Analysis  => for project .Say everything is okay ^^
A log I can give you the next time when I have a crash again

**Comment by LinearBotSystems** [comment]
Okay here is the log
[log.txt](https://github.com/megai2/d912pxy/files/4052129/log.txt)

**Comment by Entity-Five** [comment]
Closing this issue. Since version 2 was released all gpu memory is cleaned up on game close (even without dheap_mode=1)
