### ISSUE TITLE
Visual Bug in the new strike mission released 

### ISSUE THREAD

**Issue by moeyaghi** [megai2/d912pxy#221]
The Walls and floor and character seems like to be almost not loaded (Everything is almost Invisible), It Changes with movement of the camera and it seems its not only me having this problem

**To Reproduce**
1. Run game
2. Graphic Setting Doesn't Matter
3. Head to Bjora Marches , New strike Mission

**Screenshots**
https://imgur.com/gallery/d5Am1Cb

**Standard information**
1. Windows 10 Home, Version 1909
2. Hardware info: Intel Core i7-855U, 8GB 2133MHz , AMD Radeon 530 
3. GPU Driver Version 24.20.11016.11001
4. d912pxy Version 1.9 hotfix 2

**Comment by megai2** [comment]
try setting this one in config
```
[compat]
occlusion=1
```

should fix problem

**Comment by moeyaghi** [comment]
Which config file ?

**Comment by megai2** [comment]
> 
> 
> Which config file ?

you can read about it here https://github.com/megai2/d912pxy/wiki/Custom-configuration

**Comment by moeyaghi** [comment]
Thank you!

**Comment by megai2** [comment]
will close it when i update default config

**Comment by miraculix27** [comment]
I have the same problem. Change the settings in the config file dosnt work.
