### ISSUE TITLE
d912pxy Reshade

### ISSUE THREAD

**Issue by s0ulty** [megai2/d912pxy#222]
Latest Nvidia drivers, win 10, latest Reshade installed as dxgi/d3d12, latest release version of d912pxy.
GW2 works fine without Reshade, but crashes with it at certain points, like when opening map or some other UI related elements. Tried running older versions of R., windowed fs, fullscreen etc. Anything i can do about this? Tried compiling latest version of d912pxy from github, seemed to get even worse. Help appreciated, thanks!

**Comment by acbetter** [comment]
You can try d912pxy v2.0

**Comment by megai2** [comment]
Currently all reshade versions above 4.3 have buffer detection that fails with crash due to number of reasons

Use reshade 4.3 as workaround for now

**Comment by s0ulty** [comment]
Yeah, tnx for the help! I stumbled upon 4.3 working with 2.0 release. Currently using avx2 build with it. @megai2 Your tool is a godsend for this game honestly. The smoothness, it's like playing another game, i've came bck to GW2 after a year or so and right away decided to try it with d912pxy and oh boi, haven't had that much fun in this game since launch. xD Thanks a lot for your work!

**Comment by megai2** [comment]
There is special channel as well as custom releases for reshade by Serfrost

So you can try/ask/troubleshoot 
here https://discord.gg/CgUhHdB
and there https://github.com/Serfrost/ReShade-GW2
