### ISSUE TITLE
VCRUNTIME140_1.dll Missing Error Message when running install.exe

### ISSUE THREAD

**Issue by NapalmDest54** [megai2/d912pxy#223]
**Describe the bug**
VCRUNTIME140_1.dll Missing Error Message when running install.exe. 

I can execute the install.exe from Version 1.9 hotfix 2 without issue.

**To Reproduce**
Steps to reproduce the behavior.

1. Download and unzip 2.0 Release
2. Run install.exe
3. Message Appears: "The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem."

**Expected behavior**
the dx912pxy installer should run

**Standard information**

1. Windows 10 update version 1903
2. Hardware info: Intel i7 5820k, 16GB ram
3. Version of d912pxy used: 2.0

**Comment by NapalmDest54** [comment]
I have corrected this by installing the x64 version from: https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by megai2** [comment]
updated link to msvc here https://github.com/megai2/d912pxy/wiki/Reporting-crashes
