### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by beng1302** [megai2/d912pxy#226]
Clean Install of V2 standalone without other mods. Game crashes immediately when opened.
Doesnt crash if installed as chainload with arcdps but also doesnt load at all (no log or config created).
V1.9 loads correctly.

Windows 10 Home Version 1903
Amd Phenom II x4 945 3ghz 8GB RAM
Radeon RX 580 Driver 20.1.3

**Comment by megai2** [comment]
v2.0 needs fresh vcredist https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

it this not helps, check this guide 
https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by beng1302** [comment]
fresh vcredist was installed as the v2 installer wouldnt run.

**Comment by beng1302** [comment]
the non standard release_d and release_pp versions startup without crashing if that helps

**Comment by megai2** [comment]
i see the problem, your CPU does not support avx instruction set.
you can use v1.9 as workaround for now.

**Comment by beng1302** [comment]
is there a reason why the release_d and release_pp options work

**Comment by watlok** [comment]
> i see the problem, your CPU does not support avx instruction set.
> you can use v1.9 as workaround for now.

2.0 crashes on startup with a 3900x + 2070 super. 3900x supports AVX & AVX2.

**Comment by jaro-sagan** [comment]
Hi, I think I have the same problem. My CPU is Intel Core 2 Quad Q9650 which also does not support AVX. 

Do you plan a fix for that? 

btw. thank you for your awesome work 👍

**Comment by Squall-Leonhart** [comment]
I have taken care of this in my fork here
https://github.com/Squall-Leonhart/d912pxy/releases/tag/v2.1

**Comment by megai2** [comment]
Fixed properly by autoselecting version to install in both addon loader build & manual installer 

You can grab it from latest build (https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts)
 or wait for v2.1 release

**Comment by llitz** [comment]
@megai2 not sure if you want me to open a different issue, new version also crashes for me but it doesn't work with any of the newer version, even the going through the new build you did (tried all binaries).

```
*--> Crash <--*
Assertion: Failed to load Coherent DLL: 0x5 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(50)
App: Gw2-64.exe 
Pid: 1416
BaseAddr: 00007FF674DB0000
ProgramId: 101
Build: 102063
When: 2020-02-19T02:33:47Z 2020-02-18T19:33:47-07:00
Uptime:   0 days  0:00:01
Flags: 0
```

**Comment by megai2** [comment]
v2.1 released
