### ISSUE TITLE
[ error ] iframe | batches in one frame exceeded PXY_INNER_MAX_IFRAME_BATCH_COUNT, performing queued commands now

### ISSUE THREAD

**Issue by ego0125** [megai2/d912pxy#228]
Hello megai2,

I installed d912pxy__r498 for BnS(Blade & Soul). I can play BnS, but I found that the below error message is contentiously reported.
[ error ] iframe | batches in one frame exceeded PXY_INNER_MAX_IFRAME_BATCH_COUNT, performing queued commands now

I searched PXY_INNER_MAX_IFRAME_BATCH_COUNT in the Issues category, and found an article related to the error. Hence, I changed "nv_disable_throttle" to 1 as following the guide, but it didn't  fix the issue. For the testing purpose, I used both bns_config.ini and bns_hiend_config.ini.

I highly appreciate if you could check my issue, and advise how I can fix it.

[log.txt](https://github.com/megai2/d912pxy/files/4154040/log.txt)

**Comment by megai2** [comment]
it is normal.
sometimes game draws too many things at once, triggering it.

if this repeats in log too frequently (like 3Mb log with this error after 10min), that sure need changing in code

**Comment by ego0125** [comment]
Thanks very much for your answer. I'll report again if the log file exceeds 3MB within 10 mins. :)
