### ISSUE TITLE
Shadows near the player not rendering correctly

### ISSUE THREAD

**Issue by Hezkore** [megai2/d912pxy#232]
**Describe the bug**
Shadows near the player are not rendered correctly.
Instead of appearing in higher quality; they just disappear.

**To Reproduce**
1. Run game
2. Set Shadows to "High"
3. Watch shadows disappear as you move near them
4. Do the same thing in standard GW2 and notice that they do not disappear

**Expected behavior** (You've spelled behaviour wrong)
Shadows near the player should be displayed at a higher quality, not disappear.

**Videos**
Here's how it looks in-game: https://hezkore.com/junk/d912pxy.mp4
And here's how it should look: https://hezkore.com/junk/original.mp4

**Standard information**
1. Windows 10 1909
2. Hardware info: Ryzen 7 2700X, 32GB, RTX 2070
3. nVidia Drivers 441.87
4. d912pxy Version 2.0

**Additional information**
I'm no expert on this, but it seems to me like the alpha is incorrect for the nearest shadows.
If you look closely you can actually see the shadows near the player, they're just very faint.

**Comment by megai2** [comment]
Latest gw2 update changed shadow shaders, so profiles for them need to be updated.

I pushed some new profiles, you can take it from latest appveyor build or wait for v2.1 release

**Comment by Hezkore** [comment]
Yep, after clearing the shader cache with the new version this is fixed.
Well done.

I'll go ahead and close this as this will be fixed in the next release.

**Comment by Veskomenas** [comment]
I have same problem. Where i can find those updated shadows shaders pack? I tried to clear up shaders with d912pxy install file but still same problem... Thank you Megai2.

**Comment by megai2** [comment]
take latest build for that https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

**Comment by corkiran** [comment]
This exact issue (as described in OP) is present for me on the latest builds: I've tried both v2.1h1_r514 and v2.1.1_r523
Windows 10 Pro 1903
Nvidia Drivers: 445.75
Hardware: Ryzen 3700x, GTX 1070, 16GB RAM

**Comment by megai2** [comment]
maybe devs again touched shadow shaders, so new profiles needed

**Comment by nminchow** [comment]
Just confirming that I am seeing this as well. I don't seem to have this issue if I put shadows on "ultra", but I prefer to run it on high.
