### ISSUE TITLE
Window resize causes crash

### ISSUE THREAD

**Issue by Hezkore** [megai2/d912pxy#233]
**Describe the bug**
Resizing the window for a while causes a crash.

**To Reproduce**
1. Run game
2. Resize window for an extended period of time
3. Notice the crash

**Expected behavior**
You shouldn't have to hurry up and resize the window before the game crashes.
You should be able to resize the window for however long you want.

**Video**
Example of the issue: https://hezkore.com/junk/2020-02-16_00-49-17.mp4

**Standard information**

1. Windows 10 1909
2. Hardware info: Ryzen 7 2700X, 32GB, RTX 2070
3. nVidia Drivers 441.87
4. d912pxy Version 2.0
5. No log file exists

**Comment by megai2** [comment]
i added some limiting factors to keep things alive while resizing window

**Comment by Hezkore** [comment]
Latest appveyor build still crashes while resizing, it's just a bit laggier when resizing now.

**Comment by Hezkore** [comment]
It still crashes on the latest release version.
Resizing is super laggy now, and the crash is even worse.

Example: https://hezkore.com/junk/2020-02-24_18-29-26.mp4

**Comment by megai2** [comment]
> 
> 
> It still crashes on the latest release version.
> Resizing is super laggy now, and the crash is even worse, resulting in hundreds of report windows being created.
> 
> Example: https://hezkore.com/junk/2020-02-24_18-29-26.mp4

Yes, it limited resize rate to 1 resize per second. 
Crash is odd, i keeped resizing it for a solid 5 min =\

Attach a log please.

**Comment by Hezkore** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/4246553/log.txt)

**Comment by megai2** [comment]
> 
> 
> [log.txt](https://github.com/megai2/d912pxy/files/4246553/log.txt)

That is about config

> 
> 137DA02D [ info ] device | pooling.surface_limits = 00005 
> 

It tells to keep textures (5 for every unique w-h-mips-format key) in memory to avoid hitting recreation lag, resulting in every resolution dependent texture to stuck in memory when resizing

Will try to extend cleanup to include them in it too, but for a while see if all works correctly with surface_limits = 00000

**Comment by megai2** [comment]
I'm not sure on a 1:1 relation between screen resizing and device reset with back buffer resizing,
so current logic will stay: if you have surface limits setted up (to > 0) then resizing window will trash memory a bit. use other options (cleanup config section) to achive same results while avoiding this.

**Comment by Hezkore** [comment]
I have no idea what things actually do, I'm just using the "hiend" config provided with the installer.

**Comment by megai2** [comment]
Configs was made up without window-resize test as this is not very common thing to encounter.
You can read more about values here https://github.com/megai2/d912pxy/wiki/Custom-configuration

**Comment by Hezkore** [comment]
The config files still aren't updated and recommends that you use `pooling.surface_limits = 00005`
