### ISSUE TITLE
Game crashing at random

### ISSUE THREAD

**Issue by digitalruse** [megai2/d912pxy#234]
**Describe the bug**
I can't tell when or why, but the game is crashing with 2.0 enabled. Not an issue with 1.9.

**To Reproduce**
Just playing the game and it happens.

**Expected behavior**

**Standard information**

1. Windows 10 update ver
2. Hardware info: CPU, RAM, GPU:
Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz 6 Cores
Radeon Pro 560X
32GB RAM

3. GPU Driver version: Radeon 2020.0113.1626.29577
4. Version of d912pxy used: 2.0
5. Log file
[log.1.txt](https://github.com/megai2/d912pxy/files/4234040/log.1.txt)

**Comment by digitalruse** [comment]
Driver:
19.50.11.10-200113a-350865E-RadeonSoftwareAdrenalin2020

**Comment by digitalruse** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/4234081/log.txt)

Another just happened

**Comment by megai2** [comment]
try latest build https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

**Comment by RonsoXIV** [comment]
Please update if this fixes your crashes. I think I have the same problem. 

Would constantly get c++ runtime error into a no video signal black screen or a bsod video scheduler internal error. 

Game will run from anywhere between 5 minutes to an hour and just randomly crash into one of the above mentioned errors.

Im running a Rysen 5 2600 @4Ghz, amd 5700xt, 16Gb of ram

**Comment by digitalruse** [comment]
[log.1.txt](https://github.com/megai2/d912pxy/files/4238795/log.1.txt)

Took longer, but still happened:

123847A [ error ] swap chain | error: 887A0005 

123847A [ error ] swap chain | Swap error, 1 in sequence 

12384B9 [ error ] helper | Exception: E06D7363 

12384B9 [ error ] helper | Exception: E06D7363 

12384B9 [ error ] surface | d12res_tex2d w 256 h 256 arsz 1 lvls 7 fmt 71 

12384B9 [ error ] surface | throw on "texture object create failed" with HR = 0x887A0005 

12384B9 [ note ] note | 185 | "texture object create failed" | hr = 887A0005 

12384B9 [ note ] note | 186 | D3D12 device removal due to 887A0006 

12384B9 [ error ] helper | Exception: E06D7363

**Comment by megai2** [comment]
Have you removed old pck folder when updating from 1.9?

Try to set dx_debug=1 in [misc] config section
if game will not load after changes install graphics tools
https://www.thewindowsclub.com/install-graphics-tools-in-windows-10

This will enable dx12 error checking, maybe it will be helpfull
Also what addon you use besides d912pxy, does it crash without that addon?

**Comment by RonsoXIV** [comment]
[log.1.txt](https://github.com/megai2/d912pxy/files/4239953/log.1.txt)

Went OK for about 8 hours having the dx_debug=1 and having installed graphics tools

**Comment by digitalruse** [comment]
Completely clean install with dx_debug=1 enabled
[log.txt](https://github.com/megai2/d912pxy/files/4240627/log.txt)

**Comment by digitalruse** [comment]
Only have GW2mount radial with dx912

**Comment by designmesk** [comment]
Having this issue too with v. 2.1.
Radeon 5700 with driver v. 20.2.1
Crashing to black screen since v. 2.0

**Comment by megai2** [comment]
Did you do a clean install after v1.9?

**Comment by designmesk** [comment]
Yup, clean.
Will try 1.9. Running dxvk now.
Maybe it is a problem with radeon drivers. They had some similar problems afaik

**Comment by megai2** [comment]
> 
> 
> Yup, clean.
> Will try 1.9. Running dxvk now.
> Maybe it is a problem with radeon drivers. They had some similar problems afaik

Make sure you not mixed dxvk dlls with d912pxy dlls, check both bin64 and game root folder, game can load dlls from both places.

**Comment by Squall-Leonhart** [comment]
keep in mind, radeon 5700's are crashing to black screens because the drivers have several bugs.

That said, i've had a number of TDR's on my GTX 1080 with 2.1, that i did not with 2.0

**Comment by digitalruse** [comment]
Completely clean Bin, d912pxy folder/install, 2.1

Still happening.
[log.1.txt](https://github.com/megai2/d912pxy/files/4253225/log.1.txt)

**Comment by digitalruse** [comment]
So... not to jinx it, but build 518 appears to be stable.

**Comment by digitalruse** [comment]
Spoke too soon 
[log.1.txt](https://github.com/megai2/d912pxy/files/4272289/log.1.txt)

**Comment by digitalruse** [comment]
520 crashing too
[log.1.txt](https://github.com/megai2/d912pxy/files/4272752/log.1.txt)

**Comment by Squall-Leonhart** [comment]
where are you even getting these?

514 is still latest and no changes to the proxy have been made since 514

**Comment by digitalruse** [comment]
Maybe I misunderstand the link that Megai2 provided for "latest build", but it says version "520" when I download it and the new exes are different.

**Comment by Squall-Leonhart** [comment]
ah, i see now.

The latest proxy specific changes are still in hf1 under the releases section,  the appveyor builds since then have been for the overlay patches.

**Comment by digitalruse** [comment]
Apologies then. That's ignorance on my part. I'll wait for more word from megai2 then.

**Comment by megai2** [comment]
i think error tracks down to commits between r477-r478, but found nothing yet

if you can crash it at will, let me know about r477 stability

**Comment by digitalruse** [comment]
r477 was going okay for a while, then it struck again
[log.txt](https://github.com/megai2/d912pxy/files/4279254/log.txt)

**Comment by megai2** [comment]
well, then bug is in earlier changes, are you sure 1.9 release works fine?

**Comment by digitalruse** [comment]
I'll switch back again, but when I was last on 1.9 it hadn't caused any issues. Happy to test another build or turn on other logging if it helps.

**Comment by megai2** [comment]
then try r464 and r463, it will really help out if you find out what revision started to bug out as i can't trigger crash for myself

**Comment by digitalruse** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/4288254/log.txt)

Here is a log of a crash free 1.9 from last night. That said, there were two times playing where the game completely locked up for about 3 seconds, but recovered instead of crashing.  I don't know if that is something you'll see in the log.  Is there a way to turn on time stamping? So when I catch the freezes or other things I can note that?

I'll try those two builds tonight and see what happens.

**Comment by digitalruse** [comment]
So, interestingly, 1.9 and r463 have a similar behavior.  The game will occasionally freeze for about 2-3 seconds and then come back. When this happened in later builds it always resulted in a crash. I've attached a r463 log from a short play where I was mostly in Rata Sum and the behavior happened twice. 

[log.txt](https://github.com/megai2/d912pxy/files/4301313/log.txt)

**Comment by Henoman** [comment]
hey, just stopping by to let you know i have had the same (or very similar) issue as digitalruse, kept crashing me, even after i reinstalled it a few times , i have since uninstalled it because crashing wasn't that annoying in  pve, but when in wvw the queues are awfully long...i have arcdps, gw2radial and d912pxy, not sure if these logs  will help at all. I'm willing to install it again etc. i'll stop by here and there. and btw, thank you for d912pxy. :) 
[log.1.txt](https://github.com/megai2/d912pxy/files/4319454/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/4319456/log.txt)

**Comment by megai2** [comment]
added a fix
check latest build https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

**Comment by digitalruse** [comment]
Okay. So far this appears to be working. I did get one of those mega freezes, but the game recovered and didn't crash.
[log.1.txt](https://github.com/megai2/d912pxy/files/4332287/log.1.txt)

**Comment by digitalruse** [comment]
And then tragedy struck while fighting drakkar when I opened my inventory. It was going so well, but might be a fluke of some kind unrelated to d912pxy.

[log.1.txt](https://github.com/megai2/d912pxy/files/4333271/log.1.txt)

**Comment by megai2** [comment]
> 
> 
> And then tragedy struck while fighting drakkar when I opened my inventory. It was going so well, but might be a fluke of some kind unrelated to d912pxy.
> 
> [log.1.txt](https://github.com/megai2/d912pxy/files/4333271/log.1.txt)

and this is clearly out of memory crash

**Comment by megai2** [comment]
looks like all is fine now, right?

**Comment by designmesk** [comment]
Looks like it is all fine now so far. No crash since I have this combo below.
Version 2.1.1 + Radeon Adrenalin 2020 Edition 20.2.2 (RX 5700).

**Comment by megai2** [comment]
well i close it for now then
