### ISSUE TITLE
大神求幫助

### ISSUE THREAD

**Issue by FYAHK** [megai2/d912pxy#235]
I used the latest version but FPS is not stable 60

Is there any way that can help me?

Open 32-bit crazy crash

I am WIN10 version 1909

i7-9700

Graphics card GTX 1050Ti
![adf717cb464caa230514cadeb398a867](https://user-images.githubusercontent.com/61471179/75272198-6a1e3980-5838-11ea-89ea-9b0893840852.jpg)

**Comment by megai2** [comment]
32bit is not working with d912pxy

And stable 60 FPS is not garantied result

**Comment by FYAHK** [comment]
那有辦法64為源穩定FPS嗎?

**Comment by megai2** [comment]
> 
> 
> 那有辦法64為源穩定FPS嗎?

no, nothing can make game 60 fps stable

**Comment by megai2** [comment]
will just repeat it
1. FPS depend on game, tool raises FPS, but not to "stable 60 everywhere"
2. Tool does not work for 32-bit applications, only for 64-bit
