### ISSUE TITLE
lowered fps due to enabled occlusion queryes

### ISSUE THREAD

**Issue by Phyxsyus** [megai2/d912pxy#236]
Since I updated from version 2.0 to 2.1 i lost around 20 fps in some areas. Is there any config I should tweak?

Ryzen 7 3700x
16gb DDR4 @3200
Gtx 1070
Nvme SSD Samsung 970 Evo Plus

**Comment by megai2** [comment]
try set occlusion=1

**Comment by megai2** [comment]
and some ppl report game itself laggy(on dx9), does it work fine for you without d912pxy?

**Comment by rudyzhou2** [comment]
occlusion=1 seem to done the trick for me. FPS and camera movement lag seem to be back to normal

ryzen 2600x
16gb DDR4 3000
RX580

**Comment by megai2** [comment]
then you will have problems with extra things drawed, like lens flare thru mountains =]

i kinda upset about this anet "new feature" to use hw occlusions extensively, 
have some ideas how to workaround this, but need quite amount of time to implement that ideas

**Comment by rudyzhou2** [comment]
would you recommend going back to 2.0 in this case?

**Comment by megai2** [comment]
if you encounter said bugs and they bother you - yes

if you don't care about it, but care about perf - no =]

**Comment by moeyaghi** [comment]
I tried all the fixes suggested in here, nothing works my game in the new strike mission runs at 1 fps, and raid w1 from second boss to last runs 1 fps too, so i stopped playing waiting for a new build

**Comment by megai2** [comment]
will be good if you send some logs here @moeyaghi

**Comment by moeyaghi** [comment]
@megai2 How do i make logs ? sorry for being stupid xD

**Comment by megai2** [comment]
> 
> 
> @megai2 How do i make logs ? sorry for being stupid xD
They should be here: d912pxy/log.txt & d912pxy/log.1.txt

**Comment by moeyaghi** [comment]
@megai2 game running perfectly so far and no issues with dx12 ?? is it because of yesterday's gw2 patch ?

**Comment by megai2** [comment]
dunno

**Comment by megai2** [comment]
see main issue & status on it #250
