### ISSUE TITLE
enable=1 + fps_limit draws overlay when no other extras are enabled

### ISSUE THREAD

**Issue by Aussiemon** [megai2/d912pxy#237]
**Describe the bug**
When enable=1 and fps_limit under the [extras] section are enabled, but all other options are disabled, the overlay displays as a 32x32 box with no contents. It can still be toggled off with the overlay keybind at least.

**To Reproduce**
INI settings are:
[extras]
enable=1
fps_limit=90
fps_limit_inactive=0
show_fps=0
show_draw_count=0
show_fps_graph=0
show_timings=0
show_pso_compile_que=0
show_gc_que=0
overlay_toggle_key=78
fps_graph_max=80
fps_graph_min=0
fps_graph_w=512
fps_graph_h=256
enable_config_editor=0

on a fresh config.ini

1. Run game
2. Observe box in top-left of screen.

**Expected behavior**
The box should not display when there are no contents to display.

**Screenshots**
![Annotation 2020-02-27 182739](https://user-images.githubusercontent.com/13663574/75502504-2b02fc00-5990-11ea-900b-c060960e2219.png)

**Additional context**
imgui.ini respects changes to the overlay position, but not its collapsed setting. The overlay can't be shrunken smaller than 32x32.

**Comment by Aussiemon** [comment]
The black square returns when the game is closed and re-opened. I don't know if the overlay toggle setting is supposed to be saved, but it isn't with this bug.

**Comment by MTVirux** [comment]
@Aussiemon Thank you for the report, a fix is already in the works 😄 
The toggle setting is not supposed to be saved. The only parameters saved are position, size collapsed status of the windows.
