### ISSUE TITLE
Crash (log included)

### ISSUE THREAD

**Issue by Doug4130** [megai2/d912pxy#239]
[log.txt](https://github.com/megai2/d912pxy/files/4332834/log.txt)

keep crashing after a few minutes, only happens on v2 and higher

**Comment by megai2** [comment]
new version is up
if still crashing start with https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by megai2** [comment]
other reports that this bug is fixed in 2.1.1 release, so i closing issue for now
