### ISSUE TITLE
Some small shader bugs I noticed

### ISSUE THREAD

**Issue by tr7zw** [megai2/d912pxy#24]
First of all, awesome job. Wouldn't have thought that dx9 holds the game back this much.
So some small shader bugs I noticed:
The skybox may not render correctly (in this case in wvw): ![Wvw sky](http://tr7zw.de/u/1548452084.png)
The hero panel player model does not render correctly(while the shaders do work in the word):
Lightning Blessed Zypherite Gloves: ![gloves](http://tr7zw.de/u/1548452615.png) The color distortion effect flickers rapidly

Btw what about a discord? I'm currently trying to get gw2 to output sbs(side by side) vr using 3dmigoto, but getting stuck that dx9 isn't supported by them. Alternatively getting this project to work with vorpX would be even more awesome.

**Comment by megai2** [comment]
Did you have a try on troubleshooting with _ps version as described in README.md ?

**Comment by tr7zw** [comment]
Just did the troubleshooting and booth persist.
Some more information: 
The glove visual bug can also be seen in the wardrobe preview, so unlocking the skin isn't required to see this. Just preview [Lightning-Blessed Zephyrite Gloves]
The broken skybox in wvw seems to be the lower half of the untextured skybox. It can be seen on the Alphine boarders in the Citadel on the left. Using the normal dx9 renderer this lower half of the skybox seems to be hidden behind fog/viewdistance.

**Comment by megai2** [comment]
Shoul be fixed in v0.9.5.7

**Comment by megai2** [comment]
skybox color fixed and gloves too

**Comment by tr7zw** [comment]
Sorry took me some time to test again, can confirm booth are fixed, gj 👍
