### ISSUE TITLE
Silverwastes

### ISSUE THREAD

**Issue by bdikmen1** [megai2/d912pxy#240]
Fps drops to 3-5 at Silverwastes when my average fps is around 60-70. It start happening after the 17th March 2020 update and I confirmed that I'm not the only one experiencing this. I also heard that new mission maps also effected.

1. Windows 10 
2. Hardware info: i7 - 8700k - 1080ti - 16GB 3600Mhz
3. GPU Driver version - 442.59
4. Latest

**Comment by luispardal** [comment]
Confirmed. Some maps works fine, but in others the FPS frops to 6 (Silverwastes) or even 1 (Verdant Brink, for example).

Started with this new game patch (march 17).

**Comment by gotyaoi** [comment]
Do you have arc installed? I was getting this in tangled depths with arc as d3d9.dll and d912pxy as d3d9_chainload.dll, but I removed arc and put d912pxy as d3d9.dll, and it fixed the problem.

**Comment by bdikmen1** [comment]
Yes, I was also using arc. I will try removing it and inform you guys in the morning.

**Comment by MegaBlues** [comment]
> Do you have arc installed? I was getting this in tangled depths with arc as d3d9.dll and d912pxy as d3d9_chainload.dll, but I removed arc and put d912pxy as d3d9.dll, and it fixed the problem.

Can you clarify what you mean by this?

**Comment by gotyaoi** [comment]
When I was getting the bad framerates, my bin64 folder had the arcdps mod installed as d3d9.dll and the d912pxy mod installed as d3d9_chainload.dll. I deleted the d3d9.dll file that was the arc mod, uninstalled the d912pxy mod using it's install script, then reinstalled it as d3d9.dll instead of d3d9_chainload.dll.

**Comment by wolfwahl** [comment]
Can confirm this 2.1.1,  win10, amd RX480, latest 2 drivers. Some Maps stuck to 1-2 FPM (right, per Minutes), Graphicscard goes idle, GW2 Client unresponsive.

**Comment by robmart** [comment]
Had the same issue. Unistalling ARCDPS seems to work. The MAR17 update of ARCDPS did not change the result.

**Comment by IzaacJ** [comment]
Same issue. Tried clean (no arc or dx912pxy) and running fine with ~30 fps. With just arc it runs fine. With both or with just dx912pxy it drops to 1 fps.
Tested in Elon Riverlands.

**Comment by burakDayRoqos** [comment]
When you install it as d912pxy, there are no problems running along with arcdps although fps is a bit lower compared to chainload.

**Comment by megai2** [comment]
You always should start with logs and general outline of what installed or only d912pxy install.

Luckly we have game update and arcdps being broken: a common and wide spread problem.

Last arcdps update (mar.18.2020) should fix observed problems.

**Comment by burakDayRoqos** [comment]
It's fixed with 18.03.2020 arcdps version confirmed.

**Comment by megai2** [comment]
ppl on discord say same

if you still experience this problems: update arcdps
