### ISSUE TITLE
Since Update WvW EBG Map 6fps

### ISSUE THREAD

**Issue by Xyaren** [megai2/d912pxy#241]
First of all I do not have time to create a log right now.

**Describe the bug**
Very low FPS (6) on Ethernet Battlegrounds in World versus World.
**To Reproduce**
Steps to reproduce the behavior.

1. Run game
2. Join WvW EBG.
3. Witness low FPS and max GPU Usage.

**Expected behavior**
Normal FPS on EBG.
**Standard information**

1. Windows 10 update ver: 1903
2. Hardware info: CPU, RAM, GPU: i4790k @4.5Ghz, 16GB RAM, Nvidia GTX 980 4G
3. GPU Driver version 442.74
4. Version of d912pxy used (Latest 2.1.1 Fresh install)

**Additional context**

On all other WvW maps FPS are fine 60+.

**Comment by Xyaren** [comment]
@everyone please provide logs if you can.

**Comment by Xyaren** [comment]
A friend of mine just told me this also happens in some raid wings.

**Comment by megai2** [comment]
what about ArcDPS?

**Comment by Xyaren** [comment]
Can't get on EBG right now due to queue. I can already say, that using only ArcDPS there is no problem.

**Comment by megai2** [comment]
> 
> 
> Can't get on EBG right now due to queue. I can already say, that using only ArcDPS there is no problem.

If you using it - update it

**Comment by Xyaren** [comment]
Uh, just updated yesterday but there is already another patch, that seems to fix the issue ! Ty so much for your great work !
