### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by andrei9669** [megai2/d912pxy#242]
**Describe the bug**
when pressing install.exe I get System Error

`The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem`

I have Added guild wars directory to windows defender exclusions list

**To Reproduce**
Start installer.exe

**Expected behavior**
I expected installer to install?

**Screenshots**
![image](https://user-images.githubusercontent.com/31692094/77226200-30aec480-6b7f-11ea-8c70-61b8dea44234.png)
![image](https://user-images.githubusercontent.com/31692094/77226210-3c9a8680-6b7f-11ea-8bf9-6834056f815f.png)
![image](https://user-images.githubusercontent.com/31692094/77226229-5b991880-6b7f-11ea-8332-eefedfb36c15.png)

**Standard information**

1. Windows 10 | version 1909 | OS build 18363.720
2. Hardware info: 
CPU: Intel(R) Core(TIM) i5-7600 @ 3.50GHz,
RAM: 16.0 GB,
GPU: NVIDIA GeForce GTX 1660 Ti
3. GPU Driver version: 26.21.14.4274
4. Version of d912pxy used V2.1.1 and V2.1 hotfix #1
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist:
NONE

**Comment by Squall-Leonhart** [comment]
Read the system requirements.

**Comment by megai2** [comment]
If you see something related to missing DLL file, also try to install MSVC redistributable

(link to vc redist https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by andrei9669** [comment]
Thanks, that link helped
