### ISSUE TITLE
Issue in the Whisper of Jormag strike mission

### ISSUE THREAD

**Issue by Frazas** [megai2/d912pxy#243]
I am having graphical glitches in the Whisper of Jormag Strike Mission. Objects and textures don't really show unless I am in first-person view and even there many textures and objects just don't show. This just happens in this specific strike mission. Never had issues in any other map or instance, either WvW, open-world maps, fractals, etc.

I am using the latest d912pxy version, in a GTX1070 with Nvidia 442.74 drivers. I've cleared cache,, did the "enableprofiling" option on/off and the graphical glitches remain. I just wasn't able to find the log file to send...

Screenshots below to help out.

Screenshot with d912pxy:
![d912pxy](https://user-images.githubusercontent.com/62509955/77252750-eba59380-6c4d-11ea-9ea1-8a1a43885dc6.jpg)

Screenshot without d912pxy:
![vanila](https://user-images.githubusercontent.com/62509955/77252752-f06a4780-6c4d-11ea-9d3b-49d6baeb0896.jpg)

Graphical options
![options](https://user-images.githubusercontent.com/62509955/77252751-efd1b100-6c4d-11ea-9a39-a0d5360bba8e.jpg)

**Comment by megai2** [comment]
remove d912pxy/config.ini or change value "occlusion" under [compat] section to 2 in it

**Comment by Frazas** [comment]
It seems to have fixed it! Thanks!

PS: might I know what that enabled/disabled?

**Comment by megai2** [comment]
> 
> 
> It seems to have fixed it! Thanks!
> 
> PS: might I know what that enabled/disabled?

This options changes how hardware occlusion tests are performed. 
Due fact of their slow nature, they was disabled before v2.0 but now they are enabled by default
(you did not do clean install after update or using some custom config already)
