### ISSUE TITLE
CPU 100% all time

### ISSUE THREAD

**Issue by lionelchris** [megai2/d912pxy#244]
I5 6° gen
Rx 5700 XT Pulse Saphire

When i put game in ultra 1080p the CPU (I5 6° gen) is on used 100% all time but GPU is 14% usage only, and after 2 minutes game crash.
If possible optimization CPU consume?
thx

**Comment by megai2** [comment]
Try troubleshooting https://github.com/megai2/d912pxy/wiki/Reporting-crashes

**Comment by Squall-Leonhart** [comment]
See https://github.com/megai2/d912pxy/issues/236

Occlusion queries are

**Comment by megai2** [comment]
i'm closing issue as it was not answered in long time
