### ISSUE TITLE
Square around champions moon 

### ISSUE THREAD

**Issue by xtrverz** [megai2/d912pxy#245]
i7-6700k GTX 1080

A square appears around the Champion's Moon Gizmo when using dx12
https://imgur.com/a/l9HzOzc (with dx12)
https://imgur.com/a/FCd9zi9 (without)

**Comment by megai2** [comment]
added shader profile for it, but i can only test in preview

**Comment by megai2** [comment]
![изображение](https://user-images.githubusercontent.com/1693251/85569328-1e8b6900-b63b-11ea-9630-f951fce32b77.png)

**Comment by xtrverz** [comment]
If it works in preview that will probably fix the square with the actual item, any idea when you will release this fix?

**Comment by megai2** [comment]
> 
> 
> If it works in preview that will probably fix the square with the actual item, any idea when you will release this fix?

You can download it already from https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

Official release will be available when all things are at least tested by me

**Comment by xtrverz** [comment]
The square still appears when using rampage https://imgur.com/a/vtSwdMy

**Comment by megai2** [comment]
Try follow this one guide https://github.com/megai2/d912pxy/wiki/Reporting-visual-errors (steps 1-5)
Attach resulting file here if bug is fixed

**Comment by megai2** [comment]
fixed in v2.3
