### ISSUE TITLE
RX580 GPU low performance on this new version

### ISSUE THREAD

**Issue by ParanoidHitman** [megai2/d912pxy#246]
Hello There my GPU Cant seem to use the clock at max speed, it always stays in minimum i already tried OC and everything, but the GPU clock only uses % more than 50% if i put supersample ON and that boosts FPS,but it cost alot, my GPU clock is 1410, and i cant speed up since this new version of the d912pxy.
Seem to have poor performance, no matter the drive i install a newer or older version, and the problem seems to be with the software, please fix and optimize it!
So many thanks for you huge job! 🗡 

1. Windows 10 PRO Ver.1909 
OS Build:18363.720
2. Hardware info: CPU AMD FX 8320 , RAM16Gb Gskill 1600Mhz, GPU RX580 4GDDR5 Sapphire Nitro+
3. GPU Driver version AMD adrenelin 2020 20.3.1
4. Version of d912pxy used 2.1.1
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist

Hello There my GPU Cant seem to use the clock at max speed, it always stays in minimum i alrerady tried OC and everything, but the GPU clock only uses % more than 50% if i put supersample ON and that boosts FPS,but it cost alot, my GPU clock is 1410, and i cant speed up since this new version of the d912pxy.

**Comment by Squall-Leonhart** [comment]
See https://github.com/megai2/d912pxy/issues/236

**Comment by megai2** [comment]
That is driver/hw thingy, it will downclock to idle clocks if there is not enough load sended to GPU.

@Squall-Leonhart mentioned that there is some drops induced by enabled occlusion query processing. 
Anet introduced new strike missions and they heavily use them, so there is nothing i can do to avoid that performance droppings and keep glitches at bay (yet). 

You can try to set occlusion to 1 in config, to reduce pressure they put on CPU, maybe this will be enough to keep your GPU at proper clocks

Also you can workaround this problem by running any other programms that use GPU or try to configure drivers properly so it does not do this thing.

**Comment by megai2** [comment]
see main issue & status on it #250
