### ISSUE TITLE
About Blade and soul after install D912pxy

### ISSUE THREAD

**Issue by jacklee09** [megai2/d912pxy#248]
helllo. when i install D912pxy into 64bit folder, the game wont start. 
when i Start game after few second back to Start game page. 
my system: core i7-3370k
16ram
2060 video card
windows 10 home

please help.

**Comment by megai2** [comment]
hi. try updating msvc https://github.com/megai2/d912pxy/wiki/Reporting-crashes
if this not helps try following this page https://github.com/megai2/d912pxy/wiki/Reporting-crashes
