### ISSUE TITLE
d912pxy constantly crashing but only in the newest version

### ISSUE THREAD

**Issue by Peter-Petrov-21407097** [megai2/d912pxy#249]
Hello there.

Before anything else, I want to say thank you for the magnificient work you have been done for the gw2 community.

Now, on to my problem:

The game is, with your new version of d912, constanly crashing in a matter of 1, tops 2 minutes.

-> Already tried to change the delays from 2 to 10 or even 160, no diference.

-> Game works easily without this plugin, without any crashes.

-> The game folder have permission to write, read or modified files there.

-> "CPU with AVX support (since v2.0) " - this is the only thing I am not sure about, but I have put my system information in the printscreens + the log here soo that you can see what is going wrong here.

The exception is:  406D1388

https://easyupload.io/uhzo35

https://easyupload.io/dgctuq

https://easyupload.io/juai3t

https://easyupload.io/2dxr8j

https://easyupload.io/t4tk87

I dont want to waste a lot of your time, soo if you feel you need any extra information, feel free to whisper me via github for anything or any more information that you may need.

Thank you in advance and I wish you health, in this troubled times...

**Comment by megai2** [comment]
Hi, there is no critical errors in log. 
If it was working before on older version, is it working with it still?

**Comment by Peter-Petrov-21407097** [comment]
UAU! That was quick.

Answering your question, I played 30 minutes now with your "d912pxy_v2.1h1_r514" version, in game.

No crashes, no bugs, no nothing. Its the most recent one that somehow gave me that problem...

> no critical errors in log.

Doesnt the log show a 406D1388 exception? Cause I am pretty sure the client crashed with that. I only got the log of one of those situations, but it happened periodically, like once every 1, tops 2 minutes of ingame gameplay...

Again, apreciate your work on this :)

**Comment by megai2** [comment]
> 
> 
> UAU! That was quick.
> 
> Answering your question, I played 30 minutes now with your "d912pxy_v2.1h1_r514" version, in game.
> 
> No crashes, no bugs, no nothing. Its the most recent one that somehow gave me that problem...
> 
> > no critical errors in log.
> 
> Doesnt the log show a 406D1388 exception? Cause I am pretty sure the client crashed with that. I only got the log of one of those situations, but it happened periodically, like once every 1, tops 2 minutes of ingame gameplay...
> 
> Again, apreciate your work on this :)

It is exception yes, but not fatal.
Next part of log shows "normal" game exit.

**Comment by Peter-Petrov-21407097** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/4476767/log.txt)

Ok, take a look there. Its now with the current version of d912pxy. That was the last log with a crush on the end, just like 2 or 3 minutes ago.

Is this enough? Can you see any exception, error there...?

**Comment by megai2** [comment]
> 
> 
> [log.txt](https://github.com/megai2/d912pxy/files/4476767/log.txt)
> 
> Ok, take a look there. Its now with the current version of d912pxy. That was the last log with a crush on the end, just like 2 or 3 minutes ago.
> 
> Is this enough? Can you see any exception, error there...? If more information is needed, by all means, feel free to ask for it and I will provide, to the best of my knowledge.

This log shows gpu crash and i can't trace it properly, cuz tracing gpu side crashes is too slow to include in release. I'm searching code for them, but not found anything problematic yet.

Also i see newer win10 update version(and other crash report with same win10 update) & old drivers. Try updating drivers for now, maybe that is a problem.

**Comment by Peter-Petrov-21407097** [comment]
I am testing for 1 hour now, no crashes with the newest windows update.

If I dont have anything else to say in, lets see, maybe 48 hours, you can probably close this :)

**Comment by Peter-Petrov-21407097** [comment]
[information crash.txt](https://github.com/megai2/d912pxy/files/4483948/information.crash.txt)
[log.txt](https://github.com/megai2/d912pxy/files/4483949/log.txt)
[log second.txt](https://github.com/megai2/d912pxy/files/4483950/log.second.txt)

Played for around 3 hours, got 7 crashes.

I posted there 2 of the logs and also the text that comes in the gw2 client, soo that you can check it out.

Again, apreciate your patient with this and if you need any more information, you just have to ask. Wish you good health in this times :)

**Comment by megai2** [comment]
> 
> 
> [information crash.txt](https://github.com/megai2/d912pxy/files/4483948/information.crash.txt)
> [log.txt](https://github.com/megai2/d912pxy/files/4483949/log.txt)
> [log second.txt](https://github.com/megai2/d912pxy/files/4483950/log.second.txt)
> 
> Played for around 3 hours, got 7 crashes.
> 
> I posted there 2 of the logs and also the text that comes in the gw2 client, soo that you can check it out.
> 
> Again, apreciate your patient with this and if you need any more information, you just have to ask. Wish you good health in this times :)

Both are same: GPU crash.
Did you updated drivers? Or version you using is latest for your GPU?

**Comment by Peter-Petrov-21407097** [comment]
![print1](https://user-images.githubusercontent.com/22677468/79634664-da27ac80-8163-11ea-8c44-c4d0b093b776.jpg)
![print3](https://user-images.githubusercontent.com/22677468/79634666-db58d980-8163-11ea-83af-95474bf50cab.jpg)
![print2](https://user-images.githubusercontent.com/22677468/79634668-db58d980-8163-11ea-8ac9-38b78493f77f.jpg)

They indeed look to be the current drivers, as you can see in the first printcreen there, I am using the most updated drivers.

I added here two more printscreens showing my settings for the specific guild wars 2 client. I know it shows in Portuguese, soo if you happen to need a translation in some of those words, feel free to ask me. 

Anyway, I am now trying diferent combinations of settings on that screen and testing to see what happens in game with it. Give me 12, 16 hours and let me test online to see if the client crashes or not and why.

**Comment by megai2** [comment]
Also: Check that game does not use more VRAM/RAM that you have, maybe it is some kind of "silent" out of memory driver crash.

**Comment by Peter-Petrov-21407097** [comment]
And you can close this.

Looks like the problem was on my booster software. for some reason, after I launch gw2, the temperature would raise and the booster software would automatically turn the "Nivdia high performance process" off and switch to the "integrated graphic card".

Thank you for the time on this and I wish you good health, in this troubled times :)
