### ISSUE TITLE
Wine and vkd3d on Linux

### ISSUE THREAD

**Issue by Espionage724** [megai2/d912pxy#25]
Apparently there was someone who reported it worked on a Reddit post somewhere.

Here's the last lines of text I get when trying to run it, but GW2 just closes right after logging in with the launcher (game window never appears):

```
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x14cfaa0.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x14cfaa0.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16adf20.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16adf20.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0xbc92bc0.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0xbc92bc0.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16ab740.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16ab740.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16a9130.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16a9130.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16a7b70.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0x16a7b70.
0048:fixme:nvapi:unimplemented_stub function 0xbe7692ec is unimplemented!
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0xbac7320.
0048:fixme:d3d12:D3D12CreateDevice Ignoring adapter 0xbac7320.
```

I dropped the contents of the zip as-is (the bin64 and d912pxy folders) into the root GW2 folder and set a DLL override for d3d9.dll (native, then builtin). I have the libvkd3d (both x86_64 and i686) packages installed.

- Fedora Workstation 29
- AMD Radeon RX 580 (Mesa 18.2.8, Kernel 4.2.0)
- Wine 4.0 (Staging)
- vulkaninfo: https://pastebin.com/Y5vhWKev

**Comment by megai2** [comment]
Please provide debug logs and d912pxy_crash.txt if that is available. 
Use Release_d version to do this.

Then, there is chance i can get some clues about what happens.

**Comment by Espionage724** [comment]
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2799024/d912pxy_crash.txt)
[20190126-08314700.zip](https://github.com/megai2/d912pxy/files/2799025/20190126-08314700.zip) (20190126-08314700.p7d)

**Comment by krystof-riha** [comment]
* Fedora 29 KDE Spin
* NVidia GTX 1060 6GB (415.27 drivers)
* Wine 4.0 TKG through Lutris

I did the same thing, extracted the zip and added the dll override. For me the game runs but I can't see any visible change. Sadly it doesn't seem to work with DXVK at all, or at least it doesn't show the DXVK HUD.

Is there a way to see if the dll is even loaded (some small hud like DXVK has maybe)?

**Comment by Espionage724** [comment]
If I understand DXVK correctly, it only supports up to DX11. If you look in the GW2 root folder, there should be a P7logs folder; if it has a file in it, I believe that means d912pxy is being or has been used.

**Comment by krystof-riha** [comment]
> If I understand DXVK correctly, it only supports up to DX11

Ohh, sorry my bad.

Thanks for the tip with the logs folder though :)

**Comment by krystof-riha** [comment]
So I tried some more and while the game doesn't crash, there isn't any P7logs folder, and no noticeable improvement. Following the same steps (copy dll, add it into libraries in winecfg as native, then built) I can make arcdps work so I don't think I am trying to import the dll wrong.

Maybe this just doesn't work with vkd3d though

**Comment by megai2** [comment]
> 
> 
> So I tried some more and while the game doesn't crash, there isn't any P7logs folder, and no noticeable improvement. Following the same steps (copy dll, add it into libraries in winecfg as native, then built) I can make arcdps work so I don't think I am trying to import the dll wrong.
> 
> Maybe this just doesn't work with vkd3d though

If it loads correctly you should see signs of it in console or in P7logs folder.

And do not forget, wine should be compiled with vkd3d for DX12 support.

**Comment by megai2** [comment]
> 
> 
> There's a comment here that has a pre-compiled **D3D12HelloWindow** executable that can be useful for testing if vkd3d works at all: [doitsujin/dxvk#766 (comment)](https://github.com/doitsujin/dxvk/issues/766#issuecomment-439689952)
> 
> That app work seemingly works (displays an empty, blue window for me), but I assume it would just crash if vkd3d wasn't usable.
> 
> As for d912pxy, does it require a 64-bit DX9 executable for testing? I tried a quick install of an old version of WoW (32-bit DX9) and it said something about an incompatible architecture for the d3d9.dll. If it does require a 64-bit executable, does anyone have any ideas on any other executable or game to test with?

64-bit d3d9.dll 

And in link you mentioned, there is a talkings about vkd3d not supporting FL12.1, only the wip version.

**Comment by yaomtc** [comment]
I added the files to the folder as in the instructions and ran it with Wine 4.0 (vkd3d installed) and didn't have any issues, aside from running at about half the framerate I usually get (with Wine's D3D9 + pba + esync). But as d912pxy and vkd3d improve, this gap should eventually narrow... though with the additional layer of translation, I'm interested to see if that gap will still be able to be reversed for Wine users of d912pxy, and how it'll compare to VK9. Anyway, great work so far.

**Comment by megai2** [comment]
> 
> 
> I added the files to the folder as in the instructions and ran it with Wine 4.0 (vkd3d installed) and didn't have any issues, aside from running at about half the framerate I usually get (with Wine's D3D9 + pba + esync). But as d912pxy and vkd3d improve, this gap should eventually narrow... though with the additional layer of translation, I'm interested to see if that gap will still be able to be reversed for Wine users of d912pxy, and how it'll compare to VK9. Anyway, great work so far.
> 
> EDIT: Looking at the output, I see one mention of OpenGL, and none of VK. Hmm.
> [gw2.txt](https://github.com/megai2/d912pxy/files/2799817/gw2.txt)

Log shows there is no d912pxy usage.

you need to add d3d9.dll override "native then built-in"(but i'm not 100% shure) for it to load up

**Comment by megai2** [comment]
changed interface version, so you can give it a try.

**Comment by megai2** [comment]
> 
> 
> > changed interface version, so you can give it a try.
> 
> Thanks, but if you wouldn't mind and if it isn't too much trouble, is there any chance you could compile a release with this change?

already changed appveyor to compile it

**Comment by krystof-riha** [comment]
Should be here:
https://ci.appveyor.com/project/megai2/d912pxy/build/job/4qe77e8qlul96oqw/artifacts

**Comment by MontKane** [comment]
Running with [krystof-riha's suggested appveyor build (above)](https://ci.appveyor.com/project/megai2/d912pxy/build/job/4qe77e8qlul96oqw/artifacts), I manage to get a p7logs folder but the launcher does not appear. If I wait long enough, I will get a runtime error. 

![screenshot from 2019-01-28 08-36-46](https://user-images.githubusercontent.com/37989126/51843100-f4176e00-22d7-11e9-9dca-ff0d09aaf5a8.png)

(after waiting 3ish minutes)

![screenshot from 2019-01-28 08-38-49](https://user-images.githubusercontent.com/37989126/51843245-29bc5700-22d8-11e9-9397-86e9478469e3.png)

**Comment by Espionage724** [comment]
Tried it out; GW2 still doesn't start, but I get new errors now.

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2803492/d912pxy_crash.txt)
[20190128-09520100.zip](https://github.com/megai2/d912pxy/files/2803496/20190128-09520100.zip)
Terminal output: https://pastebin.com/EcLS0XsQ

**Comment by megai2** [comment]
Looks like vkd3d not support features of dx12 that i use.

**Comment by Espionage724** [comment]
After using a different repo for Wine, I get a different error log (still crashing after the launcher and before the game starts though):

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2805575/d912pxy_crash.txt)
[20190128-19575200.zip](https://github.com/megai2/d912pxy/files/2805576/20190128-19575200.zip)

**Comment by popsUlfr** [comment]
I tested this also getting something different in d912pxy_crash.txt

* Wine Staging 4.0
* vkd3d [3b1af3c85d84341405af13e6c94aa60cf596c561](https://source.winehq.org/git/vkd3d.git/commit/3b1af3c85d84341405af13e6c94aa60cf596c561)
* Nvidia GTX 980Ti 415.22.05
* Kernel 4.20.5

I tested to make sure dx12 works with this demo : https://www.youtube.com/watch?v=_YepxAtYvfg

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2810387/d912pxy_crash.txt)
[20190130-01425600.zip](https://github.com/megai2/d912pxy/files/2810388/20190130-01425600.zip)
[wine.log](https://github.com/megai2/d912pxy/files/2810389/wine.log)

**Comment by K0bin** [comment]
VkD3D is far from feature complete.

**Comment by megai2** [comment]
Yes, it can't handle shader register space for now, so wait for me iterating on shader recompilation optimization, or try to troubleshoot is on your own. It's open source after all.

**Comment by popsUlfr** [comment]
> Yes, it can't handle shader register space for now, so wait for me iterating on shader recompilation optimisation, or try to troubleshoot is on your own. It's open source after all.

Alright so proper shader register space handling would bring this closer to a workable state. I think since this project uses more extensive dx12, it should prove very useful to improve and advance vkd3d.
Getting some feedback on what would need to be prioritised in the implementation to get it up and running is also helpful.

Thank you very much for releasing and working on this project, it's really interesting and provides another option for dx9 ;)

**Comment by megai2** [comment]
> 
> 
> > Yes, it can't handle shader register space for now, so wait for me iterating on shader recompilation optimisation, or try to troubleshoot is on your own. It's open source after all.
> 
> Alright so proper shader register space handling would bring this closer to a workable state. I think since this project uses more extensive dx12, it should prove very useful to improve and advance vkd3d.
> Getting some feedback on what would need to be prioritised in the implementation to get it up and running is also helpful.
> 
> Thank you very much for releasing and working on this project, it's really interesting and provides another option for dx9 ;)

Yes, i think that 
`vk_binding_from_d3d12_descriptor_range: Unhandled register space 1`
and
`6 | d912pxy_global_objects::DXDev->CreateRootSignature(0, signature->GetBufferPointer(), signature->GetBufferSize(), __uuidof(**(&mRootSignature)), IID_PPV_ARGS_Helper(&mRootSignature)) | hr = 80004001 `
are related, what prevents Roots signature from creation.

**Comment by thunder1410** [comment]
It works for me.
I used the lutris installer of gw2 then I changed the wine version to 4.0 tkg. Then I installed this translation layer.
I think my fps with this went from 20 to 25, so it is an improvement.
The launcher is still extremely laggy.
gw2 is installed on an ntfs drive.

Ubuntu 18.04
RX 580
I5-4460
steam system information: https://gist.github.com/thunder1410/76897c9bd211c74b30968baa4037ce96

**Comment by MontKane** [comment]
> 
> 
> It works for me.
> I used the lutris installer of gw2 then I changed the wine version to 4.0 tkg. Then I installed this translation layer.
> I think my fps with this went from 20 to 25, so it is an improvement.
> The launcher is still extremely laggy.
> gw2 is installed on an ntfs drive.
> 
> Ubuntu 18.04
> RX 580
> I5-4460
> steam system information: https://gist.github.com/thunder1410/76897c9bd211c74b30968baa4037ce96

Can you please confirm that there is a p7logs folder in the game's root directory? I thought the dll was working as well, but turns out it was not (lack of p7logs folder).

**Comment by Zeioth** [comment]
It seems it's not working correctly yet on linux, but could someone please confirm the process to make wine use d912pxy instead of dx9?

**Comment by popsUlfr** [comment]
@Zeioth 
> It seems it's not working correctly yet on linux, but could someone please confirm the process to make wine use d912pxy instead of dx9? Just for testing purpose.

Sure : 

1. Download the latest release with `_d` suffix from https://github.com/megai2/d912pxy/releases
2. Merge the archive into the game folder, so as to have the `d912pxy` folder right next to the executable `Gw2-64.exe` and the `d3d9.dll` next to the existing dlls in `bin64`
3. Add `d3d9` as dll override in `winecfg`'s  **Libraries** tab, set load order to `native` or `native, builtin`
4. Launch the game, a `p7logs` folder should appear next to the executable, wine should be spouting d3d12 messages and if you have nvidia you can activate the visual indicator to see it using Vulkan instead of OpenGL

**Comment by Zeioth** [comment]
I followed the process [1](https://i.imgur.com/xyivr0u.png), [2](https://i.imgur.com/IlmDxZc.png), [3](https://i.imgur.com/jZ9VCAB.png) 

But the game's updater crashes if set the override to native. It seem like wine is unable to find the d3d9.dll for some reason - [Game's log](https://pastebin.com/LbtEwnYx).

**Comment by popsUlfr** [comment]
@Zeioth yeah sorry it has to be `native, builtin`

**Comment by megai2** [comment]
you need wine to be compiled with vkd3d
and if you got crash related to coherent dll, i think you should load Release_d version, not Debug one.
+ some msvc redists should be installed

**Comment by Zeioth** [comment]
@megai2 to be even more specific:

**Step 1)** You need to install the next packages in your operative system: 

* vkd3d lib32-vkd3d

**Step 2)** Wine build doesn't come with VKD3D enabled by default yet. To enable it, you must compile wine by downloading the [TK repo](https://github.com/Tk-Glitch/PKGBUILDS). Then:

* Open the folder '/wine-tkg-git' and edit the file 'customization.cfg'.
* Set the variable _use_vkd3d="true"
* Now open a terminal in '/wine-tkg-git' and run 'makepkg -sri' to compile and install wine

(This instructions to build wine are for arch linux based distros)

**Step 3)**  Now you can install d912pxy and run the game

* Download the latest release with _d suffix from https://github.com/megai2/d912pxy/releases
* Merge the archive into the game folder, so as to have the d912pxy folder right next to the executable Gw2-64.exe and the d3d9.dll next to the existing dlls in bin64
* Add d3d9 as dll override in winecfg's Libraries tab, set load order to native or native, builtin OR set WINEDLLOVERRIDES="d3d9=n" as environment variable
    Add d3d9 as dll override in winecfg's Libraries tab, set load order to native, builtin OR set WINEDLLOVERRIDES="d3d9=n,b" as environment variable
* Launch the game, a p7logs folder should appear next to the executable, wine should be spouting d3d12 messages and if you have nvidia you can activate the visual indicator to see it using Vulkan instead of OpenGL

**Comment by popsUlfr** [comment]
Yeah I was assuming a working vkd3d and wine installation. If you're compiling wine yourself it will pick up the vkd3d libraries if already installed (or force with `--with-vkd3d` during the wine configuration).

Before trying d912pxy make sure dx12 is working as it should. You can use this demo https://www.youtube.com/watch?v=_YepxAtYvfg launch it with `-D3D12`, if everything is installed as it should the demo should play without any problems and you should see d3d12 messages logged by wine.

**Comment by popsUlfr** [comment]
@Zeioth Right, we are at the same point ;)

The next step is to implement shader register space handling in vkd3d to get further.

**Comment by megai2** [comment]
Made some progress today, but still not working.

Maybe more *nix-familiar folks find a way to fix this problems.

1. d3dcompiler_xx.dll won't compile shaders, possible force to use original dll? 

I used cached .pck shaders to bypass this.

2. Crashing at libs/vkd3d-shader/spirv.c:2423 . Looks like a soft limit on shader registers.

**Comment by Guy1524** [comment]
@megai2 Yeah, wine's d3dcompiler is incomplete, it's recommended that you use a native version.

**Comment by Zeioth** [comment]
Wine's d3dcompiler is [pretty mature](https://www.youtube.com/watch?v=R-sHvo4rCas&feature=youtu.be), but yeah, many instructions may not be implemented yet:

**Comment by K0bin** [comment]
That video you linked doesn't touch d3dcompiler. It uses precompiled DXBC.

**Comment by Zeioth** [comment]
@K0bin IDK if this is relevant, but it looks like it.
https://github.com/doitsujin/dxvk/wiki/DXGI

**Comment by megai2** [comment]
Now you can use https://github.com/Joshua-Ashton/d9vk for d3d9 to vulkan
