### ISSUE TITLE
[gw2] workaround gpu occlusion query usage performance loss

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#250]
while this issue is not closed and you have big fps loss: set occlusion value in config to 1 or 0

new patches added more gpu occlusion query usage

current workaround on keeping them false or true all time is not viable any more
so they are enabled properly, reducing performance in the end (gpu-cpu sync stalls)

another solution is to use buffered data with frame delay

step 1) query is called, add it to replay
step 2) query is finished and asked for result
step 3) if query was called before, report result immediatly, otherwise use default 0/1
step 4) save result of actual query somewhere to read it on next frame issue

but before it, api stream should be investigated on amount of query spam and its structure regarding to frame-frame relation

**Comment by megai2** [comment]
added small workaround to reduce amount of gpu sync calls

**Comment by yechingu** [comment]
What is the utility you meant by "frame delay"? I cannot search it at all. Is it actual name of it or name for functionality of the utility?

**Comment by megai2** [comment]
that is not utility, that was an idea to use different data and it seems not working out

**Comment by megai2** [comment]
small workaround to reduce gpu sync invokations is made, other ways are not sufficient/buggy, so that is

if you want to get more perf and you are fine with some broken visuals - set compat occlusion value in config to 1 or 0
