### ISSUE TITLE
Animation bug with new adventure raptor skin

### ISSUE THREAD

**Issue by Makishii** [megai2/d912pxy#253]
Hi´,

there is some missing or laggy animation when i use the new AdventureBox Raptor Skin.
I can post a Video of what i mean exactly if you want.

Greetings,
Max

**Comment by megai2** [comment]
Hi. Does it look different without d912pxy?

**Comment by Makishii** [comment]
sry for responding so late. I think its fixed now. There was a patch and now the animation looks normal
