### ISSUE TITLE
d912pxy doesn't want to work with mount radial

### ISSUE THREAD

**Issue by exhale451** [megai2/d912pxy#255]
Hi,  I have a problem with d912pxy and mount radial to work together.

gw2raidal =>/bin64/d3d9.dll
d912pxy =>/bin64/d912pxy.dll

This should be the way to be able to work, but if i rename the d912pxy's file to d912pxy.dll, d912pxy won't work, but mount radial will. Also if i put any one of these separately in the bin64 folder they won't work, only if it's next to Gw2-64.exe.

**Comment by exhale451** [comment]
Achieved some progress. If i put the d912pxy.dll in /bin64 folder and gw2radial's d3d9.dll next to Gw2-64.exe it works until i switch characters, then dx12 stops working.  I attached the two log files, hope that helps.
[log.1.txt](https://github.com/megai2/d912pxy/files/4616421/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/4616422/log.txt)

**Comment by megai2** [comment]
gw2radial works until character switch or d912pxy? if you decided second one due to proper character portraits after character switch - all working fine, character portraits bugged only on startup.

**Comment by exhale451** [comment]
That is exactly why i thought it wasn't working, because of the portraits. This is resolved then, thank you.
