### ISSUE TITLE
BNS crashes with d912pxy installed

### ISSUE THREAD

**Issue by Braiio** [megai2/d912pxy#256]
**Describe the bug**
1. Through BNS buddy the splash screen for BNS launches for around 1-2 minutes then just crashes.
2. Through Client Launcher game crashes and gives a generic crash report

**To Reproduce**
1. Just run try running the game normally or through BNS buddy

**Expected behavior**
1. Splash screen is vanished and the process killed

**Screenshots**
1. Through NCSOFT launcher:
https://i.imgur.com/pzLKO8s.jpg

**Standard information**

1. Windows 10 update ver
2. Hardware info: CPU: INTEL CORE I5-6500 3.2GHz, 16 GB, AMD R9 390
3. GPU Driver version: 20.4.2
4. Version of d912pxy used: 2.1.1
5. Log file from: d912pxy/log.txt

log file:  [log.txt](https://github.com/megai2/d912pxy/files/4663573/log.txt)

**Comment by Braiio** [comment]
made a mistake by posting it here

**Comment by megai2** [comment]
i replied in that old report "thread", but again: Razer tools installed can be a problem

**Comment by Braiio** [comment]
I have tried turning off any Razer tools (stopping services and ending processes) I had running and it still happens (is uninstalling necessary - if so, ill try?)
anyway, here's another log i made after:
[log.txt](https://github.com/megai2/d912pxy/files/4673087/log.txt)

**Comment by megai2** [comment]
> 
> 
> I have tried turning off any Razer tools (stopping services and ending processes) I had running and it still happens (is uninstalling necessary - if so, ill try?)
> anyway, here's another log i made after:
> [log.txt](https://github.com/megai2/d912pxy/files/4673087/log.txt)

no, disabling worked fine. 
in addition:
1. make sure there is no streaming/recording features enabled in ncsoft launcher
2. is there any mods installed via bns buddy?
3. try to extent memory commit limit in your system by enabling pagefile

**Comment by Braiio** [comment]
1. turned it off
2. no
3. Tuned max size to the recommended (2938 MB). But i don't have any RAM issues. when i launch the game, only 23% of my 16 GB are used

Still nothing new, it won't launch :(

**Comment by Braiio** [comment]
@megai2 I somehow solved it.
I was suggested to take ownership of the folder of BNS and allow the folder through firewall.
But I don't think that actually helped.
What did help in my opinion, is updating windows 10 to the latest update (I had windows 10 1709).
Maybe adding this to the guide will help others :)

**Comment by megai2** [comment]
Ahh, yes, NCSoft installer installs game with some tricky user so ther is sometimes conflict on rw of files that is somehow leads to errors without errors in logs. It was seen before.

**Comment by megai2** [comment]
added this info on wiki page
