### ISSUE TITLE
GW2 hangs/crashes 

### ISSUE THREAD

**Issue by K8Skies** [megai2/d912pxy#257]
**Describe the bug**
GW2 just stops responding/crashes. Usually have to restart PC to be able to get GW2 running after this.

**To Reproduce**
Sometimes just start the game, sometimes in character screen, sometimes in the game.

**Standard information**

1. Windows 10 PRO 1909
2. Hardware info: Intel i7 4790K, 32GB DDR3, GF RTX2070S
3. Nvidia driver ver. 442.59
4. d912pxy ver. 2.1.2
5. Log file from d912pxy/log.txt and d912pxy/crash.txt
[log.txt](https://github.com/megai2/d912pxy/files/4713494/log.txt)

**Additional context**
I have tried without d912pxy and then these crashes don't happen. I have tried newest and different Nvidia drivers, and same hang still happens, 442.59 just works a little better in other games. 
I usually have barebones teamspeak up and running, but hangs happen without it too.
There are no other "troublemaker" apps installed.

**Comment by megai2** [comment]
1. Avoid using fullscreen mode and Alt+Enter mode switching due to DXGI limitations. While it works and even recovers from DXGI deadlock, this is not 100% safe. To recover from this bug manually, do soft-reboot: use Ctrl+Alt+Delete -> Logout.

2. Some of maybe "troublemaker" apps are in logs (RTSS maybe)

```
 1653CBC6 [ error ] helper | CClientConnectionManager::Connect(): failed with 0x00000002
 

1653CBC6 [ note ] note | 0 | CClientConnectionManager::Connect(): failed with 0x00000002
 

1653D665 [ error ] helper | CClientConnectionManager::Connect(): failed with 0x00000002
 

1653D665 [ note ] note | 1 | CClientConnectionManager::Connect(): failed with 0x00000002
```

**Comment by K8Skies** [comment]
Thanks. 
Windowed/ windowed fullscreen is more than a bit problematic, because it let's mouse to escape and click into second and third screens and take away the focus from GW2 screen.
Could these troublemaker apps be GPU-Z and/or HWiNFO64? They are the only ones even installed.
I will try with both apps uninstalled and on windowed mode, even though I can't use it permanently. 

Also I can't get my GFX recover from this with logout alone. So far only thing helping is a complete restart.

**Comment by megai2** [comment]
Multimonitor setups can have some oddities. GPU-Z and HWINFO64 was not causing problems before.

**Comment by Squall-Leonhart** [comment]
442.59 is a driver with issues and should not be used for dx12 applications.

**Comment by K8Skies** [comment]
Still crashing with same error on windowed fullscreen. I Cannot recover GPU with soft-reboot. 
[log.txt](https://github.com/megai2/d912pxy/files/4775285/log.txt)

Also still getting CClientConnectionManager::Connect(): failed with 0x00000002 errors from start to shutdown, are they critical or something not really important?
Can they be from Sound Blaster control panel, Corsair utility engine process or Logitech Gaming framework process, because I don't any other possible troublemakers. 


> 442.59 is a driver with issues and should not be used for dx12 applications.

I haven't read about problems with DX12 on 442.59, what kind of issues are there?
It's a shame, because 442.59 are working best for me in most games I play.

**Comment by megai2** [comment]
> 
> 
> Still crashing with same error on windowed fullscreen. I Cannot recover GPU with soft-reboot.
> [log.txt](https://github.com/megai2/d912pxy/files/4775285/log.txt)
> 
> Also still getting CClientConnectionManager::Connect(): failed with 0x00000002 errors from start to shutdown, are they critical or something not really important?
> Can they be from Sound Blaster control panel, Corsair utility engine process or Logitech Gaming framework process, because I don't any other possible troublemakers.
> 
> > 442.59 is a driver with issues and should not be used for dx12 applications.
> 
> I haven't read about problems with DX12 on 442.59, what kind of issues are there?
> It's a shame, because 442.59 are working best for me in most games I play.

Make sure you using safe OC profiles both on CPU & GPU and your system is not overheating.
There was reports of stalls/hangs with unstable OC and/or insufficient cooling.
Also make sure your GPU is properly seated in PCI-E slot.

3 of named applications can be a problem, yes.

Fact of driver ver. N working best is very strange. What problems you faceed with latest stable drivers?

**Comment by megai2** [comment]
nothing more reported on this, i'll close it for now.
if problem is still there, reopen it
