### ISSUE TITLE
Snek Legendary White Outline

### ISSUE THREAD

**Issue by hukyly** [megai2/d912pxy#258]
Any idea how could i fix this white outline on snek?

https://imgur.com/0PvxOYT

I tried switching between shaders quality and also reinstalling dx912, also updated my GPU drivers and still same.

**Comment by hukyly** [comment]
https://imgur.com/mihtEus

Without DX912pxy

**Comment by megai2** [comment]
try latest build from appveyor https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts

**Comment by hukyly** [comment]
You are a god sir, thank you very much,

pic of it fixed :

https://imgur.com/BHYk0w8
