### ISSUE TITLE
Instant crash when starting the game

### ISSUE THREAD

**Issue by Keruvil** [megai2/d912pxy#259]
**Describe the bug**
After running the install.exe with everything on default the game instantly crashes on start.
After I remove it, Guildwars starts normally again.

I hope I didn't miss it but I checked closed issues and didn't find anything like this yet.

**System**
Win 10 Pro 1909
Intel i7-9700k, RTX 2070 Super, 16GB RAM
GPU driver vers. 446.14

**Screenshots**
*--> Crash <--*
Assertion: Failed to load Coherent DLL: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(50)
App: Gw2-64.exe 
Pid: 4248
BaseAddr: 00007FF78A0E0000
ProgramId: 101
Build: 104148
When: 2020-06-07T12:10:41Z 2020-06-07T14:10:41+02:00
Uptime:   0 days  0:00:03
Flags: 0

*--> System <--*
Name: 0c6df73a
IpAddr: 
Processors: 8 [GenuineIntel:6:14:13]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 10040MB/16318MB  61%
Paged:     7111MB/18750MB  37%
Virtual:  134213230MB/134217727MB  3%
Load: 38%
CommitTotal:  11638MB
CommitLimit:  18750MB
CommitPeak:   11977MB
SystemCache:   7929MB
HandleCount:  78521
ProcessCount:   198
ThreadCount:   2813

*--> Process Memory <--*
Private:          109MB
WorkingSet:       103MB
PeakWorkingSet:   219MB
PageFaults:    299805

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    81.93       6090        
Uncategorized           43.85       4622        
Programmer Data         31.63       713         
I/O                     31.12       499         
Archive                 29.79       25          
Collide Havok           6.45        755         
Collide                 6.45        755         
File Service            1.24        12          
Collections             0.25        73          
Dictionary              0.24        41          
Networking              0.11        14          
Asset Service           0.09        457         
Event                   0.07        3           
Game                    0.05        56          
Engine                  0.02        12          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
BTree                   0.00        6           
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
UI                      0.00        20          
Text                    0.00        1           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           43.85       4622        
Archive                 29.79       25          
Collide Havok           6.45        755         
File Service            1.24        12          
Dictionary              0.24        41          
Networking              0.11        9           
Asset Service           0.09        457         
Event                   0.07        3           
Game                    0.02        46          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Collections             0.01        25          
Engine                  0.01        6           
BTree                   0.00        6           
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           
Agent                   0.00        1           
String                  0.00        8           

*--> DllList <--*
00007FF78A0E0000 - C:\Program Files\Guild Wars 2\Gw2-64.exe
00007FFFC21C0000 - C:\Windows\SYSTEM32\ntdll.dll
00007FFFC16A0000 - C:\Windows\System32\KERNEL32.DLL
00007FFFBFE20000 - C:\Windows\System32\KERNELBASE.dll
00007FFFC1810000 - C:\Windows\System32\USER32.dll
00007FFFBFC80000 - C:\Windows\System32\win32u.dll
00007FFFC0270000 - C:\Windows\System32\GDI32.dll
00007FFFC00D0000 - C:\Windows\System32\gdi32full.dll
00007FFFBF3E0000 - C:\Windows\System32\msvcp_win.dll
00007FFFBF1B0000 - C:\Windows\System32\ucrtbase.dll
00007FFFC0610000 - C:\Windows\System32\ADVAPI32.dll
00007FFFC20C0000 - C:\Windows\System32\msvcrt.dll
00007FFFC08E0000 - C:\Windows\System32\sechost.dll
00007FFFC0740000 - C:\Windows\System32\RPCRT4.dll
00007FFFC14E0000 - C:\Windows\System32\WS2_32.dll
00007FFFB9090000 - C:\Windows\SYSTEM32\VERSION.dll
00007FFFBF150000 - C:\Windows\System32\WINTRUST.dll
00007FFFBF090000 - C:\Windows\System32\MSASN1.dll
00007FFFBBD30000 - C:\Windows\SYSTEM32\WINMM.dll
00007FFFBB910000 - C:\Windows\SYSTEM32\WTSAPI32.dll
00007FFFBFCD0000 - C:\Windows\System32\CRYPT32.dll
00007FFFC1B70000 - C:\Windows\System32\PSAPI.DLL
00007FFFBBD00000 - C:\Windows\SYSTEM32\winmmbase.dll
00007FFFC02A0000 - C:\Windows\System32\ole32.dll
00007FFFBF480000 - C:\Windows\System32\cfgmgr32.dll
00007FFFC1C40000 - C:\Windows\System32\combase.dll
00007FFFBF2B0000 - C:\Windows\System32\bcryptPrimitives.dll
00007FFFC0470000 - C:\Windows\System32\OLEAUT32.dll
00007FFFC0DF0000 - C:\Windows\System32\SHELL32.dll
00007FFFC1760000 - C:\Windows\System32\shcore.dll
00007FFFBF4D0000 - C:\Windows\System32\windows.storage.dll
00007FFFBF0B0000 - C:\Windows\System32\profapi.dll
00007FFFBF0E0000 - C:\Windows\System32\powrprof.dll
00007FFFBF080000 - C:\Windows\System32\UMPDC.dll
00007FFFC2060000 - C:\Windows\System32\shlwapi.dll
00007FFFBF130000 - C:\Windows\System32\kernel.appcore.dll
00007FFFBFCB0000 - C:\Windows\System32\cryptsp.dll
00007FFF9E670000 - C:\Windows\SYSTEM32\MSACM32.dll
00007FFFAF040000 - C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.836_none_2a2600ea466b531c\COMCTL32.dll
00007FFFAFEA0000 - C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.836_none_17afac286da192bb\gdiplus.dll
00007FFF80460000 - C:\Windows\SYSTEM32\USP10.dll
00007FFFA3D80000 - C:\Windows\SYSTEM32\Secur32.dll
00007FFFB17B0000 - C:\Windows\SYSTEM32\MSIMG32.dll
00007FFFBEAC0000 - C:\Windows\SYSTEM32\CRYPTBASE.DLL
00007FFFBEF70000 - C:\Windows\SYSTEM32\SSPICLI.DLL
00007FFFC1F80000 - C:\Windows\System32\IMM32.DLL
00007FFFAACB0000 - C:\Windows\SYSTEM32\dbghelp.dll
00007FFFBFC50000 - C:\Windows\System32\bcrypt.dll
00007FFFBDCF0000 - C:\Windows\SYSTEM32\dxcore.dll
00007FFFBD3F0000 - C:\Windows\system32\uxtheme.dll
00007FFFB8F80000 - C:\Windows\SYSTEM32\cryptnet.dll
00007FFFC2160000 - C:\Windows\System32\imagehlp.dll
00007FFFBE460000 - C:\Windows\system32\rsaenh.dll
00007FFF915D0000 - C:\Windows\system32\nvspcap64.dll
00007FFFBE0E0000 - C:\Windows\SYSTEM32\ntmarta.dll
00007FFFBDCA0000 - C:\Windows\SYSTEM32\gpapi.dll
00007FFFC1FB0000 - C:\Windows\System32\clbcatq.dll
00007FFF9F460000 - C:\Windows\system32\napinsp.dll
00007FFF9EA90000 - C:\Windows\system32\pnrpnsp.dll
00007FFFBE8F0000 - C:\Windows\System32\mswsock.dll
00007FFFBE640000 - C:\Windows\SYSTEM32\DNSAPI.dll
00007FFFC1550000 - C:\Windows\System32\NSI.dll
00007FFFBE600000 - C:\Windows\SYSTEM32\IPHLPAPI.DLL
00007FFF9E9B0000 - C:\Windows\System32\winrnr.dll
00007FFFBBA40000 - C:\Windows\system32\NLAapi.dll
00007FFFA4990000 - C:\Windows\system32\wshbth.dll
00007FFFC1560000 - C:\Windows\System32\msctf.dll
00007FFFB6C90000 - C:\Windows\System32\TextInputFramework.dll
00007FFFBA950000 - C:\Windows\System32\CoreUIComponents.dll
00007FFFBCCA0000 - C:\Windows\System32\CoreMessaging.dll
00007FFFBAFB0000 - C:\Windows\SYSTEM32\wintypes.dll
00007FFFBA2A0000 - C:\Windows\SYSTEM32\WindowsCodecs.dll
00007FFFB90F0000 - C:\Windows\System32\fwpuclnt.dll
00007FFFB8D80000 - C:\Windows\System32\rasadhlp.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\Windows\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.18362.1 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x39ac <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff7`8a2726dc 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a27275b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8ac04972 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a57c8fd 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a57ae47 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a4d672b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a4d5232 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a24fd27 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a440fae 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a43f25e 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a43eed9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a44056f 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a43e8dc 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a2693a1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`8a3f7d79 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007fff`c16b7bd4 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007fff`c222ce51 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff78b908538 rcx=000000892f9fe6b0
rdx=00007ff78b908538 rsi=0000000000000032 rdi=000000892f9febe0
rip=00007ff78a27267d rsp=000000892f9fe650 rbp=000000892f9fef60
 r8=0000000000000032  r9=00007ff78a0e0000 r10=000000892f9fe8d6
r11=000000892f9feb10 r12=0000000000000002 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF78B908518  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rbx +0 00007FF78B908538  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rbx+32 00007FF78B908558  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
rcx-32 000000892F9FE690  00007ff7`8a27267d 00000089`2f9fe650 00000089`2f9fef60 00000007`00000021 
rcx +0 000000892F9FE6B0  00000000`00000020 00000000`ffffffff 00000000`00000000 00000089`2f9fe8d6 
rcx+32 000000892F9FE6D0  00000000`00000002 00000089`2f9fe7f0 00009f80`0010000f 0053002b`002b0033 
rdx-32 00007FF78B908518  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rdx +0 00007FF78B908538  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rdx+32 00007FF78B908558  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
 r9 +0 00007FF78A0E0000  00000003`00905a4d 0000ffff`00000004 00000000`000000b8 00000000`00000040 
 r9+32 00007FF78A0E0020  00000000`00000000 00000000`00000000 00000000`00000000 00000178`00000000 

*--> Code <--*
00007ff7`8a27265d  488bf941 8bf0488d 0db668cc 01488bda H..A..H...h..H..
00007ff7`8a27266d  e89e73fe ff488d4c 2460ff15 bbdc3d01 ..s..H.L$`....=.
00007ff7`8a27267d  488b8424 58010000 4c8d0544 0b3f0148 H..$X...L..D.?.H
00007ff7`8a27268d  89442440 4885db48 8b8424f8 00000044 .D$@H..H..$....D
00007ff7`8a27269d  8bce4889 4424484c 0f45c348 8b842400 ..H.D$HL.E.H..$.
00007ff7`8a2726ad  01000048 8bd74889 44245033 c9488d44 ...H..H.D$P3.H.D

*--> Stack <--*
00000089`2f9fe650  00000089`2f9fec01 00000000`00000200 00000000`00000021 00000000`00000000 .../............!...............
00000089`2f9fe670  00000089`2f9fe690 00000089`2f9fe6b0 00000000`00000000 00000089`2f9fe638 .../......./............8../....
00000089`2f9fe690  00007ff7`8a27267d 00000089`2f9fe650 00000089`2f9fef60 00000007`00000021 }&'.....P../....`../....!.......
00000089`2f9fe6b0  00000000`00000020 00000000`ffffffff 00000000`00000000 00000089`2f9fe8d6  ........................../....
00000089`2f9fe6d0  00000000`00000002 00000089`2f9fe7f0 00009f80`0010000f 0053002b`002b0033 .........../............3.+.+.S.
00000089`2f9fe6f0  00000202`002b002b 00000089`00000030 00000000`00000000 00000089`2f9fe810 +.+.....0................../....
00000089`2f9fe710  00000089`00000840 00000000`00000000 00000000`00000000 00000000`00000001 @...............................
00000089`2f9fe730  00000089`2f9fe6b0 00007ff7`8b908538 00007ff7`8b908538 00000089`2f9fe650 .../....8.......8.......P../....
00000089`2f9fe750  00000089`2f9fef60 00000000`00000032 00000089`2f9febe0 00000000`00000032 `../....2........../....2.......
00000089`2f9fe770  00007ff7`8a0e0000 00000089`2f9fe8d6 00000089`2f9feb10 00000000`00000002 .........../......./............
00000089`2f9fe790  00000000`00000000 00000000`00000000 00000000`00000000 00007ff7`8a27267d ........................}&'.....
00000089`2f9fe7b0  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009f80 ................................
00000089`2f9fe7d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe7f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe810  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe830  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe850  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe870  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe890  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe8b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe8d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe8f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe910  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe930  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000089`2f9fe950  00000000`00000000 00007fff`c22007bd 000001e0`c5cccc50 0000003c`2f9fece0 .......... .....P........../<...
00000089`2f9fe970  00000000`00000004 000001e0`ca3ebe70 000001e0`c5cf8ba0 00007fff`0f08f2f5 ........p.>.....................
00000089`2f9fe990  000001e0`c5cccd10 0000003b`02000002 00000000`00000000 000001e0`ca3e8e50 ............;...........P.>.....
00000089`2f9fe9b0  00000000`00000100 000001e0`c3950150 00000000`00000000 00000000`00000001 ........P.......................
00000089`2f9fe9d0  00000000`0000003b 000001e0`c3950000 000001e0`c3950000 00007fff`c22060b9 ;........................` .....
00000089`2f9fe9f0  000001e0`c39502e8 00000000`00000600 000001e0`ca3ea401 00007fff`0000003b ..................>.....;.......
00000089`2f9fea10  00000000`00000100 000001e0`ca4b2770 00000000`00000080 00007fff`c2201d61 ........p'K.............a. .....
00000089`2f9fea30  000001e0`c3950000 000001e0`c3950000 000001e0`ca4b2760 00000000`00000080 ................`'K.............

**Comment by megai2** [comment]
this should help https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Keruvil** [comment]
Yep,

that worked. Thanks alot!
