### ISSUE TITLE
The FPS Counter is stuck over the command Squad commands and can no longer be moved 

### ISSUE THREAD

**Issue by ReiHinoSenshi** [megai2/d912pxy#261]
Can't move the FPS counter off the commander/squad group like in previous builds tried copying the config.ini from the old build still not movable seen this is 2.1.2_r532 build I could be missing a option or such but before enable=1 and show_fps=1 was the only thing needed to be turned on.

**Comment by megai2** [comment]
Try hitting Ctrl+Alt+N key combo, it should toggle/hide overlay mode

**Comment by ReiHinoSenshi** [comment]
thank you :) came back to say that helped it has 2 modes 1 adjust/move it and other off and back on again before adjust so it worked.
