### ISSUE TITLE
GW2 Crashes/Hangs

### ISSUE THREAD

**Issue by Beilog** [megai2/d912pxy#263]
**Describe the bug**
GW2 crashes with an error sometimes without it. Error is "Exception: e06d7363" Also the game can run super good and everything is fine but it hangs for a second or two. Like everything freezes.

**To Reproduce**
It's quite random I can be just sitting in a city or after a loading screen, in combat. In any maps as I've seen.  I run medium-high settings. I can't really tell what happens and how it happens.

**Standard information**

1. Windows 10 update ver 1903
2. Hardware info: Nothing is overclocked.
GPU - RX 570 4GB
CPU - Ryzen 5 1600
RAM - DDR4 8GB 2400
3. GPU Driver version: AMD 20.5.1
4. Version of d912pxy used: Version 2.1.2
5. [log.txt](https://github.com/megai2/d912pxy/files/4814108/log.txt) file
This is the [Error.txt](https://github.com/megai2/d912pxy/files/4814163/Error.txt) I get when the game crashes.

**Additional context**
I've played the game for hours doing the same things I do with and without d912pxy, and the problem only occurs when I have d912pxy installed.

**Comment by Squall-Leonhart** [comment]
downgrade to AMD's last 2019 driver or the one from november, everything since is broken to some degree.

**Comment by Beilog** [comment]
> downgrade to AMD's last 2019 driver or the one from november, everything since is broken to some degree.
> 
> 8GB is insufficient in 2020.

Okay, ill try the driver thing. Also, I was going to get another stick of ram when I'm able. I had 16GB on my last system and didn't have problems like this. I thought it might be that but I just wanted to make sure if there is something else I can do. SInce on another system I use with 4GB of ram I don't have OOM problems.

**Comment by megai2** [comment]
d912pxy uses agressive memory reservation algorithms to hide translation & api overhead

if you see that there is low physical memory usage, but you still hit OOM, try to increase memory commit limit by using bigger page file

**Comment by Beilog** [comment]
> d912pxy uses agressive memory reservation algorithms to hide translation & api overhead
> 
> if you see that there is low physical memory usage, but you still hit OOM, try to increase memory commit limit by using bigger page file

I already have 12GB page file on my SSD. Don't know how bigger it needs to be haha.

**Comment by megai2** [comment]
> 
> 
> > d912pxy uses agressive memory reservation algorithms to hide translation & api overhead
> > if you see that there is low physical memory usage, but you still hit OOM, try to increase memory commit limit by using bigger page file
> 
> I already have 12GB page file on my SSD. Don't know how bigger it needs to be haha.
Try to add 3-5 Gb more or close some other tasks that take good amount of RAM

**Comment by megai2** [comment]
nothing more reported on this, i'll close it for now. 
if problem is still there, reopen it
