### ISSUE TITLE
mapLoadinfo not showing with today's GW2 patch

### ISSUE THREAD

**Issue by navarog3** [megai2/d912pxy#264]
**Describe the bug**
When loading the game from command prompt with the -mapLoadinfo parameter, the loading information doesn't show up on loading screens

**To Reproduce**
Run the game with the -mapLoadinfo parameter with d912pxy, loading screens won't have info. 
Load the game again with the parameter but without d912pxy and it shows up.

**Expected behavior**
The map loading formation should display on loading screens

**Standard information**

1. Windows 10 update ver: 2004 (19041.330)
2. Hardware info: i7-7700HQ, GTX 1060, 16gb ram
3. GPU Driver version: 446.14
4. Version of d912pxy used: 2.1.2
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
[log.txt](https://github.com/megai2/d912pxy/files/4822473/log.txt)

**Additional context**
Obviously not the most serious issue, but I do like having the loading information.

**Comment by megai2** [comment]
works fine on latest builds 
![изображение](https://user-images.githubusercontent.com/1693251/85512089-2a0e6e00-b602-11ea-931b-5d5124544460.png)

**Comment by navarog3** [comment]
Ok sweet. So when the next release happens it will be fixed? If so, the yeah this bug is fixed.
