### ISSUE TITLE
G-sync not working with d912pxy in Windowed Fullscreen

### ISSUE THREAD

**Issue by Exci** [megai2/d912pxy#269]
Hi,
I just bought an 2070 card and I'm having an uncertain situation. I see this comment from a year ago on reddit:

> GSync, or other kind of that, monitors are supported in windowed fullscreen mode.

In my case:
No d912pxy + Windowed Fullscreen = g-sync works 
d912pxy + Windowed Fullscreen = no g-sync (or at least the g-sync indicator doesn't pop up)
d912pxy + Full screen = g-sync works and the mod's logs are updated and don't show any errors. 

So I have two questions:
1) Any idea why g-sync doesn't work in Windowed Fullscreen with the mod enabled?
2) Most importantly: does the mod work properly now with g-sync in Fullscreen? As far as I can tell, it does (going by fps difference with/without the mod), but I'm not sure if there are still certain incompatibilities.

Thanks!

**Comment by megai2** [comment]
Try to enable/disable vsync in game options and make sure there is no special overrides in driver globally or for gw2

**Comment by Atsthio** [comment]
Using r545![изображение](https://user-images.githubusercontent.com/20736562/86389833-a4dd2600-bc9f-11ea-8a6f-80adb61cb89b.png)
![gw2gsync](https://user-images.githubusercontent.com/20736562/86389959-d524c480-bc9f-11ea-99b7-8e460bd4aa2d.png)
![gw2gsync-vsync](https://user-images.githubusercontent.com/20736562/86389967-d81fb500-bc9f-11ea-9076-28dea415bc5c.png)

**Comment by Aussiemon** [comment]
@Exci Working with my monitor at 2560x1440 with VSync disabled in game options:
![Capture](https://user-images.githubusercontent.com/13663574/89114586-602de180-d43b-11ea-946b-9595a3e079f4.PNG)
and this GSync setting in Nvidia Control Panel.
![Capture2](https://user-images.githubusercontent.com/13663574/89114618-bb5fd400-d43b-11ea-89ba-746b049ede6a.PNG)

d912pxy v2.2 (r554)

I noticed that Yolomouse was either hiding the indicator or disabling GSync. Are you using it?

If that's not the culprit, are you using any Windows 10 compatibility options?

![Capture3](https://user-images.githubusercontent.com/13663574/89114674-712b2280-d43c-11ea-82c6-b6fa29e8b036.PNG)

Disabling Fullscreen Optimizations might affect GSync if you aren't using "Windowed + Fullscreen" mode.

**Comment by Exci** [comment]
@Aussiemon I have the same settings as you. I'm not getting the g-sync indicator in windowed full screen. I'm not using yolo mouse while testing it.

**Comment by megai2** [comment]
> 
> @megai2 do you mean that there shouldn't be a global override with v-sync at all? Afaik the recommended setting is to have it on through the nvidia panel. Anyhow, I tried with it off too and it's the same situation.

If you override g-sync with v-sync, sounds like it should not work, being overriden with v-sync.
 
There is also number of situations when gsync can go wild: multiple monitors, extra 3-rd party overlays/tools

**Comment by megai2** [comment]
@Exci we discovered that some combinations of old windows 10 versions and new drivers, can cause this issues
try to make sure both windows and drivers are latest or rollback drivers to something older if you can't update windows

**Comment by megai2** [comment]
Summary:
1. Update drivers & win10 version - make sure you use combination of drivers & os version that does not create problems in other games
2. Make sure that GSync are enabled and other options are not forced - i can't override driver settings, if you set them wrong they will work as intended (i.e. wrong)
3. Check limitations & restrictions - maybe you have to use 1 monitor (if you have 2) or maybe there is some vendor restrictions (freesync on nv, low&high FPS limits and etc.)
4. If game is not capping FPS - you can cap it in d912pxy config or ingame settings

Dunno if problem is still there: reopen issue if it is.
