### ISSUE TITLE
Screenshot functions not working

### ISSUE THREAD

**Issue by rido-ramadan** [megai2/d912pxy#27]
Typical crash, but in character selection, press printscreen to screenshot automatically kills the app. Borderless window, 1080p.

**Comment by Malfrador** [comment]
Same in game.
 third party screenshot tools (Snipping tool, ShareX etc) do work.

**Comment by megai2** [comment]
Rebinding screenshot hotkey and using system behaivour works too.
This issue is not on priority for now.
