### ISSUE TITLE
Discord Go Live doesn't work with dx12pxy on

### ISSUE THREAD

**Issue by AdamusPawel** [megai2/d912pxy#270]
Hi,

Today I've updated Windows 10 to 2004 build and noticed, Go Live in Discord has stopped working with enabled dx12pxy.

I can select game from Application list, but none of GW2 settings works (windowed, fully windowed or full screen) - it shows just static discord image with movable cursor on preview when trying to stream.

Screen stram works fine somehow tho, but it's annoying when you wanna swap between running apps instead of just streaming 
 only GW2 window.

Also tried recording with Streamlabs OBS and it worked fine. nVidia overlay on/off also didn't changed anything.
Tried reinstall Discord, didn't worked aswell. Newest version of dx12pxy also didn't cured issue.

When disabled dx12pxy I was able to capture game window with Discord Go Live option.

My PC config:
- Ryzen 3900X
- 32GB RAM @3600Mhz (IF coupled mode)
- Gigabyte X570 Elite
- RTX 2060 6GB VRAM

I am using latest W10 build, nVidia graphic drivers and AMD chipset drivers. Also I have turned on option of HAGS.

Thanks!

**Comment by megai2** [comment]
I suppose that is yet another windows bug that i can't workaround.

Attach log at least, maybe it have some messages to point problem out.

**Comment by magnapeccatrix** [comment]
bummer still does not work. blank screen with mouse cursor when streaming gw2 window on discord while d912pxy is installed, big disappoinment.

**Comment by megai2** [comment]
Dunno, it properly captures whole screen, but not gw2 window.
Maybe discord does not handle dx12 apps well (or there is something new that broken in discord or win10)

I suggest reporting this problem to discord support as i can't do much about it: tool simply renders using dx12, i'm not providing or supporting or changing capture mechanisms

**Comment by magnapeccatrix** [comment]
Mere excuse to not work on a fix. It's 100% your tool that prevents discord from capturing gw2 window. Delete d912pxy and problem solved already. You did same excuses to not fix fullscreen vsync and blamed w10 for it. I started to have doubts about you.

**Comment by megai2** [comment]
I'm not giving up on things easy, but i don't have a time to cover any problem.

Just tryed it on RDR2 with dx12 - same thing, black screen with cursor. 
Also i did not found any way to debug discord go live or see how it captures video feed.

If you have more ideas about it - feel free to share.

**Comment by golyalpha** [comment]
@magnapeccatrix It's DX12 capture not being implemented in Discord that's causing Go Live to not work on Discord. If you can't deal with that, stop using this tool, as there is nothing anyone other than Discord can do.

**Comment by magnapeccatrix** [comment]
No point in replying to this after 7 months, not helpful at all. Also my point stands.

**Comment by magnapeccatrix** [comment]
Can you just stop crying over a 7 months old and closed thread, what kind of fetish and necroing is this. I won't even bother reading. Get a move on.
