### ISSUE TITLE
GW2 Locking Up if Exit via quite before doing logout 

### ISSUE THREAD

**Issue by neijek** [megai2/d912pxy#276]
Newest version v2.2 if i run the game for 5+ minutes, and try to quit out to desktop while in map the GW2 will lock up and never exit, does not do it if i first go to char screen via logout then quit. 

[log.txt](https://github.com/megai2/d912pxy/files/4998901/log.txt)

clean install of latest  v2.2 version with small edits in config file 
[config.ini.txt](https://github.com/megai2/d912pxy/files/4998904/config.ini.txt)

**Comment by Fexul** [comment]
Same problem.

**Comment by megai2** [comment]
Not repeated for me 10 times. Maybe there is something specail? Map or item used.

**Comment by Bustycat** [comment]
Yes I got the same problem with two computers installed with d912pxy.

**Comment by WanYaa** [comment]
might be that you have been running the game with save_pso_cache=1 for too long
is the game start not also longer compared to start with load_pso_cache=0 ?

**Comment by neijek** [comment]
> might be that you have been running the game with save_pso_cache=1 for too long
> is the game start not also longer compared to start with load_pso_cache=0 ?

hello wanyaa, no .. play time was less then 3 hours, in the documents they suggest to run the game for AT LEAST 3-4 hours to create a some proper cache and I've had it lock up after not even 1 hour of play time. 

as for your question about load_pso_cache i don't really notice load times, very high end pc

**Comment by megai2** [comment]
That is deadlock in unload sequence, i know what to fix, but that will take some time

**Comment by neijek** [comment]
> That is deadlock in unload sequence, i know what to fix, but that will take some time

alright, sounds good. If there's anything i can do to help let me know,

**Comment by Bustycat** [comment]
> might be that you have been running the game with save_pso_cache=1 for too long
> is the game start not also longer compared to start with load_pso_cache=0 ?

I played only one minute and it still happened.

**Comment by neijek** [comment]
> > might be that you have been running the game with save_pso_cache=1 for too long
> > is the game start not also longer compared to start with load_pso_cache=0 ?
> 
> I played only one minute and it still happened.

hey bustycay, ya if u read above me the developer "megai2" already confirmed the bug and knows the fix, but he said it will take a bit to fix.

**Comment by Squall-Leonhart** [comment]
i reproduced this once, an then was not able to again.

**Comment by megai2** [comment]
fixed in v2.2.1
