### ISSUE TITLE
Lag issue - Mount Skyscale Skin Incarnate Flame

### ISSUE THREAD

**Issue by Victorsouza02** [megai2/d912pxy#277]
**Information :**
   **Windows Version :**  Windows 10 1909
   **Hardware :** Ryzen 3 2200G , 8GB RAM and RX 570 8GB VRAM
   **GPU Driver version :** AMD Adrenaline 20.4.2
   **d912pxy version :** 2.2
   **Using other software in-game?** No

**Issue :** FPS dropping from 60 to 20-30 when mounting in Skycale with Incarnate Flame

Prints : 

With Skin Activated
![Skin Activated](https://user-images.githubusercontent.com/4674786/89123054-d74a9080-d4a2-11ea-9f15-849bee2a7efc.png)

With Skin Disabled
![withoutskin](https://user-images.githubusercontent.com/4674786/89123089-17aa0e80-d4a3-11ea-838d-b91ace403c25.png)

**Comment by megai2** [comment]
If FPS limited by GPU usage on DX9, there is no way to fix it by d912pxy

**Comment by megai2** [comment]
Checked - that effect is simply very heavy for GPU.
Effects(say shaders that are used to draw them) are translated 1:1(same problem on dx9), so nothing to do here from my side
