### ISSUE TITLE
It Doesn't Work

### ISSUE THREAD

**Issue by alperenkart** [megai2/d912pxy#278]
Game doesn't start with arcdps or without it. I tried it with arcdps while using d3d9_chainload setup option. And tried without arcdps while using default setup option. It throws different errors after I start game via launcher.

1. Windows 10 1909
2. Ryzen 7 3700X, RTX 2070, 2x8 Gigs 3600 Mhz RAM
3. Nvidia 442.74
4. Version of d912pxy 2.2
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist

[log.txt](https://github.com/megai2/d912pxy/files/5012706/log.txt)

I would like to get more FPS like anyone but it did not work.

Thanks anyway.

**Comment by wolfrik17** [comment]
Update to the latest version, log says you are running version 2.1.2 instead of version 2.2

**Comment by alperenkart** [comment]
Wow. I really don't know how is that happened. I was so sure about I downloaded the latest version. Seems like it worked. Thanks for help.
