### ISSUE TITLE
New Ice Reaver Cape does not show half of dyes

### ISSUE THREAD

**Issue by alperenkart** [megai2/d912pxy#279]
As I said on title, it has 4 dye channels but 2 of it not visible in game. Those channels just shows black on cape.

You can see it on preview too. Change your back item dyes and look via gem shop. 

Windows 10 1909
Ryzen 7 3700X, RTX 2070, 2x8 Gigs 3600 Mhz RAM
Nvidia 442.74
Version of d912pxy is 2.2
[log.txt](https://github.com/megai2/d912pxy/files/5023890/log.txt)

As you can see its just shows 2 dye channel's colors. 

![image](https://user-images.githubusercontent.com/69121537/89331397-61a91500-d69a-11ea-923c-b765d4014037.png)

**Comment by rspkers** [comment]
Confirmed. I was thinking "Wow this cape is garbage." Turns out it's bugged due to dx12pxy. The only working channels are the snow particles and the top crest. Cape is permablack. 
![Gw2-64_6DcETMgg06](https://user-images.githubusercontent.com/69250550/89420092-dcece400-d6f7-11ea-8256-db5af248d919.png)

**Comment by RapthorneLightweaver** [comment]
Confirmed x 2 
![image](https://user-images.githubusercontent.com/36140431/90178486-e3d4c000-dda3-11ea-9302-a51f5e4e1c9b.png)

**Comment by megai2** [comment]
That is pow(0,0) in shader that is considered UB 

There is 2 possible fixes for that

change dx9_pow define line in d912pxy/shaders/common.hlsli 

to
#define dx9_pow(a,b) ((a == 0) && (b == 0)) ? 0 : pow(abs(a), b)
or 
#define dx9_pow(a,b) ((a == 0) && (b == 0)) ? 1 : pow(abs(a), b)

and delete latest.pck (or any other shader cache)

can check it only in preview, so dunno what is actually right 0 or 1

**Comment by gamedeviced** [comment]
@megai2 `#define dx9_pow(a,b) ((a == 0) && (b == 0)) ? 0 : pow(abs(a), b)` works - thank you!

![2020 08 23-21 42 cropped](https://user-images.githubusercontent.com/70090026/90987279-09bf4900-e58a-11ea-862e-f5f70d276099.png)

Will this be implemented in future releases?

**Comment by ihavenodamage** [comment]
change that whole line?

![Screenshot_1](https://user-images.githubusercontent.com/70233054/91217646-33918080-e6ee-11ea-96e2-d6e5cc8af020.png)

**Comment by gamedeviced** [comment]
Yes, change the whole line. Worked for me.
