### ISSUE TITLE
Black screen on load and crash following, windowed fullscreed, just fullscreen, windowed

### ISSUE THREAD

**Issue by I2700I** [megai2/d912pxy#28]
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2799304/d912pxy_crash.txt)

[P7logs.zip](https://github.com/megai2/d912pxy/files/2799305/P7logs.zip)

**Comment by megai2** [comment]
Please read https://github.com/megai2/d912pxy#case-2 first before creating issue.
Update directx9.

**Comment by I2700I** [comment]
DirectX was updated, still the same.

**Comment by megai2** [comment]
It is dx9/driver installation problem, or other software interference, anyway, can't help with this.

**Comment by I2700I** [comment]
I just thought that could provide some valuable input, maybe it will be solved in the future releases.
Thanks for your work!
