### ISSUE TITLE
" Ctrl+Alt+N " Not working once the game was close afther a fresh install.

### ISSUE THREAD

**Issue by DoNotBlameItOnMe** [megai2/d912pxy#280]
All launch of game afther the one with fresh install " gretings " make the shortcut no working anymore.

And not working afther unistall and install again via install.exe from C:\Guild Wars 2\d912pxy folder.

**Comment by megai2** [comment]
try this fix https://github.com/megai2/d912pxy/wiki/Removing-compat-flags

**Comment by DoNotBlameItOnMe** [comment]
Cant find fix_compat_flags.ps1 and there is no entry in regedit for the game.

Each start of the game i dont see any message afther the first lauch and at the first luanch i am  able to close it with mouse and open it any time i want with the shorcut

Ctrl+Alt+N is one shot only ?

**Comment by megai2** [comment]
If you closed it on first start by pressing hide button, it will never show up back on next runs.
If you push another button or hide it with hotkey, it will be toggleable on next run.

**Comment by DoNotBlameItOnMe** [comment]
Ok , then sorry is not a bug, that worked like u said at your last message.
