### ISSUE TITLE
Character screen portraits appear, but the textures are all wrong

### ISSUE THREAD

**Issue by meowowins** [megai2/d912pxy#281]
This didn't happen until recently. [This is what it looks like](https://i.imgur.com/pftvuQm.png). I've tried doing the "fixing character portraits" fix 5 times now to  no avail. I run on Windowed Fullscreen but changed it to Fullscreen during some of the attempts to fix it as I heard there were issues with WF sometimes. Not running any other addons. Tried installing the textures and PSO Recompile but when I was trying to configure it, I found that my config.ini dœsn't have use_pso_precompile or use_pso_key_cache config under [sdb] or under anything else, so I didn't go through with it. Not sure what else I can do.

**Comment by nollidnosnhoj** [comment]
Might be related to this issue: #275 

ArenaNet need to update the game as they broke the depth buffer for portraits.

**Comment by megai2** [comment]
fixed in v2.2.1

**Comment by MysticDaedra** [comment]
I know this is closed, but I'm having a weird problem with the character portraits, wondering if it's related? Here's an image. Basically the hair isn't showing up on some of the characters, and the character itself in at least one portrait isn't even appearing. 

![image](https://user-images.githubusercontent.com/17184148/95548987-1cb39e80-09bb-11eb-8af5-05cb842fbecd.png)
