### ISSUE TITLE
Crashing at startup - d912pxy, reshade, arcdps setup

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#283]
Currently using d912pxy w/ Reshade and arcdps.  I'm using an older version of d912pxy (v1.8_r436) along with latest arcdps drivers as of Aug 15th 2020.  Anything change in the way I need to load it if I do that?  Currently it won't bootup after selecting play and instead crashes with the following log details.

Any help appreciated 

Errormsg:
"intercepted unhandled exception. remove any addons and overlays before reporting this to anet"

Log and Log.1 are from dx912py and then last is from arcdps.

[log.txt](https://github.com/megai2/d912pxy/files/5115235/log.txt)
[log.1.txt](https://github.com/megai2/d912pxy/files/5115236/log.1.txt)
[arcdps_082320.txt](https://github.com/megai2/d912pxy/files/5115237/arcdps_082320.txt)

**Comment by SaiyanOfDarkness** [comment]
Have you tried the recent update 2.2.1 to see if that changes anything?

**Comment by megai2** [comment]
any version older than 2.2 will crash due to bug in gw2 (it sets render target to depth stencil)
if anet will fix it: older versions will work fine
untill that use 2.2+

**Comment by bzeeeb** [comment]
Ok I updated and that did seem to fix it!

Are there any more recent pre-built shaders then the 2019 ones referenced in the guide?

**Comment by megai2** [comment]
You can look for new shader packs here
https://github.com/megai2/d912pxy/wiki/Shader-packs
