### ISSUE TITLE
Win 10 detects the latest release as "Trojan:Win32/Emali.A!cl"

### ISSUE THREAD

**Issue by xeron** [megai2/d912pxy#284]
Basically subj.

Win 10 with the latest updates. Only built-in antivirus, no 3rd party ones.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fEmali.A!cl&threatid=2147728322

Affected file is `d912pxy/install.exe`.

**Comment by megai2** [comment]
Looks like a false positive, no code was changed there and build is from appveyor

**Comment by megai2** [comment]
full release on virustotal
https://www.virustotal.com/gui/url/0d2a52e1d81a14957ef9f1bd4235de7e72c7630d690cd0381dbba8cb0a542829/

install.exe on virustotal
https://www.virustotal.com/gui/file/bdcfb4f41bd765fe3dd4eacc2bee8bc3512b68fccbf2ec3d1779881f1bdedb50/

**Comment by megai2** [comment]
submitted installer file to microsoft to fix this false detection
will update on news

**Comment by megai2** [comment]
false detection should be fixed now

**Comment by xeron** [comment]
Tested latest pre-release and is seems fine.

**Comment by megai2** [comment]
fixed in v2.3
