### ISSUE TITLE
Game micro stutters when closing character window

### ISSUE THREAD

**Issue by Demeth** [megai2/d912pxy#285]
Every single time i close my char's window, game loses frames.

**Comment by megai2** [comment]
can't do much about, lag is in game code, not directx

![изображение](https://user-images.githubusercontent.com/1693251/91207018-c511ea00-e710-11ea-889e-53b9390897fe.png)

basically 50ms lag spikes in game code

**Comment by megai2** [comment]
reported it to ANet, maybe they fix this. someday.

**Comment by Demeth** [comment]
Thank you for your input on the issue!
