### ISSUE TITLE
Unable to find install.exe

### ISSUE THREAD

**Issue by Zashen** [megai2/d912pxy#287]
I have downloaded the ZIP file and extracted to the GW2 source file per the instructions but, when I attempt to go in to run the installer it is nowhere to be found. 

I had checked the zip folder to see if it just wasn't extracted but, it isn't there either. 

I then went through your files on the github website and I am not seeing any install.exe within the files anywhere. I am not sure if this had been removed or renamed. 

I did confirm I have hidden files shown and have verified through each step of downloading and extracting that the install.exe was at no point within the source files I downloaded. 

If you need any other information or screenshots, please let me know.

**Comment by IsmetBesic** [comment]
Have you downloaded the source code as a zip file or one of the actual releases from here; https://github.com/megai2/d912pxy/releases? 

If it was the latter, check whether or not you have any running antivirus programs and disable them temporarily if necessary - they might have flagged the "install.exe" erroneously as a malicious file.

**Comment by megai2** [comment]
yep, you need to download release, not source code via this link https://github.com/megai2/d912pxy/releases
