### ISSUE TITLE
Unresponsive overlay

### ISSUE THREAD

**Issue by Ikjerang** [megai2/d912pxy#288]
D912pxy overlay isn't registering mouse input or hotkey toggle. Fresh install, config.ini is untouched, all other overlays are disabled or their host programs are closed. (Steam, GeForce Experience, Discord). According to the mod's overlay it installed properly, but none of the buttons work and the hotkey does nothing. I've installed it both using the add-on manager and the executable in its folder.

System specifications are as follows:
Windows 7 Pro x64, fully updated, all recommended software installed
ASUS Z170-AR 
Intel Core i5-6600K
NVIDIA GeForce GTX 960 x2
Driver ver.: 452.06
d912pxy version: v2.2.1 r558

The log shows two different exception error IDs.
[log.txt](https://github.com/megai2/d912pxy/files/5157784/log.txt)

**Comment by Nostrabobus** [comment]
I don't know if this is the same thing but I have a Win 10 install with an NVIDIA GTX 950. I installed D912pxy earlier today and all seemed ok as the process did it's work. I moved the display window to the right side of the screen and clicked the minimize icon to make it just a bar. When restarting GW2 a few hours later the routine display window is still on the right side but is now expanded, has no icon to reduce the display size and does not respond to anything,
![GW2 screen shot](https://user-images.githubusercontent.com/70777095/92280946-904c2280-eec8-11ea-9b85-055b58ec3741.jpg)

**Comment by ElimarCosta** [comment]
Same here /\

**Comment by megai2** [comment]
Overlay stats with "disabled input" state, to change that use default hotkey Ctrl+Alt+N

**Comment by mgoffin** [comment]
Can we please document the hotkey somewhere? I've been searching the Internet and the wiki and it wasn't clear what the hotkey was. It should be in the README or at the very least in the Install guide.

**Comment by megai2** [comment]
should be fixed in v2.3
also added more info on hotkeys

**Comment by Ikjerang** [comment]
Overlay works as intended now, thank you!
