### ISSUE TITLE
Reshade 4.3.0+d912pxy not working - CreateDXGIFactory1 failed with error code 0x80004002!

### ISSUE THREAD

**Issue by tmercieca** [megai2/d912pxy#289]
I am trying to set up reshade 4.3.0+d912pxy v2.2.1. I tried both a manual install and Gw2AddonManager. dxgi.dll is in same folder as Gw2-64.exe.

My specs are:
Windows 7 Home Premium x64
NVIDIA GeForce RTX2060
Intel Core i5-2500K

I am not getting the reshade menu (but I do get the d912pxy menu) so it looks to me like reshade is not working/incompatible. Therefore, I looked at the dxgi.log file and it produced the following:

> 06:29:35:631 [09108] | INFO  | Initializing crosire's ReShade version '4.3.0.563' (64-bit) built on '2019-05-25 19:00:11' loaded from "F:\Users\Tom\Desktop\gw2\dxgi.dll" to "F:\Users\Tom\Desktop\gw2\Gw2-64.exe" ...
> 06:29:35:693 [09108] | INFO  | Registering hooks for "user32.dll" ...
> 06:29:35:694 [09108] | INFO  | > Libraries loaded.
> 06:29:35:694 [09108] | INFO  | > Found 13 match(es). Installing ...
> 06:29:35:710 [09108] | INFO  | Registering hooks for "ws2_32.dll" ...
> 06:29:35:710 [09108] | INFO  | > Libraries loaded.
> 06:29:35:710 [09108] | INFO  | > Found 8 match(es). Installing ...
> 06:29:35:727 [09108] | INFO  | Registering hooks for "C:\Windows\system32\d3d9.dll" ...
> 06:29:35:727 [09108] | INFO  | > Delayed.
> 06:29:35:727 [09108] | INFO  | Registering hooks for "C:\Windows\system32\d3d10.dll" ...
> 06:29:35:727 [09108] | INFO  | > Delayed.
> 06:29:35:727 [09108] | INFO  | Registering hooks for "C:\Windows\system32\d3d10_1.dll" ...
> 06:29:35:728 [09108] | INFO  | > Delayed.
> 06:29:35:728 [09108] | INFO  | Registering hooks for "C:\Windows\system32\d3d11.dll" ...
> 06:29:35:728 [09108] | INFO  | > Delayed.
> 06:29:35:728 [09108] | INFO  | Registering hooks for "C:\Windows\system32\d3d12.dll" ...
> 06:29:35:728 [09108] | INFO  | > Delayed.
> 06:29:35:728 [09108] | INFO  | Registering hooks for "C:\Windows\system32\dxgi.dll" ...
> 06:29:35:728 [09108] | INFO  | > Delayed until first call to an exported function.
> 06:29:35:728 [09108] | INFO  | Registering hooks for "C:\Windows\system32\opengl32.dll" ...
> 06:29:35:728 [09108] | INFO  | > Delayed.
> 06:29:35:728 [09108] | INFO  | Initialized.
> 06:29:35:739 [09108] | INFO  | Installing delayed hooks for "C:\Windows\system32\d3d9.dll" (Just loaded via LoadLibrary("C:\Windows\system32\d3d9.dll")) ...
> 06:29:35:739 [09108] | INFO  | > Found 9 match(es). Installing ...
> 06:29:35:756 [09108] | INFO  | Redirecting Direct3DCreate9(32) ...
> 06:29:35:776 [09108] | INFO  | Redirecting RegisterClassW(000000000562F580 { ArenaNet_Dx_Window_Class }) ...
> 06:29:35:776 [09108] | INFO  | > Adding 'CS_OWNDC' window class style flag to 'ArenaNet_Dx_Window_Class'.
> 06:29:35:785 [09108] | INFO  | Redirecting IDirect3D9::CreateDevice(0000000006831300, 0, 1, 000000000008041A, 0x56, 000000000562F1C0, 000000000C3C67E0) ...
> 06:29:35:785 [09108] | INFO  | > Dumping presentation parameters:
> 06:29:35:785 [09108] | INFO  |   +-----------------------------------------+-----------------------------------------+
> 06:29:35:785 [09108] | INFO  |   | Parameter                               | Value                                   |
> 06:29:35:785 [09108] | INFO  |   +-----------------------------------------+-----------------------------------------+
> 06:29:35:785 [09108] | INFO  |   | BackBufferWidth                         | 1904                                    |
> 06:29:35:785 [09108] | INFO  |   | BackBufferHeight                        | 1042                                    |
> 06:29:35:785 [09108] | INFO  |   | BackBufferFormat                        | 22                                      |
> 06:29:35:785 [09108] | INFO  |   | BackBufferCount                         | 0                                       |
> 06:29:35:785 [09108] | INFO  |   | MultiSampleType                         | 0                                       |
> 06:29:35:785 [09108] | INFO  |   | MultiSampleQuality                      | 0                                       |
> 06:29:35:785 [09108] | INFO  |   | SwapEffect                              | 1                                       |
> 06:29:35:785 [09108] | INFO  |   | DeviceWindow                            | 000000000008041A                        |
> 06:29:35:785 [09108] | INFO  |   | Windowed                                | TRUE                                    |
> 06:29:35:786 [09108] | INFO  |   | EnableAutoDepthStencil                  | TRUE                                    |
> 06:29:35:786 [09108] | INFO  |   | AutoDepthStencilFormat                  | 75                                      |
> 06:29:35:786 [09108] | INFO  |   | Flags                                   | 0                                       |
> 06:29:35:786 [09108] | INFO  |   | FullScreen_RefreshRateInHz              | 0                                       |
> 06:29:35:786 [09108] | INFO  |   | PresentationInterval                    | 0                                       |
> 06:29:35:786 [09108] | INFO  |   +-----------------------------------------+-----------------------------------------+
> 06:29:35:903 [09108] | WARN  | Ignoring LoadLibrary("OLEAUT32.dll") call to avoid possible deadlock.
> 06:29:36:218 [09108] | INFO  | Recreated runtime environment on runtime 000000000CF41D30.
> 06:29:36:272 [09108] | INFO  | Destroyed runtime environment on runtime 000000000CF41D30.
> 06:29:37:057 [09108] | INFO  | Redirecting CreateDXGIFactory1({770AAE78-F26F-4DBA-A829-253C83D1B387}, 000000000562DF20) ...
> 06:29:37:059 [09108] | INFO  | Installing export hooks for "C:\Windows\system32\dxgi.dll" ...
> 06:29:37:059 [09108] | INFO  | > Found 6 match(es). Installing ...
> 06:29:37:395 [09108] | INFO  | Redirecting CreateDXGIFactory1({1BC6EA02-EF36-464F-BF0C-21CA39E5168A}, 000000000562E958) ...
> 06:29:37:400 [09108] | WARN  | > CreateDXGIFactory1 failed with error code 0x80004002!
> 

I am not sure what this means. Is it perhaps something to do with the fact I am on Windows 7 not Windows 10?

**Comment by megai2** [comment]
Yep, reshade does not load windows 7 compatibility layer for dx12. 
If it does not do this for other native dx12 games, only reshade contributors/authors can help with this.

**Comment by tmercieca** [comment]
Thanks for the clarification. I wasn't aware of such a requirement. Now everything seems to work fine on a win10 machine.
