### ISSUE TITLE
Crash to Desktop maybe 1 minute after game loads.

### ISSUE THREAD

**Issue by joreilly25** [megai2/d912pxy#29]
Loading the game results in some strange image retention issue, where I see a sort of faded version of what I was looking at a moment ago, overlaid on to what I'm now currently looking at, seems to go away after a few seconds, but then I crash to Desktop.
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2799371/d912pxy_crash.txt)
[P7logs.zip](https://github.com/megai2/d912pxy/files/2799373/P7logs.zip)

**Comment by megai2** [comment]
Fixed in v0.9.5.7
