### ISSUE TITLE
PoF cutscene textures not loading in properly

### ISSUE THREAD

**Issue by Ghostkat9** [megai2/d912pxy#294]
Like what the title said. It's similar to the HoT issue listed elsewhere but for PoF cutscenes. Not sure why this is happening but I hope there's some sort of fix for it :)

**Comment by megai2** [comment]
should be fixed in v2.3 as well as HoT cutscenes

**Comment by megai2** [comment]
I close this for now as it should work properly and noone said that is not working now.
