### ISSUE TITLE
No gw2.exe Found

### ISSUE THREAD

**Issue by plashemy** [megai2/d912pxy#296]
ive followed the instructions and placed the d912 folder in the root but when trying to install it says no gw2.exe folder found. Im confused since i am literally looking at the gw2.exe application. Any help on this one?

**Comment by IsmetBesic** [comment]
Your gw2 executable _should_ be called "Gw2-64.exe".

Is your installation of gw2 really old? Pre-dating the original release of the 64 bit client perchance?

**Comment by plashemy** [comment]
i just reinstalled it this morning. its called Gw2-64 minus the .exe for some reason

**Comment by plashemy** [comment]
I was able to get it to work though. for some reason it will not work if the file is named anything other than d3d9.dll and I dont know why. Im trying to get radial mount to work but it will not work named as chainload it only works if it is named d3d9.dll. what the heck am i doing incorrectly here.

**Comment by IsmetBesic** [comment]
https://github.com/megai2/d912pxy/wiki/Using-with-other-addons-and-overlays

**Comment by plashemy** [comment]
thanks it works now
