### ISSUE TITLE
Textures are missing in Whisper of Jormag strike mission v2.3h3

### ISSUE THREAD

**Issue by RusalkaLesna** [megai2/d912pxy#298]
**Describe the bug**
Depending on the camera angle terrain textures are missing, characters are not visible at all.  

**To Reproduce**
Go to Whisper of Jormag strike mission

**Screenshots**
![gw041](https://user-images.githubusercontent.com/57987764/94050929-3491fc80-fdd7-11ea-965b-ae3e36446531.jpg)
![gw040](https://user-images.githubusercontent.com/57987764/94051054-50959e00-fdd7-11ea-9016-3fe0a5e2388b.jpg)
![gw038](https://user-images.githubusercontent.com/57987764/94051942-94d56e00-fdd8-11ea-829b-466d9880d293.jpg)

**Standard information**
1. Windows 10 19041.508
2. Hardware info: i7-8700K, 32GB RAM, 1080Ti
3. Nvidia 456.38
4. v2.3h3

**Comment by IsmetBesic** [comment]
Set replay_threads=1 in you config for the time being - I can't pin-point the actual commit, but I believe that there was a mention of occlusion culling breaking in certain situations with replay_trheads >= 1.

**Comment by RusalkaLesna** [comment]
With replay_threads=1 it is working fine.

**Comment by megai2** [comment]
This is expected for now that occlusion query will be force on/off if multiple replay threads are in action.
