### ISSUE TITLE
No Radial and no ArcDPS

### ISSUE THREAD

**Issue by Skappz** [megai2/d912pxy#300]
Hello, 

when i installed this today (28th September 2020) i couldnt manage to get it to work while also using AddOn-Manager for ArcDPS and GWRadial. 

I think the AddOn manager might overwrite the dx12 files.

I tried multiple clean installs, then installing dx12 prior - works fine.
Then trying to add the other AddOns - dx12 not working anymore.

Felt like letting you know since your work is amazing. 

Best Regards,

**Comment by megai2** [comment]
You have to install d912pxy via addon manager too or put d912pxy folder to <your gw2 folder>/addons folder

**Comment by Skappz** [comment]
oooooh thanks a bunch. 

I will try that - wasnt sure if its updated via the AddOn-Manager.
