### ISSUE TITLE
BnS dark/ light bug

### ISSUE THREAD

**Issue by Berserkion** [megai2/d912pxy#302]
**Describe the bug**
A clear and concise description of what the bug is : In Blade and soul in some areas if i move the camera to different angle it turns so dark, and when i move it a little bit more it turn the light on again  .. i never had this before

**Expected behavior**

**Screenshots**
there is more areas than that  if u want more screenshots let me know :  https://imgur.com/a/Nzv4RLG

**Standard information**

1. Windows 10 update ver 10.0.19041 Build 19041
2. Hardware info: CPU, RAM, GPU Processor	Intel(R) Core(TM) i7-10700K CPU  -- 16 gb kingston rams - MSI rx 5600 xt GPU

3. GPU Driver version 20.9.1
4. Version of d912pxy used  d912pxy_v2.3h6_r628
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist

**Additional context**

**Comment by megai2** [comment]
I surely need a d912pxy/log.txt file and small check: will it repeat if you turn shadows off?

**Comment by Berserkion** [comment]
No i tried everything possible nothing worked, i attached the log.txt files

[log.1.txt](https://github.com/megai2/d912pxy/files/5324048/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/5324049/log.txt)

**Comment by megai2** [comment]
Should be fixed in [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4)
