### ISSUE TITLE
Miscellaneous crashes since installation

### ISSUE THREAD

**Issue by nounboundfreedom** [megai2/d912pxy#304]
Crashing for unknown reasons about once per hour. Usually happens in open world and possibly triggered by many other players being around, though not always. (Character model limit/quality already set to low). Already followed all steps on troubleshooting guide.

Unable to reproduce deliberately. Graphics settings are the same or lower than before using the addon. Crash occurs at many different times with few things in common.

Windows 10
AMD Ryzen 5 1400 Quad-Core Processor, 16 GB RAM, NVIDIA GeForce GTX 1060 6GB
GPU Driver 27.21.14.5655
d912pxy v2.3

[log.txt](https://github.com/megai2/d912pxy/files/5327936/log.txt)
Link to crash.dmp: https://drive.google.com/file/d/15YNAG0eU0ehEe1-jZkbctNAftSTRscM0/view?usp=sharing

**Comment by marksandford** [comment]
I'm having a similar experience, though perhaps a bit less frequently--every few hours in general, but not consistent:
Windows 10 build 19041.508
AMD FX-6300 six-core, 8 GB RAM, NVIDIA GeForce GTX 1050
GPU driver 27.21.14.5206
d912pxy v2.3h6

I'm happy to help troubleshoot in any way.

**Comment by Bocking** [comment]
I'm also having this problem. Every few hours ever since I added d912pxy v2.3h6.

Windows 10
AMD Ryzen 7 1700 Eight-Core Processor, 16 GB RAM, NVIDIA GeForce GTX 1080Ti
GPU driver 27.21.14.5655
d912pxy v2.3h6

**Comment by megai2** [comment]
Hi, log attached in first message shows out of memory due to small commit limit.
Try to enable page file on your system. 
(this guide should be helpful https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows )

**Comment by nounboundfreedom** [comment]
> 
> 
> Hi, log attached in first message shows out of memory due to small commit limit.
> Try to enable page file on your system.
> (this guide should be helpful https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows )

Just gave it a shot. I'll try it for a few days and report back if I have more issues. Thanks a bunch.

**Comment by nounboundfreedom** [comment]
I've been playing a lot these past couple days without a single crash. It looks like the page file issue fixed it. Thanks again!

**Comment by megai2** [comment]
Summary: Tool requires bigger commit limit that can be increased with page file 
(this guide should be helpful https://www.thewindowsclub.com/increase-page-file-size-virtual-memory-windows )
