### ISSUE TITLE
Blade & Soul 32 bit crash during loading screens.

### ISSUE THREAD

**Issue by 0Hate** [megai2/d912pxy#305]
**Describe the bug**
1# Error messages + game freeze during loading screen when exiting the dungeon Avalanche den.
See screenshot: Screenshot 1

2# Sometimes the game crashes without error messages while loading or walking in big maps.
I noticed that the game always crashes when memory usage is at 3300MB.

The game always crashes when closing the game. Blade and soul error reporter message appears and the Client.exe keeps running in the background causing players to not be able to play again until they manually kill the process.
See screenshot 2

1#
**To Reproduce**
1. Run game 32 bit game
2. Set graphics settings to "Ultra"
3. Head to "Zaiwei" location
4. Do this: "Enter portal of avalanche den"
5. "Clear the dungeon"
6. "Use the portal that appears after killing the yeti boss"
7. "Crash."
See screenshot 1

2#
1. Run game 32 bit game
2. "Close the game"
7. "Crash."
See Screenshot 2

**Expected behavior**
1# 
Appear back to the zaiwei location.

2# Game to close without error messages.

**Screenshots**
Screenshot 1: https://i.ibb.co/18vXJGm/error-message.png
Screenshot 2: https://i.ibb.co/TRx8tvJ/error-message-2.png

**Standard information**

1. Windows 10 update ver
OS Name	Microsoft Windows 10 Enterprise LTSC
Version	10.0.17763 Build 17763

2. Hardware info: CPU, RAM, GPU
Processor	Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz, 2501 Mhz, 12 Core(s), 24 Logical Processor(s)
Installed Physical Memory (RAM)	32.0 GB
Videocard: GTX 1080
3. GPU Driver version
27.21.14.5655

4. Version of d912pxy used
v2.3
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
https://gofile.io/d/I1ahW9

**Additional context**
Blade and soul rebellion private server.
download & register at to test: https://discord.gg/eqUyReD
Contact Cyan#1111 discord if you need a maxed test account.

**Comment by Berserkion** [comment]
32 bit will always crash with d912 or without it .... specially on ultra settings dont even bother wasting time on that, if u want to avoid crashes play on 64 bit .. if u want to reduce crashes on 32 bit u need to strip the game out of everything and end up with graphics looking like minecraft .

**Comment by 0Hate** [comment]
> 32 bit will always crash with d912 or without it .... specially on ultra settings dont even bother wasting time on that, if u want to avoid crashes play on 64 bit .. if u want to reduce crashes on 32 bit u need to strip the game out of everything and end up with graphics looking like minecraft .

You can increase the memory of 32 bit using: https://ntcore.com/?page_id=371
The game crashes with and without the patch btw.

**Comment by Berserkion** [comment]
good luck wasting ur time

**Comment by 0Hate** [comment]
Update. Game does not crash using the default config.ini
But the textures and everything is messed up.

**Comment by 0Hate** [comment]
I tried different configurations but it still crashes. I think personally it's a memory issue. Is there a way to set max memory usage for d912pxy or I have a better idea. Run a separate 64 bit process that handles the calls. and let it use how much memory it wants.

**Comment by megai2** [comment]
Hello.

First - right now any BnS client will crash on exit, that is known, and yet not solved. 
Have to do some core changes to fix that.

Second - 32bit BnS client is already know for its out of memory crashes. 
Even if you see it using 2500Mb, there can be situation that game fragmented memory space
and can't allocate a big chunk of memory that it needs.

On top of this, d912pxy will add a memory overhead, making thins even worse.
What you can try is to hardly tweak config.ini to conserve as much memory as you can.

This consists of various steps to try 
1. Disable/limit pooling to delete resources as fast as they are deleted by game
```
[pooling]
upload_alloc_step=8
upload_limit=0
vstream_alloc_step=8
vstream_limit=0
surface_alloc_step=0
surface_limits=00000
lifetime=0
host_va_reserve=37
keep_resident=0
```
2. Avoid using precompiled PSO cache (by default it is off)
3. Try to lower items_per_batch, maxWritesPerBatch, maxBatchesPerIFrame values all of this settings change base overhead of d912pxy. But beware - setting them too low will crash game.
4. Disable pck file preload by setting memcache_mask to 0
5. As you have 24 core CPU, setting dxc_threads and pso_threads to 1 can also help

Please note: all suggested steps can create stutter/lag, but will lower memory usage for sure.

In general it is better to use 64 bit BnS client, as you can bump memory usage & performance up by doin same steps but in "inversed" manner (also there is d912pxy/configs/bns_highend_config.ini that you can use out of box)
Also if you see unnatural perf drops on 64 bit, check that game is not flagged by FTH ( https://docs.microsoft.com/en-us/windows/win32/win7appqual/fault-tolerant-heap ) , that always a problem for me.

**Comment by 0Hate** [comment]
> Hello.
> 
> First - right now any BnS client will crash on exit, that is known, and yet not solved.
> Have to do some core changes to fix that.
> 
> Second - 32bit BnS client is already know for its out of memory crashes.
> Even if you see it using 2500Mb, there can be situation that game fragmented memory space
> and can't allocate a big chunk of memory that it needs.
> 
> On top of this, d912pxy will add a memory overhead, making thins even worse.
> What you can try is to hardly tweak config.ini to conserve as much memory as you can.
> 
> This consists of various steps to try
> 
> 1. Disable/limit pooling to delete resources as fast as they are deleted by game
> 
> ```
> [pooling]
> upload_alloc_step=8
> upload_limit=0
> vstream_alloc_step=8
> vstream_limit=0
> surface_alloc_step=0
> surface_limits=00000
> lifetime=0
> host_va_reserve=37
> keep_resident=0
> ```
> 
> 1. Avoid using precompiled PSO cache (by default it is off)
> 2. Try to lower items_per_batch, maxWritesPerBatch, maxBatchesPerIFrame values all of this settings change base overhead of d912pxy. But beware - setting them too low will crash game.
> 3. Disable pck file preload by setting memcache_mask to 0
> 4. As you have 24 core CPU, setting dxc_threads and pso_threads to 1 can also help
> 
> Please note: all suggested steps can create stutter/lag, but will lower memory usage for sure.
> 
> In general it is better to use 64 bit BnS client, as you can bump memory usage & performance up by doin same steps but in "inversed" manner (also there is d912pxy/configs/bns_highend_config.ini that you can use out of box)
> Also if you see unnatural perf drops on 64 bit, check that game is not flagged by FTH ( https://docs.microsoft.com/en-us/windows/win32/win7appqual/fault-tolerant-heap ) , that always a problem for me.

Thank you, I will try your suggestion and see if the crashes stop.

I can't use 64 bit so I am forced to use the 32 bit client.
