### ISSUE TITLE
Blade and Soul visual bug

### ISSUE THREAD

**Issue by skwarrior14** [megai2/d912pxy#306]
**Describe the bug**
while on login the screen brightness changes, if im hovering  a character the screen gets darker and makes another screen on the top left
while ingame icons are cut in half and i also get another screen on the top left and screen is darker

**To Reproduce**
Installed d912pxy and started game with bnsbuddy
just hover a character or go ingame

**Expected behavior**
not do what im assuming are visual bugs

**Screenshots**
https://ibb.co/93HGrPC
https://ibb.co/ZT1KT6m
https://ibb.co/60bbZdj

**Standard information**

1. Windows 10 update ver
Windows 10 Home
Version 1990 
OS Build 18363.1139

2. Hardware info: CPU, RAM, GPU
Processor Intel(R) Core(TM) i5-4430 CPU @3.00GHz 4 Cores
Installed memory(RAM) 8,00 GB
GPU AMD Radeon R7 200 Series

3. GPU Driver version
Radeon Software 20.9.1

4. Version of d912pxy
v2.3
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
[log.txt](https://github.com/megai2/d912pxy/files/5386639/log.txt)

**Comment by megai2** [comment]
you are using wrong config file
delete d912pxy folder in game installation, install it again via BnS buddy, should work properly

**Comment by skwarrior14** [comment]
thats how i did it 
and it didnt work

**Comment by megai2** [comment]
Log shows that config is wrong. Open d912pxy folder, delete config.ini there and rename bns_config.ini to config.ini.
Should work properly this way.

**Comment by skwarrior14** [comment]
now it works 
it looks like bnsbuddy was dowloading and installing the gw2 config file
so i installed through bnsbuddy but then replaced the config file with the bns one in the folder from here
