### ISSUE TITLE
Crash direct after d912pxy installed

### ISSUE THREAD

**Issue by ArgaViking** [megai2/d912pxy#308]
I followed instruction for installing d912pxy and it crash direct when game start. No another addons/tools/overlays installed. Already followed all steps on troubleshooting guide.

**Standard information**

1. Windows 10 64 bit
2. Hardware info: Intel i7 2600k, 8 GB RAM, NVIDIA GeForce GTX 780 3GB
3. GPU Driver version: 27.21.14.5671
4. Version of d912pxy used: v2.3
5. [log.txt](https://github.com/megai2/d912pxy/files/5390118/log.txt) [crash.dmp](https://www.dropbox.com/s/l9rhfy5hk5fm2va/Crash.dmp?dl=0)

**Comment by megai2** [comment]
Looks like you using very old win10 version that lacks some dx12 features, try to update it to version 1607

**Comment by ArgaViking** [comment]
Update latest build fixed issue.
