### ISSUE TITLE
KERNELBASE.dll Crash

### ISSUE THREAD

**Issue by Neocyte** [megai2/d912pxy#309]
**Describe the bug**
Guild Wars 2 will suddenly stop playing sound, fail to load textures, then crash with a hardware exception in "C:\WINDOWS\System32\KERNELBASE.dll". The Guild Wars 2 root folder will no longer be accessible: "Accessing a function that does not exist".

**To Reproduce**
Use all addons and reshade:
1) ArcDPS - bin64\d3d9.dll
2) RadialMount - bin64\d3d9_chainload.dll
3) d912pxy - bin64\d912pxy.dll
4) ReShade - root\dxgi.dll

Play the game and randomly crash. 

**Screenshots**
On crash:
![exception](https://user-images.githubusercontent.com/37944166/96927457-132f3980-1485-11eb-9fc0-148a826b43e1.png)

On reopening Guild Wars 2:
![exception2](https://user-images.githubusercontent.com/37944166/96928053-0232f800-1486-11eb-9f1a-34e3a6fd05b7.png)
![exception3](https://user-images.githubusercontent.com/37944166/96928066-05c67f00-1486-11eb-8810-1eafe5349614.png)

**Standard information**

1. Windows 10 Education ver 2004
2. Hardware info: Ryzen 3700x, 16gb DDR4 3200mhz Trident Z RAM, ASUS ROG STRIX 2080
3. GeForce Game Ready Driver ver 456.71
4. d912pxy ver 2.3h6, ArcDPS ver Oct 13, RadialMount ver 1.2.4, ReShade ver 4.7.0
5. [arcdps_lastcrash.log](https://github.com/megai2/d912pxy/files/5425549/arcdps_lastcrash.log)
[log.txt](https://github.com/megai2/d912pxy/files/5425551/log.txt)

**Comment by megai2** [comment]
ArcDPS intercepts crash and does not give callstack to troubleshoot problem.
Try isolating problem by removing other addons by one.

**Comment by Squall-Leonhart** [comment]
This looks more like storage hardware or driver failure rather than the libraries provided here.

**Comment by Neocyte** [comment]
> ArcDPS intercepts crash and does not give callstack to troubleshoot problem.
> Try isolating problem by removing other addons by one.

It's d912xpy. I uninstalled all addons, deleted bin64, updated my GPU driver and MVCR, and reinstalled d912pxy.
After a few minutes in game, the sound stopped playing, and I crashed again.
I was then unable to access ANY file in my G drive until I restarted my PC:

![1](https://user-images.githubusercontent.com/37944166/97752248-06849400-1aca-11eb-86ee-d991ccd68f1f.png)
![2](https://user-images.githubusercontent.com/37944166/97752262-0daba200-1aca-11eb-86e3-fa1f851ca237.png)

Here are the log.txt and Crash.dmp:
[log.txt](https://github.com/megai2/d912pxy/files/5467407/log.txt)
[Crash.zip](https://github.com/megai2/d912pxy/files/5467413/Crash.zip)

**Comment by Squall-Leonhart** [comment]
Sorry, but d912pxy cannot do what you are claiming.

**Comment by Neocyte** [comment]
RESOLVED

Turns out that my kernalbase.dll from Windows 10 was somehow corrupted...

I fixed the issue by executing "sfc /scannow" on the command prompt as the administrator. This verified the integrity of all Windows files and repaired them.
