### ISSUE TITLE
 integrated video card

### ISSUE THREAD

**Issue by Jam1313** [megai2/d912pxy#310]
The problem occurred on a laptop HP Pavilion cx-0171.
Processor: Intel (R) Core (TM) i5-8300H CPU @ 2.30GHz
Video: NVIDIA GeForce GTX 1050 Ti / 27.21.14.5671 / 20200930
Video: Intel (R) UHD Graphics 630 / 29.20.100.8881 / 20201007
DeviceName: DISPLAY1, BPP: 32, P: True, 1920x1080
OS (x64) Microsoft Windows NT 6.3.20241.1005
OS Name: Windows 10 Pro 2004 / 10/26/2020
.NET 4.7.2+ (528449) / MEMORY: 16273 MB (6215 MB)

When using DX12Mod, the game (BnS) does not use the 1050 Ti, but uses the HD 630. There is no way to disable the HD 630. Drivers and Win 10 indicate the use of 1050 Ti.

**Comment by megai2** [comment]
i need a d912pxy/log.txt at least

**Comment by mirh** [comment]
Did you force your gpu [here](https://www.onmsft.com/how-to/how-to-set-per-app-graphical-performance-settings-in-windows-10)?
