### ISSUE TITLE
Cannot install after uninstall.

### ISSUE THREAD

**Issue by gochev** [megai2/d912pxy#313]
**Before starting**

**Describe the bug**
I had only 8Gbs of ram and was running out of memory so I uninstalled it with the install script, however now I cannot install it again even if I select install or if I clear the cache nothing happens.

**To Reproduce**
Install it
Uninstall it
Try to install it again.
Game : Guild Wars 2

**Expected behavior**
The reinstall to works :) 

**Standard information**

1. Windows 10 update ver
2. Hardware info: i7, 32GB of Ram, RTX 2080
3. GPU Driver version (latest nvidia) 
4. Version of d912pxy used
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
The log file doesnt show anything strange

[log.1.txt](https://github.com/megai2/d912pxy/files/5468820/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/5468821/log.txt)

**Additional context**

**Comment by megai2** [comment]
Changed code that do deletion/copy of files in installer, 
should prevent system/av from blocking this operations.

**Comment by megai2** [comment]
Installer is fixed in [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4)
