### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Neocyte** [megai2/d912pxy#315]
**Describe the bug**
For the past week, GW2 has been randomly crashing for me with an exception in "C:\WINDOWS\System32\KERNELBASE.dll".

The crashes occur with d912pxy, ArcDPS, RadialMount, and Reshade installed and chainloaded. **They stop when d912pxy is uninstalled.** 

I have tried everything: reinstalling GW2, reinstalling and updating Windows to version 20H2, updating all drivers, updating all Visual C++, executing sfc /scannow, transferring an identical KERNELBASE.dll from another PC. Clearly, my issue does not have to do with corrupt hardware or software. 

**To Reproduce**

1. Manually install the latest release of d912pxy
2. Play the game for a few minutes
3. Sound eventually disappears, and a crash occurs due to an unhandled exception

**Standard information**

1. Windows 10 Education 20H2
2. Hardware info: Ryzen 3700x, 16gb DDR4 3200mhz Trident Z RAM, ASUS ROG STRIX 2080
3. GeForce Game Ready Driver ver 457.09
4. d912pxy ver 2.3h6, ArcDPS ver Oct 29, RadialMount ver 1.2.4, ReShade ver 4.8.2
5. 
[arcdps_lastcrash.log](https://github.com/megai2/d912pxy/files/5478540/arcdps_lastcrash.log)
[log.1.txt](https://github.com/megai2/d912pxy/files/5478543/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/5478546/log.txt)

**Comment by megai2** [comment]
So you fixed that with different reshade presets?

**Comment by Neocyte** [comment]
It was my M.2 NVME SSD that kept disconnecting after a few minutes into any application. That was why my logs were extremely vague and why I could not access any folders after the crash. I physically reseated my RAM and SSD, and everything seems to be okay now.
