### ISSUE TITLE
Visual glitch in Whisper of Jormag Strike Mission

### ISSUE THREAD

**Issue by strongstancer** [megai2/d912pxy#316]
**Describe the bug**
During the Strike Mission "Whisper of Jormag" nearly nothing is rendered except the boss platform and some other terrain, sometimes AoE-indicators. No characters, no boss model, only very few effects.

**To Reproduce**
Steps to reproduce the behavior.

1. Run game
2. Independent of graphics settings
3. Head to "Whisper of Jormag" location (Strike Mission)
4. Do this: Just enter the instance

**Expected behavior**
Normal loading of terrain and character models.

**Screenshots**
![gw035](https://user-images.githubusercontent.com/47291567/99183097-d0861780-2739-11eb-901a-5143d8a5a4c9.jpg)
![gw030](https://user-images.githubusercontent.com/47291567/99183098-d11eae00-2739-11eb-8da1-352c34b74b76.jpg)
![gw031](https://user-images.githubusercontent.com/47291567/99183101-d1b74480-2739-11eb-9ba2-34c0b15fba0d.jpg)
![gw033](https://user-images.githubusercontent.com/47291567/99183102-d1b74480-2739-11eb-9ca6-ec41f9bf29ff.jpg)
![gw034](https://user-images.githubusercontent.com/47291567/99183103-d24fdb00-2739-11eb-8016-d939ce672ba4.jpg)

**Standard information**

1. Windows 10 update ver: 17763
2. Hardware info: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 CPUs), ~3.6GHz; 32768MB RAM; NVIDIA GeForce RTX 2080 Ti
3. GPU Driver version: 442.59
4. Version of d912pxy used: v2.3h6
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
[log.txt](https://github.com/megai2/d912pxy/files/5542241/log.txt)

**Additional context**
Never had this problem in any other area of the game. Only recently did the strike mission after a long time but I am sure I had d912pxy running when I last did it a few months ago and there were no problems.
I know my OS and GPU-Drivers are outdated but I always get errors when I try to update them. Fresh install is scheduled in 2 weeks.

**Comment by darek2347** [comment]
Try changing replay_threads to 1

**Comment by strongstancer** [comment]
solved, great thanks!

**Comment by darek2347** [comment]
> 
> 
> solved, great thanks!

No problem! You could also read here [https://github.com/megai2/d912pxy/wiki/Custom-configuration](url) how to configure dx12pxy to your hardware.
