### ISSUE TITLE
Items icon in B&S become halves

### ISSUE THREAD

**Issue by nwchung20** [megai2/d912pxy#317]
![Screenshot_201202_000](https://user-images.githubusercontent.com/75359212/100844598-09064f00-34b7-11eb-8c13-4ec33959c55f.jpg)
![Screenshot_201202_001](https://user-images.githubusercontent.com/75359212/100844604-0b68a900-34b7-11eb-9f8d-aef6bc377c8e.jpg)

![Untitled 1](https://user-images.githubusercontent.com/75359212/100845356-0e17ce00-34b8-11eb-9c28-589caaa6c82d.jpg)
![Untitled 2](https://user-images.githubusercontent.com/75359212/100845360-107a2800-34b8-11eb-8706-da758e744f0e.jpg)
![Untitled 3](https://user-images.githubusercontent.com/75359212/100845362-1112be80-34b8-11eb-81c6-bc838581f4ff.jpg)

**Expected behavior**
Icon in my game become halves

**Standard information**

1. Windows 10 update ver 2004, OS build 19041.630
2. Hardware info: CPU, RAM, GPU as attached
3. GPU Driver version Nvidia RTX 2070 Version 457.30
4. Version of d912pxy used 2.3.1
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist

**Additional context**

Issue solved, thank you

**Comment by old4ever** [comment]
How did you solve it? I have the same problem, please share the solution.

> ![Screenshot_201202_000](https://user-images.githubusercontent.com/75359212/100844598-09064f00-34b7-11eb-8c13-4ec33959c55f.jpg)
> ![Screenshot_201202_001](https://user-images.githubusercontent.com/75359212/100844604-0b68a900-34b7-11eb-9f8d-aef6bc377c8e.jpg)
> 
> ![Untitled 1](https://user-images.githubusercontent.com/75359212/100845356-0e17ce00-34b8-11eb-9c28-589caaa6c82d.jpg)
> ![Untitled 2](https://user-images.githubusercontent.com/75359212/100845360-107a2800-34b8-11eb-8706-da758e744f0e.jpg)
> ![Untitled 3](https://user-images.githubusercontent.com/75359212/100845362-1112be80-34b8-11eb-81c6-bc838581f4ff.jpg)
> 
> **Expected behavior**
> Icon in my game become halves
> 
> **Standard information**
> 
> 1. Windows 10 update ver 2004, OS build 19041.630
> 2. Hardware info: CPU, RAM, GPU as attached
> 3. GPU Driver version Nvidia RTX 2070 Version 457.30
> 4. Version of d912pxy used 2.3.1
> 5. Log file from /P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
> 
> **Additional context**
> Add any other context about the problem here.
> 
> Issue solved, thank you

**Comment by megai2** [comment]
i guess bns buddy bugs out config file, delete d912pxy/config.ini and rename d912pxy/bns_config.ini to config.ini

**Comment by RinDman** [comment]
Still buggy and FPS drops to 5 FPS in crowded map :(  Will try to provide logs

**Comment by nwchung20** [comment]
> How did you solve it? I have the same problem, please share the solution.

![image](https://user-images.githubusercontent.com/75359212/101269786-5b908580-37ad-11eb-9f2f-f61251a07929.png)

**Comment by RinDman** [comment]
Worked for me, thx !
