### ISSUE TITLE
[Win7] [ Release v2.3.1 + "hotfix"] [Crash]

### ISSUE THREAD

**Issue by TheQuickFox** [megai2/d912pxy#319]
Continuation to closed report  #318
https://github.com/megai2/d912pxy/issues/318

I installed the hotfix but GW2 still crashes on launch with the hotfix installed.

Game crash log:
> *--> Crash <--*
Exception: e06d7363  
App: Gw2-64.exe 
Pid: 7668
BaseAddr: 000000013F9B0000
ProgramId: 101
Build: 109065
Module: KERNELBASE.dll
When: 2020-12-13T14:49:03Z 2020-12-13T15:49:03+01:00
Uptime:   0 days  0:00:02
Flags: 0
DumpFile: Crash.dmp

d912pxy log file:
> D4CE7 [ info ] log | d912pxy dll loaded 
D4CE7 [ info ] dyn_imports | Loading dynamic libs 
D4CE7 [ info ] dyn_imports | set 1 lib 0 loaded from ./d912pxy/12on7/d3d12.dll at 000007FEC77D0000 
D4CE7 [ info ] dyn_imports | Pepe: Is this windows 7? windows 7 right. 
D4CE7 [ error ] dyn_imports | Dyn lib d3dcompiler_47_v10_x64.dll 1 failed to load 
D4CE7 [ error ] dyn_imports | throw on "Dyn lib failed to load" with HR = 0xFFFFFFFF 
D4CE7 [ note ] note | 0 | "Dyn lib failed to load" | hr = FFFFFFFF

**Comment by TheQuickFox** [comment]
2.3 still works fine.

**Comment by megai2** [comment]
should be finally corected

**Comment by TheQuickFox** [comment]
Fixed! Thank you for the quick reply!
