### ISSUE TITLE
Problems with AV software

### ISSUE THREAD

**Issue by Gimgamgoo** [megai2/d912pxy#320]
**Describe the bug**
After installation my AV software (Bullguard) detects install.exe as a virus

---
From Bullguard (paid for) AV software:

C:\Program Files\Guild Wars 2\d912pxy\install.exe

Virus name: Drop.Win64.MLDExe.430
Behaviour: 
C:\Program Files\Guild Wars 2\d912pxy\installed.flag
C:\Program Files\Guild Wars 2\d912pxy\install.exe

Actions
Move to quarantine: Succeeded
---

Removing/Disabling the AV software is not an option.

Is there a reason (other than it contains a virus) why the AV softwrae detects it as such? It does not detect it prior to running, so I assume install.exe adjusts itself during installation to cause this after installation?

![Virus in DX12 GW2](https://user-images.githubusercontent.com/76697985/103228103-ecc7c780-4927-11eb-9c40-98f4d073d282.jpg)

**Standard information**

1. Windows 10 update ver 19041.685
2. Hardware info: i9-9900K, GeForce 2080 RTX, 32GB RAM
3. GPU Driver version 460.89
4. Version of d912pxy used: v2.3.1h2_r641

**Comment by megai2** [comment]
install.exe does not modify itself, 
maybe your AV does not like installed.flag and install.exe files when they are both present

**Comment by daemonjax** [comment]
You should be able to add the path as an exception so it's not scanned at all.  Any good AV software should allow you to do that (Avast, for example).

**Comment by Gimgamgoo** [comment]
Thanks for the fast replies. My AV has settings to exclude files/folders so I can exclude the GW2 folder. However, do I need to replace the files install.exe and install.flag by re-running the install? Or do I just wait till there's an update?

**Comment by daemonjax** [comment]
Your AV actually deleted it and didn't just quarantine the files?  I'd check your quarantine area first -- it's probably there and you can just right-click  to restore it.  If not (I'd definitely set the AV up to never delete files unless the quarantine action fails), and you need to re-run the install for some reason, then yeah you'd have to re-download it and re-install it.

**Comment by megai2** [comment]
I changed installer code a bit, should prevent fake triggers.

**Comment by megai2** [comment]
Corrected installer is in [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4)

**Comment by megai2** [comment]
updated installer is live.
AVs don't flag it for me, if problem is repeated - reopen issue.
