### ISSUE TITLE
Add Option to start without Overlay

### ISSUE THREAD

**Issue by wolfgangbures** [megai2/d912pxy#321]
It would be nice to start without the overlay, once successfull install has been verified.

**Comment by IsmetBesic** [comment]
As per https://github.com/megai2/d912pxy/wiki/Custom-configuration#extras you can edit the **config.ini** file and set the following line to disable the d912pxy overlay (note that you cannot open it with the shortcut unless you re-enable it in the config): 

```
[...]

[extras] 
enable=0
[...]
```

**Comment by wolfgangbures** [comment]
Ah, thank you for this hint.
Still, a "default off and turn it on with hotkey" would also be nice :-)

**Comment by megai2** [comment]
Or you can delete config.ini and select to hide overlays and stuff at startup

**Comment by megai2** [comment]
Added button in overlay to disable overlay.
