### ISSUE TITLE
Screen flickers black the first time using something with drunk effect

### ISSUE THREAD

**Issue by jcogilvie** [megai2/d912pxy#322]
**Describe the bug**
I've been running the latest version since it released, so I imagine what caching is going to happen has happened, yet one persistent issue remains every time I restart the gw2 client.  It isn't game breaking; just a kind of annoying nitpick.  The first time my character drinks any alcohol (e.g., egg nog from Wintersday) the whole screen flashes black.

**To Reproduce**
1. Run game
2. Obtain egg nog Wintersday item (any alcohol should work though)
3. Consume it

**Expected behavior**
Full screen wobble/drunk effect happens without first flashing everything black

**Screenshots**
Full screen wobble/drunk effect happens after the whole screen goes black for a moment

**Standard information**

1. Windows 10 pro 2004 19041.685
2. Hardware info: i7 6900k, nvidia gtx1080
3. GPU Driver version 460.79 (released 12/9/2020)
4. Version of d912pxy used (2.3h6)
5. Log file from d912pxy/log.txt attached

**Comment by jcogilvie** [comment]
[log.txt](https://github.com/megai2/d912pxy/files/5766186/log.txt)

**Comment by megai2** [comment]
That is a "known bug" without precompile it will always do a single black screen every time.

In [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4) precompile enabled by default, 
but with limited amount of elements, to avoid too long game startup time and extra RAM usage,
should help in general, but not 100%

**Comment by megai2** [comment]
workaround for this bug is live. if it still too annoying - reopen issue please.
