### ISSUE TITLE
Gw2 Crashing randomly after upgrading to 32Gigs of RAM

### ISSUE THREAD

**Issue by demonpuppet** [megai2/d912pxy#324]
I will randomly just crash. I have installed the RAM properly nothing else about the computer has any issues. It will randomly just crash. If someone can double check the Bug Report I do not quite understand it

**How to Reproduce**
I do not know how to reproduce. I am just curious if this is something on my end

**Expected behavior**
It will crash you out either giving an Anet bug report or the Arc Dps Bug Report(If you have Arc installed)

**Standard information**

1.  Windows10 Home 20H2
2. I7-9700k 3.6GHz, RTX 2700 Super, Corsair Vengeance 16 Gigs LPX, Corsair Vengeance 16 Gigs RGB Pro
3. Geforce Driver ver 460.89
4. v2.3.1 + "hotfix"
5. Bug Report below v
Jan 06 18:28:18 arcdps 20210104.230606-345-x64
Jan 06 18:28:18 client: gw2 0x7FF6FF9B0000-0x7FF701F0D000 (0x17D68F13)
Jan 06 18:28:18 client: arcdps 0x7FFDA3CB0000-0x7FFDA3D9E000 (0xAA6B0548)
Jan 06 18:28:18 client: chainloading d3d9
Jan 06 18:28:18 config: loading from "C:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
Jan 06 18:28:18 client: ready
Jan 06 19:27:27 error: intercepted crash from hardware exception in "C:\WINDOWS\System32\KERNELBASE.dll"
Jan 06 19:27:27 client: --- exception ---
			code: 0x00000000E06D7363
			addr: 0x00007FFDDC40D759
			offs: 0x000000000002D759
			prms:   0000000000000004
			flgs: 0x0000000000000001
Jan 06 19:27:27 client: --- system ---
			cpu: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
			ram: 13351MB / 32683MB used
			gpu: NVIDIA GeForce RTX 2070 SUPER
Jan 06 19:27:27 client: --- modules ---
			0x7FF6FF9B0000 - 0x7FF701F0D000    C:\Program Files\Guild Wars 2\Gw2-64.exe
			0x7FFDDE7B0000 - 0x7FFDDE9A6000    C:\WINDOWS\SYSTEM32\ntdll.dll
			0x7FFDB28B0000 - 0x7FFDB28C2000    C:\Program Files\AVG\Antivirus\aswhook.dll
			0x7FFDDCF30000 - 0x7FFDDCFED000    C:\WINDOWS\System32\KERNEL32.DLL
			0x7FFDDC3E0000 - 0x7FFDDC6A9000    C:\WINDOWS\System32\KERNELBASE.dll
			0x7FFDD98A0000 - 0x7FFDD9930000    C:\WINDOWS\SYSTEM32\apphelp.dll
			0x7FFDDC8B0000 - 0x7FFDDCA50000    C:\WINDOWS\System32\USER32.dll
			0x7FFDDC780000 - 0x7FFDDC7A2000    C:\WINDOWS\System32\win32u.dll
			0x7FFDDCFF0000 - 0x7FFDDD01A000    C:\WINDOWS\System32\GDI32.dll
			0x7FFDDC050000 - 0x7FFDDC159000    C:\WINDOWS\System32\gdi32full.dll
			0x7FFDDC6E0000 - 0x7FFDDC77D000    C:\WINDOWS\System32\msvcp_win.dll
			0x7FFDDC210000 - 0x7FFDDC310000    C:\WINDOWS\System32\ucrtbase.dll
			0x7FFDDE1B0000 - 0x7FFDDE25C000    C:\WINDOWS\System32\ADVAPI32.dll
			0x7FFDDD2D0000 - 0x7FFDDD36E000    C:\WINDOWS\System32\msvcrt.dll
			0x7FFDDC810000 - 0x7FFDDC8AC000    C:\WINDOWS\System32\sechost.dll
			0x7FFDDCBF0000 - 0x7FFDDCD1B000    C:\WINDOWS\System32\RPCRT4.dll
			0x7FFDDE140000 - 0x7FFDDE1AB000    C:\WINDOWS\System32\WS2_32.dll
			0x7FFDDC7B0000 - 0x7FFDDC810000    C:\WINDOWS\System32\WINTRUST.dll
			0x7FFDDD550000 - 0x7FFDDD558000    C:\WINDOWS\System32\PSAPI.DLL
			0x7FFDDCE00000 - 0x7FFDDCF2A000    C:\WINDOWS\System32\ole32.dll
			0x7FFDDE340000 - 0x7FFDDE696000    C:\WINDOWS\System32\combase.dll
			0x7FFDDCD30000 - 0x7FFDDCDFD000    C:\WINDOWS\System32\OLEAUT32.dll
			0x7FFDDD9F0000 - 0x7FFDDE132000    C:\WINDOWS\System32\SHELL32.dll
			0x7FFDDBEF0000 - 0x7FFDDC04D000    C:\WINDOWS\System32\CRYPT32.dll
			0x7FFDD5EA0000 - 0x7FFDD5EAA000    C:\WINDOWS\SYSTEM32\VERSION.dll
			0x7FFDD7CA0000 - 0x7FFDD7CB4000    C:\WINDOWS\SYSTEM32\WTSAPI32.dll
			0x7FFDCCAF0000 - 0x7FFDCCB17000    C:\WINDOWS\SYSTEM32\WINMM.dll
			0x7FFDD36B0000 - 0x7FFDD36CE000    C:\WINDOWS\SYSTEM32\MSACM32.dll
			0x7FFDC0340000 - 0x7FFDC04E6000    C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.685_none_faeca4db76168538\gdiplus.dll
			0x7FFDBECD0000 - 0x7FFDBED80000    C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\COMCTL32.dll
			0x7FFDC13D0000 - 0x7FFDC13E9000    C:\WINDOWS\SYSTEM32\USP10.dll
			0x7FFDD9830000 - 0x7FFDD9837000    C:\WINDOWS\SYSTEM32\MSIMG32.dll
			0x7FFDC8CB0000 - 0x7FFDC8CBC000    C:\WINDOWS\SYSTEM32\Secur32.dll
			0x7FFDC0F30000 - 0x7FFDC0F56000    C:\WINDOWS\SYSTEM32\winmmbase.dll
			0x7FFDDB8D0000 - 0x7FFDDB8DC000    C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
			0x7FFDDBDA0000 - 0x7FFDDBDDC000    C:\WINDOWS\SYSTEM32\SSPICLI.DLL
			0x7FFDDD520000 - 0x7FFDDD550000    C:\WINDOWS\System32\IMM32.DLL
			0x7FFDDBAE0000 - 0x7FFDDBAF2000    C:\WINDOWS\SYSTEM32\MSASN1.dll
			0x7FFDDC310000 - 0x7FFDDC390000    C:\WINDOWS\System32\bcryptPrimitives.dll
			0x7FFDD43F0000 - 0x7FFDD45D4000    C:\WINDOWS\SYSTEM32\dbghelp.dll
			0x7FFDDA060000 - 0x7FFDDA7F5000    C:\WINDOWS\SYSTEM32\windows.storage.dll
			0x7FFDDB960000 - 0x7FFDDB98C000    C:\WINDOWS\SYSTEM32\Wldp.dll
			0x7FFDDD020000 - 0x7FFDDD0CE000    C:\WINDOWS\System32\SHCORE.dll
			0x7FFDDE6A0000 - 0x7FFDDE6F5000    C:\WINDOWS\System32\shlwapi.dll
			0x7FFDDBE20000 - 0x7FFDDBE46000    C:\WINDOWS\SYSTEM32\profapi.dll
			0x7FFDD9E60000 - 0x7FFDD9E72000    C:\WINDOWS\SYSTEM32\kernel.appcore.dll
			0x7FFDDC6B0000 - 0x7FFDDC6D7000    C:\WINDOWS\System32\bcrypt.dll
			0x7FFDD99A0000 - 0x7FFDD9A3E000    C:\WINDOWS\system32\uxtheme.dll
			0x7FFDD5D70000 - 0x7FFDD5DA1000    C:\WINDOWS\SYSTEM32\cryptnet.dll
			0x7FFDDD560000 - 0x7FFDDD57D000    C:\WINDOWS\System32\imagehlp.dll
			0x7FFDDB8B0000 - 0x7FFDDB8C8000    C:\WINDOWS\SYSTEM32\CRYPTSP.dll
			0x7FFDDB000000 - 0x7FFDDB034000    C:\WINDOWS\system32\rsaenh.dll
			0x7FFDD3580000 - 0x7FFDD35BB000    C:\WINDOWS\SYSTEM32\dxcore.dll
			0x7FFDDC390000 - 0x7FFDDC3DE000    C:\WINDOWS\System32\cfgmgr32.dll
			0x7FFDAB0C0000 - 0x7FFDAB379000    C:\WINDOWS\system32\nvspcap64.dll
			0x7FFDDAC30000 - 0x7FFDDAC63000    C:\WINDOWS\SYSTEM32\ntmarta.dll
			0x7FFDDA810000 - 0x7FFDDA833000    C:\WINDOWS\SYSTEM32\gpapi.dll
			0x7FFDC5F70000 - 0x7FFDC5FB5000    C:\WINDOWS\SYSTEM32\DINPUT8.dll
			0x7FFDCC6D0000 - 0x7FFDCC822000    C:\WINDOWS\SYSTEM32\inputhost.dll
			0x7FFDD9500000 - 0x7FFDD95F2000    C:\WINDOWS\SYSTEM32\CoreMessaging.dll
			0x7FFDD7B40000 - 0x7FFDD7C37000    C:\WINDOWS\SYSTEM32\PROPSYS.dll
			0x7FFDD7E10000 - 0x7FFDD7F66000    C:\WINDOWS\SYSTEM32\wintypes.dll
			0x7FFDD91A0000 - 0x7FFDD94FE000    C:\WINDOWS\SYSTEM32\CoreUIComponents.dll
			0x7FFDCBB50000 - 0x7FFDCC240000    C:\WINDOWS\SYSTEM32\nvapi64.dll
			0x7FFDDD580000 - 0x7FFDDD9E7000    C:\WINDOWS\System32\SETUPAPI.DLL
			0x7FFDDD160000 - 0x7FFDDD209000    C:\WINDOWS\System32\clbcatq.dll
			0x7FFDC2A40000 - 0x7FFDC2A57000    C:\WINDOWS\system32\napinsp.dll
			0x7FFDC2A20000 - 0x7FFDC2A3B000    C:\WINDOWS\system32\pnrpnsp.dll
			0x7FFDC24F0000 - 0x7FFDC2505000    C:\WINDOWS\system32\wshbth.dll
			0x7FFDD79D0000 - 0x7FFDD79ED000    C:\WINDOWS\system32\NLAapi.dll
			0x7FFDDB380000 - 0x7FFDDB3BB000    C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
			0x7FFDDB6E0000 - 0x7FFDDB74A000    C:\WINDOWS\System32\mswsock.dll
			0x7FFDDB3D0000 - 0x7FFDDB49B000    C:\WINDOWS\SYSTEM32\DNSAPI.dll
			0x7FFDDE760000 - 0x7FFDDE768000    C:\WINDOWS\System32\NSI.dll
			0x7FFDC1BD0000 - 0x7FFDC1BE2000    C:\WINDOWS\System32\winrnr.dll
			0x7FFDCCC90000 - 0x7FFDCCD0F000    C:\WINDOWS\System32\fwpuclnt.dll
			0x7FFDD5860000 - 0x7FFDD586A000    C:\Windows\System32\rasadhlp.dll
			0x7FFDDCA50000 - 0x7FFDDCB66000    C:\WINDOWS\System32\msctf.dll
			0x7FFDCCB90000 - 0x7FFDCCC8D000    C:\WINDOWS\SYSTEM32\textinputframework.dll
			0x7FFDB4F80000 - 0x7FFDB4FD5000    C:\Program Files\YoloMouse\Yolo64.dll
			0x7FFDD6790000 - 0x7FFDD6944000    C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
			0x7FFDD2540000 - 0x7FFDD25EC000    C:\WINDOWS\SYSTEM32\TextShaping.dll
			0x7FFDA0FB0000 - 0x7FFDA10C4000    C:\Program Files\Guild Wars 2\bin64\CoherentUI64.dll
			0x7FFDA3CB0000 - 0x7FFDA3D9E000    C:\Program Files\Guild Wars 2\bin64\d3d9.dll
			0x7FFDD1B40000 - 0x7FFDD1C40000    C:\WINDOWS\SYSTEM32\WINHTTP.dll
			0x7FFDD6350000 - 0x7FFDD635B000    C:\WINDOWS\SYSTEM32\WINNSI.DLL
			0x7FFDDB040000 - 0x7FFDDB04A000    C:\WINDOWS\SYSTEM32\DPAPI.dll
			0x7FFD9E1E0000 - 0x7FFD9E2A3000    C:\Program Files\Guild Wars 2\bin64\d3d9_chainload.dll
			0x7FFDDA840000 - 0x7FFDDA933000    C:\WINDOWS\SYSTEM32\dxgi.dll
			0x7FFDBDCD0000 - 0x7FFDBDD69000    C:\WINDOWS\SYSTEM32\MSVCP140.dll
			0x7FFDD9810000 - 0x7FFDD981C000    C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
			0x7FFDBE650000 - 0x7FFDBE667000    C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
			0x7FFDAF570000 - 0x7FFDAF750000    C:\WINDOWS\SYSTEM32\d3d12.dll
			0x7FFDD81E0000 - 0x7FFDD863D000    C:\WINDOWS\SYSTEM32\d3dcompiler_47.dll
			0x7FFDD2100000 - 0x7FFDD22CF000    C:\WINDOWS\system32\d3d9.dll
			0x7FFDD9C80000 - 0x7FFDD9CAF000    C:\WINDOWS\SYSTEM32\dwmapi.dll
			0x7FFDD2FC0000 - 0x7FFDD30C5000    C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2635d5c616c804dc\nvldumdx.dll
			0x7FFD87260000 - 0x7FFD88EA7000    C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2635d5c616c804dc\nvd3dumx.dll
			0x7FFDDACE0000 - 0x7FFDDAD3A000    C:\WINDOWS\SYSTEM32\WINSTA.dll
			0x7FFD93440000 - 0x7FFD97E13000    C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2635d5c616c804dc\nvwgf2umx.dll
			0x7FFD866A0000 - 0x7FFD86E12000    C:\Program Files\NVIDIA Corporation\Ansel\NvCamera64.dll
			0x7FFDDA800000 - 0x7FFDDA80D000    C:\WINDOWS\SYSTEM32\HID.DLL
			0x7FFDD7A20000 - 0x7FFDD7A27000    C:\WINDOWS\SYSTEM32\XINPUT9_1_0.dll
			0x7FFDD7F70000 - 0x7FFDD81D4000    C:\WINDOWS\SYSTEM32\d3d11.dll
			0x7FFD90F80000 - 0x7FFD91384000    C:\Program Files\NVIDIA Corporation\Ansel\d3dcompiler_47_64.dll
			0x7FFDCC560000 - 0x7FFDCC58B000    C:\WINDOWS\SYSTEM32\D3DSCache.dll
			0x7FFDDBDE0000 - 0x7FFDDBE0E000    C:\WINDOWS\SYSTEM32\USERENV.dll
			0x7FFDD6BB0000 - 0x7FFDD6DB8000    C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
			0x7FFD9C660000 - 0x7FFD9C7E4000    C:\WINDOWS\System32\Speech\Common\sapi.dll
			0x7FFDD4140000 - 0x7FFDD414B000    C:\WINDOWS\SYSTEM32\msdmo.dll
			0x7FFDD5F60000 - 0x7FFDD5FE5000    C:\WINDOWS\System32\MMDevApi.dll
			0x7FFDDBCA0000 - 0x7FFDDBCCC000    C:\WINDOWS\System32\DEVOBJ.dll
			0x7FFDD8C30000 - 0x7FFDD8E17000    C:\WINDOWS\SYSTEM32\dcomp.dll
			0x7FFDB9C80000 - 0x7FFDB9CC6000    C:\WINDOWS\SYSTEM32\wdmaud.drv
			0x7FFDD2930000 - 0x7FFDD2939000    C:\WINDOWS\SYSTEM32\ksuser.dll
			0x7FFDD7370000 - 0x7FFDD737A000    C:\WINDOWS\SYSTEM32\AVRT.dll
			0x7FFDD61A0000 - 0x7FFDD6324000    C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
			0x7FFDDB4A0000 - 0x7FFDDB4EB000    C:\WINDOWS\SYSTEM32\powrprof.dll
			0x7FFDDB360000 - 0x7FFDDB372000    C:\WINDOWS\SYSTEM32\UMPDC.dll
			0x7FFDD2920000 - 0x7FFDD292D000    C:\WINDOWS\SYSTEM32\msacm32.drv
			0x7FFDD2720000 - 0x7FFDD272B000    C:\WINDOWS\SYSTEM32\midimap.dll
			0x7FFDD9A80000 - 0x7FFDD9A94000    C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
			0x7FFDD5FF0000 - 0x7FFDD609E000    C:\WINDOWS\SYSTEM32\mscms.dll
			0x7FFDD5EB0000 - 0x7FFDD5EC1000    C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
			0x7FFDB8E00000 - 0x7FFDB8E43000    C:\WINDOWS\SYSTEM32\icm32.dll
			0x7FFDBDDB0000 - 0x7FFDBE4E7000    C:\Program Files\NVIDIA Corporation\NvContainer\MessageBus.dll
			0x7FFDD6180000 - 0x7FFDD619D000    C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
			0x7FFD7EDD0000 - 0x7FFD80392000    C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2635d5c616c804dc\nvcuda64.dll
			0x7FFDD9BA0000 - 0x7FFDD9C7E000    C:\WINDOWS\SYSTEM32\wer.dll
			0x7FFDBB120000 - 0x7FFDBB1B2000    C:\WINDOWS\SYSTEM32\aepic.dll
			0x7FFDC68F0000 - 0x7FFDC6908000    C:\WINDOWS\SYSTEM32\NETAPI32.dll
			0x7FFDD7CD0000 - 0x7FFDD7E0C000    C:\WINDOWS\SYSTEM32\DSREG.DLL
			0x7FFDDB0A0000 - 0x7FFDDB12A000    C:\WINDOWS\SYSTEM32\msvcp110_win.dll
			0x7FFDD7980000 - 0x7FFDD79B6000    C:\WINDOWS\SYSTEM32\XmlLite.dll
			0x7FFDBA4A0000 - 0x7FFDBA585000    C:\WINDOWS\System32\FlightSettings.dll
			0x7FFDD6960000 - 0x7FFDD6A00000    C:\WINDOWS\SYSTEM32\policymanager.dll
			0x7FFDD7600000 - 0x7FFDD763E000    C:\WINDOWS\System32\netprofm.dll
			0x7FFDD5980000 - 0x7FFDD5990000    C:\WINDOWS\System32\npmproxy.dll
			0x7FFDD9B70000 - 0x7FFDD9B9A000    C:\WINDOWS\SYSTEM32\rmclient.dll
			0x7FFDBEED0000 - 0x7FFDBEFC4000    C:\Windows\System32\Windows.Security.Authentication.OnlineId.dll
			0x7FFDD4610000 - 0x7FFDD4DA5000    C:\Windows\System32\OneCoreUAPCommonProxyStub.dll
			0x7FFDD6330000 - 0x7FFDD6347000    C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
			0x7FFDC0BD0000 - 0x7FFDC0C6D000    C:\WINDOWS\SYSTEM32\webio.dll
			0x7FFDDAF20000 - 0x7FFDDAFB1000    C:\WINDOWS\system32\schannel.DLL
			0x7FFDBE690000 - 0x7FFDBE6A5000    C:\WINDOWS\SYSTEM32\mskeyprotect.dll
			0x7FFDDB990000 - 0x7FFDDB9CB000    C:\WINDOWS\SYSTEM32\NTASN1.dll
			0x7FFDDB9D0000 - 0x7FFDDB9F7000    C:\WINDOWS\SYSTEM32\ncrypt.dll
			0x7FFDBEB10000 - 0x7FFDBEB36000    C:\WINDOWS\system32\ncryptsslp.dll
Jan 06 19:27:27 client: --- registers ---
			RAX: 0x00007FFDDC228302   R8:  0x000001C934498400
			RBX: 0x00007FFD9E264300   R9:  0x00007FFDDC300980
			RCX: 0x000001C921081770   R10: 0x000001C9344984B0
			RDX: 0x000000038752EA10   R11: 0x0000000000000065
			RBP: 0x000000038752FA40   R12: 0x000001C956A575C0
			RSP: 0x000000038752F060   R13: 0x0000000000000000
			RSI: 0x000000038752F1D0   R14: 0x0000000180000000
			RDI: 0x0000000019930520   R15: 0x0000000000000001
			RIP: 0x00007FFDDC40D759
Jan 06 19:27:27 client: --- code ---
			0x7FFDDC40D719: 894C2420 89542424 48894424 304D85C9
			0x7FFDDC40D729: 744CB80F 00000048 8D4C2440 443BC049
			0x7FFDDC40D739: 8BD1440F 47C04489 44243849 C1E003E8
			0x7FFDDC40D749: 2A470600 488D4C24 2048FF15 1F231900
			0x7FFDDC40D759: 0F1F4400 00488B8C 24C00000 004833CC
			0x7FFDDC40D769: E8D20906 004881C4 D8000000 C3CC8364
			0x7FFDDC40D779: 243800EB CFCCCCCC CCCCCCCC CCCCCCCC
			0x7FFDDC40D789: CCCCCCCC CCCCCC40 534883EC 30488BD1
Jan 06 19:27:27 client: --- stack ---
			0x00038752F040: 00000080 01000000 20059319 00000000
			0x00038752F050: 40FA5287 03000000 59D740DC FD7F0000
			0x00038752F060: 10F15287 03000000 0043269E FD7F0000
			0x00038752F070: D0F15287 03000000 0867279E FD7F0000
			0x00038752F080: 63736DE0 01000000 00000000 00000000
			0x00038752F090: 59D740DC FD7F0000 04000000 FD7F0000
			0x00038752F0A0: 20059319 00000000 D0F15287 03000000
			0x00038752F0B0: 0043269E FD7F0000 00001E9E FD7F0000
			0x00038752F0C0: 00000000 00000000 C075A556 C9010000
			0x00038752F0D0: D0F15287 03000000 40FA5287 03000000
			0x00038752F0E0: 60F15287 03000000 1F687DDE FD7F0000
			0x00038752F0F0: 20059319 00000000 00000000 FD7F0000
			0x00038752F100: B0844934 C9010000 B0844934 C9010000
			0x00038752F110: 0090299E FD7F0000 00001E9E FD7F0000
			0x00038752F120: 164CB35F A3ED0000 48F15287 03000000
			0x00038752F130: 0043269E FD7F0000 804865BE FD7F0000
			0x00038752F140: 00000000 00000000 40FA5287 03000000
			0x00038752F150: 0867279E FD7F0000 2F8B229E FD7F0000
			0x00038752F160: 00001E9E FD7F0000 20059319 00000000
			0x00038752F170: D0F15287 03000000 0043269E FD7F0000
			0x00038752F180: 00001E9E FD7F0000 F0F15287 03000000
			0x00038752F190: C87B259E FD7F0000 A88C239E FD7F0000
			0x00038752F1A0: 00000000 00000000 A843259E FD7F0000
			0x00038752F1B0: 00000080 01000000 00000000 00000000
			0x00038752F1C0: C87B259E FD7F0000 FFFFFFFF 00000000
			0x00038752F1D0: 084B259E FD7F0000 00000000 00000000
			0x00038752F1E0: 00000000 00000000 00000000 00000000
			0x00038752F1F0: 22007300 77006100 70002000 63006800
			0x00038752F200: 61006900 6E002000 31003000 20006900
			0x00038752F210: 6E006900 74002000 65007200 72006F00
			0x00038752F220: 72007300 2C002000 63006800 65006300
			0x00038752F230: 6B002000 64006900 73007000 6C006100
			0x00038752F240: 79002000 73006500 74007400 69006E00
			0x00038752F250: 67007300 22002000 7C002000 68007200
Jan 06 19:27:27 client: --- trace ---
			ep 0x7FFDDC40D759 frame 0x00038752F130 rva 0x00000002D759 in KERNELBASE
			ep 0x7FFDBE654880 frame 0x00038752F190 rva 0x000000004880 in VCRUNTIME140
			ep 0x7FFD9E238CA8 frame 0x00038752F9F0 rva 0x000000058CA8 in d3d9_chainload @ d912pxy_swapchain::SwapHandle_Init_Error
			ep 0x7FFD9E22361C frame 0x00038752FA60 rva 0x00000004361C in d3d9_chainload @ d912pxy_gpu_que::ExecuteCurrentGPUWork
			ep 0x7FFD9E2237B8 frame 0x00038752FA90 rva 0x0000000437B8 in d3d9_chainload @ d912pxy_gpu_que::ThreadJob
			ep 0x7FFD9E23AA48 frame 0x00038752FAC0 rva 0x00000005AA48 in d3d9_chainload @ d912pxy_thread_main
			ep 0x7FFDDCF47034 frame 0x00038752FAF0 rva 0x000000017034 in KERNEL32
			ep 0x7FFDDE7FD0D1 frame 0x00038752FB70 rva 0x00000004D0D1 in ntdll
			thread start 0x7FFD9E23A9F0 rva 0x00004061D0D1 in d3d9_chainload @ d912pxy_thread_main

**Additional context**
I have Graphics Tool installed. I have tried uninstalling ArcDps and even doing a complete fresh reinstall of Gw2 and Dx12.

**Comment by megai2** [comment]
This is a GPU crash, can't say much if there is no way to reproduce it.
Let me know if [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4) works fine for you.

**Comment by demonpuppet** [comment]
> This is a GPU crash, can't say much if there is no way to reproduce it.
> Let me know if [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4) works fine for you.

Installed 2.4 and installed new Nvidia driver today. Still crashed though. Would you suggest doing a fresh install of Drivers?

**Comment by megai2** [comment]
Better to find scenario when game crashes. 
But i guess nothing special happens =\

If you have OC or changed timings on RAM, or any other OC (GPU/CPU), try running stability tests,
for some reason tool is sensetive for this.

**Comment by demonpuppet** [comment]
My CPU is Over locked. I can run a stability check but the temps are always extremely low 40-50ish Celsius and was fine on the extreme stress test. CPU is fairly new. GPU is also new but no OC on it was just running it at 3200. I never did a fresh fresh install of drivers though when I upgraded my GPU a few months back

**Comment by megai2** [comment]
If you want to cut out possibility of wrong drivers - fresh install is good idea.
But i suggest tesing RAM as it was origin of crashing after all.

**Comment by demonpuppet** [comment]
> If you want to cut out possibility of wrong drivers - fresh install is good idea.
> But i suggest tesing RAM as it was origin of crashing after all.

How do you suggest testing RAM?

**Comment by demonpuppet** [comment]
Did a complete fresh install of drivers went from a 980TI to a 2070 Super. I’ll update if anything changes

**Comment by Squall-Leonhart** [comment]
You are mixing ram, the only safe way to do this is have each matching pair in the same channel and even then depends entirely on the capabilities of the machines bios and whether or not it applies xmp profiles per channel rather than globally.

DX12 and Vulkan are more reliant on the CPU and Memory being stable than prior Graphics api's.

**Comment by seanmacky** [comment]
This is clearly a hardware issue. Now you have 32 gb of ram your cpu's Imc will more voltage. Up your vccsa and vccio voltage until your stable. Also try running ram voltage at 1.45 which is well within ddr4 rated specs.

**Comment by megai2** [comment]
@demonpuppet issue still persists on latest release bins?

**Comment by demonpuppet** [comment]
Sorry to not reply for a while. But I actually refunded the 16 gb of RAM and bought the 32 gb one instead. The Corsair Vengeance RGB Pro. It works perfectly fine. So I’m assuming it’s because I had mixed RAM. Gave my old RAM to my little sister lol

**Comment by megai2** [comment]
Issue solved then! =]
