### ISSUE TITLE
GW2 crashes with newest D912pxy in combination with re-shade 4.9.0

### ISSUE THREAD

**Issue by MasterJam-ai** [megai2/d912pxy#325]
After updating to recent re-shade 4.9.0 revision the game continiously crashes.
And after first crash the game won't even get past the character pick.

**Comment by megai2** [comment]
If you run reshade with depth detection: it sometimes can bug out, disable it or use forks with better depth detection.
+in [v2.4](https://github.com/megai2/d912pxy/releases/tag/v2.4) there is some fixes that should help

**Comment by Irubataru** [comment]
Sorry, I am not entirely sure if I understand. I also have crashes since upgrading re-shade, but I only have the following shaders enabled: ChromaticAberration, Technicolor, and LumaSharpen. What do I have to do to avoid the crashes?

**Comment by MasterJam-ai** [comment]
I can confirm that with your newest version 2.4 it's running smooth on latest ReShade 4.9.0. (not using new "special" ReShade version for newest release option)

**Comment by megai2** [comment]
fix is live in 2.4
