### ISSUE TITLE
Guild Wars 2 crashes when installing ArcDPS, d912pxy and GW2 Radial

### ISSUE THREAD

**Issue by DeckStarg** [megai2/d912pxy#326]
I first installed Radial and renamed file to d3d9_chainload.dll

I then installed ArcDPS and left it as d3d9.dll

I then installed d912pxy.

Game crashes will all 3 installed.

I reset to clean install and only install d912pxy then everything works.

Can't install Radial or ArcDPS.

Intel Core i7-8700K
G.Skill Trident Z RGB DDR4 3200MHz 4 x 8GB
MSI Ventus 2X Geforce RTX3070
Windows 10 Pro 20H2

**Comment by megai2** [comment]
What version if radial is used? Do you have any other overlays like RTSS?
Attach d912pxy/log.txt or crash.txt please

**Comment by megai2** [comment]
Or try using https://github.com/fmmmlee/GW2-Addon-Manager

**Comment by DeckStarg** [comment]
Thanks.

I have been using the add on manager. I saw a video reference for Arky.
Going to try install via CMD

**Comment by DeckStarg** [comment]
> What version if radial is used? Do you have any other overlays like RTSS?
> Attach d912pxy/log.txt or crash.txt please

Haven't been using any overlays at all.  Only using the Addon Manager provided in the download.  Re-installed a fresh copy of Guild Wars and now the game crashes when I try and install d912pxy

**Comment by DeckStarg** [comment]
*--> Crash <--*
Assertion: Failed to load Coherent DLL. Error code: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(58)
App: Gw2-64.exe 
Pid: 19080
BaseAddr: 00007FF7B7D90000
ProgramId: 101
Build: 110146
When: 2021-01-08T20:54:29Z 2021-01-08T22:54:29+02:00
Uptime:   0 days  0:00:02
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Processors: 12 [GenuineIntel:6:14:10]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical: 25023MB/32687MB  76%
Paged:    24684MB/37551MB  65%
Virtual:  134213168MB/134217727MB  3%
Load: 23%
CommitTotal:  12867MB
CommitLimit:  37551MB
CommitPeak:   18723MB
SystemCache:  21719MB
HandleCount:  98335
ProcessCount:   208
ThreadCount:   2961

*--> Process Memory <--*
Private:          122MB
WorkingSet:       108MB
PeakWorkingSet:   227MB
PageFaults:    276936

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    80.26       6130        
Uncategorized           43.22       4533        
Programmer Data         30.59       842         
I/O                     30.07       524         
Archive                 28.73       24          
Collide Havok           6.45        755         
Collide                 6.45        755         
File Service            1.24        12          
Collections             0.25        81          
Dictionary              0.24        41          
Networking              0.11        14          
Asset Service           0.09        483         
Event                   0.07        3           
Game                    0.05        56          
Engine                  0.02        12          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
BTree                   0.00        8           
Install                 0.00        30          
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           

*--> Memory Category Usage (Exclusive) <--*
[Category]              [Size(MB)]  [Count]     
Uncategorized           43.22       4533        
Archive                 28.73       24          
Collide Havok           6.45        755         
File Service            1.24        12          
Dictionary              0.24        41          
Networking              0.11        9           
Asset Service           0.09        483         
Event                   0.07        3           
Game                    0.03        46          
Content                 0.02        1           
Threading               0.01        14          
Model-Programmer        0.01        1           
Collections             0.01        31          
Engine                  0.01        6           
BTree                   0.00        8           
Install                 0.00        30          
Platform                0.00        65          
CharClient              0.00        5           
Services                0.00        8           
File Core               0.00        2           
Text                    0.00        1           
Download                0.00        3           
UI                      0.00        14          
Programmer Data         0.00        2           

*--> DllList <--*
00007FF7B7D90000 - E:\Guild Wars 2\Gw2-64.exe
00007FFF70990000 - C:\Windows\SYSTEM32\ntdll.dll
00007FFF6EFC0000 - C:\Windows\System32\KERNEL32.DLL
00007FFF6E150000 - C:\Windows\System32\KERNELBASE.dll
00007FFF6B550000 - C:\Windows\SYSTEM32\apphelp.dll
00007FFF70500000 - C:\Windows\System32\USER32.dll
00007FFF6E470000 - C:\Windows\System32\win32u.dll
00007FFF6F8A0000 - C:\Windows\System32\GDI32.dll
00007FFF6E6A0000 - C:\Windows\System32\gdi32full.dll
00007FFF6E500000 - C:\Windows\System32\msvcp_win.dll
00007FFF6E5A0000 - C:\Windows\System32\ucrtbase.dll
00007FFF6F080000 - C:\Windows\System32\ADVAPI32.dll
00007FFF6E9F0000 - C:\Windows\System32\msvcrt.dll
00007FFF6F490000 - C:\Windows\System32\sechost.dll
00007FFF6F530000 - C:\Windows\System32\RPCRT4.dll
00007FFF6F820000 - C:\Windows\System32\WS2_32.dll
00007FFF6E4A0000 - C:\Windows\System32\WINTRUST.dll
00007FFF6F810000 - C:\Windows\System32\PSAPI.DLL
00007FFF706A0000 - C:\Windows\System32\ole32.dll
00007FFF6F130000 - C:\Windows\System32\combase.dll
00007FFF6FA00000 - C:\Windows\System32\OLEAUT32.dll
00007FFF6FDB0000 - C:\Windows\System32\SHELL32.dll
00007FFF63FF0000 - C:\Windows\SYSTEM32\VERSION.dll
00007FFF69A20000 - C:\Windows\SYSTEM32\WTSAPI32.dll
00007FFF63BE0000 - C:\Windows\SYSTEM32\WINMM.dll
00007FFF6E890000 - C:\Windows\System32\CRYPT32.dll
00007FFF20540000 - C:\Windows\SYSTEM32\MSACM32.dll
00007FFF57F20000 - C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.685_none_faeca4db76168538\gdiplus.dll
00007FFF69770000 - C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\COMCTL32.dll
00007FFF56670000 - C:\Windows\SYSTEM32\USP10.dll
00007FFF60720000 - C:\Windows\SYSTEM32\MSIMG32.dll
00007FFF55230000 - C:\Windows\SYSTEM32\winmmbase.dll
00007FFF53400000 - C:\Windows\SYSTEM32\Secur32.dll
00007FFF6DAB0000 - C:\Windows\SYSTEM32\CRYPTBASE.DLL
00007FFF6DF80000 - C:\Windows\SYSTEM32\SSPICLI.DLL
00007FFF6EF90000 - C:\Windows\System32\IMM32.DLL
00007FFF6DCC0000 - C:\Windows\SYSTEM32\MSASN1.dll
00007FFF6E0D0000 - C:\Windows\System32\bcryptPrimitives.dll
00007FFF6C010000 - C:\Windows\SYSTEM32\dbghelp.dll
00007FFF6C220000 - C:\Windows\SYSTEM32\windows.storage.dll
00007FFF6DB40000 - C:\Windows\SYSTEM32\Wldp.dll
00007FFF6FD00000 - C:\Windows\System32\SHCORE.dll
00007FFF6EF30000 - C:\Windows\System32\shlwapi.dll
00007FFF6E000000 - C:\Windows\SYSTEM32\profapi.dll
00007FFF6C9D0000 - C:\Windows\SYSTEM32\kernel.appcore.dll
00007FFF6E7B0000 - C:\Windows\System32\bcrypt.dll
00007FFF6B640000 - C:\Windows\system32\uxtheme.dll
00007FFF63D70000 - C:\Windows\SYSTEM32\cryptnet.dll
00007FFF6EA90000 - C:\Windows\System32\imagehlp.dll
00007FFF6DA90000 - C:\Windows\SYSTEM32\CRYPTSP.dll
00007FFF6D1E0000 - C:\Windows\system32\rsaenh.dll
00007FFF64010000 - C:\Windows\SYSTEM32\dxcore.dll
00007FFF6E420000 - C:\Windows\System32\cfgmgr32.dll
00007FFF23690000 - C:\Windows\system32\nvspcap64.dll
00007FFF6CE10000 - C:\Windows\SYSTEM32\ntmarta.dll
00007FFF6C9F0000 - C:\Windows\SYSTEM32\gpapi.dll
00007FFF62A40000 - C:\Windows\SYSTEM32\DINPUT8.dll
00007FFF5EAE0000 - C:\Windows\SYSTEM32\inputhost.dll
00007FFF6A810000 - C:\Windows\SYSTEM32\wintypes.dll
00007FFF6B320000 - C:\Windows\SYSTEM32\CoreMessaging.dll
00007FFF69820000 - C:\Windows\SYSTEM32\PROPSYS.dll
00007FFF6AFC0000 - C:\Windows\SYSTEM32\CoreUIComponents.dll
00007FFF60FA0000 - C:\Windows\SYSTEM32\nvapi64.dll
00007FFF6EAB0000 - C:\Windows\System32\SETUPAPI.DLL
00007FFF6F8D0000 - C:\Windows\System32\clbcatq.dll
00007FFF43B50000 - C:\Windows\system32\napinsp.dll
00007FFF414B0000 - C:\Windows\system32\pnrpnsp.dll
00007FFF68840000 - C:\Windows\system32\wshbth.dll
00007FFF69230000 - C:\Windows\system32\NLAapi.dll
00007FFF6D560000 - C:\Windows\SYSTEM32\IPHLPAPI.DLL
00007FFF6D8C0000 - C:\Windows\System32\mswsock.dll
00007FFF6D5A0000 - C:\Windows\SYSTEM32\DNSAPI.dll
00007FFF6EF20000 - C:\Windows\System32\NSI.dll
00007FFF41490000 - C:\Windows\System32\winrnr.dll
00007FFF63DC0000 - C:\Windows\System32\fwpuclnt.dll
00007FFF64000000 - C:\Windows\System32\rasadhlp.dll
00007FFF70830000 - C:\Windows\System32\msctf.dll
00007FFF5E9E0000 - C:\Windows\SYSTEM32\textinputframework.dll
00007FFF674E0000 - C:\Windows\SYSTEM32\WindowsCodecs.dll
00007FFF5F4C0000 - C:\Windows\SYSTEM32\TextShaping.dll

*--> Game Context <--*
MapId: 0
Flags: 0x241
ElapsedTime: 00:00:01

*--> World State <--*
<WorldState />

[DbgHelp.dll is C:\Windows\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.19041.488 (64/32-bit compatible)]

*--> ClientContextThreadProc Thread 0x1e58 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff7`b7f23e2c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b7f23eab 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b88d95cd 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b82332bd 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b8231807 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b818c50b 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b818b012 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b7f01177 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b80f4c6e 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b80f2eac 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b80f2b29 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b80f41bf 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b80f252c 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b7f1a9c1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ff7`b80ab5f9 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007fff`6efd7034 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007fff`709dd0d1 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=0000000000000001 rbx=00007ff7b95fcd38 rcx=00000072adffe750
rdx=00007ff7b95fcd38 rsi=000000000000003a rdi=00000072adffec80
rip=00007ff7b7f23dcd rsp=00000072adffe6f0 rbp=00000072adfff000
 r8=000000000000003a  r9=00007ff7b7d90000 r10=00000072adffe976
r11=00000072adffebb0 r12=0000000000000002 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

rbx-32 00007FF7B95FCD18  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rbx +0 00007FF7B95FCD38  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rbx+32 00007FF7B95FCD58  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
rcx-32 00000072ADFFE730  00007ff7`b7f23dcd 00000072`adffe6f0 00000072`adfff000 00000007`0000002d 
rcx +0 00000072ADFFE750  00000000`00000020 00000000`ffffffff 00000000`00000000 00000072`adffe976 
rcx+32 00000072ADFFE770  00000200`00000002 00007fff`709b0c02 00009f80`0010000f 0053002b`002b0033 
rdx-32 00007FF7B95FCD18  62655761`6e657241 6e657265`686f435c 74477741`5c744774 00000000`7070632e 
rdx +0 00007FF7B95FCD38  2e2e5c2e`2e5c2e2e 5c656e69`676e455c 62655761`6e657241 6e657265`686f435c 
rdx+32 00007FF7B95FCD58  6f437741`5c695574 00000070`70632e68 73676e69`74746573 6d616e65`6c69662e 
 r9 +0 00007FF7B7D90000  00000003`00905a4d 0000ffff`00000004 00000000`000000b8 00000000`00000040 
 r9+32 00007FF7B7D90020  00000000`00000000 00000000`00000000 00000000`00000000 00000178`00000000 

*--> Code <--*
00007ff7`b7f23dad  488bf941 8bf0488d 0da6e7d1 01488bda H..A..H......H..
00007ff7`b7f23dbd  e88e70fe ff488d4c 2460ff15 6ba54001 ..p..H.L$`..k.@.
00007ff7`b7f23dcd  488b8424 58010000 4c8d0584 d5410148 H..$X...L....A.H
00007ff7`b7f23ddd  89442440 4885db48 8b8424f8 00000044 .D$@H..H..$....D
00007ff7`b7f23ded  8bce4889 4424484c 0f45c348 8b842400 ..H.D$HL.E.H..$.
00007ff7`b7f23dfd  01000048 8bd74889 44245033 c9488d44 ...H..H.D$P3.H.D

*--> Stack <--*
00000072`adffe6f0  00000072`adffecad 00000000`00000200 00000000`0000002d 00000000`00000000 ....r...........-...............
00000072`adffe710  00000072`adffe730 00000072`adffe750 00000000`00000000 00000072`adffe6d8 0...r...P...r...............r...
00000072`adffe730  00007ff7`b7f23dcd 00000072`adffe6f0 00000072`adfff000 00000007`0000002d .=..........r.......r...-.......
00000072`adffe750  00000000`00000020 00000000`ffffffff 00000000`00000000 00000072`adffe976  .......................v...r...
00000072`adffe770  00000200`00000002 00007fff`709b0c02 00009f80`0010000f 0053002b`002b0033 ...........p............3.+.+.S.
00000072`adffe790  00000202`002b002b 00000000`00000000 00000240`00000000 00007fff`53350100 +.+.................@.....5S....
00000072`adffe7b0  00000240`7734bc50 00000240`6e8f0000 00000000`00000000 00000000`00000001 P.4w@......n@...................
00000072`adffe7d0  00000072`adffe750 00007ff7`b95fcd38 00007ff7`b95fcd38 00000072`adffe6f0 P...r...8._.....8._.........r...
00000072`adffe7f0  00000072`adfff000 00000000`0000003a 00000072`adffec80 00000000`0000003a ....r...:...........r...:.......
00000072`adffe810  00007ff7`b7d90000 00000072`adffe976 00000072`adffebb0 00000000`00000002 ........v...r.......r...........
00000072`adffe830  00000000`00000000 00000000`00000000 00000000`00000000 00007ff7`b7f23dcd .........................=......
00000072`adffe850  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00009f80 ................................
00000072`adffe870  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe890  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe8b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe8d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe8f0  00000000`00000000 00000000`00000000 746e6572`65686f43 6c6c642e`34364955 ................CoherentUI64.dll
00000072`adffe910  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe930  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe950  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe970  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe990  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe9b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe9d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000072`adffe9f0  00000240`7734f6e0 00000000`00000008 00000000`00000000 00000240`7734b6b0 ..4w@.....................4w@...
00000072`adffea10  00000000`00000004 00000000`1808ecfc 00000240`7734f6e0 00007fff`02000002 ..................4w@...........
00000072`adffea30  00000000`00000004 00000240`7734b6b0 00000000`00000100 00000240`6e8f0150 ..........4w@...........P..n@...
00000072`adffea50  00000000`00000000 00000000`00000001 00000000`00000038 00000240`6e8f0000 ................8..........n@...
00000072`adffea70  00000000`00000000 00007fff`709a0df1 00000240`6e8f02e8 00000072`adffed80 ...........p.......n@.......r...
00000072`adffea90  00000000`00000001 00000000`00000038 00000000`00000100 00000240`6e8f0150 ........8...............P..n@...
00000072`adffeab0  00000240`70d07950 00007fff`709a48ea 00000240`6e8f0000 00000000`00000000 Py.p@....H.p.......n@...........
00000072`adffead0  00000240`70d07940 00000000`00000080 00000072`00000038 00000000`00000038 @y.p@...........8...r...8.......

*--> Error Logs <--*
20:54:29Z Coherent DLL load filepath: E:\Guild Wars 2\bin64\CoherentUI64.dll
Crashed at 20:54:29Z

**Comment by megai2** [comment]
Try installing [MSVC](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by DeckStarg** [comment]
OMW I did that about 10min ago (before seeing this reply) and it works now.
I also did it using Arky's method instead of the addon.

Thank you

**Comment by megai2** [comment]
Closing issue then

**Comment by DeckStarg** [comment]
No problem
