### ISSUE TITLE
 RC3 will lead to complete system restart

### ISSUE THREAD

**Issue by MasterJam-ai** [megai2/d912pxy#331]
with newest RC3 GW2 is crashing after approx. 10 minutes of gaming leading to a complete system restart.

**Comment by megai2** [comment]
Without any logs i can't say what is going on.
But i suggest checking system temperatures if system restarts.

**Comment by MasterJam-ai** [comment]
temperatures were fine...after reverting back to previous version of initial 2.4 it's working fine again. Sorry I will try to gather some log files, but today I had no time and could only provide the written feedback. I will take a look into this tomorrow.
As always: cheers mate ;-)

**Comment by megai2** [comment]
@MasterJam-ai problem still here?

**Comment by MasterJam-ai** [comment]
sry it took a while 
Still not fixed also not with 2.4.1.
Game totally crashed and whole system restarts
[log.txt](https://github.com/megai2/d912pxy/files/6002468/log.txt)

**Comment by Squall-Leonhart** [comment]
This is a stability issue with your computer, perform standard hardware diagnostics and consult with other AMD Ryzen users.

**Comment by megai2** [comment]
Log simply ended without any errors: i.e. no error is detected at dx12 side or inside proxy code.
I suggest that system crashes due to some kind of hardware/driver problems.
In v2.4 GPU work submission changed to properly keep GPU at non-idle clocks and 100% busy if CPU side allows that.
Check that power supply is ok, nothing is bad with GPU placement in slot, GPU cooling and whole system OC if there is any.

**Comment by MasterJam-ai** [comment]
The system is rock solid on every other aspect of usage.Only recent D912pxy is causing this.So I will stay with older version which is running smooth as it's not worth the hussle to search for bug which might be non-existent in the end. The only thing I will do once is to remove the OC of my GPU. But thanks anyways for your great support. Much appreciated.Am 21.02.2021 09:03 schrieb megai2 <notifications@github.com>:
Log simply ended without any errors: i.e. no error is detected at dx12 side or inside proxy code.
I suggest that system crashes due to some kind of hardware/driver problems.
In v2.4 GPU work submission changed to properly keep GPU at non-idle clocks and 100% busy if CPU side allows that.
Check that power supply is ok, nothing is bad with GPU placement in slot, GPU cooling and whole system OC if there is any.

**Comment by Squall-Leonhart** [comment]
> The system is rock solid on every other aspect of usage.

And?

Seems you need a crash course in system Hardware diagnostics.

**Comment by megai2** [comment]
@MasterJam-ai let me know if keeping OC down helps.

**Comment by megai2** [comment]
added a relaxed submission option, should solve your problem, but will not utilize GPU for 100%

[compat]
relaxed_gpu_submission=1

**Comment by MasterJam-ai** [comment]
I can cofirm that with 2.4.2 this issue is solved.
Without changing anything in the actual d912pxy settings (standard installation) nor in my system (even keeping OC)

**Comment by megai2** [comment]
Maybe driver updates?
