### ISSUE TITLE
Some areas not showing

### ISSUE THREAD

**Issue by Mirevea** [megai2/d912pxy#332]
**Describe the bug**
Some area of effect are not appearing. For example, in the Underground fractal, the red AoE indicators from the turrets you have to run through with a held item are not showing. Similar to that, in Thunderhead Peaks, in one of the hearts, the indicator of where a skirt is throwing item you must grab is not showing
![imagen](https://user-images.githubusercontent.com/77887732/106458464-b8987700-6490-11eb-8adc-775d46e1fde6.png)

**To Reproduce**
Seems like that areas are not appearing cause a bug.

1. Run game
2. Set graphics settings to high / very high
3. Head to volcanic fractal / Thunderhead Peaks location
4. Do this: -> Go to wherever place with a mechanic that requires to check Areas on the floor

**Expected behavior**
For example, in thunderhead Peaks, an area should appear indicating where the Item will be dropped by NPCs. In fractal the Area should indicate where the shoot of the turret will hit you.

**Screenshots**

**Standard information**

1. Windows 10 update ver
2. Hardware info: CPU, RAM, GPU -> i59600K // 16gb ram // RTX 3060
3. GPU Driver version (Updated Nvidia)
4. Version of d912pxy used (2.4 pre-release)
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist

**Additional context**

**Comment by megai2** [comment]
Looks fine for me.
Please share what gfx settings you use and a log file from d912pxy/log.txt

![изображение](https://user-images.githubusercontent.com/1693251/106487547-d29f7d00-64c3-11eb-9d8d-f410d3e7c514.png)

**Comment by Mirevea** [comment]
Hello megai! Sorry for delay, here are my gfx:
![imagen](https://user-images.githubusercontent.com/77887732/106529307-916e9380-64ea-11eb-88e5-1fb5cfba6210.png)
![imagen](https://user-images.githubusercontent.com/77887732/106529347-9cc1bf00-64ea-11eb-90aa-6f9831c81381.png)

Aand the log file -> (Some exceptions..)
[log.txt](https://github.com/megai2/d912pxy/files/5907390/log.txt)

**Comment by Mirevea** [comment]
Good morning megai2!
Time to add some new info, today the area of the skirrt now is visible, but the indicator of where a npc is throwing item you must grab still not showing:
![imagen](https://user-images.githubusercontent.com/77887732/106568619-cf43da00-6533-11eb-9cd7-e9490f02e621.png)

Another example that i found was in Vabbi, where the indicator of where the npc is throwing organs not showing either. It seems that that particular indicator / area is not visible regardless of location.
![imagen](https://user-images.githubusercontent.com/77887732/106569512-eb944680-6534-11eb-81b2-e82f9bd5609d.png)


log file of today -> 
[log.txt](https://github.com/megai2/d912pxy/files/5909543/log.txt)

**Comment by megai2** [comment]
Try using this values in config file
```
[mt]
dxc_threads = 0
pso_threads = 0
```

**Comment by Mirevea** [comment]
Hello!
I used them but still not area showing, btw.. the NPC does not do the animation throwing item.
![imagen](https://user-images.githubusercontent.com/77887732/106634477-1d7eca80-6580-11eb-8d12-d5d19914cb92.png)

Log file -> 
[log.txt](https://github.com/megai2/d912pxy/files/5912884/log.txt)

**Comment by Mirevea** [comment]
Another example.. flame walls on Wing 5 are not showing...
![imagen](https://user-images.githubusercontent.com/77887732/106806078-c6ecbb80-6667-11eb-91f4-79c52fa7120d.png)

**Comment by Mirevea** [comment]
Hello!
I just updated to your new release and the bug persist..

**Comment by megai2** [comment]
Do you use any other addons/overlays installed?

**Comment by Mirevea** [comment]
Nope, just this addon :(

**Comment by Mirevea** [comment]
Hello Megai2!
If it's usefull.. mines areas on wing3 aren't showing either..
![imagen](https://user-images.githubusercontent.com/77887732/107284381-03505b00-6a5e-11eb-8f0d-68d940611eab.png)

You need something more to investigate??

**Comment by megai2** [comment]
Still no idea what to do in order to reproduce this problem.

Did you make any changes in config file?
Maybe you own some rare item in game that bugs out render?

**Comment by Mirevea** [comment]
Morning Megai!
I'm using the Alrais config file, but i think i discovered the problem, now the areas are showing!
![imagen](https://user-images.githubusercontent.com/77887732/107756725-edc08700-6d24-11eb-8417-b6f600b804eb.png)

This option disabled all the areas, including the NPCs ones! 
Dunno if its inGame bug or got relation with the d912pxy.

That option disables too the flame walls, look ->
![imagen](https://user-images.githubusercontent.com/77887732/107758169-cc609a80-6d26-11eb-9147-5b62210b2c03.png)

Now i see them with the option disabled.

Do you think that its related with mod? or inGame bug?

**Comment by megai2** [comment]
@Mirevea i guess this is how this option should work - hide (i.e. don't render) AoE rings everywhere.
If it works same way without proxy - then this is not a bug, but a feature of game.

**Comment by megai2** [comment]
I guess problem is settled?

**Comment by Mirevea** [comment]
Hello!
Yes sure.
Thanks for the support!!
