### ISSUE TITLE
GPU cl execution error - Blade & Soul 64bit

### ISSUE THREAD

**Issue by ego0125** [megai2/d912pxy#333]
Hello,

I got GPU cl execution error continuously on 2.4rc3. It was OK on 2.3.1h2.

I tried TDR_10 and TDR_160, but it didn't help. Would you please advise how I can avoid the error?

52245 [ info ] swap chain | Window: A05A6 Width: 1280 Height: 768 Fullscreen: 0 Buffers: 2 Format: 21 
55D1B [ error ] GPU command list | GPU cl execution took 15071 ms time! Probably TDR crash 
565A7 [ info ] swap chain | Window: A05A6 Width: 3440 Height: 1440 Fullscreen: 0 Buffers: 2 Format: 21 
621B3 [ error ] GPU command list | GPU cl execution took 2917 ms time! Probably TDR crash 
63B65 [ error ] GPU command list | GPU cl execution took 6464 ms time! Probably TDR crash 
64578 [ error ] GPU command list | GPU cl execution took 2578 ms time! Probably TDR crash

**Comment by megai2** [comment]
Hi. Does it crash in the end or only makes spam in log?

**Comment by ego0125** [comment]
It crashed after a while(random).

**Comment by megai2** [comment]
Can you share a full log file and maybe some context of crash, for ex. did it crashed in loading screen or so?

**Comment by ego0125** [comment]
Here's the full log for last 7~8 hours. There was a crash one time on the day when I reported this, but no further crash since then.

[log.txt](https://github.com/megai2/d912pxy/files/5938423/log.txt)

**Comment by megai2** [comment]
Check that GPU is placed in PCI-E slot correctly and if there is any OC, that OC is stable.
If crashes are still here, i'll add a workaround to prevent this.

**Comment by ego0125** [comment]
GPU is placed correctly, and there's no OC. And, 2.4.1 is also same, 2.3.1 h2 is fine.

**Comment by megai2** [comment]
add this to config to avoid TDR if it still triggers by now

[compat]
relaxed_gpu_submission=1

(works only in latest build)
https://ci.appveyor.com/project/megai2/d912pxy/build/artifacts
