### ISSUE TITLE
Request: Enable running in fullscreen at user discretion

### ISSUE THREAD

**Issue by ECHOSUD** [megai2/d912pxy#334]
Based on instructions and authors notes while d912pxy may not run as intended when GW2 is fullscreen I still had very significant performance improvements with previous d912pxy builds with GW2 running fullscreen at 2048 by 1152.
The native resolution of my laptop is 4k and my gtx1060 struggles to run games at 4k or windowed fullscreen. I would very much appreciate the ability to continue using d912pxy in fullscreen understanding that I would be comprimising stability for performance.

I'm sorry if this isn't the place for feedback or requests.

**Comment by megai2** [comment]
I'll add workaround

**Comment by megai2** [comment]
Will be in 2.4.1
