### ISSUE TITLE
[QUESTION] Permanent hide d912pxy window on startup

### ISSUE THREAD

**Issue by TrYkeRm4N** [megai2/d912pxy#336]
Hi

First of all, thanks for your great work with this addon.

Is there any way to permament hide the screen that the addon shows when the game loads? I mean the one that you need to hit CTRL+ALT+N twice to hide. I try to see something into the config menu but my search was unsuccessfull.

Thanks in advance.

**Comment by megai2** [comment]
Added hide button in overlay
