### ISSUE TITLE
Ask for dll bitness on install

### ISSUE THREAD

**Issue by mirh** [megai2/d912pxy#337]
I get that people are here for GW2, but if Gw2-64.exe is not here, then you shouldn't automatically drop the x64 dll
(in fact, it's probably more likely 99% of times the 32-bit one will be required)

**Comment by Squall-Leonhart** [comment]
64bit is the majority of windows installs at this point, gw launcher automatically pulls down and uses the 64bit binary unless told otherwise.

**Comment by megai2** [comment]
Added an option in installer.

**Comment by mirh** [comment]
Thanks. 
And no, even in another 20 years the majority of d3d9 programs will still be be predominantly 32-bit.

**Comment by mirh** [comment]
I don't see it to be honest.

**Comment by megai2** [comment]
Live in 2.4.2 release

**Comment by mirh** [comment]
I'm not really sure burying it optionally inside "Use standard release? n" is the smartest choice, but whatever.
