### ISSUE TITLE
[Custom config] Need advice for GTX 1060 6GB

### ISSUE THREAD

**Issue by SebCorbin** [megai2/d912pxy#338]
I've been using this plugin for quite a while now and overall the quality is superb, but I'm experiencing lags during map changes or running around map (especially Lion's arch). I would like to know your (the community) configs because I can see using task manager that the GPU/RAM is not fully put to work

**Comment by darek2347** [comment]
I have 4gb vram 16gb ram

[pooling]
upload_alloc_step=64
upload_limit=128
upload_limit_big=128
vstream_alloc_step=64
vstream_alloc_step_big=64
vstream_limit=256
vstream_limit_big=256
surface_alloc_step=0
surface_limits=00003
lifetime=10000
host_va_reserve=37
keep_resident=1
[upload]
tex_async=5

I leave rest at default. In metas and cities I almost hit vram limit but that's with firefox open in background eating 700+ MB. You could increase upload_limit(_big), vstream_limit(_big) and surface_limits for more vram usage (surface_limits is a hex value btw). Also read more on wiki [here](https://github.com/megai2/d912pxy/wiki/Custom-configuration).

**Comment by SebCorbin** [comment]
Thanks a lot for your answer, that wiki page is quite another language for me. Anyway, I tweaked some settings but now my RAM (8GB) is almost always full, which settings affect RAM et which affect VRAM ?

**Comment by darek2347** [comment]
After some brief testing here's what I'd do

[pooling]
upload_alloc_step=64 
upload_limit=6144
upload_limit_big=6144
vstream_alloc_step=64
vstream_alloc_step_big=64
vstream_limit=6144
vstream_limit_big=6144
surface_alloc_step=0
surface_limits=00000
lifetime=6000
host_va_reserve=37
keep_resident=1

[cleanup]
period=6000
subsleep=50
soft_limit=2000
hard_limit=3000
after_reset_maid=3

[sdb]
precompile_limit=5000

[replay]
items_per_batch=10

[upload]
tex_async=5

[batching]
maxBatchesPerIFrame=4096

Leave rest at default.

Don't change "surface_limits" without 16gb ram, 4+gb vram. I think I've read the dev saying to keep "lifetime" and "period" the same value but I might be wrong. You could try lowering "subsleep" to 20-30. "replay_threads" can be set to 2-4 but it breaks Whisper of Jormag strike missions and possibly other things.

Also my config from first post isn't that good and I'll probably change it after some more testing.

**Comment by megai2** [comment]
Updated ready to use configs, but suggested here ones are close to them.

To reduce RAM usage better to keep 

[upload]
tex_async=0

and reduce either cleanup period with lifetime or cleanup soft & hard limit i.e

[pooling]
lifetime=6000

[cleanup]
period=3000

or 

[cleanup]
soft_limit=1000
hard_limit=2000

**Comment by SebCorbin** [comment]
Thanks a lot to both of you, I'll try that for a while!

**Comment by SebCorbin** [comment]
Works perfectly, closing :)
