### ISSUE TITLE
chain load order for reshade/arc

### ISSUE THREAD

**Issue by Deshke** [megai2/d912pxy#34]
as this is only a wrapper it should be possible to chain load Arc and reshade, question is what the steps for that would be
```
gw2 -> arc -> reshade ->  d912pxy 

```
the current way to chain load arc and reshade is to load arc first and then reshade

![image](https://user-images.githubusercontent.com/1473225/51799894-7b58d900-2227-11e9-9053-518f181cf8e3.png)

* d3d9 is arc
* d3d9_chainload is reshade

bhagawan69 did a thing for BGDM back in the day http://gw2bgdm.blogspot.com/p/faq.html

> 2.9 Can I have both ArcDps + BGDM Reshade/GemFx/SweetFx all together?
> 
> Yes! but since Arcdps doesn't support loading Reshade (see image above) you'll can only chain the DLL's in 1 way: Arc first -> Arc loads BGDM -> BGDM loads Reshade/etc.
> 
> The way to achieve that is done as per the below and us basically a combination of FAQ items 2.7/2.8:
> a. Place d3d9.dll that comes with Arc in the folder
> b. Rename the d3d9.dll that comes with BGDM to 'd3d9_chainload.dll'
> c. Rename the d3d9.dll that is installed by Reshade/SweetFx/GemFx  to 'Reshade64.dll'

@megai2 i think you've spoke to /u/deltaconnected already, question is how chain load these?

**Comment by megai2** [comment]
d912pxy should be loaded on the end of the chain, yes.

I think that reshade have no ability to chainload anything, so i can't help with this.

Basically you can do 
gw2 ->ArcDPS -> d912pxy 
by renaming d3d9.dll that comes with d912pxy to d3d9_chainload.dll

This way ArcDPS will chainload d912pxy, but on my tests it crashes in ArcDPS code.

I not yet contacted /u/deltaconnected, but ppl already asked him, he refused to do something by now.
When i made some changes to basic imgui implementation and test this out, i will contact him with that changes and maybe we will make things work.

**Comment by Deshke** [comment]
created a new ticket in https://github.com/04348/Gw2Hook/issues/10 so maybe @ebarjou has a idea

**Comment by megai2** [comment]
moved to #38
