### ISSUE TITLE
gw2 crash not sure what is the problem

### ISSUE THREAD

**Issue by knyvzx** [megai2/d912pxy#340]
*--> Crash <--*
OOM: Heap, bytes=1048672, 
App: Gw2-64.exe 
Pid: 13768
BaseAddr: 00007FF658A60000
ProgramId: 101
Build: 111532
When: 2021-02-18T06:30:05Z 2021-02-17T22:30:05-08:00
Uptime:   0 days  4:02:45
Flags: 0
DumpFile: Crash.dmp

*--> System <--*
Name: fe687ec8
IpAddr: 10.0.0.105
Processors: 16 [GenuineIntel:6:5:4]
OSVersion: Windows 10.0 (64 bit)

*--> System Memory <--*
Physical:  3412MB/16056MB  21%
Paged:        0MB/22200MB  0%
Virtual:  134066659MB/134217727MB  3%
Load: 78%
CommitTotal:  22200MB
CommitLimit:  22200MB
CommitPeak:   22200MB
SystemCache:   4367MB
HandleCount:  108695
ProcessCount:   193
ThreadCount:   2886

*--> Process Memory <--*
Private:         13411MB
WorkingSet:      5529MB
PeakWorkingSet:  7562MB
PageFaults:  37871248

*--> Memory Category Usage (Inclusive) <--*
[Category]              [Size(MB)]  [Count]     
Root                    2191.62     2571990     
VRAM                    1846.67     32794       
Programmer Data         1212.96     586173      
Uncategorized           839.71      1908704     
VRAM - Character Tex    777.20      2089        
Engine                  691.28      308437      
Model-Programmer        478.20      85709       
Model Granny            468.92      36070       
Game                    331.94      179030      
VRAM - Prop Geo         258.23      1778        
Content                 234.65      60147       
VRAM - Composite Tex    164.17      335         
Collections             135.85      14531       
Dictionary              131.58      4118        
Gr                      131.04      155424      
VRAM - Prop Tex         109.81      321         
Art Assets              101.92      34022       
VRAM - World Map Tex    81.94       413         
VRAM - Gr Postproc      79.39       20          
VRAM - UI Textures      78.91       2509        
Character Models        75.20       11335       
Composite Models        73.73       3088        
Text                    72.68       8834        
Gr Umbra                61.41       6470        

*--> Memory Category Usage (Exclusive) <--*
[Category]                 [Size(MB)]  [Count]     
Uncategorized              839.71      1908704     
VRAM - Character Tex       777.20      2089        
Model Granny               468.92      36070       
VRAM - Prop Geo            258.23      1778        
Content                    234.65      60147       
VRAM - Composite Tex       164.17      335         
Dictionary                 131.58      4118        
VRAM - Prop Tex            109.81      321         
VRAM - World Map Tex       81.94       413         
VRAM - Gr Postproc         79.39       20          
VRAM - UI Textures         78.91       2509        
Text                       72.68       8834        
Gr Umbra                   61.41       6470        
Map Zone                   53.64       12490       
VRAM - Terrain Tex         53.33       49          
VRAM - Effect Texture      52.89       269         
Composite Tex Pool         43.85       91          
VRAM - DDI Shader          37.21       22962       
VRAM - DirectX Geo Buffers 30.56       1520        
Composite Packfile         29.54       736         
Archive                    28.83       54          
Gr Material                23.22       50189       
VRAM - Composite Geo       22.57       128         
VRAM - Character Geo       19.33       92          

*--> DllList <--*
00007FF658A60000 - K:\Guild Wars 2\Guild Wars 2\Gw2-64.exe
00007FFED0730000 - C:\WINDOWS\SYSTEM32\ntdll.dll
00007FFECE790000 - C:\WINDOWS\System32\KERNEL32.DLL
00007FFECE3F0000 - C:\WINDOWS\System32\KERNELBASE.dll
00007FFECFF30000 - C:\WINDOWS\System32\USER32.dll
00007FFECDF80000 - C:\WINDOWS\System32\win32u.dll
00007FFED0540000 - C:\WINDOWS\System32\GDI32.dll
00007FFECDE70000 - C:\WINDOWS\System32\gdi32full.dll
00007FFECE6F0000 - C:\WINDOWS\System32\msvcp_win.dll
00007FFECE010000 - C:\WINDOWS\System32\ucrtbase.dll
00007FFECF480000 - C:\WINDOWS\System32\ADVAPI32.dll
00007FFECF3E0000 - C:\WINDOWS\System32\msvcrt.dll
00007FFECF240000 - C:\WINDOWS\System32\sechost.dll
00007FFECF6B0000 - C:\WINDOWS\System32\RPCRT4.dll
00007FFED0680000 - C:\WINDOWS\System32\WS2_32.dll
00007FFECDFB0000 - C:\WINDOWS\System32\WINTRUST.dll
00007FFECF2E0000 - C:\WINDOWS\System32\PSAPI.DLL
00007FFEC7C50000 - C:\WINDOWS\SYSTEM32\VERSION.dll
00007FFEC92F0000 - C:\WINDOWS\SYSTEM32\WTSAPI32.dll
00007FFECEE90000 - C:\WINDOWS\System32\ole32.dll
00007FFEBFC90000 - C:\WINDOWS\SYSTEM32\WINMM.dll
00007FFECEB30000 - C:\WINDOWS\System32\combase.dll
00007FFECE8B0000 - C:\WINDOWS\System32\OLEAUT32.dll
00007FFECF7E0000 - C:\WINDOWS\System32\SHELL32.dll
00007FFECE290000 - C:\WINDOWS\System32\CRYPT32.dll
00007FFE8C050000 - C:\WINDOWS\SYSTEM32\MSACM32.dll
00007FFEB9D70000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.789_none_faf0a7e97612e7bb\gdiplus.dll
00007FFEAA4C0000 - C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\COMCTL32.dll
00007FFEB7E00000 - C:\WINDOWS\SYSTEM32\winmmbase.dll
00007FFEB9CA0000 - C:\WINDOWS\SYSTEM32\USP10.dll
00007FFEABA10000 - C:\WINDOWS\SYSTEM32\MSIMG32.dll
00007FFEB3970000 - C:\WINDOWS\SYSTEM32\Secur32.dll
00007FFECD840000 - C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
00007FFECDD20000 - C:\WINDOWS\SYSTEM32\SSPICLI.DLL
00007FFECF3A0000 - C:\WINDOWS\System32\IMM32.DLL
00007FFECDA50000 - C:\WINDOWS\SYSTEM32\MSASN1.dll
00007FFECE1C0000 - C:\WINDOWS\System32\bcryptPrimitives.dll
00007FFECBB00000 - C:\WINDOWS\SYSTEM32\dbghelp.dll
00007FFECBFC0000 - C:\WINDOWS\SYSTEM32\windows.storage.dll
00007FFECD8D0000 - C:\WINDOWS\SYSTEM32\Wldp.dll
00007FFECF0A0000 - C:\WINDOWS\System32\SHCORE.dll
00007FFECE850000 - C:\WINDOWS\System32\shlwapi.dll
00007FFECDDA0000 - C:\WINDOWS\SYSTEM32\profapi.dll
00007FFECC790000 - C:\WINDOWS\SYSTEM32\kernel.appcore.dll
00007FFECE6C0000 - C:\WINDOWS\System32\bcrypt.dll
00007FFECB450000 - C:\WINDOWS\system32\uxtheme.dll
00007FFEC7C10000 - C:\WINDOWS\SYSTEM32\cryptnet.dll
00007FFECF2F0000 - C:\WINDOWS\System32\imagehlp.dll
00007FFECD820000 - C:\WINDOWS\SYSTEM32\CRYPTSP.dll
00007FFECCF80000 - C:\WINDOWS\system32\rsaenh.dll
00007FFEC4F70000 - C:\WINDOWS\SYSTEM32\dxcore.dll
00007FFECE240000 - C:\WINDOWS\System32\cfgmgr32.dll
00007FFE87EB0000 - C:\WINDOWS\system32\nvspcap64.dll
00007FFECCBB0000 - C:\WINDOWS\SYSTEM32\ntmarta.dll
00007FFECC760000 - C:\WINDOWS\SYSTEM32\gpapi.dll
00007FFED0570000 - C:\WINDOWS\System32\clbcatq.dll
00007FFEA55C0000 - C:\WINDOWS\system32\napinsp.dll
00007FFEA55A0000 - C:\WINDOWS\system32\pnrpnsp.dll
00007FFEC8C50000 - C:\WINDOWS\system32\wshbth.dll
00007FFEC9660000 - C:\WINDOWS\system32\NLAapi.dll
00007FFECD2F0000 - C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
00007FFECD650000 - C:\WINDOWS\System32\mswsock.dll
00007FFECD330000 - C:\WINDOWS\SYSTEM32\DNSAPI.dll
00007FFECF3D0000 - C:\WINDOWS\System32\NSI.dll
00007FFEA5580000 - C:\WINDOWS\System32\winrnr.dll
00007FFEBE650000 - C:\WINDOWS\System32\fwpuclnt.dll
00007FFEBE280000 - C:\Windows\System32\rasadhlp.dll
00007FFECF530000 - C:\WINDOWS\System32\msctf.dll
00007FFEB4550000 - C:\WINDOWS\SYSTEM32\textinputframework.dll
00007FFECAC70000 - C:\WINDOWS\System32\CoreUIComponents.dll
00007FFECAFD0000 - C:\WINDOWS\System32\CoreMessaging.dll
00007FFECA5A0000 - C:\WINDOWS\SYSTEM32\wintypes.dll
00007FFEC7130000 - C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
00007FFEA9390000 - C:\WINDOWS\SYSTEM32\TextShaping.dll
00007FFEAF610000 - K:\Guild Wars 2\Guild Wars 2\bin64\CoherentUI64.dll
00007FFEAD090000 - K:\Guild Wars 2\Guild Wars 2\bin64\d3d9.dll
00007FFECC7B0000 - C:\WINDOWS\SYSTEM32\dxgi.dll
00007FFEC8B10000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
00007FFEBBFD0000 - C:\WINDOWS\SYSTEM32\MSVCP140.dll
00007FFEBBFB0000 - C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
00007FFEC7D90000 - C:\WINDOWS\SYSTEM32\WINNSI.DLL
00007FFEC7900000 - C:\WINDOWS\SYSTEM32\d3d12.dll
00007FFEC9B80000 - C:\WINDOWS\SYSTEM32\d3dcompiler_47.dll
00007FFEB13C0000 - C:\WINDOWS\system32\d3d9.dll
00007FFECB6B0000 - C:\WINDOWS\SYSTEM32\dwmapi.dll
00007FFECDC40000 - C:\WINDOWS\SYSTEM32\DPAPI.dll
00007FFEC4E40000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_aba80042aca9c3c9\nvldumdx.dll
00007FFE8FF10000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_aba80042aca9c3c9\nvd3dumx.dll
00007FFEC4740000 - C:\WINDOWS\SYSTEM32\nvapi64.dll
00007FFED00D0000 - C:\WINDOWS\System32\SETUPAPI.DLL
00007FFECCC60000 - C:\WINDOWS\SYSTEM32\WINSTA.dll
00007FFEA3D60000 - C:\WINDOWS\SYSTEM32\D3D12Core.dll
00007FFE82A10000 - C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_aba80042aca9c3c9\nvwgf2umx.dll
00007FFEC77D0000 - C:\WINDOWS\SYSTEM32\D3DSCache.dll
00007FFECDD60000 - C:\WINDOWS\SYSTEM32\USERENV.dll
00007FFEC7510000 - C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
00007FFECA700000 - C:\WINDOWS\SYSTEM32\dcomp.dll
00007FFEC7DA0000 - C:\WINDOWS\System32\MMDevApi.dll
00007FFECDC10000 - C:\WINDOWS\System32\DEVOBJ.dll
00007FFE879B0000 - C:\WINDOWS\SYSTEM32\wdmaud.drv
00007FFEA7260000 - C:\WINDOWS\SYSTEM32\ksuser.dll
00007FFEC8170000 - C:\WINDOWS\SYSTEM32\AVRT.dll
00007FFEC7E30000 - C:\WINDOWS\SYSTEM32\AUDIOSES.DLL
00007FFECD460000 - C:\WINDOWS\SYSTEM32\powrprof.dll
00007FFECD2D0000 - C:\WINDOWS\SYSTEM32\UMPDC.dll
00007FFEA6F70000 - C:\WINDOWS\SYSTEM32\msacm32.drv
00007FFEA6E10000 - C:\WINDOWS\SYSTEM32\midimap.dll
00007FFECB5C0000 - C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll
0000020C3DF40000 - C:\Program Files\Logitech Gaming Software\SDK\LCD\x64\LgLcdApi.dll
00007FFEA3B80000 - C:\Users\pikab\AppData\Roaming\discord\0.0.309\modules\discord_hook\2e1ff455c11\DiscordHook64.dll
00007FFEC6C40000 - C:\WINDOWS\SYSTEM32\mscms.dll
00007FFEC6D80000 - C:\WINDOWS\SYSTEM32\ColorAdapterClient.dll
00007FFEC5750000 - C:\WINDOWS\SYSTEM32\icm32.dll
00007FFEAD2A0000 - C:\WINDOWS\SYSTEM32\dxilconv.dll
00007FFEB9950000 - C:\Users\pikab\AppData\Local\Temp\E6223622-1658-4A83-8AE4-AF9C5808A7CB\bink2w64.dll
00007FFEB9600000 - C:\WINDOWS\SYSTEM32\DSOUND.DLL
00007FFEABFD0000 - C:\Windows\System32\Windows.UI.dll
00007FFEC7CE0000 - C:\Windows\System32\WindowManagementAPI.dll
00007FFEB1F20000 - C:\Windows\System32\InputHost.dll
00007FFEC93B0000 - C:\Windows\System32\PROPSYS.dll

[DbgHelp.dll is C:\WINDOWS\SYSTEM32\dbghelp.dll]
[DbgHelp.dll version 10.0.19041.804 (64/32-bit compatible)]

*-->  Thread 0x48f8 <--*

*--> Trace <--*
Pc                Rt                : Args
00007ff6`58bf442b 00007ff6`58be944b : 00000000`00000000 00000000`000000a8 00007ff6`5a0120f8 00000000`00100060 
00007ff6`58be944b 00007ff6`58cd7255 : 00000000`00100060 0000020c`60f63338 0000020c`5a20a5e8 00007ff6`35545844 
00007ff6`58cd7255 00007ff6`58cd6d20 : 00000064`b52ffb30 00000000`00000001 00000000`0000001d 00000000`0000fffc 
00007ff6`58cd6d20 00007ff6`58c017eb : 00000000`00000001 00000000`00000000 00000000`00000003 0000020d`3e8edb48 
00007ff6`58c017eb 00007ff6`58c0147e : 00000000`58455441 0000020c`5a20a5b0 00000000`00000000 00000000`00000000 
00007ff6`58c0147e 00007ff6`58d34741 : 0000020e`29d7dd20 0000020c`60f18f90 00000000`00000000 00000000`00000000 
00007ff6`58d34741 00007ff6`58d3411c : 0000020c`5c06b760 00000064`b52ffca9 00000000`0000fff4 00000000`000c9ae8 
00007ff6`58d3411c 00007ff6`596cf730 : a6a9020c`00000000 0000020d`d91a6d78 00000000`00000000 0000020d`d91a6d50 
00007ff6`596cf730 00007ff6`58d4900f : 0000020d`d91a6d50 00000000`00000000 00007ff6`5a956d50 00000000`000001fc 
00007ff6`58d4900f 00007ff6`58d49e8c : 00000000`00000000 0000020d`d91a6d50 0000020d`ddd15060 00000000`00000000 
00007ff6`58d49e8c 00007ffe`ce7a7034 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`ce7a7034 00007ffe`d077d241 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 
00007ffe`d077d241 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 

*--> Thread registers <--*
rax=000000003f800000 rbx=0000000000000000 rcx=0000000000000000
rdx=000000003f800000 rsi=00000064b52ffa10 rdi=0000000000000005
rip=00007ff658bf442b rsp=00000064b52ff470 rbp=0000000000000000
 r8=0000000000000000  r9=3f80000000000000 r10=000000003f800000
r11=0000000000000000 r12=0000000000000008 r13=0000000000000060
r14=0000000000000000 r15=000000000000000c
cs=0033 ss=002b ds=002b es=002b fs=0053 gs=002b efl=00000202

*--> Code <--*
00007ff6`58bf440b  85c00f85 91000000 ff15cfc1 40014889 ............@.H.
00007ff6`58bf441b  056006d2 01488d4c 2460ff15 0dbf4001 .`...H.L$`....@.
00007ff6`58bf442b  488b8424 58010000 4c8d0546 f0410148 H..$X...L..F.A.H
00007ff6`58bf443b  89442440 4885ff48 8b8424f8 00000044 .D$@H..H..$....D
00007ff6`58bf444b  8bcd4889 4424484c 0f45c748 8b842400 ..H.D$HL.E.H..$.
00007ff6`58bf445b  01000048 8bd64889 4424508b cb488d44 ...H..H.D$P..H.D

*--> Stack <--*
00000064`b52ff470  00000064`b52ffa23 00000000`00000040 00000000`00000013 00000000`00000000 #./.d...@.......................
00000064`b52ff490  00000064`b52ff4b0 00000064`b52ff4d0 00000000`00000000 00000064`b52ff458 ../.d...../.d...........X./.d...
00000064`b52ff4b0  00007ff6`58bf442b 00000064`b52ff470 00000000`00000000 00000007`00000013 +D.X....p./.d...................
00000064`b52ff4d0  00000000`00000000 00000000`fffffffa 00000000`00000000 00000064`b52ff6f1 ........................../.d...
00000064`b52ff4f0  00007f00`00000007 00000097`000002a0 00001fbf`0010000f 0053002b`002b0033 ........................3.+.+.S.
00000064`b52ff510  00000246`002b002b 00007ff6`58d4f85c 00000064`b52ffc90 0000020e`8ce12690 +.+.F...\..X....../.d....&......
00000064`b52ff530  00000000`00000004 00000000`00000030 00000064`00000004 ffffffff`fffffffe ........0...........d...........
00000064`b52ff550  00000064`b52ff4d0 00000000`00000000 00000000`00000005 00000064`b52ff470 ../.d...................p./.d...
00000064`b52ff570  00000000`00000000 00000064`b52ffa10 00007ff6`5a012108 00007ff6`5a012108 ........../.d....!.Z.....!.Z....
00000064`b52ff590  00000000`00000000 00000064`b52ff6f1 00000064`b52ff930 00000000`00000008 ........../.d...0./.d...........
00000064`b52ff5b0  00000000`00000060 00000000`00000000 00000000`0000000c 00007ff6`58bf442b `.......................+D.X....
00000064`b52ff5d0  00000000`0000027f 00000000`00000000 00000000`00000000 0000ffff`00001fbf ................................
00000064`b52ff5f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff610  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff630  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff650  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff670  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff690  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff6b0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff6d0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff6f0  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff710  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff730  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff750  00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 ................................
00000064`b52ff770  00000000`00000000 00007ffe`d0776196 00007ff6`00000000 0000020c`5a40ef40 .........aw.............@.@Z....
00000064`b52ff790  00000000`00000000 0000020c`5a3d0000 0000020c`5a3d0468 00000000`00020080 ..........=Z....h.=Z............
00000064`b52ff7b0  00000000`00002210 0000020c`5a3d0e70 00000064`e1000dec 00000000`00000000 ."......p.=Z........d...........
00000064`b52ff7d0  00000000`00000000 00000000`00002020 00000000`00002010 00000000`00000202 ........  ....... ..............
00000064`b52ff7f0  00000000`00000000 00000064`b52ff8c9 0000020c`5a200000 00007ffe`d0746f9c ........../.d..... Z.....ot.....
00000064`b52ff810  0000020c`5a3d0000 00007ffe`d07479db 00000000`000f012d 00000000`000000d9 ..=Z.....yt.....-...............
00000064`b52ff830  0000020d`2f91f750 00000000`e1000dec 00000000`00000002 00007ffe`d07479db P../.....................yt.....
00000064`b52ff850  00000000`00000000 00000000`00000000 00000000`00100080 00000000`00100070 ........................p.......

*--> Error Logs <--*
ontent is referencing a propID that doesn't exist propId='1924002649382879764'
06:25:02Z Texture '0x03539b' dimensions too small
06:25:02Z Loading '0x03539b' texture failed
06:25:03Z Texture missing mip chain: 0x1a1ed9
06:25:03Z Texture missing mip chain: 0x1a1edb
06:25:03Z Model '0x22e310': Permutation 'stoweda' not found, auto selecting permutation
06:25:13Z Texture missing mip chain: 0x0f8c78
06:25:22Z Texture missing mip chain: 0x193de1
06:25:22Z Texture missing mip chain: 0x193de2
06:25:22Z Texture missing mip chain: 0x1a1eda
06:25:25Z Model '0x22e310': Permutation 'stoweda' not found, auto selecting permutation
06:25:37Z Model '0x22e310': Permutation 'stoweda' not found, auto selecting permutation
06:25:42Z Texture missing mip chain: 0x19d407
06:25:42Z Texture missing mip chain: 0x19d40d
06:25:42Z Texture '0x213587' dimensions too small
06:25:42Z Loading '0x213587' texture failed
06:25:42Z Texture '0x213588' dimensions too small
06:25:42Z Loading '0x213588' texture failed
06:25:44Z Texture missing mip chain: 0x19d40b
06:25:44Z Texture missing mip chain: 0x19d40c
06:26:41Z Texture '0x213593' dimensions too small
06:26:41Z Loading '0x213593' texture failed
06:26:41Z Texture '0x213594' dimensions too small
06:26:41Z Loading '0x213594' texture failed
06:26:56Z Model '0x22e310': Permutation 'stoweda' not found, auto selecting permutation
06:26:57Z Content is referencing a propID that doesn't exist propId='1972964328275477224'
06:27:53Z Couldn't find projectile effect for skill 'soUQE.mxnTo'
06:28:50Z Model '0x0e617c': Permutation 'sword' not found, auto selecting permutation
06:28:51Z Couldn't find projectile effect for skill 'xYDfZ.f0qXr'
06:28:52Z Texture missing mip chain: 0x193de0
06:28:52Z Texture missing mip chain: 0x193de1
06:28:52Z Texture missing mip chain: 0x193de2
06:28:52Z Texture missing mip chain: 0x1a1eda
06:29:23Z Couldn't find projectile effect for skill 'soUQE.mxnTo'
06:29:53Z Texture missing mip chain: 0x19d40b
06:29:53Z Texture missing mip chain: 0x19d40c
Crashed at 06:30:08Z

*--> DirectX Device Info <--*
VendorId    = 0x10de
DeviceId    = 0x1b80
Version     = 27.21.0014.6140
Description = NVIDIA GeForce GTX 1080
Compat      = 0x00100000
VidMem      = 0 MB

*--> NVidia Info <--*
DriverVersion = r461_36

Please help. Im not sure if it is memory problem but my friends have 16gb as well and they never crash. Thank you all appreciated :)

**Comment by megai2** [comment]
Hi. This is an out of memory crash as stated in crash (OOM).
Try to increase page file [size](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/how-to-increase-virtual-memory-in-windows-10-a/46dacaf5-15cf-4f5d-9d5a-cba1401ae4c9) or closing other memory demanding applications

**Comment by Squall-Leonhart** [comment]
get off that driver.

.40 and .51HF have been released since.
