### ISSUE TITLE
gw2 crash on startup with "-cuda" parameter

### ISSUE THREAD

**Issue by A-tG** [megai2/d912pxy#341]
If the game is launched with "-cuda" command line argument it crashes (or freezes for a long period of time).
OS Win 10 x64 20H2 19042.804
GPU nvidia gtx 1660 with 460.89 driver
CPU amd ryzen 2600x

**Comment by Squall-Leonhart** [comment]
The game doesn't use -cuda

**Comment by megai2** [comment]
Option is outdated and that is it. 
It is changes some occlusion stuff, but not officialy supported AFAIK since core gw2.

**Comment by A-tG** [comment]
The point is I was launching game with that parameter and there was no problems (what if I get better performance I thought, lets just keep it). But I was no able to use d912pxy for a long time, I thought something wrong with my system and only accidentally I found out that "-cuda" was the problem. At least it should be added "troubleshooting" page.
