### ISSUE TITLE
Game failing to start with ArcDPS+d912pxy on 2.4.1

### ISSUE THREAD

**Issue by ruvaldak** [megai2/d912pxy#342]
[log.1.txt](https://github.com/megai2/d912pxy/files/6036883/log.1.txt)

With ArcDPS+Buildpad+SCT installed with d912pxy as d3d9_chainload.dll, GW2 fails to start. Exception C0000005 seems to be the only error code.

**Comment by megai2** [comment]
Make sure you use latest ( feb.23.2021 ) build of arcdps.

**Comment by ruvaldak** [comment]
> Make sure you use latest ( feb.23.2021 ) build of arcdps.

I am. Triple checked today, problem still occurs.

**Comment by megai2** [comment]
> 
> 
> > Make sure you use latest ( feb.23.2021 ) build of arcdps.
> 
> I am. Triple checked today, problem still occurs.

Crash callstack does not originate from d912pxy, so i guess i can't help here.
Also simple setup of proxy+arcdps works for me.

I suggest checking other stuff you have installed, that is not updated, (SCT for ex.)
And check that you don't have extra dlls in bin64 as arcdps simply loads everything in there and can mess up stuff.

**Comment by ruvaldak** [comment]
It was arcdps_bhud (blishhud arcdps integration). Didn't even see it in bin64 when I combed through it earlier. Mbad.

**Comment by megai2** [comment]
So issue is solved, at least for me.
