### ISSUE TITLE
Climbing Memory Usage

### ISSUE THREAD

**Issue by Qwertofdeath** [megai2/d912pxy#343]
Whenever I launch GW2 my memory usage seems a tad bit high (which looked normal given some of the configs I've been trying in order to remedy this problem) but my memory usage on launch and continual play seem to climb gradually. At first I thought the problem was my config, so I uninstalled and reinstalled while clearing the shader cache to get the default config and clean slate, but it seems to not matter either way. My memory usage starts anywhere between 4g and 9g and climbs up through play until it eventually hits 95% usage.
 Now, I understand that memory usage with some of the higher end configs can do this, but when the default one did it, i turned here. This isn't very impactful on performance until memory swapping issues start showing. I don't run any other addons, and my graphic settings are on the "high" setting across the board, with "medium" on both player model settings. No crashes from this yet.

 Memory usage seems to increase based on the number of maps I've loaded into in a session, and doesn't seem to drop back down regardless of time passing or changes to the pooling section of my config. 

My computer specs:
RTX 2070
AMD Ryzen 3900x
16 Gb Memory
1 TB SSD

**Comment by Squall-Leonhart** [comment]
and this is why the pagefile is required.

**Comment by Qwertofdeath** [comment]
A very informative answer, to be sure. The question's main purpose was to ask the question of if there was a way to make it not do that, or at the very least slow it's impact. The reason this stood out to me is that it occurred even with the base default config, and strikes me more as a sort of memory "leak" and shouldn't be the norm for everybody.

**Comment by Squall-Leonhart** [comment]
not in any application where the memory management isn't directly controlled by a invalidation and discard system.

**Comment by Qwertofdeath** [comment]
Well, i suppose I'll just tweak with it more to get it where I like it with this existing then. Thanks for the responses.

**Comment by megai2** [comment]
@Qwertofdeath if log does not show memory leak in VA allocators on exit, 
there should be no leak in general. (debug build can show more)

If you frequently change maps, for example 6-10 map loads per minute,
default config can eat up memory for some time.

Other sources are persistent pipeline objects, but amount of memory they eat depends on driver.

**Comment by zhuhuoyuyan** [comment]
Hello, I also encountered this problem. How did you solve it? Our configuration is very close



> 好吧，我想我将对其进行更多调整，以使它在现有的情况下达到我喜欢的位置。感谢您的答复。
