### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Me4fun** [megai2/d912pxy#344]
Mar 02 10:17:20 arcdps 20210225.232422-348-x64
Mar 02 10:17:20 client: gw2 0x7FF7B0060000-0x7FF7B25CE000 (0xB08A8D01)
Mar 02 10:17:20 client: arcdps 0x7FFC28320000-0x7FFC2842D000 (0x38718F31)
Mar 02 10:17:20 client: chainloading d3d9
Mar 02 10:17:20 config: loading from "C:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 02 10:17:21 client: ready
Mar 02 10:17:21 error: intercepted crash from hardware exception in "C:\Windows\System32\KERNELBASE.dll"
Mar 02 10:17:21 client: --- exception ---
			code: 0x00000000E06D7363
			addr: 0x00007FFC659BD759
			offs: 0x000000000002D759
			prms:   0000000000000004
			flgs: 0x0000000000000001
Mar 02 10:17:21 client: --- system ---
			cpu: AMD Ryzen 5 3600 6-Core Processor              
			ram: 6803MB / 16328MB used
			gpu: NVIDIA GeForce RTX 2070 SUPER
Mar 02 10:17:21 client: --- modules ---
			0x7FF7B0060000 - 0x7FF7B25CE000    C:\Program Files\Guild Wars 2\Gw2-64.exe
			0x7FFC67DF0000 - 0x7FFC67FE6000    C:\Windows\SYSTEM32\ntdll.dll
			0x7FFC35540000 - 0x7FFC35552000    C:\Program Files\Avast Software\Avast\aswhook.dll
			0x7FFC67050000 - 0x7FFC6710D000    C:\Windows\System32\KERNEL32.DLL
			0x7FFC65990000 - 0x7FFC65C59000    C:\Windows\System32\KERNELBASE.dll
			0x7FFC67380000 - 0x7FFC67520000    C:\Windows\System32\USER32.dll
			0x7FFC65C90000 - 0x7FFC65CB2000    C:\Windows\System32\win32u.dll
			0x7FFC671C0000 - 0x7FFC671EA000    C:\Windows\System32\GDI32.dll
			0x7FFC65CC0000 - 0x7FFC65DCB000    C:\Windows\System32\gdi32full.dll
			0x7FFC658F0000 - 0x7FFC6598D000    C:\Windows\System32\msvcp_win.dll
			0x7FFC65530000 - 0x7FFC65630000    C:\Windows\System32\ucrtbase.dll
			0x7FFC67D00000 - 0x7FFC67DAC000    C:\Windows\System32\ADVAPI32.dll
			0x7FFC67280000 - 0x7FFC6731E000    C:\Windows\System32\msvcrt.dll
			0x7FFC662C0000 - 0x7FFC6635C000    C:\Windows\System32\sechost.dll
			0x7FFC66360000 - 0x7FFC6648B000    C:\Windows\System32\RPCRT4.dll
			0x7FFC666B0000 - 0x7FFC6671B000    C:\Windows\System32\WS2_32.dll
			0x7FFC65890000 - 0x7FFC658F0000    C:\Windows\System32\WINTRUST.dll
			0x7FFC671A0000 - 0x7FFC671A8000    C:\Windows\System32\PSAPI.DLL
			0x7FFC67BD0000 - 0x7FFC67CFA000    C:\Windows\System32\ole32.dll
			0x7FFC675D0000 - 0x7FFC67926000    C:\Windows\System32\combase.dll
			0x7FFC66F80000 - 0x7FFC6704D000    C:\Windows\System32\OLEAUT32.dll
			0x7FFC66780000 - 0x7FFC66EC2000    C:\Windows\System32\SHELL32.dll
			0x7FFC65630000 - 0x7FFC65786000    C:\Windows\System32\CRYPT32.dll
			0x7FFC5D190000 - 0x7FFC5D19A000    C:\Windows\SYSTEM32\VERSION.dll
			0x7FFC60AB0000 - 0x7FFC60AC4000    C:\Windows\SYSTEM32\WTSAPI32.dll
			0x7FFC5C920000 - 0x7FFC5C947000    C:\Windows\SYSTEM32\WINMM.dll
			0x7FFC50A90000 - 0x7FFC50AAE000    C:\Windows\SYSTEM32\MSACM32.dll
			0x7FFC58AB0000 - 0x7FFC58C5B000    C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.789_none_faf0a7e97612e7bb\gdiplus.dll
			0x7FFC5C870000 - 0x7FFC5C920000    C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.488_none_4238de57f6b64d28\COMCTL32.dll
			0x7FFC58EC0000 - 0x7FFC58ED9000    C:\Windows\SYSTEM32\USP10.dll
			0x7FFC61510000 - 0x7FFC61517000    C:\Windows\SYSTEM32\MSIMG32.dll
			0x7FFC47EB0000 - 0x7FFC47EBC000    C:\Windows\SYSTEM32\Secur32.dll
			0x7FFC3EE60000 - 0x7FFC3EE86000    C:\Windows\SYSTEM32\winmmbase.dll
			0x7FFC64EE0000 - 0x7FFC64EEC000    C:\Windows\SYSTEM32\CRYPTBASE.DLL
			0x7FFC65410000 - 0x7FFC6544C000    C:\Windows\SYSTEM32\SSPICLI.DLL
			0x7FFC67170000 - 0x7FFC671A0000    C:\Windows\System32\IMM32.DLL
			0x7FFC65110000 - 0x7FFC65122000    C:\Windows\SYSTEM32\MSASN1.dll
			0x7FFC65DD0000 - 0x7FFC65E50000    C:\Windows\System32\bcryptPrimitives.dll
			0x7FFC59FD0000 - 0x7FFC5A1B4000    C:\Windows\SYSTEM32\dbghelp.dll
			0x7FFC636A0000 - 0x7FFC63E30000    C:\Windows\SYSTEM32\windows.storage.dll
			0x7FFC64F90000 - 0x7FFC64FBC000    C:\Windows\SYSTEM32\Wldp.dll
			0x7FFC67520000 - 0x7FFC675CE000    C:\Windows\System32\SHCORE.dll
			0x7FFC67110000 - 0x7FFC67165000    C:\Windows\System32\shlwapi.dll
			0x7FFC65460000 - 0x7FFC65486000    C:\Windows\SYSTEM32\profapi.dll
			0x7FFC634A0000 - 0x7FFC634B2000    C:\Windows\SYSTEM32\kernel.appcore.dll
			0x7FFC65C60000 - 0x7FFC65C87000    C:\Windows\System32\bcrypt.dll
			0x7FFC62F00000 - 0x7FFC62F9E000    C:\Windows\system32\uxtheme.dll
			0x7FFC5D130000 - 0x7FFC5D161000    C:\Windows\SYSTEM32\cryptnet.dll
			0x7FFC66570000 - 0x7FFC6658D000    C:\Windows\System32\imagehlp.dll
			0x7FFC64EF0000 - 0x7FFC64F08000    C:\Windows\SYSTEM32\CRYPTSP.dll
			0x7FFC64640000 - 0x7FFC64674000    C:\Windows\system32\rsaenh.dll
			0x7FFC5D320000 - 0x7FFC5D35B000    C:\Windows\SYSTEM32\dxcore.dll
			0x7FFC65790000 - 0x7FFC657DE000    C:\Windows\System32\cfgmgr32.dll
			0x7FFC3C4F0000 - 0x7FFC3C7A9000    C:\Windows\system32\nvspcap64.dll
			0x7FFC64270000 - 0x7FFC642A3000    C:\Windows\SYSTEM32\ntmarta.dll
			0x7FFC63E40000 - 0x7FFC63E63000    C:\Windows\SYSTEM32\gpapi.dll
			0x7FFC66ED0000 - 0x7FFC66F79000    C:\Windows\System32\clbcatq.dll
			0x7FFC445B0000 - 0x7FFC445C7000    C:\Windows\system32\napinsp.dll
			0x7FFC42B70000 - 0x7FFC42B8B000    C:\Windows\system32\pnrpnsp.dll
			0x7FFC60580000 - 0x7FFC60595000    C:\Windows\system32\wshbth.dll
			0x7FFC612D0000 - 0x7FFC612ED000    C:\Windows\system32\NLAapi.dll
			0x7FFC649B0000 - 0x7FFC649EB000    C:\Windows\SYSTEM32\IPHLPAPI.DLL
			0x7FFC64D10000 - 0x7FFC64D7A000    C:\Windows\System32\mswsock.dll
			0x7FFC649F0000 - 0x7FFC64ABB000    C:\Windows\SYSTEM32\DNSAPI.dll
			0x7FFC67990000 - 0x7FFC67998000    C:\Windows\System32\NSI.dll
			0x7FFC424B0000 - 0x7FFC424C2000    C:\Windows\System32\winrnr.dll
			0x7FFC5B120000 - 0x7FFC5B19F000    C:\Windows\System32\fwpuclnt.dll
			0x7FFC5EBF0000 - 0x7FFC5EBFA000    C:\Windows\System32\rasadhlp.dll
			0x7FFC66590000 - 0x7FFC666A5000    C:\Windows\System32\msctf.dll
			0x7FFC4F3A0000 - 0x7FFC4F49B000    C:\Windows\SYSTEM32\textinputframework.dll
			0x7FFC62500000 - 0x7FFC6285E000    C:\Windows\System32\CoreUIComponents.dll
			0x7FFC62BE0000 - 0x7FFC62CD2000    C:\Windows\System32\CoreMessaging.dll
			0x7FFC61520000 - 0x7FFC61674000    C:\Windows\SYSTEM32\wintypes.dll
			0x7FFC5EF10000 - 0x7FFC5F0C4000    C:\Windows\SYSTEM32\WindowsCodecs.dll
			0x7FFC4AE70000 - 0x7FFC4AF1C000    C:\Windows\SYSTEM32\TextShaping.dll
			0x7FFC28430000 - 0x7FFC28544000    C:\Program Files\Guild Wars 2\bin64\CoherentUI64.dll
			0x7FFC28320000 - 0x7FFC2842D000    C:\Program Files\Guild Wars 2\bin64\d3d9.dll
			0x7FFC5BBD0000 - 0x7FFC5BCD0000    C:\Windows\SYSTEM32\WINHTTP.dll
			0x7FFC5EAF0000 - 0x7FFC5EAFB000    C:\Windows\SYSTEM32\WINNSI.DLL
			0x7FFC65320000 - 0x7FFC6532A000    C:\Windows\SYSTEM32\DPAPI.dll
			0x7FFC0C320000 - 0x7FFC0CA68000    C:\Program Files\Guild Wars 2\bin64\d3d9_chainload.dll
			0x7FFC5B970000 - 0x7FFC5B990000    C:\Windows\SYSTEM32\d3d12.dll
			0x7FFC63E70000 - 0x7FFC63F63000    C:\Windows\SYSTEM32\dxgi.dll
			0x7FFC61680000 - 0x7FFC61ADD000    C:\Windows\SYSTEM32\d3dcompiler_47.dll
			0x7FFC5A8C0000 - 0x7FFC5AA8F000    C:\Windows\system32\d3d9.dll
			0x7FFC631B0000 - 0x7FFC631DF000    C:\Windows\SYSTEM32\dwmapi.dll
			0x7FFC5D1A0000 - 0x7FFC5D2A5000    C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_272b5c540127d6d2\nvldumdx.dll
			0x7FFBF4810000 - 0x7FFBF645A000    C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_272b5c540127d6d2\nvd3dumx.dll
			0x7FFC5BEF0000 - 0x7FFC5C5E1000    C:\Windows\SYSTEM32\nvapi64.dll
			0x7FFC65E50000 - 0x7FFC662B7000    C:\Windows\System32\SETUPAPI.DLL
			0x7FFC642E0000 - 0x7FFC6433A000    C:\Windows\SYSTEM32\WINSTA.dll
			0x7FFC1EA10000 - 0x7FFC1EBDD000    C:\Windows\SYSTEM32\D3D12Core.dll
			0x7FFC22F10000 - 0x7FFC278E6000    C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_272b5c540127d6d2\nvwgf2umx.dll
			0x7FFC4E880000 - 0x7FFC4E8AB000    C:\Windows\SYSTEM32\D3DSCache.dll
			0x7FFC653E0000 - 0x7FFC6540E000    C:\Windows\SYSTEM32\USERENV.dll
			0x7FFC5F0E0000 - 0x7FFC5F2E1000    C:\Windows\SYSTEM32\twinapi.appcore.dll
			0x7FFC27A10000 - 0x7FFC27B49000    C:\Windows\SYSTEM32\dxilconv.dll
			0x7FFC20710000 - 0x7FFC20896000    C:\Windows\System32\Speech\Common\sapi.dll
			0x7FFC61310000 - 0x7FFC6131B000    C:\Windows\SYSTEM32\msdmo.dll
			0x7FFC5F310000 - 0x7FFC5F395000    C:\Windows\System32\MMDevApi.dll
			0x7FFC652D0000 - 0x7FFC652FC000    C:\Windows\System32\DEVOBJ.dll
Mar 02 10:17:21 client: --- registers ---
			RAX: 0x00007FFC0C74D563   R8:  0x00007FFC0C7E62DB
			RBX: 0x0000016EA20071F0   R9:  0x0000016E00000003
			RCX: 0x0000016EA216EFE4   R10: 0x00007FFC0C74D563
			RDX: 0x00007FFC0C8067B6   R11: 0x0031016EA216EFE4
			RBP: 0x0000003B31FFD8C0   R12: 0x0000000000000000
			RSP: 0x0000003B31FFD730   R13: 0x0000000000000000
			RSI: 0x0000000000000000   R14: 0x000000000000004B
			RDI: 0x0000003B31FFE4D8   R15: 0x0000000000000001
			RIP: 0x00007FFC659BD759
Mar 02 10:17:21 client: --- code ---
			0x7FFC659BD719: 894C2420 89542424 48894424 304D85C9
			0x7FFC659BD729: 744CB80F 00000048 8D4C2440 443BC049
			0x7FFC659BD739: 8BD1440F 47C04489 44243849 C1E003E8
			0x7FFC659BD749: 2A470600 488D4C24 2048FF15 AF231900
			0x7FFC659BD759: 0F1F4400 00488B8C 24C00000 004833CC
			0x7FFC659BD769: E8D20906 004881C4 D8000000 C3CC8364
			0x7FFC659BD779: 243800EB CFCCCCCC CCCCCCCC CCCCCCCC
			0x7FFC659BD789: CCCCCCCC CCCCCC40 534883EC 30488BD1
Mar 02 10:17:21 client: --- stack ---
			0x003B31FFD710: 4B000000 00000000 D8E4FF31 3B000000
			0x003B31FFD720: C0D8FF31 3B000000 59D79B65 FC7F0000
			0x003B31FFD730: CCCCCCCC CCCCCCCC F07100A2 6E010000
			0x003B31FFD740: 00000000 00000000 CCCCCCCC CCCCCCCC
			0x003B31FFD750: 63736DE0 01000000 00000000 00000000
			0x003B31FFD760: 59D79B65 FC7F0000 04000000 CCCCCCCC
			0x003B31FFD770: 20059319 00000000 A8E4FF31 3B000000
			0x003B31FFD780: C816920C FC7F0000 0000320C FC7F0000
			0x003B31FFD790: 00000000 00000000 00000000 00000000
			0x003B31FFD7A0: 00000000 00000000 C0D8FF31 3B000000
			0x003B31FFD7B0: 40D8FF31 3B000000 8F69E167 FC7F0000
			0x003B31FFD7C0: D8E4FF31 3B000000 00000000 CCCCCCCC
			0x003B31FFD7D0: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
			0x003B31FFD7E0: 0000A30C FC7F0000 0000320C FC7F0000
			0x003B31FFD7F0: 6106F4D7 737A0000 CCCCCCCC CCCCCCCC
			0x003B31FFD800: F07100A2 6E010000 00D4720C FC7F0000
			0x003B31FFD810: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
			0x003B31FFD820: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
			0x003B31FFD830: C816920C FC7F0000 CCCCCCCC CCCCCCCC
			0x003B31FFD840: 0000320C FC7F0000 CCCCCCCC CCCCCCCC
			0x003B31FFD850: 20059319 00000000 CCCCCCCC CCCCCCCC
			0x003B31FFD860: CCCCCCCC CCCCCCCC 20059319 00000000
			0x003B31FFD870: A8E4FF31 3B000000 C816920C FC7F0000
			0x003B31FFD880: 0000320C FC7F0000 D8E4FF31 3B000000
			0x003B31FFD890: C0D8FF31 3B000000 18795F0C FC7F0000
			0x003B31FFD8A0: A8E4FF31 3B000000 C816920C FC7F0000
			0x003B31FFD8B0: A408890C FC7F0000 FFFFFFFF 00000000
			0x003B31FFD8C0: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
			0x003B31FFD8D0: 6D007300 67002000 7C002000 68007200
			0x003B31FFD8E0: 20003D00 20004600 46004600 46004600
			0x003B31FFD8F0: 46004600 46000000 CCCCCCCC CCCCCCCC
			0x003B31FFD900: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
			0x003B31FFD910: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
			0x003B31FFD920: CCCCCCCC CCCCCCCC CCCCCCCC CCCCCCCC
Mar 02 10:17:21 client: --- trace ---
			ep 0x7FFC659BD759 frame 0x003B31FFD800 rva 0x00000002D759 in KERNELBASE
			ep 0x7FFC0C72D400 frame 0x003B31FFD890 rva 0x00000040D400 in d3d9_chainload @ CxxThrowException
			ep 0x7FFC0C5F7918 frame 0x003B31FFE4E0 rva 0x0000002D7918 in d3d9_chainload @ d912pxy_helper::ThrowIfFailed
			ep 0x7FFC0C613BFE frame 0x003B31FFE620 rva 0x0000002F3BFE in d3d9_chainload @ d912pxy_noncom::ThrowErrorDbg
			ep 0x7FFC0C666DA2 frame 0x003B31FFE760 rva 0x000000346DA2 in d3d9_chainload @ d912pxy_swapchain::ThrowCritialError
			ep 0x7FFC0C6623FC frame 0x003B31FFEBA0 rva 0x0000003423FC in d3d9_chainload @ d912pxy_swapchain::InitDXGISwapChain
			ep 0x7FFC0C6658A2 frame 0x003B31FFED60 rva 0x0000003458A2 in d3d9_chainload @ d912pxy_swapchain::SwapHandle_Setup
			ep 0x7FFC0C664B44 frame 0x003B31FFEE60 rva 0x000000344B44 in d3d9_chainload @ d912pxy_swapchain::Swap
			ep 0x7FFC0C6647D5 frame 0x003B31FFEF60 rva 0x0000003447D5 in d3d9_chainload @ d912pxy_swapchain::SetPresentParameters
			ep 0x7FFC0C5D580B frame 0x003B31FFF080 rva 0x0000002B580B in d3d9_chainload @ d912pxy_device::Reset
			ep 0x7FFC0C5BF00B frame 0x003B31FFF1E0 rva 0x00000029F00B in d3d9_chainload @ d912pxy_device::com_Reset
			ep 0x7FF7B028D463 frame 0x003B31FFF770 rva 0x00000022D463 in Gw2-64
			ep 0x7FF7B028CB6D frame 0x003B31FFF7D0 rva 0x00000022CB6D in Gw2-64
			ep 0x7FF7B028B9E5 frame 0x003B31FFF800 rva 0x00000022B9E5 in Gw2-64
			ep 0x7FF7B023CF2F frame 0x003B31FFF850 rva 0x0000001DCF2F in Gw2-64
			ep 0x7FF7B023D28D frame 0x003B31FFF880 rva 0x0000001DD28D in Gw2-64
			ep 0x7FF7B0203FBB frame 0x003B31FFF8C0 rva 0x0000001A3FBB in Gw2-64
			ep 0x7FF7B0200668 frame 0x003B31FFF8F0 rva 0x0000001A0668 in Gw2-64
			ep 0x7FF7B02023DA frame 0x003B31FFF920 rva 0x0000001A23DA in Gw2-64
			ep 0x7FF7B0B97743 frame 0x003B31FFFA10 rva 0x000000B37743 in Gw2-64
			ep 0x7FF7B0506696 frame 0x003B31FFFA70 rva 0x0000004A6696 in Gw2-64
			ep 0x7FF7B04FEA1B frame 0x003B31FFFAA0 rva 0x00000049EA1B in Gw2-64
			ep 0x7FF7B01D8773 frame 0x003B31FFFAE0 rva 0x000000178773 in Gw2-64
			ep 0x7FF7B03CBE0E frame 0x003B31FFFBF0 rva 0x00000036BE0E in Gw2-64
			ep 0x7FF7B03CA0BC frame 0x003B31FFFCA0 rva 0x00000036A0BC in Gw2-64
			ep 0x7FF7B03C9D39 frame 0x003B31FFFD20 rva 0x000000369D39 in Gw2-64
			ep 0x7FF7B03CB3CF frame 0x003B31FFFD70 rva 0x00000036B3CF in Gw2-64
			ep 0x7FF7B03C973C frame 0x003B31FFFDA0 rva 0x00000036973C in Gw2-64
			ep 0x7FF7B01F1A51 frame 0x003B31FFFDD0 rva 0x000000191A51 in Gw2-64
			ep 0x7FF7B0382A91 frame 0x003B31FFFE00 rva 0x000000322A91 in Gw2-64
			ep 0x7FFC67067034 frame 0x003B31FFFE30 rva 0x000000017034 in KERNEL32
			ep 0x7FFC67E3D241 frame 0x003B31FFFEB0 rva 0x00000004D241 in ntdll
			thread start 0x7FF7B0382A34 rva 0x000000322A34 in Gw2-64

**Comment by Me4fun** [comment]
0 | CreateDXGIFactory2 failed because DXGI_CREATE_FACTORY_DEBUG was specified, but DXGIDebug.dll is not present on the system. This flag must be removed, or the Windows SDK must be installed.
 

1 | msg | hr = FFFFFFFF

**Comment by megai2** [comment]
By default debug for DXGI is not enabled.
If you used debug build or not default config, please use release build and this value in config
```
[dx]
debug=0
```
