### ISSUE TITLE
Trading Post and Logon Servers connection errors

### ISSUE THREAD

**Issue by Squidgeididdly** [megai2/d912pxy#351]
After installing, the trading post will not load or only partially load and I am receiving "cannot connect to login server" errors.

For context:
I have installed using the addon manager
I played for an hour or two before installing, used the TP and all was well.
After installing I can't get the listings for items to appear on the TP, and am receiving the login errors.
Everything else so far is running very well :)

**Comment by megai2** [comment]
That is connectivity problems of game. 
d912pxy is not involved in networking or other stuff, so it can't affect this.

**Comment by Squidgeididdly** [comment]
turns out it was arc, uninstalled that and everything was fine again. Cheers for responding :)
