### ISSUE TITLE
Whisper of Jormag no texture

### ISSUE THREAD

**Issue by gele05** [megai2/d912pxy#354]
Hello i'm running the problem only on this map (the Strike), i have no texture on whisper of jormag.

**Comment by gele05** [comment]
https://gyazo.com/743ac2dfa8681136343013811fab101e like that

**Comment by IsmetBesic** [comment]
Make sure that "replay_threads" is set to 1 in your config.ini

**Comment by gele05** [comment]
> Make sure that "replay_threads" is set to 1 in your config.ini

I've tried and it work! Finally! 

Thanks alot.

I've setted before on replay_threads to 4. Can you explain if possible which is the problem?

**Comment by megai2** [comment]
Occlusion will be disabled when replay threads are more than 1, that will break rendering.
