### ISSUE TITLE
Performance Drop after updating to v2.4.2

### ISSUE THREAD

**Issue by TeamDivisionOne** [megai2/d912pxy#355]
Hi, I have been using d912pxy for a relatively long time and its been a game changer (thank you). However, after updating to v2.4.2, the game just has not been running smoothly. Loading into any new map (despite shaderpack already built for that map which in this case is Mistlock Sanctuary), has a starting FPS of 10~ which gradually increases after 5s back up to 55-60. Another issue is metas (v.2.4 was the old version I was using) which had 25~ FPS on my current settings but is now a solid 15FPS. On top of the FPS issues, the game has just been clunky in general. This includes taking 1s-3s after clicking 'Log Out' to swap characters and swapping maps.
_One thing I've noticed is there is high CPU usage for GW2 a lot of the times just randomly (even on a map that's been loaded 50+ times)_

I am running the same exact settings and hardware as before and here are some of the things I've attempted to solve this issue:
- Reinstall d912pxy (v2.4 or v.2.4.2) (Problem now persists with all versions after updating)
- Cleared shaderpacks and let it rebuild
- Reinstalled GW2
- Tested without d912pxy to ensure it wasn't a GW2 base issue
- Latest Graphics Drivers

Hardware / Temps:
CPU: Intel I7-6700k (<60C)
GPU: Nvidia GTX 1080 (<70C)
SSD: Samsung 970 Pro 1TB
Mobo: MSI Gaming M7 Z170
RAM: 32GB 

![Settings](https://user-images.githubusercontent.com/55223776/112684904-c12e7d80-8e41-11eb-9c14-6499e4033af9.PNG)

If there is anything else I may provide, please let me know.

**Comment by megai2** [comment]
> Reinstall d912pxy (v2.4 or v.2.4.2) (Problem now persists with all versions after updating)

If it was working good before on v2.4, it should keep working fine.
Keep overlay enabled after reinstall. I guess performance drop will be seen only when PSO numbers is above 0.

**Comment by TeamDivisionOne** [comment]
> > Reinstall d912pxy (v2.4 or v.2.4.2) (Problem now persists with all versions after updating)
> 
> If it was working good before on v2.4, it should keep working fine.
> Keep overlay enabled after reinstall. I guess performance drop will be seen only when PSO numbers is above 0.

Is there any settings I can change to try to fix this issue / logs to provide to help diagnose this issue? Abnormally high CPU usage in GW2 every so often coincides with the frame drops. Sometimes the FPS drops below numbers (<15) that the base GW2 game doesn't even reach for me.

**Comment by megai2** [comment]
> 
> Is there any settings I can change to try to fix this issue / logs to provide to help diagnose this issue? Abnormally high CPU usage in GW2 every so often coincides with the frame drops. Sometimes the FPS drops below numbers (<15) that the base GW2 game doesn't even reach for me.

Attach log file - the d912pxy/log.txt
Keep overlay on as i suggested and take a screenshot when bug happens

**Comment by TeamDivisionOne** [comment]
> > Is there any settings I can change to try to fix this issue / logs to provide to help diagnose this issue? Abnormally high CPU usage in GW2 every so often coincides with the frame drops. Sometimes the FPS drops below numbers (<15) that the base GW2 game doesn't even reach for me.
> 
> Attach log file - the d912pxy/log.txt
> Keep overlay on as i suggested and take a screenshot when bug happens
I've uploaded both (not sure the difference between the 2)
[log.1.txt](https://github.com/megai2/d912pxy/files/6217811/log.1.txt)
[log.txt](https://github.com/megai2/d912pxy/files/6217812/log.txt)

![Frame Drops](https://user-images.githubusercontent.com/55223776/112762808-61fa7580-8fc7-11eb-817c-0fbf6a06d680.PNG)

**Comment by TeamDivisionOne** [comment]
-Resolved issue. Swapped to a new CPU and Mobo (Ryzen 7 5800x + ASUS Prime B550 Plus) and this issue seemed to have faded away. Previous CPU may have had an issue after update / reinstall and would not cooperate in any way.
