### ISSUE TITLE
help with gamma problems

### ISSUE THREAD

**Issue by bluenote73** [megai2/d912pxy#356]
Hi, thanks for this, it is very useful. I know gamma isn't your problem, but I wonder if you can offer any suggestion because my game is way too dark, I really need gamma control. LCD monitor brightness is up, and I set gfx card to increase brightness and/or play with windows gamma, but it's really not a good solution. Sorry to bother you with this, I hope you can help though.
thx

**Comment by JDjitsu** [comment]
I'm wondering if you've ever figured out how to not make it so dark. I have the same issue. It's my only gripe I have with this so far is that it makes GW2 super dark and regular Nvidia color and monitor settings just don't really do the trick.

**Comment by megai2** [comment]
I used windows builtin monitor calibration tool to fight this issue. 
Other solution is use custom shader or stuff like ReShade or nvidia freestyle, etc.
