### ISSUE TITLE
Logs for crashes I had since I don't know where to upload them.

### ISSUE THREAD

**Issue by BaseSquare** [megai2/d912pxy#36]
Changed maps and played the game in-general smoothly.

Changed settings on Windowed Fullscreen without crashing successfully : 

Anti-Aliasing to FXAA
Rendering from Subsample -> Native
Texture Quality Low -> High

Once I ticked the "Use Best Texture Filtering" command it crashed to desktop without error.

In all of my play I had weird glitchy white stuff among all textures, ground and object alike except character models. After character models loaded fully the white glitchy particles/tiny squares were gone from them at least. Character select has the white pixelated glitchy stuff I mentioned among all characters.

Circles from AOE spells were gone. Water was gone as well like many people mentioned. 

UI worked smoothly.

FPS was increased but limited to 60 so I can't input accurate gains. In general gameplay was smoother apart from the visual glitches and the missing AOE spell circles. I'll attach my logs, hopefully they help out, can't wait to try it once it's stable.
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2800133/d912pxy_crash.txt)

GitHub doesn't support Crash.dmp and the p7d stuff from that folder so I can't upload them here, if anyone needs them I'll upload it somewhere else and attach the link.

**Comment by rkujo** [comment]
you can .zip the folder then upload
