### ISSUE TITLE
Log File full of Connect issues but Program appears to work correctly

### ISSUE THREAD

**Issue by Lady-Holychild** [megai2/d912pxy#363]
I am New to GW2 so its a fresh install on a NON System Drive E:\Guild Wars 2\d912pxy.
TACO Installed within the Guild Wars 2 Folder working without issue.
Totally Fresh install of d912pxy, done twice incase I had messed up.
Taken ALL the default answers

I know the Program is working as zoning into a new zone takes a while and then there are items / npc/ textures / mobs etc etc popping into display.

I did notice that if I was fighting a world event died and waypointed back then said mob would be invisible for a while when I got back, though could engage and do damage so purely a cosmetic issue, which was why I checked the log to find litteraly hundreds of lines of :
64C9BC2 [ error ] helper | CClientConnectionManager::Connect(): failed with 0x00000002
 
64C9BC2 [ note ] note | 12297 | CClientConnectionManager::Connect(): failed with 0x00000002

Thinking from the name it may be a Visual C++ Issue reloaded the latest redists both x64 and x86 Ver: 14.28.29913.0

**Screenshots**

**Standard information**

1. Win 10 Pro Version 20H2 OS Build 19042.867
2. Hardware info: i7-3770K, 16Gb Ram Nvidia Geforce GTX 1070Ti
3. GPU Driver version : 27.21.14.6589
4. Version of d912pxy used : d912pxy_v2.4.3.1_r685
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
6. [log.txt](https://github.com/megai2/d912pxy/files/6292182/log.txt)

**Comment by megai2** [comment]
Hi. This is debug logging from one of 3-rd party softwares installed on your PC.
You can disable debug logging redirect by setting enable_veh to 0 in d912pxy/config.ini under [log] category

**Comment by Lady-Holychild** [comment]
@megai2 
Many Thanks, updated the ini file and now a nice clean neat 14kb log file, no idea what 3rd party is causing it have so much installed but thanks glad to know it wasn't an issue either with the Application or my install.
