### ISSUE TITLE
Does it still work with extras.enabled = 0 ?

### ISSUE THREAD

**Issue by breuerfelix** [megai2/d912pxy#365]
First of all: thanks for this awesome tool!  
I didn't want to see the fps graph and i know that i can toggle it on and off. But i also didn't want to see it when the game launched and manually hiding it every time.

my question now is: when disabling the overlay, does the directx mod still work ?  
When pressing the button in the UI to disable the overlay it says that the overlay and all extras get disabled .. which sounds like the whole stuff is getting disabled since the plugin itself is a pretty neat extra you know ? :D

just wanted to be sure that extras = 0 means only disabling the UI stuff ?  
maybe a note in the menu: "only disabling overlay, the mod is still active" would be nice :)

**Comment by IsmetBesic** [comment]
> when disabling the overlay, does the directx mod still work ? 

Yes. You can verify that d912pxy still initializes by checking whether or not a log file has been created inside your d912pxy folder.

**Comment by breuerfelix** [comment]
thanks for the clarification! maybe someone else is stumbling across this issue aswell in the future :)

also thanks for the future clarification!
