### ISSUE TITLE
GW2 stop working after restart client

### ISSUE THREAD

**Issue by EisenWagen** [megai2/d912pxy#366]
Last version of dx12pxy.Perevious was the same
Install>All works fine>restart client> dx12pxy doesn't work until reinstall

**Comment by megai2** [comment]
Does not bug out this way for me.
Attach a d912pxy/log.txt at least

**Comment by Serfrost** [comment]
Needs more information. A log as suggested would make all the difference here.

"It crash and no work no more" just doesn't help.
