### ISSUE TITLE
Attempting removal of chainload dll instead restored from "backup"?

### ISSUE THREAD

**Issue by GirthCurse** [megai2/d912pxy#368]
When attempting to remove the install of d912pxy, after selecting option 2 (remove), instead of saying "Installation removed" the installer gave me a message about a backup being detected and restored it.  The d3d9_chainload.dll was not removed. and there was a file with backup in the name in /bin64/ that I never instructed d912pxy to create.

**To Reproduce**
Happened when I was attempting to uninstall d912pxy to await the next arcdps update (I assume the game will not load d3d9_chainload.dll without d3d9.dll present); I manually uninstalled and then reinstalled to try to reproduce the issue, but it did not happen again and the installer said "Installation removed" as expected. To my knowledge I did not install with any different options from before.

**Expected behavior**
Expected to uninstall, instead it did not uninstall and simply reinstalled from a backup I had no desire to have created.

Windows 10 20h2
7700k @ 4.8GHz, TridentZ RGB 3600, 1080TI
Latest Nvidia WHQL drivers
Latest d912pxy
Manually deleted logs oops

**Comment by megai2** [comment]
Install always keeps backup for file that it will overwrite.
So if you made 2 installations via installer, it will restore 1-st dll on uninstallation.

**Comment by megai2** [comment]
In sum - works as intended. 
Install always keeps backup for file that it will overwrite and restores it when using uninstall option.
