### ISSUE TITLE
Could I get a recent shader pack / keep current pack on reinstall? 

### ISSUE THREAD

**Issue by bzeeeb** [megai2/d912pxy#369]
Need to reinstall dxpy due to having an outdated version (2.2) and it's crashing in startup, can I keep the shader pack or should I drop that too?  Just takes so long to load stuff fresh.

I checked the shader pack wiki and seem like it was last updated in 2019?  Does that cover most of it? 

--
*Update I ended up reinstalling, but I wasn't sure how to unpack the shader pck, or do I just leave it as is and the leading "1_" will make gw2 pick it up?

**Comment by megai2** [comment]
1. You can keep old packs, while they are compatible. Just backup pck folder.
2. Ready to use packs are all outdated. Since speedup of compilation process, no one are up for updating them.
3. Game changes shaders with each update, so time-to-time cleanups are needed too.

**Comment by megai2** [comment]
Looks like question is answered
