### ISSUE TITLE
Display issues after install

### ISSUE THREAD

**Issue by hkelemental** [megai2/d912pxy#37]
Apologies if I am doing something incorrectly.

I tried installing d912pxy and got some graphical issues where the whole screen is mostly covered in flickering pixels/boxes, purple or multicolored. I have tried a few things, including the graphical issues steps in the readme. GW2 does not crash, and the issue happens at character select and when i select character/world loads.

I don't know if it's normal or a perms issue, but the install.bat and uninstall.bat mention issues finding a file.

It looks like something involving Antialiasing or post processing, as the issue is lessened but not removed if those settings in GW2 are lowered as far as they can go.
I am running:
Windows 10 1809
Direct X 12
Avast Antivirus
AMD FX-8350
AMD R9 Fury

Here's all my screenshots, including different settings, TS, and no issues screenshot after running remove.bat:
[d912pxy stuff.zip](https://github.com/megai2/d912pxy/files/2800396/d912pxy.stuff.zip)
[P7logs.zip](https://github.com/megai2/d912pxy/files/2800430/P7logs.zip)

**Comment by megai2** [comment]
check if this persist with latest version

**Comment by megai2** [comment]
You don't need to paste in sources, ony binary files.
Your installation is fine. 
Thx for crashreport, working on it.
