### ISSUE TITLE
Frame loss issue for multi gpu user

### ISSUE THREAD

**Issue by BlackRussians** [megai2/d912pxy#370]
I am currently using 2 graphic cards not SLI.
![photo](https://user-images.githubusercontent.com/13686736/116834817-bf9f6480-abfa-11eb-98ce-4a8b74fa8926.jpg)

My gpu index orders on my windows are gpu0 rtx 3070, gpu1 rtx 2070 super.
I am mainly using rtx 2070 super on my computer when I play game because i am only using rtx 3070 for mining.
But whenever I use d912pxy, it uses rtx 3070 card as gpu copy not 3d. so there was a lot of frame loss.
I am guessing maybe d912pxy program use preferentially gpu0.

Can you add gpu select option for multi gpu user?

[log.txt](https://github.com/megai2/d912pxy/files/6412575/log.txt)

**Comment by megai2** [comment]
added gpu selection via config

look for lines in log

0: VRAM: 005980 Mb | FL: FL_12_1 should work 100% (15) | NVIDIA GeForce RTX 2060
1: VRAM: 000128 Mb | FL: FL_12_1 should work 100% (15) | Intel(R) UHD Graphics 630

and select needed gpu by

[dx]
force_gpu_index=1

**Comment by BlackRussians** [comment]
Thanks for adding new feature.
It is working well !!
