### ISSUE TITLE
Is this glitch caused by d912pxy?

### ISSUE THREAD

**Issue by SaiyanOfDarkness** [megai2/d912pxy#372]
Asking for a guildie...

![image](https://user-images.githubusercontent.com/24264268/118403349-a56e7900-b633-11eb-8dc7-ffecb344bd7d.png)

**Comment by megai2** [comment]
There was some problems with same-ish looking artifacts, but it solved long ago.
So i suggest checking system stability and installing proper GPU drivers first.

**Comment by megai2** [comment]
Runned validation tests and there is nothing wrong found. 
As there is no more info to dig into problem(logs, hardware info), i close this for now as this looks to be a problem with hardware/driver.
