### ISSUE TITLE
Dragonstorm graphics

### ISSUE THREAD

**Issue by mickebo** [megai2/d912pxy#373]
First:
d912pxy works just flawless everywhere in the game but Dragonstorm.

**Describe the bug**
Almost no graphics in Dragonstorm

**To Reproduce**
Steps to reproduce the behavior.

1. Run game
2. Set graphics settings to: using same settings as in rest of game where d912pxy works flawless.
3. Head to Dragonstorm location
4. Do this: just enter the map

**Expected behavior**
Be able to see ground, mobs, players, well the map is expected, but I dont.
It is the same in story or meta.

**Screenshots**
![gw003](https://user-images.githubusercontent.com/84439024/118782932-df878700-b88e-11eb-832b-f3f986910458.jpg)
![gw005](https://user-images.githubusercontent.com/84439024/118782950-e3b3a480-b88e-11eb-80d6-8e03d98c1b10.jpg)
![gw007](https://user-images.githubusercontent.com/84439024/118782964-e615fe80-b88e-11eb-90c0-157bb6f5a2f8.jpg)

**Standard information**

1. Windows 10 update ver: Windows 10 Pro 20H2 19042.985, Windows Feature Experience Pack 120.2212.2020.0
2. Hardware info: 11600K, 32gb ram, 2080TI
3. GPU Driver version: 466.47 but it didnt work with the earlier ones either
4. Version of d912pxy used: d912pxy_v2.4.3.2_r687
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
[log.txt](https://github.com/megai2/d912pxy/files/6507157/log.txt)

**Additional context**
Tried to Set"enable_profiling=1" in config but cannot find setting?
Uninstalled d912pxy and graphics in Dragonstorm works.
Installed d912pxy again, but GW2 crashes on start. Put my own old config file and it starts as it should.
[myownconfig.txt](https://github.com/megai2/d912pxy/files/6507212/myownconfig.txt)
Problem is still there.
Have I maybe messed up my config?

**Comment by megai2** [comment]
This maps need proper occlusion query emulation to work properly
For this you need to set replay threads to 1

```
[replay]
replay_threads=1
```

**Comment by mickebo** [comment]
Thank you, works perfectly.

I would be very happy for some advice on my config.

**Comment by megai2** [comment]
You can use any supplied configs, most of time they do the trick
