### ISSUE TITLE
Crash to Desktop during Meta events(?)

### ISSUE THREAD

**Issue by dokbanks** [megai2/d912pxy#382]
Crashed me and lots other when the Gerent spawned in on SCAR. Not using arcdps or other addons. Any other info can be provided on request!

**Comment by dokbanks** [comment]
Sorry for lack of information! If there's any logs that need attaching I can try my best to find them for you.

**Comment by dokbanks** [comment]
Ok found the log from \dx912pxy
[log.txt](https://github.com/megai2/d912pxy/files/6620407/log.txt)

**Comment by dokbanks** [comment]
Crashed again for me and others during Death Branded Shatterer 
[log.txt](https://github.com/megai2/d912pxy/files/6620520/log.txt)

**Comment by LinearBotSystems** [comment]
I'm not sure what they done with yesterdays update but for me the game become unplayable by having heavy fps drops and freezes. Maybe this has to do with this too.

**Comment by IsmetBesic** [comment]
@dokbanks, one of the attached logs seems to be showing issues with cached PSO items - have you tried clearing your shader cache since updating already? 

`C28DB9 [ error ] PSO item | cached CreateGraphicsPipelineState error 887E0002 for 1510FC162BB2DE17_C15CB304EEEB5C2C_41331F0CF8DD7217 `

**Comment by LinearBotSystems** [comment]
I'm only sitting on the side here but I needed to delete my shader cache too yesterday otherwise Gw2 wouldn't start only freeze on the login screen. I'm not sure what they done but they done something again otherwise this wouldn't be necessary.

**Comment by dokbanks** [comment]
> 
> 
> @dokbanks, one of the attached logs seems to be showing issues with cached PSO items - have you tried clearing your shader cache since updating already?
> 
> `C28DB9 [ error ] PSO item | cached CreateGraphicsPipelineState error 887E0002 for 1510FC162BB2DE17_C15CB304EEEB5C2C_41331F0CF8DD7217 `

Hi there! Thank you for the advise, although I am unsure how I do that? If you could tell me how, I'll give it a try and see if I experience more crashes today! Thank you!

**Comment by LinearBotSystems** [comment]
> 
> 
> > @dokbanks, one of the attached logs seems to be showing issues with cached PSO items - have you tried clearing your shader cache since updating already?
> > `C28DB9 [ error ] PSO item | cached CreateGraphicsPipelineState error 887E0002 for 1510FC162BB2DE17_C15CB304EEEB5C2C_41331F0CF8DD7217 `
> 
> Hi there! Thank you for the advise, although I am unsure how I do that? If you could tell me how, I'll give it a try and see if I experience more crashes today! Thank you!

Go to the C:\Program Files\Guild Wars 2\d912pxy\   folder and delete latest.pck

**Comment by IsmetBesic** [comment]
> > > @dokbanks, one of the attached logs seems to be showing issues with cached PSO items - have you tried clearing your shader cache since updating already?
> > > `C28DB9 [ error ] PSO item | cached CreateGraphicsPipelineState error 887E0002 for 1510FC162BB2DE17_C15CB304EEEB5C2C_41331F0CF8DD7217 `
> > 
> > 
> > Hi there! Thank you for the advise, although I am unsure how I do that? If you could tell me how, I'll give it a try and see if I experience more crashes today! Thank you!
> 
> Go to the C:\Program Files\Guild Wars 2\d912pxy\ folder and delete latest.pck

More precisely, it's inside the "pck" folder inside the "d912pxy" folder.

**Comment by dokbanks** [comment]
> 
> 
> > > > @dokbanks, one of the attached logs seems to be showing issues with cached PSO items - have you tried clearing your shader cache since updating already?
> > > > `C28DB9 [ error ] PSO item | cached CreateGraphicsPipelineState error 887E0002 for 1510FC162BB2DE17_C15CB304EEEB5C2C_41331F0CF8DD7217 `
> > > 
> > > 
> > > Hi there! Thank you for the advise, although I am unsure how I do that? If you could tell me how, I'll give it a try and see if I experience more crashes today! Thank you!
> > 
> > 
> > Go to the C:\Program Files\Guild Wars 2\d912pxy\ folder and delete latest.pck
> 
> More precisely, it's inside the "pck" folder inside the "d912pxy" folder.

Ok great, thank you for that, I've now done that and see how I get on tonight!

**Comment by mickebo** [comment]
same issue and deleting latest.pck worked fine for me

**Comment by LinearBotSystems** [comment]
> 
> 
> same issue and deleting latest.pck worked fine for me

Well let me know if you have still fps problems so that I'm not alone xD

**Comment by dokbanks** [comment]
Yes, everything seems fine now that the latest.pck file was deleted, so far so good, thank you very much for helping! I'm getting the same performance wise as I was before XD
