### ISSUE TITLE
Crashing when loading into world on latest patch

### ISSUE THREAD

**Issue by royalmustard** [megai2/d912pxy#388]
**Describe the bug**
Loading into the character screen works fine, but when I select a character I first get the loading screen and then it crashes.

**To Reproduce**
Start game on latest patch. Select character

**Standard information**

1. Windows 10 latest stable
2. Hardware info: i5-7500, 16GB RAM, GTX1060 6GB
[log.txt](https://github.com/megai2/d912pxy/files/6890771/log.txt)
[crash.txt](https://github.com/megai2/d912pxy/files/6890773/crash.txt)

**Comment by IsmetBesic** [comment]
Update arcdps. Moreover, consider rebuilding your shader cache - your log points to many files inside the pck folder being unreadable by the most recent version of d912pxy by now.

**Comment by megai2** [comment]
Yep, don't forget to update your arcdps every patch.
