### ISSUE TITLE
Virus detected by VirusTotal

### ISSUE THREAD

**Issue by darkretailer** [megai2/d912pxy#389]
VirusTotal has found Trojan.Malware.300983.susgen within your current last release.
https://www.virustotal.com/gui/file/13f64119dac962b5d41a2644edc13a7eddc3e469e8b433bd977d15f772a8ec7f/detection

**Comment by megai2** [comment]
This is false-positive trigger on install.exe because it does very simple file copy. 

68 of 69 checks are in green, so i close issue for now
