### ISSUE TITLE
A Possible way to stress test FPS.

### ISSUE THREAD

**Issue by magnapeccatrix** [megai2/d912pxy#39]
Hello, I've found this method that lowers FPS a lot.
Not sure if it's a legit way to test fps but if you want to do it, requirements are:
-Frostfang axe
-Endless Miniature Tonic
Put character on walking mode and just spam movement keys while holding mouse right click.
https://www.youtube.com/watch?v=HGF0FrOjAt4

**Comment by megai2** [comment]
Interesting. Can you look up on memory/video memory usage with this running?
Cause it can be gw2 engine related if memory usage shows no odd behaivour.

**Comment by magnapeccatrix** [comment]
Hello, this fps drop isn't related to tool. Been happening on original dx9 as well.

**Comment by megai2** [comment]
Will be nice if you check for memory behaivour anyway.

**Comment by magnapeccatrix** [comment]
Okay, I will try, have 1 monitor and tool was working only on fullscreen for me, otherwise alt-tab is freezing the last frame and can't reach task manager to end process (I can see desktop and cursor, can click on task bar too but whenever cursor leaves task bar territory, nothing is clickable and focus switches to frozen game frame so I have to restart PC to fix it)

**Comment by megai2** [comment]
Looks like it behaving correct. Thanks for testing out.

**Comment by magnapeccatrix** [comment]
Could this be a way to stress test the tool and see if it's doing well compared to dx9, instead of trying to get in 50 people squad events?

**Comment by megai2** [comment]
no
