### ISSUE TITLE
Game crashes on character screen after installation

### ISSUE THREAD

**Issue by Erebos86** [megai2/d912pxy#397]
Hello megai2, 

i try to use your DX12 mod for GW2, but unfortunately the game crashes everytime. Could you help me ?

**Before starting**
Please read [troubleshooting](https://github.com/megai2/d912pxy#troubleshooting) section of README.md

--> Done

Please remove/disable all possible interfering software before reporting anything, so you are sure that bug comes from this project.

--> Razer Central and TS3 deactivated, no Overlay mods or something used. Standard GW2 Installation

**Describe the bug**

After installing the DX12 mod according to the instructions and starting the game, the overlay query of your mod comes up in the charackter screen. After I have confirmed the query, it comes to GW2.exe crash. 
After restarting, there is no more overlay and the crash happens immediately.

The troubleshooting was done according to instructions. MSVC (x86 and X64) was updated, DX 9 as well. Graphics drivers are always up to date through Nvidia Geforce Expirience.

The mod was uninstalled before. Reinstalled after updates. Same procedure. Debugmode was started, error reproduced.

After uninstalling the mod, GW2 works normally again. 

All data was collected, a Github account created and here I am now for the bug report :-)

**To Reproduce**
Steps to reproduce the behavior.

1. Run game --> Game crashes on character screen

**Expected behavior**
I would have expected the game to start normally :-)

**Screenshots**
None

**Standard information**

1. Windows 10 Pro 64 Bit, Version 10.0, Build 18363
2. Hardware info: 
   CPU : Intel Core i9-9900k 3,6 Ghz , 16 CPUs 
   RAM: 65536 MB Ram
   GPU: Nvidia Geforche RTX 2070 Super
3. GPU Driver version
4. Version of d912pxy used:   v2.3h6_r628
5. Log file from <game root>/P7logs folder or d912pxy/log.txt and d912pxy/crash.txt if exist
  --> see attachement
[crash.txt](https://github.com/megai2/d912pxy/files/7100831/crash.txt)
[log.txt](https://github.com/megai2/d912pxy/files/7100834/log.txt)

**Additional context**
Add any other context about the problem here. --> GW2 crash report speaks about a Memory-Error. No other context known.

**Comment by megai2** [comment]
Hello.
v2.3 no longer works, use latest release.

**Comment by Erebos86** [comment]
hmm... I thought i´ve clicked on : https://github.com/megai2/d912pxy/releases
but perhaps i´ve got the old version via a old link in an video discription :-)

Thanks for the hint, now it works :D
