### ISSUE TITLE
Crash with AMD Driver 21.8.2

### ISSUE THREAD

**Issue by Xtreme89** [megai2/d912pxy#399]
HI,

i have Crash with the AMD Graphics Version 21.8.2 i use the latest Version from d912pxy - Windows are Up2Date with latest Version from Windows 10

I have also try to clear cache from d912pxy and deinstall/install

LogFile See Attachment

![Unbenannt](https://user-images.githubusercontent.com/11071616/133240350-1d15132d-cc0f-42d4-bc19-bffff9da773a.png)
[log.txt](https://github.com/megai2/d912pxy/files/7161013/log.txt)

**Comment by Xtreme89** [comment]
I try to disable the Nahimic Service on Windows, but still the same error any other ideas?

**Comment by Xtreme89** [comment]
GrahpicDriver is Now 21.10.4 and i disable AlienCommand,
here is the new log file - any ideas?
[log.txt](https://github.com/megai2/d912pxy/files/7458764/log.txt)
le

**Comment by megai2** [comment]
try running not in fullscreen (change settings on dx9 before using dx12)

try changing dheap_mode to 1 in config under [compat] section (d912pxy/config.ini) 

also there is driver overlay (amd ags i guess?) maybe it also acts up

other options is setting debug to 1 in config upder [dx] setction 
but it needs graphic tools to be installed on system

**Comment by Xtreme89** [comment]
> try running not in fullscreen (change settings on dx9 before using dx12)
> 
> try changing dheap_mode to 1 in config under [compat] section (d912pxy/config.ini)
> 
> also there is driver overlay (amd ags i guess?) maybe it also acts up
> 
> other options is setting debug to 1 in config upder [dx] setction but it needs graphic tools to be installed on system

Hi,

Thanks i will try these Options. I will post the results


Thanks

**Comment by Xtreme89** [comment]
Hi,

nothing helps. Here is the Log File
[gw2_log.txt](https://github.com/megai2/d912pxy/files/7495513/gw2_log.txt)

[log.txt](https://github.com/megai2/d912pxy/files/7495515/log.txt)

**Comment by megai2** [comment]
Unfortunately i don't see any debug marks in log, so it should be digged around via debug build and other debug stuff.
I think that is not worth it for now, better use gw2 dx11 beta so developers can work on it by actual user feedback.
