### ISSUE TITLE
Guild Wars 2 Using Direct X 11 Natively test phase.

### ISSUE THREAD

**Issue by ReiHinoSenshi** [megai2/d912pxy#401]
So as gw2 did not go all the way to Direct X 12 any plans to do a Direct X 11 to 12? Just because Anet stopped just short...So not as much of a issue as a question.

**Comment by sicu** [comment]
Here you go: https://github.com/megai2/d912pxy/issues/394#issuecomment-907744578

**Comment by ReiHinoSenshi** [comment]
And thanks for the reply :)
