### ISSUE TITLE
large ram allocation?

### ISSUE THREAD

**Issue by Me4fun** [megai2/d912pxy#404]
Commit Kb in resource monitor is 8,721,000 KB is that normal?
[log.txt](https://github.com/megai2/d912pxy/files/7538300/log.txt)

**Comment by Me4fun** [comment]
[log.1.txt](https://github.com/megai2/d912pxy/files/7538307/log.1.txt)

**Comment by megai2** [comment]
Yes, that is normal. d912pxy uses greedy allocation to reduce stutters by default.
