### ISSUE TITLE
replay thread sync crashes

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#41]
based on reports #40 #37 #36 #30

**Comment by rkujo** [comment]
[P7logs.zip](https://github.com/megai2/d912pxy/files/2802429/P7logs.zip)

Crashes from Istan farm I'm using 417.71 driver on gtx 980 if you have driver recommendations im happy to try. I would like to try it in wvw raid today but it crashes too much for that for now.

**Comment by rkujo** [comment]
Also it doesnt create any txt crashes is it something missing from latest build?

**Comment by megai2** [comment]
> Also it doesnt create any txt crashes is it something missing from latest build?
Looks like it bypasses all crash handling in my code and gw2 code. 
I should make some improvements on crash handling, so it's fine that there is no txt crash logs.
