### ISSUE TITLE
tree shader transparency error

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#44]

**Comment by changeofplans** [comment]
This was fixed for me on v0.9.5.8 for me and broken again on v0.9.5.9.

**Comment by xvwyh** [comment]
Fixed for me as of 0.9.6a.

**Comment by changeofplans** [comment]
It is still not fixed in the latest version. 
![2019 02 07-15 54_01](https://user-images.githubusercontent.com/13071635/52432567-de812000-2af1-11e9-80ec-dc9b070143e2.png)

**Comment by megai2** [comment]
Looks like shader cache is got invalid and there was no common.hlsli file update on your side.
Anyway, works fine on build 40.
Tested areas: metrica, mount maelstrom, cliffside fractal.
