### ISSUE TITLE
Running OBS-Studio with D912 active causes GPU to go into low power 3D mode, resulting in loss of performance

### ISSUE THREAD

**Issue by moriz1** [megai2/d912pxy#48]
repro step:
-run GW2 with D912 active
-run GPU-Z to see clock speeds
-open OBS-Studio (latest public version)

you should see a sudden drop in GPU clock speed and utilization as soon as OBS-Studio opens.

ingame, FPS instantly drops by half (due to VSync, probably) to 30 fps.

this behavior is NOT observed with D912 disabled.

hardware:
-Ryzen 2700X
-RTX 2080 Ti
-nvidia driver version 417.71

EDIT:

after further testing, i've noticed the following interesting effects:
-the issue only seems to appear if i use a **capture card**. if i use display capture in OBS:S, clock speed and FPS are not affected
-further from above, if i have "Display Capture" as one of the sources, then the problem goes away. this is true even if I have "Video Capture Device" as a source active as well, and even if I overlap "Display Capture" completely with the capture card input.
-as soon as I disable Display Capture, the issue comes back.

**Comment by moriz1** [comment]
OBS 22.0.2, 64-bit.

encoder doesn't matter; merely having OBS Studio open would cause the clock speed drop.

power settings in Nvidia control panel has no effect.

**Comment by guzmanuy** [comment]
Ok, im on the pc now, 3 monitors , 1 of them running on intel integrated graphics of my processor, 2 of them on a gtx 1060 6gb , Principal screen with gw2 with d9d12 active, obs studio working fantastic on the second one so far, had some clockspeed falls, but it recovered ,card running at 1974mhz. Note: im using not the original obs studio build, im using the beta one that uses the optimization for NVENC encoder.

**Comment by moriz1** [comment]
i think the key thing here is that i'm using a capture card. see my edit of my original post.

**Comment by guzmanuy** [comment]
Interesting...dunno why you're having this problem then, since i dont use any capture cards like elgato hd my only advice its to ckeck all the configs , maybe theres someting there.

**Comment by megai2** [comment]
Maybe capture card do some syncing thru DXGI, making your GPU to be underloaded resulting in low clocks.
Suggest try fullscreen.

And if you really want to bench out/have better performance, try to use something NVFBC enabled, like GFE/Shadowplay or cap. card(but giving this thread there is something to troubleshoot over). There is a way to config it to run over custom ngnix rtmp server. Best practice is to set that server on another pc and run OBS on it.

**Comment by megai2** [comment]
think this is resolved for now

**Comment by moriz1** [comment]
it's not resolved. same behavior as before.

i found a workaround: merely having a "display capture" source active, even if it is completely covered, makes the problem go away.
