### ISSUE TITLE
Skybox bugged during day->night and night->day transitions

### ISSUE THREAD

**Issue by moriz1** [megai2/d912pxy#50]
During dusk and dawn, the skybox would immediately take on a peach-orange hue. This would persist for the entire duration of the transition. This is especially noticeable at the instant the day-to-night transition starts, when the sky instantly turn from pale blue to a pale peach color. this peach color would slowly darken over the span of dusk until it becomes a dark muddy orange, until the game fully shifts into night, when the sky instantly snap between muddy orange to dark-gray-blue (which is the proper night color).

the transition is reversed for night-dawn-day.

**Comment by megai2** [comment]
https://github.com/megai2/d912pxy/blob/master/README.md#troubleshooting
