### ISSUE TITLE
AMD hw glitching

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#52]
Alright so I ran the game again with the deleted .psk, waited for each shader setting to load (around 3 minutes each) and well there was not much in-game difference from Low to High. Except in Character Select where the differences are very obvious from Low to the other two. I didn't encounter any crashes but I also didn't try anything apart switching from Windowed Fullscreen to Simple Windowed, I'll attach the logs after deleting the .psk, hopefully they'll help. Pictures in char select are from Low to High : 

![screenshot_5](https://user-images.githubusercontent.com/37269606/51877134-bc5e0400-2373-11e9-8a03-2748f24ca0b7.jpg)
![screenshot_7](https://user-images.githubusercontent.com/37269606/51877143-c253e500-2373-11e9-9338-3cecb1c040a9.jpg)
![screenshot_8](https://user-images.githubusercontent.com/37269606/51877148-c6800280-2373-11e9-8cec-812b9b97d281.jpg)
![screenshot_1](https://user-images.githubusercontent.com/37269606/51877154-cd0e7a00-2373-11e9-88e4-72318f519d34.jpg)
![screenshot_2](https://user-images.githubusercontent.com/37269606/51877159-d4358800-2373-11e9-9ae1-18021285db6d.jpg)
![screenshot_3](https://user-images.githubusercontent.com/37269606/51877171-e3b4d100-2373-11e9-8b26-ba69b3e71dfc.jpg)
![screenshot_4](https://user-images.githubusercontent.com/37269606/51877182-e9121b80-2373-11e9-810d-e98d33594800.jpg)

[Logs from v0.9.5.8a number 2 (after deleting shaders_cso.psk).zip](https://github.com/megai2/d912pxy/files/2805618/Logs.from.v0.9.5.8a.number.2.after.deleting.shaders_cso.psk.zip)

_Originally posted by @BaseSquare in https://github.com/megai2/d912pxy/issues/45#issuecomment-458368803_

**Comment by ZTHawk** [comment]
I am running version d912pxy_v0.9.5.9a and having the same issue.
GPU: AMD 390

**Comment by megai2** [comment]
no changes with d912pxy/pck/shaders_cso.pck removal?

**Comment by ZTHawk** [comment]
I have removed d912pxy/pck/shaders_cso.pck. The moment the first geometry was visuble the visual error occurred.
Background, cursor and HUD seems not to be affected.
If I stand still then the areas where no animation is going on have an unchanged visual error. So it looks like if it is static.
If I move the camera around and I look precisely at all the artifacts then the seem to keep their shape most of the time.
I can also see names and visual errors of other characters (when they are moving) through walls.

**Comment by megai2** [comment]
Check with post processing: none, antialiasing: none, amblient occlusion: none and depth blur: none settings.

**Comment by ZTHawk** [comment]
Disabled those options.
Tested with window, window fullscreen and fullscreen.
Additionally I tested with settings set to "best performance" and "best appearance". No change.
Visual errors and "wallhack".

**Comment by Throne3d** [comment]
I have the same issue, on an ATI AMD Radeon R5 M335. Interestingly, it also seems to happen when I use my integrated graphics (Intel Core i7 6600U, Intel HD Graphics 520), but I'm not sure why that would be, and it might be that I'm misconfiguring something when testing that. v0.9.5.9 doesn't seem to have fixed it. No noticeable difference when using `ps` mode or after removing d912pxy/pck/shaders_cso.pck.

The graphical glitches do not apply to the inventory or settings panel, and they seem to apply differently to mounts and my character from the scenery. They're mostly static (as if it's a texture issue with some kind of overlay effect?), but this changes based on camera positioning and sometimes when moving in-world. I think the glitches are worse in shadowed areas?

**Comment by BaseSquare** [comment]
New version didn't change much for me too. Shaders are still the same, followed the settings again and pretty much tried everything from scratch since it's a new version but nothing.

One thing I noticed is that Low Shader settings improve the static glitchyness, pictures from Low to Medium to High : 

![screenshot_7](https://user-images.githubusercontent.com/37269606/51936857-d0584300-2411-11e9-9faa-c474c7660376.jpg)
![screenshot_8](https://user-images.githubusercontent.com/37269606/51936867-d51cf700-2411-11e9-9ecc-c37eb5b780b4.jpg)
![screenshot_10](https://user-images.githubusercontent.com/37269606/51936871-d8b07e00-2411-11e9-9fb1-bcfefde251da.jpg)

**Comment by megai2** [comment]
So only shader settings have effect on it?

**Comment by Throne3d** [comment]
Shader settings have no impact for me (except on the underlying image):

- Low: https://puu.sh/CEgBg/5fb1dc4f54.png
- Medium: https://puu.sh/CEgBy/a72c1c0a37.png
- High: https://puu.sh/CEgCu/0888b40295.png

Shadows are doing really weird things (on both my integrated and regular graphics card):

- None: https://puu.sh/CEgH2/a621168d94.png
- Low: https://puu.sh/CEgHg/9b390176a3.png
- Medium: https://puu.sh/CEgHQ/f2ceb4746f.png
- High: https://puu.sh/CEgIe/a77e020f29.png

(This might not be related. If I start the game with shadows on "High", then switch to "None", the issue happens there, too, briefly. It might just be slow to load.)

None of the following seem to affect it: Animation, Antialiasing, Environment, LOD Distance, Reflections, Textures, Shaders, Postprocessing, Character Model Limit, Character Model Quality.

Switching between different Render Sampling values with Shadows set to "None" seems to fix it until something moves across my camera or I move my camera. (It also decreases the size of the artifacts when I use "Native" or "Supersample" instead of "Subsample".) It also looks like my raptor's tail is leaving artifacts when I run around, when it moves across my display.

Can someone else verify these? My computer has really bad specs, which might be causing some of this.

**Comment by BaseSquare** [comment]
As for me changing shadows had a weird effect as in making everything kinda darker. I would call it being worse than Shadows Off.

So I wouldn't say that ONLY the shaders setting had an effect, but the effect changing from Shadows in my game was not that significant. But I won't say that there was no change at all.

**Comment by megai2** [comment]
I'm out of ideas for now. Pointing out problem right now need some frame debugging like RenderDoc.

**Comment by changeofplans** [comment]
I had the same problem, but I don't have any glitches since a few builds back. Rx 580 8gb here. I do a clean install on every update if that helps.

**Comment by Riwaha** [comment]
When reflections is set to all, looking straight down, you can see what looks like shadows(even when shadows is `none`) or perhaps the outlines of the model(NPCs, mounts, buildings) on the screen in the artifact areas, even though these models are offscreen. This was most noticeable around the Lion's Arch bank and Grand Plaza looking toward Fort Mariner.

I am not sure this is related to the issue, but I felt I should add this. It almost seems like a depth issue, since the artifacts are not clearing.

**Comment by Throne3d** [comment]
I've never used RenderDoc before, but I tried looking into it. Problem is, whenever I start Guild Wars 2 under RenderDoc, it crashes right after the launcher. I'm using `d912pxy_v0.9.6.1a`. If I remove d912pxy, Guild Wars 2 crashes right after the launcher again, but this time RenderDoc contains diagnostic errors like `d3d11_shader_cache.cpp( 272) - Error   - Couldn't create pixel shader for RENDERDOC_CopyMSToArray E_INVALIDARG`, I assume because it only works with d3d11 and up.

Any idea why it might crash with RenderDoc, and how I can try to fix that? I could also run a different frame debugger if you know of one, but I'm very inexperienced at graphics debugging.

**Comment by megai2** [comment]
RenderDoc needs a patch to run anything with d3d9 usage.

Use this capture. https://yadi.sk/d/yS3AviUmM9rbmg
Try to find on what API call frame bugs out.

**Comment by Throne3d** [comment]
I'm not actually seeing the same bug in that frame when I try replaying it using RenderDoc. https://puu.sh/CIILF/44ef0be53f.jpg I opened the file, then used Tools > Start Replay Loop, on my integrated graphics, which I'm guessing is the correct procedure. (Trying to use my graphics card has RenderDoc crash on me during the loading process: `Invalid state adding resource mapping - id is invalid or live pointer is NULL`?)

**Comment by megai2** [comment]
> 
> 
> I'm not actually seeing the same bug in that frame when I try replaying it using RenderDoc. https://puu.sh/CIILF/44ef0be53f.jpg I opened the file, then used Tools > Start Replay Loop, which I'm guessing is the correct procedure, on my integrated graphics. (Trying to use my graphics card has RenderDoc crash on me during the loading process: `Invalid state adding resource mapping - id is invalid or live pointer is NULL`? This shouldn't matter given that both my integrated graphics and graphics card produce the issue in practice.)

can you save resulting image in 1:1 scale?

**Comment by Throne3d** [comment]
I think that image was at 1:1 scale, though cropped. I can't figure out how to save the whole image through RenderDoc (saving textures seems to get me black images), but here's an attempt to capture more of the screen: https://puu.sh/CIKfr/122b400191.jpg

And in the texture viewer: https://puu.sh/CIKkH/57248df027.png

**Comment by megai2** [comment]
> 
> 
> I think that image was at 1:1 scale, though cropped. I can't figure out how to save the whole image through RenderDoc (saving textures seems to get me black images), but here's an attempt to capture more of the screen: https://puu.sh/CIKfr/122b400191.jpg
> 
> And in the texture viewer: https://puu.sh/CIKkH/57248df027.png

Save them in BMP as alpha channel makes them transparent.

Look up on draw 1275 draw 1037 draw 1064

Also check that your GPU(even CPU internal) is in use, maybe it using sofrware rasterizer.

**Comment by megai2** [comment]
Also, will be nice to see logfile from latest version.

**Comment by Throne3d** [comment]
GPU is definitely in use by qRenderDoc, according to Task Manager. GitHub doesn't support BMP, so I've put the images into this zip file:

[draws-2019-02-07-20-32.zip](https://github.com/megai2/d912pxy/files/2842565/draws-2019-02-07-20-32.zip)

Here are the log files with `d912pxy_v0.9.6.1a`:
[20190207-20472500.zip](https://github.com/megai2/d912pxy/files/2842610/20190207-20472500.zip)

(I also tried it with the debug mode, but those logs are like 300MB – I can probably send them if you really want, but I've sent the non-debug ones first, instead.)

**Comment by Throne3d** [comment]
… Hm, so I just found something interesting which is probably relevant: with d912pxy, when I set Guild Wars 2 to use my integrated graphics, it still uses my graphics card. (Without d912pxy, it obeys what I set it to use in the AMD settings app.)

The bug might not be showing in RenderDoc for me because of this – RenderDoc is definitely using my integrated graphics, and apparently all my GW2 d912pxy images have used my graphics card instead.

I'll look into getting RenderDoc to work with my graphics card.

**Comment by megai2** [comment]
> 
> 
> I got it working (…by just restarting my computer…)! Here's a sample showing the graphical glitches:
> 
> [draws-2019-02-07-22-32.zip](https://github.com/megai2/d912pxy/files/2842911/draws-2019-02-07-22-32.zip)
> 
> It looks like draw 1037 doesn't have them (unless they're well hidden), whereas 1064 _definitely_ does, and then so does 1275 and the final image. Hopefully this helps! I'll prod around a bit more to see if I can track it down any better, but I might not have any luck.
> 
> (Edit: Actually, I have no idea how to track it down further – trying to break down the collection from 1043-1064 doesn't seem to change anything in the texture viewer, and only seems to only change the mesh output substantially in draw 1044. :P)

what about alpha channel on draw 1037?

**Comment by Throne3d** [comment]
The alpha of draw 1037 _doesn't_ have the artifacts:
[draw3_1037_2drendertarget_alpha.zip](https://github.com/megai2/d912pxy/files/2843148/draw3_1037_2drendertarget_alpha.zip)

(Sorry about the delay - RenderDoc had yet more crashing issues, and I don't know why.)

The alpha of 1064 _does_ have them: 
[draw3_1064_2drendertarget_alpha.zip](https://github.com/megai2/d912pxy/files/2843154/draw3_1064_2drendertarget_alpha.zip)

And draw 1275's also _doesn't_ have the artifacts (but its alpha only shows the raptor in the distance anyway):
[draw3_1275_2drendertarget_alpha.zip](https://github.com/megai2/d912pxy/files/2843155/draw3_1275_2drendertarget_alpha.zip)

**Comment by megai2** [comment]
> 
> 
> The alpha of draw 1037 _doesn't_ have the artifacts:
> [draw3_1037_2drendertarget_alpha.zip](https://github.com/megai2/d912pxy/files/2843148/draw3_1037_2drendertarget_alpha.zip)
> 
> (Sorry about the delay - RenderDoc had yet more crashing issues, and I don't know why.)
> 
> The alpha of 1064 _does_ have them:
> [draw3_1064_2drendertarget_alpha.zip](https://github.com/megai2/d912pxy/files/2843154/draw3_1064_2drendertarget_alpha.zip)
> 
> And draw 1275's also _doesn't_ have the artifacts (but its alpha only shows the raptor in the distance anyway):
> [draw3_1275_2drendertarget_alpha.zip](https://github.com/megai2/d912pxy/files/2843155/draw3_1275_2drendertarget_alpha.zip)

so it bugs out on 1043 or you can note this somewhere inbetween 1037-1043 ?

**Comment by Riwaha** [comment]
I have been following along with this issue, and my outputs are the same as @Throne3d 

The issue starts on draw# 1043.

**Comment by megai2** [comment]
Try running without pck files. If this will help on glitching, then this is different PCF sampler behaivour.

**Comment by Riwaha** [comment]
I just deleted both pck files, I waited about 3 minutes, and it reappeared.

**Comment by megai2** [comment]
> 
> 
> I deleted both pck files and waited about 3 minutes, it reappeared.

Same bug pattern?

**Comment by Riwaha** [comment]
Yes, the pattern was matching.

**Comment by Riwaha** [comment]
I just rebooted and after clearing all shader caches, including AMD shader cache, I also downloaded the appveyor build of your latest changes.
Setting reflections: off, ambient occlusion: off, I don't see the pattern anymore on the ground, I am only seeing the buggy "squares" on the screen(invisible walls, buggy nameplates).

**Comment by megai2** [comment]
> 
> 
> I just rebooted and after clearing all shader caches, including AMD shader cache, I also downloaded the appveyor build of your latest changes.
> Setting reflections: off, ambient occlusion: off, shadows: off, I don't see the pattern anymore on the ground, I am only seeing the buggy "squares" on the screen(invisible walls, buggy nameplates).

**Comment by Riwaha** [comment]
I just tried changing all the settings and waiting for the shaders to load, I can't get the pattern outlined red, but the outlined green is still there.
![output](https://user-images.githubusercontent.com/35466177/52481359-4c722980-2b7c-11e9-9f89-57be3efe3e8a.png)

**Comment by megai2** [comment]
try latest build when it compiles up, but not forget to install it cleanly(remove d912pxy folder first)

**Comment by Riwaha** [comment]
Tried with different settings, here are the results:
1: Reflections: None, Shadows: None, Ambient Occlusion: Off
![1](https://user-images.githubusercontent.com/35466177/52483354-b4773e80-2b81-11e9-9629-8acef28bfc53.png)

2: Reflections: All, Shadows: None, Ambient Occlusion: Off
![2](https://user-images.githubusercontent.com/35466177/52483426-e9839100-2b81-11e9-9933-b8d1205be303.png)

3: Reflections: None, Shadows: High, Ambient Occlusion: Off
![3](https://user-images.githubusercontent.com/35466177/52483540-35ced100-2b82-11e9-8ce5-9fd607f434eb.png)

4: Reflections: None, Shadows: Ultra, Ambient Occlusion: Off
![4](https://user-images.githubusercontent.com/35466177/52483616-5dbe3480-2b82-11e9-8b55-01e86da96930.png)

5: Reflections: None, Shadows: None, Ambient Occlusion: On
![5](https://user-images.githubusercontent.com/35466177/52483712-93fbb400-2b82-11e9-8561-478b145a88db.png)

**Comment by Riwaha** [comment]
Check the images again, I messed up my notes and labeled them one off, I am sorry.

**Comment by megai2** [comment]
On build 41? Please check that common.hlsli file IS updated and shader cache IS deleted.
Also try to run game without profiles.pck again.

If it still bugged, try to look closely on 1037-1043 draws, render targets on them are in floating point format. You need to adjust max-min range to actually see what is going on with them.

**Comment by Riwaha** [comment]
Yes, Build 41, Looking at 1038-1042, trying different values for min/max, all I see are black, white, or red textures.

**Comment by ZTHawk** [comment]
Test 0.9.6.2. Still issues but I think they are now worse. Shaders set to low are terrible.

**Comment by megai2** [comment]
> 
> 
> Test 0.9.6.2. Still issues but I think they are now worse. Shaders set to low are terrible.

Worse or terrible, is not a comparable statement. Screenshots/etc is.
Be shure that you did clean install.(old shaders_cso.pck are removed)

**Comment by ZTHawk** [comment]
Seems I was wrong because I tested it now at a new location. But nethertheless here are the screenshots.
Everything is set to max. First screenshot is with shaders set to high and second with shaders set to low.
Additionally some of the "white" areas with shaders set to low are flickering (no movement around that area).
(Screenshot taken in "The Forge" in "Thunderhead Peaks")
Yes I have done a clean install. Removed my old dx12pxy folder and copied the new one from 0.9.6.2.

Shaders High
![gw008](https://user-images.githubusercontent.com/23618799/52531037-609a6000-2d0f-11e9-8c7f-f6097bb5f9b9.jpg)
Shaders Low
![gw009](https://user-images.githubusercontent.com/23618799/52531038-6abc5e80-2d0f-11e9-9c3d-ec161f7d828f.jpg)

**Comment by megai2** [comment]
I added branch on this, check the build on appveyor.

**Comment by ZTHawk** [comment]
I see the branch but I do not understand what you mean with "appveyor". I do not see any new binary.

I have deleted the pck files and did a test with 0.9.6.2. This is the result:
![gw010](https://user-images.githubusercontent.com/23618799/52532474-2daf9680-2d26-11e9-884c-926e6b5789b9.jpg)

So deleting the cache makes things worse.

PS:
Do I need to use the _PS or _PP version in any way? I tried the _PS version and anfter recompiling I only had the normal visual issues from my previous post. But Shader Low was equal to High.

**Comment by Throne3d** [comment]
This is the appveyor: https://ci.appveyor.com/project/megai2/d912pxy/history

You can download the different versions by opening a specific commit's build in there (look for the latest amd_compat one), opening the right variant (e.g. Release), and downloading its artifact. e.g.: https://ci.appveyor.com/project/megai2/d912pxy/builds/22255309/job/kks0n6iivhywjet4/artifacts has "d912pxy_Release.zip" for the current latest commit of the amd_compat branch.

**Comment by ZTHawk** [comment]
I tried now the version from appveyor.
When using the PCK inside the package then I have the display issues.
When deleting the PCK and letting it to recompile then I get the "white" areas issue from my post above.

**Comment by megai2** [comment]
are results same for amd_compat latest(build 51)? 
when you use no profile, you should run default release build, not _ps one, cause ps generates profiles back.

**Comment by ZTHawk** [comment]
My last comment was for amd_compat build 51.
Amd_compat 51 has the display issues from the first post.
When deleting from amd_compat 51 the PCK files, then I get the "white" area issues.
So yes, amd_compat 51 has the same issues as 0.9.6.2.

**Comment by megai2** [comment]
Please add screenshots, as it more informational for me that just comments on how it looks like.
and as i see it keep build number 51(nah), so be shure on what build you use.

If there is no builds on amd_compat branch, that fix problem, let me know this, then 
I will start to making a more debbugish way to find a problem.

**Comment by megai2** [comment]
If there is no good results.

Here is the plan:
1. Set setting to max, except the internal resolution, keep it native.
2. Run Debug version (not Release_d)
3. Locate d912pxy\shaders\hlsl\c8e034d14c3e3a39.hlsl file on your installation
4. Tweak it until the problem is solved or source of it are found. 
4.1. Change file
4.2. Clear shader cache
4.3. Test
5. Report back on results

OFC you should have a programming skill and hlsl knoweledge to do this.

**Comment by megai2** [comment]
Added debug runtime messages redirection to logs for Debug version.
Try to running it and maybe there will be something usefull.

**Comment by Throne3d** [comment]
I've replaced my computer's hard drive, so I might not have all the libraries I had before, but attempting to use the Debug build of `d912pxy__r77` now nets me a crash at startup:

```
*--> Crash <--*
Assertion: Failed to load Coherent DLL: 0x7e 
File: ..\..\..\Engine\ArenaWeb\CoherentUi\AwCoh.cpp(50)
App: Gw2-64.exe 
Pid: 15240
BaseAddr: 00007FF772890000
ProgramId: 101
Build: 95112
When: 2019-02-14T22:41:45Z
Uptime:   0 days  0:00:01
Flags: 0
```

The Release version doesn't cause this crash. Debug on `v0.9.6.3a_r68` also causes this for me, as does `d912pxy__r81`. (Release versions load up fine and show the usual graphical glitches.)

**Comment by Throne3d** [comment]
Also, here's an updated screenshot – highest settings, except "render sampling" on "native", in windowed fullscreen 1920x1080, on Release `r77`:

![image](https://user-images.githubusercontent.com/577128/52824004-e66f3000-30ae-11e9-9a59-aadf59cc153e.png)

**Comment by Throne3d** [comment]
Update: we've been going through this some more in a GW2 discord, but haven't yet found any solutions. It might be a driver issue; I've had various crashes through the testing process that suggest there might be something up with mine.

I think we plan to prod at nameplates in the coming days to see if their weird rendering around these squares helps reveal any of the mystery :P

**Comment by megai2** [comment]
Nameplates pixel shader -  d6cdb18b52595352.hlsl
Here i can see only two things 

1. Alpha test - added a possible fix
2. Floating point texture sampling - maybe texture is broken on some passes, need a frame capture on this for shure. I have a fork of renderdoc that will work for d912pxy, but you should compile it by hand.

**Comment by megai2** [comment]
https://yadi.sk/d/wNG9xkpDcjuDbQ renderdoc capture with nameplates.
UI and nameplates is from draw 1911 to 2327

1. Check for glitch on nameplates.
2. If it is here, select any draw from 1911 to 2327
3. Then find "2d render target 8284" and view contens of it
4. Then select "channels: custom" in texture viewer, add new custom shader
5. Fill that shader with attached [test_shader.txt](https://github.com/megai2/d912pxy/files/2872383/test_shader.txt), hit refresh
6. Select newly made custom shader in texture viewer
7. You should see results: 
![suggested_result](https://user-images.githubusercontent.com/1693251/52905328-bdcf6d80-3249-11e9-947b-94055865eb35.png)


If you see that all is ok
1. Find a bugged out draw of nameplate, that use d6cdb18b52595352.hlsl shader (pipeline state -> PS)
2. Look up texture that bound in s0 slot for this draw. (![guide](https://user-images.githubusercontent.com/1693251/52905311-85c82a80-3249-11e9-9167-7d8bc6772bfe.png))
3. Attach this texure here, both RGB and A channel in 2 files(not jpg)

If you see that this is not ok
1. Check original "2d render target 8284" with default channels selected(i.e. no custom shader for preview)
2. Change min/max range to see actual image more detailed
3. If there is no errors on default view mode you can try extra:
Extra: try to change  test_shader.hlsl until it works properly

**Comment by Throne3d** [comment]
It seems fixed for me in `d912pxy_v0.9.6.5a_r91.zip` (after a long time debugging it)!

Hopefully it's now also fixed for other people having this issue. Can you guys check the update?

**Comment by Riwaha** [comment]
Can confirm this has been fixed.

**Comment by ZTHawk** [comment]
I can also confirm that there are no more artifacts/wall hacks.
