### ISSUE TITLE
Pixelated objects/characters

### ISSUE THREAD

**Issue by hel-ish** [megai2/d912pxy#59]
v0.9.6 introduced small visible pixels in objects and characters for me and friends when chainloaded with arcdps.

https://i.imgur.com/P4e2Ut8.jpg
https://i.imgur.com/HXpTOrx.jpg
https://i.imgur.com/7GJgA4l.jpg

Mind you this does not appear everywhere and I think it highly depends on lighting. Replicateable in Underground easily.

**Comment by megai2** [comment]
is this with arc?

**Comment by pro0digy** [comment]
i have the same issue.

**Comment by hel-ish** [comment]
> is this with arc?

Yes, this only happens when it's used in combination with arcdps.

**Comment by Malfrador** [comment]
I have the same small pixels on grass in WvW (newest d912pxy + arc) Disabling "best texture filtering" fixes it. Maybe it helps with these pixels too.

**Comment by hel-ish** [comment]
> I have the same small pixels on grass in WvW (newest d912pxy + arc) Disabling "best texture filtering" fixes it. Maybe it helps with these pixels too.

Can confirm that disabling best texture filtering fixes the issue. Seems more of a temporal fix.

**Comment by megai2** [comment]
new arcdps update coming feb 26 with fix included

**Comment by megai2** [comment]
updated imgui patch once again, sended info on this to deltaconnected.
hope it will work and patched up before feb 26 =)

**Comment by hel-ish** [comment]
Just an update that the issue still persist with both newest versions of arcdps and d912pxy.

**Comment by megai2** [comment]
fixed on latest dev build of arcdps https://www.deltaconnected.com/arcdps/dev/d3d9.dll
or new build after gw2 client update
