### ISSUE TITLE
Crashes on Windowed Fullscreen, Works on Fullscreen. Some reports

### ISSUE THREAD

**Issue by magnapeccatrix** [megai2/d912pxy#6]
Hello, I just created this topic to add my p7d files (they are the logs I assume)

There is some sort of white tint on entire camera view. Terrain and Structures are warping with flashing lights, it's hard to tell and hard to notice.

About FPS, it was somewhat same with dx9 or wired to dx12, but I did feel looking around moving camera it was much more smoother than dx9 (felt less laggy) [that's checked in WvW]

My system specs are: i7-5820k, nvidia gtx 1080, 16gb ddr4, GW2 is on a seperate ssd.

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2779988/d912pxy_crash.txt)
[P7logs.zip](https://github.com/megai2/d912pxy/files/2779989/P7logs.zip)
[Crash.zip](https://github.com/megai2/d912pxy/files/2780005/Crash.zip)

**Comment by magnapeccatrix** [comment]
Hello, wanted to add during Dragon's Stand Meta, when cutscene of dragon came in, I wanted to alt tab to desktop and game crashed, paused on video frame and I had to end process tree.

**Comment by megai2** [comment]
Hi, thx on report, addeded some more detailed issues.

Alt-tabs can take a long time, especially if shader cache is not yet made(you basically see things loading part-by part slowly), cause it will not respond to any commands until they are compiled and saved. 

On crashes, there is new version coming up.
