### ISSUE TITLE
Blocky/square looking trees

### ISSUE THREAD

**Issue by dvanderh** [megai2/d912pxy#61]
![guild wars 2 2019-02-03 19_35_58](https://user-images.githubusercontent.com/8694092/52522265-2d11f400-2c83-11e9-898f-b2385be820cd.png)

This is in Bloodtide Coast. Possibly happening in other areas as well.

I'm using version Alpha v0.9.6.1

**Comment by IsmetBesic** [comment]
I noticed the same visual glitch in Auric Basin today but I was able to resolve it by deleting the "shader_cso.pck" file in the GW2\d912pxy\pck folder and relaunching the game (shaders will be recompiled on-demand so expect some funky visuals until everything settles in). 

The issue itself seems to be tied to the pre-compiled shaders bundled with the current release, however, @megai2 has already adressed this source of possible visual glitches in this [commit](https://github.com/megai2/d912pxy/commit/e638daf04f2dc402623101e32d54da16e47a63ad) by removing the pre-compiled shader bundle from the release builds for the time being.

**Comment by megai2** [comment]
remove d912pxy\pck\shader_cso.pck, should work on v0.9.6.1a
