### ISSUE TITLE
windowed fullscreen causes GPU to run in low power mode, leading to severe loss of performance

### ISSUE THREAD

**Issue by moriz1** [megai2/d912pxy#62]
tested on v0.9.6.2

workaround:
-run OBS:Studio in the background, with "display capture" as a source. this causes GPU to go back to full power mode and restores performance

i suspect anything that puts a load on the GPU would also be a workaround.

**Comment by megai2** [comment]
windows/driver power settings?

**Comment by moriz1** [comment]
GPU is already set to run at prefer max performance.

**Comment by megai2** [comment]
> 
> 
> GPU is already set to run at prefer max performance.

For me it's working right, maybe there is some common issue for your GPU?

**Comment by moriz1** [comment]
> Or in fact you do streaming with capture card?

if i run the game in windowed fullscreen, WITHOUT OBS open, my GPU goes to low powered mode.

if i run the game in windowed fullscreen, WITH OBS open and display capture enabled, my GPU goes back to full power mode.

just by having OBS:S open and sitting idle is enough to correct the issue. i don't have to record/stream anything.

**Comment by megai2** [comment]
> 
> 
> > Or in fact you do streaming with capture card?
> 
> if i run the game in windowed fullscreen, WITHOUT OBS open, my GPU goes to low powered mode.
> 
> if i run the game in windowed fullscreen, WITH OBS open and display capture enabled, my GPU goes back to full power mode.
> 
> just by having OBS:S open and sitting idle is enough to correct the issue. i don't have to record/stream anything.

There was a report on case when capture card do a same low power thing.

**Comment by moriz1** [comment]
yeah, i reported it. this is a different issue that results in the same behaviour.

**Comment by megai2** [comment]
> 
> 
> yeah, i reported it. this is a different issue that results in the same behaviour.

I not found recomendations or samples on DX12 and GPU power managment.
GPU driver should pump power mode automatically on demand.
Please check, maybe this is a common problem with some GPU's/setups/drivers.

Also on a solution, check an NVIDIA control panel for power config(as i remember you was runnning NV card).

**Comment by moriz1** [comment]
there's an nvidia control panel option called "prefer maximum performance", except it's not enough. this setting only ensures that the GPU is **at least** in "idle 3D" performance. for my 2080 Ti, "idle 3D" is 1350 Mhz, while "full power 3D" is at 1965 Mhz. this results in a huge drop in performance.

my current hypothesis, is that D912pxy confuses nvidia's driver profiles, and it thinks that there's no game running.

**Comment by megai2** [comment]
Can you run a _pp release while doing that workaround? 
Like switch bug on/off 2-3 times.
Then send log to me.

**Comment by moriz1** [comment]
here they are.

i first opened the game to Lion's Arch, and switched OBS:Studio on and off a few times.

i then zoned to EBG, and repeated the same with OBS:Studio.
[20190211-23271800.zip](https://github.com/megai2/d912pxy/files/2854137/20190211-23271800.zip)
![performance_graph](https://user-images.githubusercontent.com/8854387/52611838-67cb8600-2e55-11e9-9232-f852dd8d4e97.png)

**Comment by megai2** [comment]
Yes, all other sides looks fine. 
Meanwhile, not found any solution on power managment other than OC tools.

There is some reports in internet on RTX and multimonitor clock speeds.
And also on same clock freezing overall or specific to microsoft DX12 titles.
People troubleshoot them with vbios updates or plain driver updates.

One more case might be from variable refresh rate monitors:
targeted at some low FPS A, system can't push to higher clock rates because while it waits for monitor, load drops off to "idle" condition. Quantum FPS!

Summary, only workaround for now:
A. Force GPU to run at 100% clocks all the time
B. Run any software that trigger high power GPU state, without actually making any load.

**Comment by moriz1** [comment]
> @moriz1 Friend of mine had this problem, and quick google search reveals that it's not uncommon for 2080ti. In case of my friend, with his Evga card, problem got solved after updating video bios, check if there is update available for your card.

i tried updating vbios, but the same behaviour persists.

@megai2 you are correct: the issue here is that D912pxy causes such a low GPU load, that my video card drops to its base clock, which is 1350 Mhz on GPU core. the magic load appears to be 38-40%. if i can hit the card with a load above that, it'll instantly go full speed, resulting in a drastic increase in performance.

however, lion's arch still appears to be very CPU bottlenecked, since i'd get the same performance even if GPU core clock manages to hit full speed.

it also seems to have nothing to do with variable refresh rate monitors, since i'm using a standard 60Hz display.

**Comment by megai2** [comment]
> 
> 
> > @moriz1 Friend of mine had this problem, and quick google search reveals that it's not uncommon for 2080ti. In case of my friend, with his Evga card, problem got solved after updating video bios, check if there is update available for your card.
> 
> i tried updating vbios, but the same behaviour persists.
> 
> @megai2 you are correct: the issue here is that D912pxy causes such a low GPU load, that my video card drops to its base clock, which is 1350 Mhz on GPU core. the magic load appears to be 38-40%. if i can hit the card with a load above that, it'll instantly go full speed, resulting in a drastic increase in performance.
> 
> however, lion's arch still appears to be very CPU bottlenecked, since i'd get the same performance even if GPU core clock manages to hit full speed.
> 
> it also seems to have nothing to do with variable refresh rate monitors, since i'm using a standard 60Hz display.

Hope they fix this behaivour as there is no software limit for frame time in code.

LA is, hopefully we can pump some data on source of CPU load by using "-umbra gpu".

So i repeat last post fragment and close this for now.

Summary, only workaround for now:
A. Force GPU to run at 100% clocks all the time
B. Run any software that trigger high power GPU state, without actually making any load.
