### ISSUE TITLE
DXGI swapchain init crash

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#63]
this time i get the d912pxy_crash.txt telling that i should check display settings, but i have no clue whats wrong.

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2842259/d912pxy_crash.txt)
[P7logs.zip](https://github.com/megai2/d912pxy/files/2842260/P7logs.zip)

_Originally posted by @setiseta in https://github.com/megai2/d912pxy/issues/13#issuecomment-461549463_

**Comment by megai2** [comment]
Additional logging are added for this case, please reproduce this error and send logs.

**Comment by setiseta** [comment]
the additional logs are in the P7logs?
on the d912pxy_crash.txt it was the same.
i can post the P7logs at the evening.

**Comment by megai2** [comment]
> 
> 
> the additional logs are in the P7logs?
> on the d912pxy_crash.txt it was the same.
> i can post the P7logs at the evening.

Yes, in base logs that saved in P7logs folder.

**Comment by setiseta** [comment]
[crash.zip](https://github.com/megai2/d912pxy/files/2857506/crash.zip)
actual logs from 0.9.6.2

**Comment by megai2** [comment]
> 
> 
> [crash.zip](https://github.com/megai2/d912pxy/files/2857506/crash.zip)
> actual logs from 0.9.6.2

Very odd. Try running game in a window before installing, maybe it will do something.
Looks like I need to redirect stderr to file somehow, to properly get issue source, but this will take some time.

**Comment by megai2** [comment]
Rediredted DXGI debug messages to P7logs for Debug build(not Release_d), now it should show what is wrong.

**Comment by megai2** [comment]
https://ci.appveyor.com/api/buildjobs/mf7b0ntbi2oa1x9u/artifacts/d912pxy__r87.zip try to run this version, but install Debug one and send log from P7logs here.

**Comment by clouser123** [comment]
This is what I am getting.
[p7log.zip](https://github.com/megai2/d912pxy/files/2872504/p7log.zip)
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2872505/d912pxy_crash.txt)

Specs:
> Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 CPUs), ~2.8GHz
> Memory: 32768MB RAM
> Card name: NVIDIA GeForce GTX 1060 with Max-Q Design
> Dedicated Memory: 6052 MB
> Current Mode: 1920 x 1080 (32 bit) (74Hz)

**Comment by megai2** [comment]
You need to install https://www.thewindowsclub.com/install-graphics-tools-in-windows-10 to run debug version, or maybe this will fix both errors. Anyway install and send logs again.

**Comment by clouser123** [comment]
[p7logs-postgraphicstoolsinstallation.zip](https://github.com/megai2/d912pxy/files/2872769/p7logs-postgraphicstoolsinstallation.zip)
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2872770/d912pxy_crash.txt)

Crash still occurring. I installed Graphics Tools and reinstalled the debug version from the link you posted (r87).

**Comment by megai2** [comment]
> 
> 
> [p7logs-postgraphicstoolsinstallation.zip](https://github.com/megai2/d912pxy/files/2872769/p7logs-postgraphicstoolsinstallation.zip)
> [d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2872770/d912pxy_crash.txt)
> 
> Crash still occurring. I installed Graphics Tools and reinstalled the debug version from the link you posted (r87).

Can you set windowed mode/windowed fullscreen mode in game settings priror to installing and see if it works? And OFC send logs if it not works.

**Comment by clouser123** [comment]
The logs attached above are pulled after launching with -windowed and going fullscreen.
If not, the game crashes as soon as the game is launched (Pressing PLAY). 

Not sure if relevant or not, but I run a dual monitor setup. Both are the same resolution, one is 60Hz and the other 74Hz (where I run the game).

**Comment by megai2** [comment]
> 
> 
> The logs attached above are pulled after launching with -windowed and going fullscreen.
> If not, the game crashes as soon as the game is launched (Pressing PLAY).
> 
> Not sure if relevant or not, but I run a dual monitor setup. Both are the same resolution, one is 60Hz and the other 74Hz (where I run the game).

Fullscreen via Alt-Enter or game settings?
Better to add logs of fullscreen startup crash then.

**Comment by setiseta** [comment]
[GuildWars2.zip](https://github.com/megai2/d912pxy/files/2900754/GuildWars2.zip)
Acutal Logs with 0.9.6.7

**Comment by megai2** [comment]
> 
> 
> [GuildWars2.zip](https://github.com/megai2/d912pxy/files/2900754/GuildWars2.zip)
> Acutal Logs with 0.9.6.7

still need a log from Debug version, as standart error reporting shows "DXGI_ERROR_INVALID_CALL".
if you shure that game runs good in window mode, exact window mode, not windowed fullscreen, debug layer should write something about origin of error you have.

**Comment by megai2** [comment]
> 
> 
> [GuildWars2.zip](https://github.com/megai2/d912pxy/files/2900754/GuildWars2.zip)
> Acutal Logs with 0.9.6.7

Also i see in last crashlog that you using Overwolf overlay, some custom dxgi.dll in game bin64 folder and yolomouse.
Probably you should try run game with this tools disabled.

**Comment by setiseta** [comment]
Oh, yes forgot to disable overwolf and yolomouse.
What custom dxgi.dll? There are some from disabled tools (Reshade and arcdps) just renamed, but should not be loaded or am i wrong?

how to use debug version or where to download from 9.6.7 or should i use a different version?

**Comment by megai2** [comment]
> 
> 
> Oh, yes forgot to disable overwolf and yolomouse.
> What custom dxgi.dll? There are some from disabled tools (Reshade and arcdps) just renamed, but should not be loaded or am i wrong?
> 
> how to use debug version or where to download from 9.6.7 or should i use a different version?
C:\Games\GuildWars2\bin64\dxgi.dll <= this. I don't know where it came from.

For installing debug version you should answer "No" in installer when asked "Use standard release?" and then select Debug build by answering "4".

**Comment by setiseta** [comment]
[GuildWars2.zip](https://github.com/megai2/d912pxy/files/2900883/GuildWars2.zip)
This should be the debug version, with overwolf und yolomouse disabled.

**Comment by megai2** [comment]
> 
> 
> [GuildWars2.zip](https://github.com/megai2/d912pxy/files/2900883/GuildWars2.zip)
> This should be the debug version, with overwolf und yolomouse disabled.

it not even logged properly, maybe running it several times until proper log is saved will do the trick?

but still you should check for that custom dxgi.dll cause problem is in call to dxgi, and that dll looks too suspicious =)

**Comment by setiseta** [comment]
Ok, I cleaned the bin64 from all .dll's i thought not loaded. It seems to work now.
It seems the dxgi.dll was something from a reshade installation. from the filedate it was very old. (2015)
maybe someone knows what are the default files in the bin64? so i dont need to redownload the whole game.

**Comment by megai2** [comment]
> 
> 
> Ok, I cleaned the bin64 from all .dll's i thought not loaded. It seems to work now.
> It seems the dxgi.dll was something from a reshade installation. from the filedate it was very old. (2015)
> maybe someone knows what are the default files in the bin64? so i dont need to redownload the whole game.

You can safely remove bin64 folder as game will redowload only needed files that you deleted from bin64, not the whole game.

So whole problem was in conflict with old reshade installation.

Before we close the issue, check for signature bugs like delayed loading or bugged character icons on login screen.
