### ISSUE TITLE
not working by installing in bin64 directory

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#64]
If you see that installing in bin64 have zero effect, try installing in game root folder.

If this is still not working, please try troubleshoot this by running game as administrator and finding a source of problem on your system first.

Then report on either succesfull result or not, so i can update install instructions.

**Comment by megai2** [comment]
not reported anymore, closed

**Comment by tedsu** [comment]
Hi, I've been trying to get it to work, installing it in game root folder, running it as an admin, doing all of this on a fresh install (installed every vcredist too) and I still can't get a log.txt

**Comment by tedsu** [comment]
I realized I was installing it as chainload (since I was planning on using arcdps) so after changing it to default, it worked. So the problem is to get it working with arcdps.
