### ISSUE TITLE
Issues with SLI

### ISSUE THREAD

**Issue by Squallaus** [megai2/d912pxy#66]
Think with the v0.962  SLI almost works but not quite. When running in SLI mode it loading of new objects seem to load really slow atleast maybe 1 minute+ but still have some things not loaded like special effects from legendary weapons. When I configure GW2 to run on 1 GPU only via nvidia control panel options, new objects load in less than 10 seconds.

Any chance you can try and get SLI working too in the near future? I think it's almost there.

Played wvw and fractals last night with v0.962 i think the fps improved in wvw, not so much in fractals. But over all  the game seems more responsive than normal so i'm guessing the fps is more consistent.

Also is vsync still not working? When i try to tick vsync in the graphics options my game crashes. Seem to get minor screen tearing while i was running around in wvw last night.

Thanks. Keep up the great work!

**Comment by megai2** [comment]
Slow load on first seen asset after install is expected.
When game is exited normally, shader cache is updated and all that was loaded last time, loads in quite fast, as you noted this.

SLI support for now is based on driver behaivour, as there is nothing usefull to do yet with multi GPU features of DX12.

VSync is working, prob. ArcDPS compat problem. 

On other things(vsync one too) read https://github.com/megai2/d912pxy#troubleshooting
