### ISSUE TITLE
[reports] General performance errors

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#67]
Read README.md troubleshooting case 4 first!
Then post performance related errors here using this template.

```
1. p7d logfile
2. performance_graph.png 
3. Time of performance drop relative to game start. (@ 33s, @ 42s)
4. Description of encountered error and how to reproduce it.
```

**Comment by loqi93** [comment]
1. p7d logfile[20190804-222319000.zip](https://github.com/megai2/d912pxy/files/3465299/20190804-222319000.zip)
2. performance graph [dx12_perf_graph.zip](https://github.com/megai2/d912pxy/files/3465300/dx12_perf_graph.zip)

Frequent drop fps to 30, #175

**Comment by megai2** [comment]
reorganized wiki and stuff, this issue is no longer in works
