### ISSUE TITLE
GSync/FreeSync & FPS more than max refresh rate

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#68]
> > My GPU keeps crashing (screen goes to no display and returns back no hard crash) when I have the game on top but as soon as I pull up another window I'm stable and getting 150-200 fps in open world. I checked every single overlay I could think of (Shadowplay, Windows Xbox, etc.).
> > If you can think of anything causing this or if you have a solution please let me know.
> > Ps. You're doing God's work son!
> > [crash.zip](https://github.com/megai2/d912pxy/files/2854891/crash.zip)
> 
> GSync monitor? Old drivers?
> Hold on, will add more info on this case in next releases.
> Will post updates on this in #63 as that errors seems to be related.

Yes I do have a GSync monitor but you mentioned that it is supported in windowed fullscreen
All of my drivers are updated.

_Originally posted by @bdikmen1 in https://github.com/megai2/d912pxy/issues/13#issuecomment-462723217_

**Comment by megai2** [comment]
Latest changes added an no-wait presentation code, looks like this creates errors if FPS is more than maximum refresh rate of monitor.

Before i do something related to code, i want to see a logfile of this problem with  [r69](https://ci.appveyor.com/api/buildjobs/68f6aoqkp8ojmdly/artifacts/d912pxy__r69.zip) and up.

**Comment by bdikmen1** [comment]
I limited my fps to 60 but still crashed. Not sure if helps but so that you know.

**Comment by megai2** [comment]
> 
> 
> I limited my fps to 60 but still crashed. Not sure if helps but so that you know.

Ingame limit is kinda "soft", one frame more will trigger the error.

Please post new logs on r69.

**Comment by megai2** [comment]
need to test this bug on latest release

**Comment by bdikmen1** [comment]
There's an ongoing issues with G-sync caused by driver 418.91. Screen keeps flickering and I'm not sure how to test it until Nvidia fixes it

**Comment by megai2** [comment]
roll back to stable driver?

**Comment by bdikmen1** [comment]
Wouldn't that cause other problems with d912pxy?

**Comment by megai2** [comment]
> 
> 
> Wouldn't that cause other problems with d912pxy?

If it worked with old drivers, why it should stop working? Should be fine.

**Comment by megai2** [comment]
As no-wait behaivour error is patched by fallback to prev. tested solution, this bug is no more.
