### ISSUE TITLE
ReShade like features

### ISSUE THREAD

**Issue by megai2** [megai2/d912pxy#69]
at this point, it might be easier to incorporate reshade features directly into d912pxy, than to wait for some way to chainload.

_Originally posted by @moriz1 in https://github.com/megai2/d912pxy/issues/38#issuecomment-463068854_

**Comment by moriz1** [comment]
i'm curious as to how this would work with d912pxy shader cache. does this mean that the cache would need to be recompiled every time we add a new shader, or change a variable?

**Comment by megai2** [comment]
For every original DX9 shader code change, new recompilation performed and cache entry are created.
But this only for DX9 shaders and their path to DX12.

Any other things can be done differently.

**Comment by moriz1** [comment]
Is there a way to add new post processing shaders? That's basically what reshade and gw2hook are for. Gw2hook can also inject shaders before the game draws the UI.

I imagine we'd be using compute shaders if d912pxy ever gains this capability.

**Comment by megai2** [comment]
There are many ways to implement this.
1. By dx9 api like reshade do
2. By dx12 api
3. By shader injections
4. By shader replacement

Any of dx12 features can be used, but you know, dx12 features are not creating any of fancy things, they must be used correctly.

**Comment by megai2** [comment]
Big question is TOS compliancy as any shader modifications can be used badly.

**Comment by moriz1** [comment]
That'll depend on what kind of data you give access to.

For gw2hook, you're given only color and depth buffer. Since GW2 doesn't use visual obscurance as a gameplay feature, you couldn't write shaders to cheat with.

**Comment by megai2** [comment]
I can add logic to load shader sources from d912pxy/shaders/hlsl/custom or even from d912pxy/pck/$config_defined_name$.pck as a general solution.

**Comment by moriz1** [comment]
will these shaders be loaded at the end of the rendering chain? can we also load textures?

the great thing about GW2Hook is that it loads post processing shaders before the UI, as well as disabling the built in bloom shader.

**Comment by megai2** [comment]
> 
> 
> will these shaders be loaded at the end of the rendering chain? can we also load textures?
> 
> the great thing about GW2Hook is that it loads post processing shaders before the UI, as well as disabling the built in bloom shader.

They will be loaded instead of default ones, no additional draw passes/resource loads.

You must find shader hash name, get its original somehow and make modifications to it.

Like bloom post process shader is [BDF9552455D08BAA.txt](https://github.com/megai2/d912pxy/files/2898388/BDF9552455D08BAA.txt)
(i renamed it to txt for github)
With s0 being base texture and s1 being bloom texture.
You can modify it as you want and then put it into custom folder, clean shader cache and boom! =]

**Comment by moriz1** [comment]
that's really cool! reshade never had the ability to replace shaders, though it does load additional shaders.

i guess if i want to remove certain shaders, i can simply modify that shader to just output the base texture instead. and if i want to add a new post processing shader, i'd have to basically sacrifice one of the preexisting ones.

**Comment by megai2** [comment]
> 
> 
> that's really cool! reshade never had the ability to replace shaders, though it does load additional shaders.
> 
> i guess if i want to remove certain shaders, i can simply modify that shader to just output the base texture instead. and if i want to add a new post processing shader, i'd have to basically sacrifice one of the preexisting ones.

Or extend.

**Comment by moriz1** [comment]
how do i find the shader hash name?

**Comment by megai2** [comment]
> 
> 
> how do i find the shader hash name?

You need to capture frame by graphics debugger/analyzer software when running debug version of d912pxy
Find the draw call you interested in, find name of shader it uses.

Tricky part is: running graphics debugger/analyzer. 
I have a fork of RenderDoc, but you should compile it by yourself.

**Comment by megai2** [comment]
Is this enougth to allow "most used" visual effects/overhauls being used?

**Comment by moriz1** [comment]
Assuming we can also access the depth buffer in some way: yes. This is more than enough.

The only drawback is the difficulty and inconvenience. There isn't a way to reload shaders while the game is still running, which makes debugging custom shaders very slow.

**Comment by megai2** [comment]
> 
> 
> Assuming we can also access the depth buffer in some way: yes. This is more than enough.
> 
> The only drawback is the difficulty and inconvenience. There isn't a way to reload shaders while the game is still running, which makes debugging custom shaders very slow.

If you use renderdoc for finding shader hash names, you can use it for debugging too.
Depth buffer can be accessed if it set to some texture slot by game.

I think you should open up another issue with more detailed description of how this should be done in a scope of user.

Also if you up to making custom shaders or know someone who is up to it, there is public wiki here on github that you can use to add some tutorials/instructions.

**Comment by moriz1** [comment]
I think this is already good enough for users. Anyone capable of writing custom shaders won't have problems with the way things are implemented.

Two things might still be needed: 1) ability to inject a new shader, 2) ability to use dx12 shaders directly.

**Comment by megai2** [comment]
> 
> 
> I think this is already good enough for users. Anyone capable of writing custom shaders won't have problems with the way things are implemented.
> 
> Two things might still be needed: 1) ability to inject a new shader, 2) ability to use dx12 shaders directly.

1. I will look up on points of shader injection, but later after beta release
2. The hlsl files that you use in custom folder are already dx12 shaders

**Comment by WanYaa** [comment]
I think gw2hook did not allow to change fog settings on WvW or PvP maps to make it TOS compliant

**Comment by megai2** [comment]
> 
> 
> I think gw2hook at least did not allow to change fog settings on WvW or PvP maps to make it TOS compliant

It was made originally to remove fog. I do not make custom shaders, so it is your responce if you do something illegal.

**Comment by ruvaldak** [comment]
Should add TAA post process, just thought id chime in. Anti aliasing solutions in gw2 are extremely limited, either shit smaa/fxaa or super sampling

**Comment by rkujo** [comment]
if someone can make a library for d912 custom shader files that would be really cool

**Comment by megai2** [comment]
also, on custom textures, if you have some suggestions on how to identify textures from d3d9 api side, this can be done.

**Comment by dasfalco** [comment]
Are we looking for these or am i understanding something wrong?
https://github.com/FransBouma/reshade-shaders

**Comment by megai2** [comment]
> 
> 
> Are we looking for these or am i understanding something wrong?
> https://github.com/FransBouma/reshade-shaders

I think second option is correct.

**Comment by megai2** [comment]
Custom shaders is in place and ReShade support DX12 now.  
Now ReShade can be used normally.
