### ISSUE TITLE
Crashed in Istan

### ISSUE THREAD

**Issue by Asonur** [megai2/d912pxy#70]
Logs here hope it works, i have barely any idea if im doing this right.

[Asonur logs 2019-02-17.zip](https://github.com/megai2/d912pxy/files/2873083/Asonur.logs.2019-02-17.zip)

[crashlog .zip](https://github.com/megai2/d912pxy/files/2873093/crashlog.zip)

went to istan waypoint astralarium, mounted griffon and flew over to GH. Before i could reach the next platform (other side of the bridge) it suddenly crashed. Hope it helps.

**Comment by megai2** [comment]
related to #14
