### ISSUE TITLE
Any chance for x86 build?

### ISSUE THREAD

**Issue by Slurmy** [megai2/d912pxy#71]

**Comment by megai2** [comment]
Chance is more then 0.

**Comment by ivan89el** [comment]
Maybe we should do a test build?

**Comment by megai2** [comment]
Maybe, but i'm not on this for now.
Current build can eat >4Gb in no time.
This should be handled some way first.

**Comment by ivan89el** [comment]
@megai2
Thanks for the answer and hope in the future.
