### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by kulgark** [megai2/d912pxy#73]
Random crashes inside instances (so far a couple of times during dungeons in ARAH and Fractals, at Underground Facility and Deepstone) that will make me hard reset my pc, I'll attach the log file
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2881767/d912pxy_crash.txt)
[P7logs.zip](https://github.com/megai2/d912pxy/files/2881771/P7logs.zip)

**Comment by megai2** [comment]
#13
