### ISSUE TITLE
Game instantly crashes in any mode after pressing "Play" in launcher

### ISSUE THREAD

**Issue by Aeteris** [megai2/d912pxy#8]
Specs are i5-6600, 16gb DDR4 RAM, GTX 1060 6GB, Win10 x64, x64 executable

[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2792957/d912pxy_crash.txt)
[crash.zip](https://github.com/megai2/d912pxy/files/2792958/crash.zip)

**Comment by megai2** [comment]
Installed incorrectly, it should be like a guildwars2/d912pxy/install.bat

**Comment by Aeteris** [comment]
Well I tried both ways, I'll see if I am just plain dumb/

**Comment by Aeteris** [comment]
![image](https://user-images.githubusercontent.com/47007582/51708152-302aa480-2034-11e9-84d3-54cc6d76d68d.png)
![image](https://user-images.githubusercontent.com/47007582/51708167-3882df80-2034-11e9-99d1-dc72474defda.png)

Installed correctly, still crashes. Also, creates copy of d3d9.dll and P7x64.dll in game's root directory.
[crash.zip](https://github.com/megai2/d912pxy/files/2793601/crash.zip)
[d912pxy_crash.txt](https://github.com/megai2/d912pxy/files/2793603/d912pxy_crash.txt)

**Comment by clouser123** [comment]
I am experiencing the same kind of crash but it seems like I do have it installed fine. 

Crash.txt says:

```
0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
0 | "hlsl generator not support passed dst modifier" | hr = FFFFFFFF 
0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
```

**Comment by megai2** [comment]
> 
> 
> I am experiencing the same kind of crash but it seems like I do have it installed fine.
> 
> Crash.txt says:
> 
> ```
> 0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
> 0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
> 0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
> 0 | "hlsl generator not support passed dst modifier" | hr = FFFFFFFF 
> 0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
> 0 | "swap chain 10 init errors, check display settings" | hr = FFFFFFFF 
> ```

Look latest comment here #63
