### ISSUE TITLE
Shadows on the Ultra setting do not display

### ISSUE THREAD

**Issue by wolf88804** [megai2/d912pxy#99]
Ever since the 9.7 update when shadows are on Ultra or high they do not display, however on none/low they do display (although appear to be the equivalent of low and medium.) All other settings are maxed out and this was not an issue before this update.

**Comment by megai2** [comment]
![gw123](https://user-images.githubusercontent.com/1693251/53680574-94551e00-3cee-11e9-87e8-53c9b6ea072a.jpg)
Please report according to https://github.com/megai2/d912pxy/wiki/Reporting-visual-errors
